-- Supabase authoritative team / platform / package-system registry for the new private admin preview.
-- This is additive and read-only from the preview; legacy pages and source tables are untouched.
create table if not exists public.dashboard_platform_team_map (
  id uuid primary key default gen_random_uuid(),
  team_name text not null,
  system_name text not null,
  source_system text not null,
  country_name text not null,
  country_code text not null,
  source_country text not null,
  platform_name text not null,
  source_platform text not null,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_system, source_country, source_platform)
);

alter table public.dashboard_platform_team_map enable row level security;
revoke all on table public.dashboard_platform_team_map from anon, authenticated;

insert into public.dashboard_platform_team_map
  (team_name, system_name, source_system, country_name, country_code, source_country, platform_name, source_platform, metadata)
values
  ('M8', 'AR系统', 'AR', '巴西', 'BR', '巴西', 'POP555', 'POP555', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴西', 'BR', '巴西', 'POP678', 'POP678', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴西', 'BR', '巴西', 'POP888', 'POP888', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴西', 'BR', '巴西', 'POPBEM', 'POPBEM', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴西', 'BR', '巴西', 'POPBRA', 'POPBRA', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴西', 'BR', '巴西', 'POPCEU', 'POPCEU', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴西', 'BR', '巴西', 'POPLUA', 'POPLUA', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴西', 'BR', '巴西', 'POPPG', 'POPPG', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', '51GAME', '51GAME', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', '55CLUB', '55CLUB', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', '6CLUB', '6CLUB', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', '82LOTTERY', '82LOTTERY', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', '91CLUB', '91CLUB', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', 'BIGMUMBAI', 'BIGMUMBAI', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', 'IN999', 'IN999', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', 'JAICLUB', 'JAICLUB', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', 'JALWA', 'JALWA', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', 'LOTTERY77', 'LOTTERY7', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', 'OKWIN', 'OKWIN', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', 'RAJAGAMES', 'RAJA', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', 'RAJALOTTERY', 'RAJALOTTERY', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', 'SHREEWIN', 'Shree.Win', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', 'TPPLAY', 'TPPLAY', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印度', 'IN', '印度', 'VEERGAME', 'Veer.Game', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '缅甸', 'MM', '缅甸', '6LOTTERY', '6LOTTERY', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '印尼', 'ID', '印尼', '55FIVE', '55FIVE', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '马来', 'MY', '马来', 'MZPLAY', 'MZPLAY', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '尼日利亚', 'NG', '尼日利亚', 'FB999', 'FB999', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴基斯坦', 'PK', '巴基斯坦', '92COCO', '92COCO', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴基斯坦', 'PK', '巴基斯坦', '92DADU', '92DADU', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴基斯坦', 'PK', '巴基斯坦', '92GAME', '92GAME', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴基斯坦', 'PK', '巴基斯坦', '92GLORY', '92GLORY', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴基斯坦', 'PK', '巴基斯坦', '92GO', '92GO', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴基斯坦', 'PK', '巴基斯坦', '92PKR', '92PKR', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴基斯坦', 'PK', '巴基斯坦', '92R', '92R', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴基斯坦', 'PK', '巴基斯坦', '92STAR', '92STAR', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴基斯坦', 'PK', '巴基斯坦', '92STRIKE', '92STRIKE', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '巴基斯坦', 'PK', '巴基斯坦', 'YAYWIN', 'YAYWIN', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '越南', 'VN', '越南', '66CLUB', '66CLUB', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '越南', 'VN', '越南', '82VN', '82VN', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '越南', 'VN', '越南', '92LOTTERY', '92LOTTERY', '{}'::jsonb),
  ('M8', 'AR系统', 'AR', '越南', 'VN', '越南', 'VN168', 'VN168', '{}'::jsonb),
  ('M8', '新AR系统', 'NEW_AR', '印度', 'IN', '印度', 'DHANIWIN', 'DhaniWin', '{}'::jsonb),
  ('M8', '新AR系统', 'NEW_AR', '印度', 'IN', '印度', '9K.CLUB', '9K.CLUB', '{}'::jsonb),
  ('M8', '新AR系统', 'NEW_AR', '巴基斯坦', 'PK', '巴基斯坦', 'POPZAR', 'POPZAR', '{}'::jsonb),
  ('M8', '新AR系统', 'NEW_AR', '巴基斯坦', 'PK', '巴基斯坦', '92BLAZE', '92BLAZE', '{}'::jsonb),
  ('M8', '新AR系统', 'NEW_AR', '墨西哥', 'MX', '墨西哥', 'CATRINABET', 'CATRINABET', '{}'::jsonb),
  ('M8', '多利系统', 'DOLI', '印尼', 'ID', '印尼', 'FB168', 'FB168', '{}'::jsonb),
  ('M8', '多利系统', 'DOLI', '印尼', 'ID', '印尼', 'FB333', 'FB333', '{}'::jsonb),
  ('M8', 'KB系统', 'KB', '印度', 'IN', '印度', 'YASH.BET', 'YASH.BET', '{}'::jsonb),
  ('M8', '万利系统', 'WANLI', '巴基斯坦', 'PK', '巴基斯坦', '3PATTI-SUPER', '3PATTI-SUPER', '{}'::jsonb),
  ('M8', '其他系统 / 交易所', 'OTHER', '越南', 'VN', '越南', 'COINVID', 'COINVID', '{}'::jsonb),
  ('M8', '其他系统 / 交易所', 'OTHER', '越南', 'VN', '越南', 'VNCORE', 'VNCORE', '{}'::jsonb),
  ('M8', 'WG系统', 'WG', '越南', 'VN', '越南', '98VV', '98VV', '{}'::jsonb),
  ('M8', 'WG系统', 'WG', '越南', 'VN', '越南', 'XX98', 'XX98', '{}'::jsonb),
  ('M8', 'WG系统', 'WG', '巴西', 'BR', '巴西', '26BET', '26BET', '{}'::jsonb),
  ('M8', 'WG系统', 'WG', '巴西', 'BR', '巴西', 'POPKKK', 'POPKKK', '{}'::jsonb),
  ('M8', 'WG系统', 'WG', '巴西', 'BR', '巴西', 'POPMIU', 'POPMIU', '{}'::jsonb),
  ('M8', 'LG系列', 'LG', '菲律宾', 'PH', '菲律宾', 'SUPERLG', 'SUPERLG', '{}'::jsonb),
  ('M8', 'LG系列', 'LG', '菲律宾', 'PH', '菲律宾', 'LGPARTY', 'LGPARTY', '{}'::jsonb),
  ('M8', 'LG系列', 'LG', '菲律宾', 'PH', '菲律宾', 'LGSABONG', 'LGSABONG', '{}'::jsonb),
  ('M8', 'LG系列', 'LG', '菲律宾', 'PH', '菲律宾', 'LGBIGWIN', 'LGBIGWIN', '{}'::jsonb),
  ('M8', 'LG系列', 'LG', '印尼', 'ID', '印尼', 'LG111', 'LG111', '{}'::jsonb),
  ('M8', 'LG系列', 'LG', '巴基斯坦', 'PK', '巴基斯坦', 'LG789', 'LG789', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', '43R', '43R', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'BOOMRIO', 'BOOMRIO', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'PLAYERBR', 'PLAYERBR', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPBEA', 'POPBEA', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPBIS', 'POPBIS', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPBOA', 'POPBOA', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPBUL', 'POPBUL', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPCRA', 'POPCRA', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPDEZ', 'POPDEZ', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPFEZ', 'POPFEZ', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPFLU', 'POPFLU', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPFOI', 'POPFOI', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPLUZ', 'POPLUZ', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPMEL', 'POPMEL', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPN1', 'POPN1', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPNOV', 'POPNOV', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPSEN', 'POPSEN', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPSUR', 'POPSUR', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPTAM', 'POPTAM', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPTIG', 'POPTIG', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPVAI', 'POPVAI', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPWB', 'POPWB', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'POPZOE', 'POPZOE', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '巴西', 'BR_PANGHU', '胖虎巴西', 'SSS55', 'SSS55', '{}'::jsonb),
  ('M8', '熊猫后台', 'PANDA', '菲律宾', 'PH', '菲律宾', 'PH19', 'PH19', '{}'::jsonb),
  ('M8', 'NPG系统', 'NPG', '哥伦比亚', 'CO', '哥伦比亚', 'NPG哥伦比亚', 'NPG哥伦比亚盘口', '{}'::jsonb),
  ('M8', 'NPG系统', 'NPG', '墨西哥', 'MX', '墨西哥', 'NPG墨西哥', 'NPG墨西哥盘口', '{}'::jsonb),
  ('M8', 'NPG系统', 'NPG', '智利', 'CL', '智利', 'NPG智利', 'NPG智利盘口', '{}'::jsonb),
  ('M8', 'KP系统', 'KP', '南美', 'SA', '南美', 'CO66', 'CO66', '{}'::jsonb)
on conflict (source_system, source_country, source_platform) do update
  set team_name=excluded.team_name,
      system_name=excluded.system_name,
      country_name=excluded.country_name,
      country_code=excluded.country_code,
      platform_name=excluded.platform_name,
      active=true,
      metadata=excluded.metadata,
      updated_at=now();

create index if not exists dashboard_platform_team_map_filters_idx
  on public.dashboard_platform_team_map (team_name, country_code, system_name, platform_name)
  where active;
create index if not exists dashboard_platform_team_map_lookup_idx
  on public.dashboard_platform_team_map (source_system, source_country, source_platform)
  where active;

comment on table public.dashboard_platform_team_map is 'Authoritative Supabase mapping for team, country, package system, and platform labels used by the private admin preview.';
