-- 07_账号细分权限_后台操作记录_待执行
-- 在已经完成的 dashboard_profiles 基础上增加：
-- 1) 每个 Viewer 的模块查看权限
-- 2) Admin 后台操作记录
-- 3) 三方数据 RLS 真正按权限控制

alter table public.dashboard_profiles
  add column if not exists permissions jsonb not null default '{"home":true,"third_party":true,"auto_withdraw":false,"work_orders":false,"customer_service":false}'::jsonb;

-- 已有 Admin 自动拥有全部模块权限；已有 Viewer 保持三方量可查看。
update public.dashboard_profiles
set permissions = case
  when role = 'admin' then '{"home":true,"third_party":true,"auto_withdraw":true,"work_orders":true,"customer_service":true}'::jsonb
  else coalesce(permissions, '{"home":true,"third_party":true,"auto_withdraw":false,"work_orders":false,"customer_service":false}'::jsonb)
end,
updated_at = now();

create table if not exists public.dashboard_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid null,
  actor_username text not null default '',
  action text not null,
  target_username text not null default '',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists dashboard_audit_log_created_idx
  on public.dashboard_audit_log(created_at desc);

alter table public.dashboard_audit_log enable row level security;
-- 不开放浏览器直接读取 audit log；Admin 通过 Edge Function 查看。

create or replace function public.dashboard_has_permission(permission_key text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.dashboard_profiles p
    where p.auth_user_id = auth.uid()
      and p.active = true
      and (
        p.role = 'admin'
        or coalesce((p.permissions ->> permission_key)::boolean, false) = true
      )
  );
$$;

revoke all on function public.dashboard_has_permission(text) from public;
grant execute on function public.dashboard_has_permission(text) to authenticated;

-- 三方数据：不再是“只要登录就能看”，必须有 third_party 权限。
drop policy if exists dashboard_read_third_party_volume on public.third_party_volume;
create policy dashboard_read_third_party_volume
on public.third_party_volume for select to authenticated
using (public.dashboard_has_permission('third_party'));

drop policy if exists dashboard_read_third_party_rates on public.third_party_rates;
create policy dashboard_read_third_party_rates
on public.third_party_rates for select to authenticated
using (public.dashboard_has_permission('third_party'));

drop policy if exists dashboard_read_third_party_platform_status on public.third_party_platform_status;
create policy dashboard_read_third_party_platform_status
on public.third_party_platform_status for select to authenticated
using (public.dashboard_has_permission('third_party'));

drop policy if exists dashboard_read_sync_status on public.sync_status;
create policy dashboard_read_sync_status
on public.sync_status for select to authenticated
using (public.dashboard_has_permission('third_party'));

-- 登录用户仍只能直接读取自己的 profile；Admin 的用户列表/修改/重置密码/日志/手动刷新全部走 Edge Function。
