/* Production is an authenticated, read-only bridge. Offline samples stay labelled samples. */
(function(){
 if(!window.HENSEM_PRODUCTION||typeof window.hensemLiveRequest!=='function')return;
 const previousRender=render,previousSync=syncFilters;const ratePage=pages.find(p=>p[0]==='rates');if(ratePage){ratePage[2]='费率表';ratePage[4]='费率表'}const teamPage=pages.find(p=>p[0]==='teams');if(teamPage){teamPage[2]='团队 / 平台归属';teamPage[4]='团队 / 平台归属'}const workPage=pages.find(p=>p[0]==='workorders');if(workPage){workPage[2]='申述工单';workPage[4]='申述工单'}if(state.page==='platform_systems')state.page='teams';
 if(!pages.some(p=>p[0]==='payout_config')){pages.push(['payout_config','▣','自动出款配置','AUTO PAYOUT CONFIGURATION','自动出款配置','']);const merchant=navGroupsV3.find(g=>g[0]==='merchant');if(merchant)merchant[3].splice(merchant[3].indexOf('deposit_tracking')+1,0,'payout_config')}
 if(!pages.some(p=>p[0]==='auto_withdraw')){pages.push(['auto_withdraw','▣','自动出款','AUTO WITHDRAWAL','自动出款','']);const merchant=navGroupsV3.find(g=>g[0]==='merchant');if(merchant)merchant[3].splice(merchant[3].indexOf('payout_config')+1,0,'auto_withdraw')}
 if(!pages.some(p=>p[0]==='withdraw_operators')){pages.push(['withdraw_operators','▣','操作人统计','WITHDRAWAL OPERATORS','操作人统计','']);const merchant=navGroupsV3.find(g=>g[0]==='merchant');if(merchant)merchant[3].splice(merchant[3].indexOf('auto_withdraw')+1,0,'withdraw_operators')}
 const isWithdrawPage=page=>['auto_withdraw','withdraw_operators'].includes(page);
 if(window.HensemLivePayoutConfig)HensemLivePayoutConfig.configure({request:r=>window.hensemLiveRequest(r),onChange:()=>{if(state.page==='payout_config')render()}});
 const providerPage=pages.find(p=>p[0]==='providers');if(providerPage){providerPage[2]='代收汇总';providerPage[4]='代收汇总'}
 if(!pages.some(p=>p[0]==='provider_payout')){pages.push(['provider_payout','⇄','代付汇总','PAYOUT SUMMARY','代付汇总','']);const group=navGroupsV3.find(g=>g[3].includes('providers'));if(group)group[3].splice(group[3].indexOf('providers')+1,0,'provider_payout')}
 const providerDirection=page=>page==='providers'?'charge':page==='provider_payout'?'withdraw':null;
 const L={comparisonResults:[],comparisonStatus:'idle',comparisonError:'',queryNow:Date.now(),overviewTab:'all',multi:{team:[],platform:[],source:[],provider:[],direction:[]},team:'all',providerOptions:[],providerOptionsKey:'',providerOptionsBusy:false,providerOptionsError:'',providerOptionsSerial:0,openMulti:'',multiSearch:{},providerConfigPlatform:'all',loadedView:'full',matrixMode:'range',catalog:[],results:[],catalogReady:false,loading:false,dirty:false,error:'',progress:'',serial:0,currency:'INR',country:'',countryTouched:false,platform:'all',source:'all',provider:'',direction:'all',status:'all',from:'',to:'',orderNumber:'',thirdPartyOrderNumber:'',memberId:'',systemOrderId:'',utr:'',page:1,size:20,detail:null,detailBusy:false,view:'business',feePage:1,feeSize:20,feeScope:'all',feeCountry:'all',feeQuery:'',localPage:1,localSize:20,groups:[],fees:null,feeError:'',feeLoading:false,feeSerial:0,feeLookupRows:null,feeLookupLoading:false,feeLookupError:'',feeLookupSerial:0,workorders:null,workordersLoading:false,workordersError:'',workordersPage:1,workordersSize:20,workordersSerial:0,autoWithdraw:null,autoWithdrawLoading:false,autoWithdrawError:'',autoWithdrawPage:1,autoWithdrawSize:20,autoWithdrawSerial:0,autoWithdrawPlatform:'all',autoWithdrawAccount:'',depositIssues:null,depositIssuesLoading:false,depositIssuesError:'',depositIssuesPage:1,depositIssuesSize:20,depositIssuesSerial:0,depositIssuesPlatform:'all',depositIssuesProvider:'',depositIssuesStatus:'all',depositIssuesQuery:'',providerConfig:null,providerConfigLoading:false,providerConfigError:'',providerConfigPage:1,providerConfigSize:20,providerConfigSerial:0,providerConfigRaw:'',providerConfigCanonical:'',providerConfigCountry:'all',providerConfigDirection:'all',providerConfigStatus:'all',platformAssignments:null,platformAssignmentsLoading:false,platformAssignmentsError:'',platformAssignmentsPage:1,platformAssignmentsSize:20,platformAssignmentsSerial:0,teamPlatformTeam:'all',teamPlatformCountry:'all',teamPlatformSystem:'all',teamPlatformQuery:'',teamPlatformStatus:'all'};
 L.feeView='original';if(window.HensemLiveRatesRestored)HensemLiveRatesRestored.configure({request:request=>window.hensemLiveRequest(request),onUnavailable:()=>{L.feeView='normalized';liveRates(true)}});
 if(['collection','providers'].includes(state.page))L.direction='charge';if(['payout','stuck','provider_payout'].includes(state.page))L.direction='withdraw';window.adminLive=L;
 const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const N=v=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('en-US',{maximumFractionDigits:2,minimumFractionDigits:2});
 const C=v=>Number(v||0).toLocaleString('en-US');
 const R=(n,d)=>Number(d)>0?(Number(n)/Number(d)*100).toFixed(2)+'%':'—';
 const directionName=d=>d==='charge'?'代收':d==='withdraw'?'代付':'全部';
 const statName=s=>({success:'成功',pending:'处理中',failed:'失败',rejected:'拒绝',unknown:'未知',all:'全部状态'}[s]||s);
 const countKeys=['all_count','success_count','pending_count','failed_count','rejected_count','unknown_count','missing_amount_count','created_success_count'];
 const amountKeys=['all_amount','success_amount','pending_amount','failed_amount','rejected_amount','unknown_amount'];
 const empty=()=>Object.fromEntries([...countKeys,...amountKeys].map(k=>[k,0]));
 function plus(rows){const sum=empty(),currencies=new Set((rows||[]).map(row=>row.currency).filter(value=>value!==null&&value!==undefined&&String(value)!=='')),mixedCurrencies=currencies.size>1;for(const row of rows){for(const k of countKeys)sum[k]+=Number(row[k]||0);for(const k of amountKeys){if(mixedCurrencies||row[k]===null||sum[k]===null)sum[k]=null;else sum[k]+=Number(row[k]||0)}}return sum}
 function combine(rows,keys){const groups=new Map();for(const r of rows){const id=keys.map(k=>r[k]??'').join('\x1f');if(!groups.has(id))groups.set(id,{...Object.fromEntries(keys.map(k=>[k,r[k]])),items:[],platformIds:new Set()});const g=groups.get(id);g.items.push(r);if(r.platformId)g.platformIds.add(r.platformId)}return [...groups.values()].map(g=>({...g,...plus(g.items),latest_synced_at:g.items.map(r=>r.latest_synced_at).filter(Boolean).sort().at(-1)||null,platform_count:g.platformIds.size}));}
 function groupRows(name){return L.results.flatMap(x=>(x.groups?.[name]||[]).map(r=>({...r,source:x.platform?.source,platformId:x.platform?.id,platform:x.platform?.name,country:x.platform?.country,scopeGroup:x.platform?.scopeGroup})));}
 function unknownProviderNotice(rows){const unknown=(rows||[]).filter(r=>{const value=String(r.provider??'').trim();return !value||value==='未识别通道'||value==='未提供'});if(!unknown.length)return '';const groups=combine(unknown,['direction','source','platform','country','currency']).sort((a,b)=>String(a.source).localeCompare(String(b.source))||String(a.direction).localeCompare(String(b.direction))||String(a.platform).localeCompare(String(b.platform)));const legacyPlatforms=[...new Set(groups.map(row=>(row.platform||'未提供平台')+' · '+(row.country||'未提供国家')))];const details=groups.map(row=>'<tr><td>'+E(row.source||'—')+'</td><td>'+E(row.platform||'未提供平台')+'</td><td>'+E(row.country||'未提供国家')+'</td><td>'+E(directionName(row.direction))+'</td><td>'+N(row.all_amount)+'</td><td>'+C(row.all_count)+'</td></tr>').join('');const total=plus(unknown);return '<div class="live-unknown-provider-note" role="status"><strong>需要你确认的未识别三方</strong><p>这些正式订单的原始通道字段为空，当前暂按“未识别通道”汇总。下面按来源、平台、国家、方向逐行列出金额和笔数；你确认对应三方后，我再补归类。</p><p>平台 / 国家：'+E(legacyPlatforms.join('、'))+'</p><div class="live-table table-wrap"><table><thead><tr><th>来源</th><th>平台</th><th>国家</th><th>方向</th><th>金额</th><th>笔数</th></tr></thead><tbody>'+details+'</tbody></table></div><p class="live-panel-note">未识别合计：'+N(total.all_amount)+' · '+C(total.all_count)+' 笔</p></div>'}
 function rateKey(value){return String(value??'').trim().toLowerCase().replace(/[\s._()（）-]+/g,'')}
 function feeDisplay(row){const percent=row?.collectFee??row?.payoutFee,single=row?.collectSingleFee??row?.payoutSingleFee;const p=percent===null||percent===undefined||String(percent).trim()===''?'':String(percent).trim(),s=single===null||single===undefined||String(single).trim()===''?'':String(single).trim();return p&&s?p+' / 单笔 '+s:p||s||''}
 function feeForRow(row){const rows=Array.isArray(L.feeLookupRows)?L.feeLookupRows:[];if(!rows.length||!row||!row.provider||['未识别通道','未提供'].includes(String(row.provider)))return L.feeLookupLoading?'读取中…':'未匹配';const provider=rateKey(row.provider),country=rateKey(L.country),direction=row.direction==='withdraw'?'payout':'collect',field=direction==='payout'?'payoutFee':'collectFee',single=direction==='payout'?'payoutSingleFee':'collectSingleFee';let candidates=rows.filter(r=>rateKey(r.provider)===provider&&String(r[field]??r[single]??'').trim()!=='');if(country)candidates=candidates.filter(r=>rateKey(r.country)===country||rateKey(r.scopeGroup)===country);const platforms=[...(row.platforms||[]),row.platform].filter(Boolean).map(rateKey);const platformRows=candidates.filter(r=>r.scopeType==='platform'&&platforms.includes(rateKey(r.platform)));const genericRows=candidates.filter(r=>r.scopeType!=='platform');candidates=platformRows.length?platformRows:genericRows;const values=[...new Set(candidates.map(r=>{const value=direction==='payout'?{payoutFee:r.payoutFee,payoutSingleFee:r.payoutSingleFee}:{collectFee:r.collectFee,collectSingleFee:r.collectSingleFee};return feeDisplay(value)}).filter(Boolean))];return values.length===1?values[0]:values.length?'多档费率':'未匹配'}
 async function ensureFeeLookup(force=false){if(!force&&(Array.isArray(L.feeLookupRows)||L.feeLookupLoading))return;if(!force&&L.feeLookupError)return;const serial=++L.feeLookupSerial;L.feeLookupLoading=true;L.feeLookupError='';render();try{const rows=[];let total=0;do{const result=await window.hensemLiveRequest({action:'rates',scopeType:'all',offset:rows.length,limit:500});if(serial!==L.feeLookupSerial)return;const page=Array.isArray(result?.rows)?result.rows:[];total=Number(result.total||0);if(total>20000||(!page.length&&rows.length<total))throw Error('费率目录不完整，请重试');rows.push(...page)}while(rows.length<total);L.feeLookupRows=rows;}catch(e){if(serial!==L.feeLookupSerial)return;L.feeLookupError=e.message||'费率读取失败';L.feeLookupRows=[];}finally{if(serial===L.feeLookupSerial){L.feeLookupLoading=false;render()}}}
 const summary=()=>plus(L.results.flatMap(x=>x.summary||[]));
 function option(value,label,current){return '<option value="'+E(value)+'" '+(value===current?'selected':'')+'>'+E(label)+'</option>'}
 function activeValues(key,allValue='all'){const values=Array.isArray(L.multi?.[key])?L.multi[key]:[];const value=L[key];if(value!==undefined&&value!==null&&value!==''&&value!==allValue&&(!values.length||values.length!==1||values[0]!==value))return [value];if(values.length)return values.slice();return []}
 function matchesFilter(key,value,allValue='all'){const values=activeValues(key,allValue);return !values.length||values.includes(value)}
 function multiCaption(key,items){const values=activeValues(key);const labels=items.filter(([value])=>values.includes(value)).map(([,label])=>label);return labels.length===0?'全部':labels.length===1?labels[0]:labels.length+' 项已选'}
 function multiSelect(key,label,items,wide=false){return HensemLiveFilters.multi({key,label,items:items.filter(([value])=>value!==''&&value!=='all'),values:activeValues(key),open:L.openMulti===key,search:L.multiSearch[key]||'',wide,busy:key==='provider'&&L.providerOptionsBusy,error:key==='provider'?L.providerOptionsError:''})}
 window.liveMultiToggle=function(el){if(!el?.isConnected)return;const key=el.dataset.multi;if(el.open){L.openMulti=key;document.querySelectorAll('details[data-multi]').forEach(other=>{if(other!==el)other.open=false})}else if(L.openMulti===key)L.openMulti=''};
 window.liveMultiSearch=function(key,value){L.multiSearch[key]=value;const root=document.querySelector('details[data-multi="'+key+'"]');if(!root)return;let count=0;root.querySelectorAll('.live-multi-option').forEach(row=>{row.hidden=!row.dataset.search.includes(value.toLocaleLowerCase());if(!row.hidden)count++});root.querySelector('.live-multi-empty').hidden=count>0;};
 window.liveMultiAll=function(key,all){const root=document.querySelector('details[data-multi="'+key+'"]');if(!root)return;const values=all?[...new Set([...activeValues(key),...Array.from(root.querySelectorAll('.live-multi-option:not([hidden]) input')).map(e=>e.value)])]:[];setMultiValues(key,values)};
 document.addEventListener?.('click',e=>{if(e.target.closest?.('.live-multi'))return;L.openMulti='';document.querySelectorAll('details[data-multi]').forEach(el=>el.open=false)});
 document.addEventListener?.('keydown',e=>{if(e.key!=='Escape')return;document.querySelectorAll('details[data-multi][open]').forEach(el=>{el.open=false;el.querySelector('summary')?.focus()});L.openMulti=''});
 async function loadProviderOptions(force=false){
   if(!L.catalogReady)return;const ids=selected().map(p=>p.id).sort(),key=JSON.stringify([ids,L.direction]);if(!force&&key===L.providerOptionsKey)return;
   const serial=++L.providerOptionsSerial;L.providerOptionsKey=key;L.providerOptionsBusy=true;L.providerOptionsError='';L.providerOptions=[];render();
   try{const result=await window.hensemLiveRequest({action:'providerOptions',platformIds:ids,direction:L.direction});if(serial!==L.providerOptionsSerial)return;L.providerOptions=result.providers||[];}
   catch(e){if(serial!==L.providerOptionsSerial)return;L.providerOptionsError=e.message||'归类目录读取失败';L.providerOptionsKey='';}
   finally{if(serial===L.providerOptionsSerial){L.providerOptionsBusy=false;render()}}
 }

 function select(key,label,items,wide=false){return '<div class="live-field '+(wide?'wide':'')+'"><label for="live-'+key+'">'+label+'</label><select '+(key==='country'?'required aria-required="true" ':'')+'id="live-'+key+'" onchange="liveSet(\''+key+'\',this.value)">'+items.map(([v,l])=>option(v,l,L[key])).join('')+'</select></div>'}
 function input(key,label,type='text',extra=''){return '<div class="live-field '+(type==='datetime-local'?'clock':'')+'"><label for="live-'+key+'">'+label+'</label><input id="live-'+key+'" type="'+type+'" '+(type==='datetime-local'?'step="1"':'maxlength="200" placeholder="完整值精确匹配"')+' value="'+E(L[key])+'" onchange="liveSet(\''+key+'\',this.value)" '+extra+'></div>'}
 const countryScope=()=>false;const selected=()=>L.catalog.filter(p=>(!!L.country&&p.country===L.country)&&matchesFilter('source',p.source)&&matchesFilter('platform',p.id)&&matchesFilter('team',p.team||'__unassigned__'));
 const selectedCurrencies=()=>[...new Set(selected().map(p=>p.currency).filter(Boolean))];
 function syncCurrency(){const currencies=selectedCurrencies();L.currency=currencies.length===1?currencies[0]:currencies.length?'多币种':'—';}
 function localClock(epoch,zone){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(epoch).map(x=>[x.type,x.value]));return p.year+'-'+p.month+'-'+p.day+'T'+p.hour+':'+p.minute+':'+p.second}
 function instant(value,zone,end=false){const full=value.length===16?value+':00':value;if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$/.test(full))throw Error('请输入日期、小时、分钟和秒');const wall=Date.parse(full+'Z');if(!Number.isFinite(wall)||new Date(wall).toISOString().slice(0,19)!==full)throw Error('日期时间无效');const offsets=new Set([-48,-24,0,24,48].map(h=>{const e=wall+h*3600000;return Date.parse(localClock(e,zone)+'Z')-e}));const candidates=[...offsets].map(o=>wall-o).filter(e=>localClock(e,zone)===full);if(candidates.length!==1)throw Error('平台时区存在跳时或重复时间，请调整边界');return new Date(candidates[0]+(end?1000:0)).toISOString()}
 function table(headers,rows,classes='',footerRows=[]){return '<div class="live-table table-wrap '+classes+'"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody>'+(footerRows.length?'<tfoot>'+footerRows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tfoot>':'')+'</table>'+(rows.length?'':'<div class="live-empty">当前筛选范围没有已入库记录</div>')+'</div>'}
 function box(title,body,note='',tools=''){return '<section class="panel"><div class="panel-head"><h2>'+title+'</h2>'+tools+'</div>'+body+(note?'<div class="live-panel-note">'+note+'</div>':'')+'</section>'}
 function metric(label,value,sub=''){return '<div class="live-metric"><label>'+label+'</label><strong>'+value+'</strong>'+(sub?'<small>'+sub+'</small>':'')+'</div>'}
 function comparisonRows(direction){return L.comparisonResults.flatMap(x=>x.summary||[]).filter(r=>!direction||r.direction===direction)}
 function comparisonNote(){
  if(L.comparisonStatus==='loading')return '<span class="live-compare muted">对比读取中</span>';
  if(L.comparisonStatus!=='ready')return '<span class="live-compare muted" title="'+E(L.comparisonError||'对比尚未读取')+'">对比暂不可用</span>';
  return '';
 }
 function compareMetric(key,current,rate=false,direction){
  const pending=comparisonNote();if(pending)return pending;const previous=plus(comparisonRows(direction));
  const d=rate?HensemLiveCompare.rateDelta(current.success_count,current.all_count,previous.success_count,previous.all_count):HensemLiveCompare.delta(current[key],previous[key]);
  return '<span class="live-compare '+E(d.trend)+'">'+E(L.comparisonLabel||'较前一日')+' '+E(d.display)+'</span>';
 }
 function comparisonCaption(){
  const q=L.results[0],prior=L.comparisonResults[0],zone=q?.platform?.timezone;
  const cur=q?E(formatTime(q._parts?.[0]?.startAt||q.startAt,zone))+' 至 '+E(formatTime(new Date(Date.parse(q._parts?.at(-1)?.endAt||q.endAt)-1000).toISOString(),zone)):'';
  const prev=prior?E(formatTime(prior._parts?.[0]?.startAt||prior.startAt,zone))+' 至 '+E(formatTime(new Date(Date.parse(prior._parts?.at(-1)?.endAt||prior.endAt)-1000).toISOString(),zone)):'';
  return '<div class="live-comparison-caption"><b>'+directionName(L.direction)+'</b><span>本期 '+cur+'</span>'+(L.comparisonStatus==='ready'?'<span>对比 '+prev+'</span>':'<span>'+E(L.comparisonStatus==='loading'?'正在读取前期同范围数据':L.comparisonError||'对比暂不可用')+'</span>')+'<span>同平台、同方向、同筛选；全部按创建时间、成功按成功时间；金额按各平台币种分别核算，成功率对比为百分点</span></div>';
 }
 function visibleDirections(){return L.direction==='all'?['charge','withdraw']:[L.direction]}
 function totals(){return HensemLiveLayout.totals({directions:visibleDirections().map(direction=>({key:direction,label:directionName(direction),summary:plus(L.results.flatMap(r=>r.summary||[]).filter(r=>r.direction===direction)),previous:plus(comparisonRows(direction))})),currency:L.currency,comparisonStatus:L.comparisonStatus,comparisonLabel:L.comparisonLabel,comparisonError:L.comparisonError,money:N,count:C,rate:R})}

 function businessCells(r){return [N(r.all_amount),C(r.all_count),N(r.success_amount),C(r.success_count),N(r.pending_amount),C(r.pending_count),N(r.failed_amount),C(r.failed_count),R(r.success_count,r.all_count)]}
 const businessHeaders=['全部金额','全部笔数','成功金额','成功笔数','处理中金额','处理中笔数','失败金额','失败笔数','成功率'];
 function pager(total,page,size,kind){const max=Math.max(1,Math.ceil(total/size)),start=Math.max(1,Math.min(page-3,max-6)),end=Math.min(max,start+6);let nums='';for(let p=start;p<=end;p++)nums+='<button '+(p===page?'class="on"':'')+' onclick="livePage('+p+',\''+kind+'\')">'+p+'</button>';return '<div class="live-pager"><span>共 <b>'+C(total)+'</b> 条　'+(total?C((page-1)*size+1)+'–'+C(Math.min(page*size,total)):'0')+'</span><div class="right"><select aria-label="每页条数" onchange="livePageSize(this.value,\''+kind+'\')">'+[20,30,50,100,500].map(n=>option(n,n+' 条 / 页',size)).join('')+'</select><button '+(page===1?'disabled':'')+' onclick="livePage(1,\''+kind+'\')">首页</button><button '+(page===1?'disabled':'')+' onclick="livePage('+(page-1)+',\''+kind+'\')">上一页</button>'+nums+'<button '+(page>=max?'disabled':'')+' onclick="livePage('+(page+1)+',\''+kind+'\')">下一页</button><button '+(page>=max?'disabled':'')+' onclick="livePage('+max+',\''+kind+'\')">尾页</button><span>共 '+C(max)+' 页　前往</span><input id="live-jump-'+kind+'" type="number" min="1" max="'+max+'" aria-label="跳转页码"><span>页</span><button onclick="liveJump(\''+kind+'\','+max+')">确定</button></div></div>'}
 function pagedTable(headers,rows,title,note=''){L.groups=rows;const max=Math.max(1,Math.ceil(rows.length/L.localSize));L.localPage=Math.min(L.localPage,max);return box(title,table(headers,rows.slice((L.localPage-1)*L.localSize,L.localPage*L.localSize))+pager(rows.length,L.localPage,L.localSize,'local'),note)}
 function pairedTable(title,headers,rows,note,kind,footerRows=[]){const all=rows||[],max=Math.max(1,Math.ceil(all.length/L.localSize)),page=Math.min(L.localPage,max),from=(page-1)*L.localSize;L.localPage=page;return box(title,table(headers,all.slice(from,from+L.localSize),'',footerRows)+pager(all.length,page,L.localSize,kind||'local'),note)}
 function directionFooter(label,rows,sourceColumns=0,tailColumns=0){const total=plus(rows||[]),platforms=(rows||[]).reduce((n,row)=>n+Number(row.platform_count||0),0);return ['<strong>'+E(label)+'</strong>',...Array.from({length:sourceColumns},()=>'<span class="muted">—</span>'),C(platforms),...businessCells(total),...Array.from({length:tailColumns},()=>'<span class="muted">—</span>')]}
 function businessFooter(label,rows,prefixColumns=0,tailColumns=0){return ['<strong>'+E(label)+'</strong>',...Array.from({length:prefixColumns},()=>'<span class="muted">—</span>'),...businessCells(plus(rows||[])),...Array.from({length:tailColumns},()=>'<span class="muted">—</span>')]}
 function providersView(){const sourceRows=groupRows('provider'),rows=combine(sourceRows,['source','provider','direction','currency']).sort((a,b)=>b.all_count-a.all_count),headers=['三方','来源','平台数',...businessHeaders,'手续费'];if(L.feeLookupRows===null&&!L.feeLookupLoading)ensureFeeLookup();return unknownProviderNotice(sourceRows)+'<div class="grid equal live-paired-dimensions">'+visibleDirections().map(d=>{const subset=rows.filter(r=>r.direction===d);return pairedTable('三方经营汇总 · '+directionName(d),headers,subset.map(r=>['<button class="link" onclick="liveProvider('+E(JSON.stringify(r.provider))+')">'+E(r.provider||'未提供')+'</button>',E(r.source||'—'),C(r.platform_count),...businessCells(r),E(feeForRow(r))]),'金额与笔数独立展示；'+directionName(d)+'无数据时仍保留空表。','local',[directionFooter(directionName(d)+'汇总',subset,1,1)]);}).join('')+'</div>'}
 function platformsView(){const rows=L.results.flatMap(r=>(r.summary||[]).map(x=>({...x,platform:r.platform}))).sort((a,b)=>b.all_count-a.all_count),headers=['平台','来源','授权分组',...businessHeaders,'源数据更新时间'];return '<div class="grid equal live-paired-dimensions">'+visibleDirections().map(d=>{const subset=rows.filter(r=>r.direction===d);return pairedTable('平台经营汇总 · '+directionName(d),headers,subset.map(r=>['<button class="link" onclick="liveChoosePlatform(\''+E(r.platform.id)+'\')">'+E(r.platform.name)+'</button>',E(r.platform.source),E(r.platform.scopeGroup||'未绑定'),...businessCells(r),E(formatTime(r.latest_synced_at,r.platform.timezone))]),'正式数据范围由账号权限控制；'+directionName(d)+'无数据时仍保留空表。','local',[businessFooter(directionName(d)+'汇总',subset,2,1)]);}).join('')+'</div>'}
 function chart(rows){const hours=Array.from({length:24},(_,hour)=>({...plus(rows.filter(r=>Number(r.hour)===hour)),hour})),max=Math.max(1,...hours.map(r=>r.all_count)),w=700,h=155;let svg='<svg class="live-chart" viewBox="0 0 760 210" role="img" aria-label="当地创建小时全部与成功笔数">';for(let i=0;i<4;i++){const y=15+i*h/3;svg+='<line x1="43" x2="742" y1="'+y+'" y2="'+y+'"/><text x="34" y="'+(y+3)+'" text-anchor="end">'+C(Math.round(max*(3-i)/3))+'</text>'}for(const [key,color]of[['all_count','#4e75ed'],['success_count','#35a697']])svg+='<polyline fill="none" stroke="'+color+'" stroke-width="2.4" points="'+hours.map((r,i)=>(43+i*w/23)+','+(15+h-r[key]/max*h)).join(' ')+'"/>';for(let i=0;i<24;i+=3)svg+='<text x="'+(43+i*w/23)+'" y="193" text-anchor="middle">'+String(i).padStart(2,'0')+':00</text>';return svg+'</svg><div class="live-legend"><span>● 全部笔数</span><span style="color:#35a697">● 成功笔数</span><span>全部 / 处理中按各平台当地创建小时；成功按各平台当地成功小时</span></div>'}
 function overview(){
  const tabs=[['all','经营全景'],['providers','三方表现'],['dimensions','平台 / 国家 / 团队'],['amount','金额档位'],['time','24小时 / 每日'],['latency','成功时效'],...(L.direction!=='charge'?[['pending','代付中等待']]:[]),['coverage','费用 / 工单 / 风险']];
  if(!tabs.some(([key])=>key===L.overviewTab))L.overviewTab='all';
  const nav='<nav class="live-overview-tabs" aria-label="总览分类">'+tabs.map(([key,label])=>'<button class="'+(L.overviewTab===key?'on':'')+'" onclick="liveOverviewTab(\''+key+'\')">'+label+'</button>').join('')+'</nav>';
  let body='';
  if(L.overviewTab==='all')body=overviewPanorama();
  if(L.overviewTab==='providers')body=providersView();
  if(L.overviewTab==='dimensions')body=overviewDimensions()+platformsView();
  if(L.overviewTab==='amount')body=overviewAmounts()+box('24小时 × 金额档位',overviewMatrix(),'每一小时独立列；金额、笔数、成功率独立指标行。');
  if(L.overviewTab==='time')body='<div class="live-charts">'+visibleDirections().map(d=>box(directionName(d)+' · 24小时订单笔数',overviewChart(false,d))+box(directionName(d)+' · 24小时订单金额',overviewChart(true,d))).join('')+'</div>'+overviewDaily();
  if(L.overviewTab==='latency')body=overviewDurationSummary(false)+latencyView(false);
  if(L.overviewTab==='pending')body=overviewDurationSummary(true)+latencyView(true);
  if(L.overviewTab==='coverage')body=overviewCoverage();
  return comparisonCaption()+totals()+nav+body;
 }
 window.liveOverviewTab=function(key){L.overviewTab=key;L.localPage=1;render()};
 function overviewStateTable(){return ''}

 function overviewChart(money,direction){
  const field=money?'all_amount':'all_count',success=money?'success_amount':'success_count';
  const current=groupRows('hourly').filter(r=>r.direction===direction),previous=L.comparisonResults.flatMap(r=>r.groups?.hourly||[]).filter(r=>r.direction===direction);
  const lines=[{name:'本期全部',color:'#4e75ed',rows:current,key:field},{name:'本期成功',color:'#35a697',rows:current,key:success},...(L.comparisonStatus==='ready'?[{name:'前期全部',color:'#a2afc5',rows:previous,key:field,dash:true}]:[])];
  for(const line of lines)line.points=Array.from({length:24},(_,hour)=>plus(line.rows.filter(r=>Number(r.hour)===hour))[line.key]);
  const max=Math.max(1,...lines.flatMap(l=>l.points).filter(v=>v!==null));let svg='<svg class="live-chart" viewBox="0 0 760 210" role="img" aria-label="'+(money?'每小时金额与前期对比':'每小时笔数与前期对比')+'">';
  for(let i=0;i<4;i++){const y=15+i*155/3;svg+='<line x1="43" x2="742" y1="'+y+'" y2="'+y+'"/><text x="36" y="'+(y+3)+'" text-anchor="end">'+C(Math.round(max*(3-i)/3))+'</text>'}
  for(const line of lines){let segments=[];for(let i=0;i<24;i++){const v=line.points[i];if(v===null){if(segments.length)svg+='<polyline fill="none" stroke="'+line.color+'" stroke-width="2" points="'+segments.join(' ')+'"/>';segments=[];continue}segments.push((43+i*700/23)+','+(170-v/max*155))}if(segments.length)svg+='<polyline fill="none" stroke="'+line.color+'" stroke-width="2" '+(line.dash?'stroke-dasharray="5 4"':'')+' points="'+segments.join(' ')+'"/>'}
  for(let i=0;i<24;i+=3)svg+='<text x="'+(43+i*700/23)+'" y="193" text-anchor="middle">'+String(i).padStart(2,'0')+':00</text>';
  return svg+'</svg><div class="live-legend">'+lines.map(l=>'<span style="color:'+l.color+'">● '+l.name+'</span>').join('')+'</div>';
 }
 function overviewAmounts(){const field=L.matrixMode==='range'?'amount_range':'amount',rows=combine(groupRows(field),['direction','bucket']).sort((a,b)=>String(a.bucket).localeCompare(String(b.bucket),undefined,{numeric:true})),headers=['金额档位 · '+E(L.currency),'全部金额','全部笔数','成功金额','成功笔数','成功率','笔数占比'];return '<div class="grid equal live-paired-dimensions">'+visibleDirections().map(d=>{const total=plus(L.results.flatMap(x=>x.summary||[]).filter(x=>x.direction===d)).all_count;return box('金额档位分布 · '+directionName(d),table(headers,rows.filter(r=>r.direction===d).map(r=>[E(r.bucket==='other'?'其他金额':r.bucket==='unknown'?'金额缺失':r.bucket),N(r.all_amount),C(r.all_count),N(r.success_amount),C(r.success_count),R(r.success_count,r.all_count),R(r.all_count,total)])),'金额区间按 100–200、201–300… 不重叠；全部 / 处理中按创建时间，成功按成功时间；无数据方向仍保留空表。')}).join('')+'</div>'}
 function overviewMatrix(){return visibleDirections().map(d=>'<h3 class="live-subheading">'+directionName(d)+'</h3>'+matrixBody(d)).join('')}
 function overviewDaily(){const rows=combine(groupRows('daily'),['direction','date']).sort((a,b)=>String(a.date).localeCompare(String(b.date)));return pagedTable(['方向','当地日期',...businessHeaders],rows.map(r=>[directionName(r.direction),E(r.date),...businessCells(r)]),'每日经营明细')}
 function overviewDimensions(){const raw=L.results.flatMap(result=>(result.summary||[]).map(r=>({...r,platformId:result.platform.id,country:result.platform.country,source:result.platform.source,team:result.platform.team||'未绑定团队'})));const sections=[['国家 / 授权分组','country'],['包网来源','source'],['团队归属','team']];return '<div class="live-dimension-grid">'+sections.map(([title,key])=>{const rows=combine(raw,[key,'direction']);return box(title,table([title,'方向','平台数','全部金额','全部笔数','成功率'],rows.map(r=>[E(r[key]),directionName(r.direction),C(r.platform_count),N(r.all_amount),C(r.all_count),R(r.success_count,r.all_count)])))}).join('')+'</div>'}
 function overviewDurationSummary(pending){return (pending?['withdraw']:visibleDirections()).map(direction=>{const rows=combineAging(L.results.flatMap(r=>r.groups?.[pending?'pending_age':'latency']||[]).filter(r=>r.direction===direction)),valid=rows.reduce((n,r)=>n+Number(r.count||0),0),money=rows.some(r=>r.amount===null)?null:rows.reduce((n,r)=>n+Number(r.amount||0),0),s=plus(L.results.flatMap(r=>r.summary||[]).filter(r=>r.direction===direction)),all=pending?s.pending_count:s.success_count;return '<h3 class="live-subheading">'+directionName(direction)+(pending?'等待时效':'成功时效')+'</h3><div class="live-mini-stats">'+metric(pending?'有效等待笔数':'有效成功时效笔数',C(valid))+metric('有效时效金额',N(money))+metric('有效时间覆盖率',R(valid,all))+metric('无有效时间笔数',C(Math.max(0,all-valid)))+'</div>'}).join('')}

 function overviewCoverage(){return '<div class="live-coverage-grid">'+[['当前费率','已接入正式配置，代收、代付、单笔费和限额独立列。','rates','查看费率表'],['手续费估算','复杂阶梯费率尚未逐单匹配，历史生效版本待补齐。','','未计算'],['申述工单','正式工单按代收、代付分开展示，包含存款与取款未到账记录。','workorders','查看申述工单'],['存款未到账明细','Google Sheet「UPI核对」安全字段已同步到 Supabase，页面只读同步后的正式数据。','deposit_tracking','查看存款明细'],['掉单 / 风险事件','正式订单接口不包含核对标记与风险事件，暂不生成虚构数量。','data_health','查看数据覆盖'],['团队归属 / 在线账号','未绑定团队独立列示；真实在线心跳尚未接入。','data_health','查看数据覆盖']].map(([title,text,page,action])=>'<article><h3>'+title+'</h3><p>'+text+'</p>'+(page?'<button class="link" onclick="setPage(\''+page+'\')">'+action+' →</button>':'<span class="muted">'+action+'</span>')+'</article>').join('')+'</div>'}
 function overviewPanorama(){const a=summary(),raw=combine(groupRows('provider'),['provider','source','direction']),providers=raw.sort((a,b)=>b.all_count-a.all_count).slice(0,8),countries=new Set(L.results.map(r=>r.platform.country)),teams=new Set(L.results.map(r=>r.platform.team).filter(Boolean));const coverage='<div class="live-mini-stats">'+metric('有订单平台数',C(L.results.filter(r=>r.total>0).length))+metric('三方原始通道数',C(raw.length))+metric('国家 / 授权分组',C(countries.size))+metric('已绑定团队数',C(teams.size))+'</div>';return coverage+overviewStateTable()+'<div class="live-charts">'+visibleDirections().map(d=>box(directionName(d)+' · 24小时订单笔数',overviewChart(false,d))+box(directionName(d)+' · 24小时订单金额',overviewChart(true,d))).join('')+'</div>'+'<div class="live-charts">'+box('三方占比 · 前8项',table(['三方','来源','方向','全部金额','全部笔数','成功率','笔数占比'],providers.map(r=>[E(r.provider),E(r.source),directionName(r.direction),N(r.all_amount),C(r.all_count),R(r.success_count,r.all_count),R(r.all_count,plus(L.results.flatMap(x=>x.summary||[]).filter(x=>x.direction===r.direction)).all_count)])),'', '<button class="link" onclick="liveOverviewTab(\'providers\')">全部三方 →</button>')+overviewAmounts()+'</div>'+overviewDurationSummary(false)+latencyView(false)+(L.direction!=='charge'?overviewDurationSummary(true)+latencyView(true):'')+overviewDimensions()+platformsView()+overviewCoverage()}
 function timeView(){const rows=combine(groupRows('hourly'),['direction','hour']).sort((a,b)=>Number(a.hour)-Number(b.hour));return totals()+visibleDirections().map(d=>box(directionName(d)+' · 24 小时全部 / 成功订单',chart(rows.filter(r=>r.direction===d)))).join('')+pagedTable(['方向','创建小时',...businessHeaders],rows.map(r=>[directionName(r.direction),String(r.hour).padStart(2,'0')+':00–'+String(r.hour).padStart(2,'0')+':59:59',...businessCells(r)]),'每小时经营明细')}
 function amountView(){const field=L.matrixMode==='range'?'amount_range':'amount',rows=combine(groupRows(field),['direction','bucket']).sort((a,b)=>String(a.bucket).localeCompare(String(b.bucket),undefined,{numeric:true}));return totals()+overviewAmounts()+box('金额档位与订单状态',table(['方向','金额档位 · '+E(L.currency),...businessHeaders],rows.map(r=>[directionName(r.direction),E(r.bucket==='other'?'其他金额':r.bucket==='unknown'?'金额缺失':r.bucket),...businessCells(r)])),'金额区间按 100–200、201–300… 不重叠；全部 / 处理中按创建时间，成功按成功时间；切换“精确金额”可查看原始金额档位。')}
 function matrixBody(direction){const field=L.matrixMode==='range'?'matrix_range':'matrix',rows=combine(groupRows(field).filter(r=>r.direction===direction),['bucket','hour']),exact=['100','200','300','400','500','750','1000','1500','2000','5000'],ranges=['100–200','201–300','301–400','401–500','501–750','751–1,000','1,001–2,000','2,001–5,000','≥5,001'];const bands=L.matrixMode==='range'?ranges:exact,buckets=[...bands,...[...new Set(rows.map(r=>r.bucket))].filter(b=>!bands.includes(b))];return '<div class="live-definition">每格从上到下：① 全部笔数　② 全部金额（'+E(L.currency)+'）　③ 成功率；区间不重复</div>'+table(['金额 / 时',...Array.from({length:24},(_,h)=>String(h).padStart(2,'0')+'时')],buckets.map(bucket=>[E(bucket==='other'?'其他金额':bucket==='unknown'?'金额缺失':bucket),...Array.from({length:24},(_,hour)=>{const r=rows.find(r=>r.bucket===bucket&&Number(r.hour)===hour)||empty();return '<div class="matrix-cell"><b>'+C(r.all_count)+'笔</b><span>'+N(r.all_amount).replace(/\.00$/,'')+'</span><span>'+R(r.success_count,r.all_count)+'</span></div>'})]),'live-matrix')}
 function matrixView(){const tools='<div class="live-tabs"><button class="'+(L.matrixMode==='exact'?'on':'')+'" onclick="liveMatrixMode(\'exact\')">精确金额</button><button class="'+(L.matrixMode==='range'?'on':'')+'" onclick="liveMatrixMode(\'range\')">金额区间</button></div>';return totals()+'<div class="section-switcher"><div class="tabs"><button class="'+(L.view!=='matrixDetail'?'on':'')+'" onclick="liveView(\'business\')">24 小时 × 金额段</button><button class="'+(L.view==='matrixDetail'?'on':'')+'" onclick="liveView(\'matrixDetail\')">高频组合的订单状态</button></div></div>'+(L.view==='matrixDetail'?matrixDetail():visibleDirections().map(d=>box(directionName(d)+' · 24 小时 × 金额段',matrixBody(d),'',tools)).join(''))}
 window.liveMatrixMode=function(mode){if(!['exact','range'].includes(mode))return;L.matrixMode=mode;render()};
 function matrixDetail(){const field=L.matrixMode==='range'?'matrix_range':'matrix',rows=groupRows(field).sort((a,b)=>b.all_count-a.all_count);return pagedTable(['方向','金额档位','创建小时',...businessHeaders],rows.map(r=>[directionName(r.direction),E(r.bucket),String(r.hour).padStart(2,'0')+'时',...businessCells(r)]),'高频组合的订单状态')}

 function dailyView(){const rows=combine(groupRows('daily'),['source','provider','date','direction','currency']).sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(a.provider).localeCompare(String(b.provider)));const dates=[...new Set(rows.map(r=>r.date))].sort();const entities=combine(rows,['source','provider','direction']);const tabs='<div class="live-tabs"><button class="'+(L.view!=='dailyMatrix'?'on':'')+'" onclick="liveView(\'dailyList\')">每日金额 / 笔数明细</button><button class="'+(L.view==='dailyMatrix'?'on':'')+'" onclick="liveView(\'dailyMatrix\')">每日成功率横向对比</button></div>';return totals()+tabs+(L.view==='dailyMatrix'?box('三方每日成功率',table(['三方','来源','方向',...dates.map(d=>E(d.slice(5)))],entities.map(e=>[E(e.provider),E(e.source),directionName(e.direction),...dates.map(date=>{const r=rows.find(r=>r.date===date&&r.source===e.source&&r.provider===e.provider&&r.direction===e.direction);return r?R(r.success_count,r.all_count):'—'})])),'最多31天；无订单为 —，不当作0%失败。'):pagedTable(['日期','三方','来源','方向',...businessHeaders],rows.map(r=>[E(r.date),E(r.provider),E(r.source),directionName(r.direction),...businessCells(r)]),'逐日三方经营数据'))}
 function formatTime(value,zone){if(!value)return '—';const e=Date.parse(value);return Number.isFinite(e)?localClock(e,zone||'UTC').replace('T',' '):'—'}
 function detailsView(){const fee=L.view==='orderFees',version=L.view==='orderRates',d=L.detail,platform=d?.platform||selected()[0],zone=platform?.timezone;const headers=version?['订单号','系统 ID','平台','三方','方向','百分比费率','固定费','费率版本','生效时间','失效时间','计费状态','操作']:fee?['订单号','系统 ID','平台','团队','三方','方向','订单金额','估算手续费','实际手续费','计费状态','费率版本','创建时间','操作']:['订单号','系统 ID','平台','团队','国家','三方','方向','订单金额','状态','核对标记','创建时间','操作'];
 const rows=(d?.rows||[]).map((r,i)=>{const no='<button class="link mono" onclick="liveOrder('+i+')">'+E(r.order_number||r.orderNumber||r.order_no||'—')+'</button>',id=E(r.system_order_id||r.source_id||r.id||'—'),pn=E(platform?.name||'—'),provider=E(r.provider||'未提供'),dir=directionName(r.direction),action='<button class="link" onclick="liveOrder('+i+')">查看 →</button>',team=E(platform?.team||'未绑定团队'),time=E(formatTime(r.created_at,zone));if(version)return [no,id,pn,provider,dir,'—','—','—','—','—','未匹配',action];if(fee)return [no,id,pn,team,provider,dir,N(r.amount),'—',N(r.withdraw_fee),'未匹配','—',time,action];return [no,id,pn,team,E(platform?.country||'—'),provider,dir,N(r.amount),'<span class="live-badge '+E(r.status_group||r.status)+'">'+E(statName(r.status_group||r.status))+'</span>','—',time,action]});
 let info=L.platform==='all'?'<div class="live-status">请选择商户（平台）后查询逐笔订单。汇总统计包含当前全部授权平台。</div>':L.detailBusy?'<div class="live-status">正在读取订单页…</div>':!d?'<div class="live-status">点击查询读取订单明细</div>':'';
 return box('订单列表',info+table(headers,rows,'order-columns-v4')+pager(Number(d?.total||0),L.page,L.size,'server'),version?'历史费率版本与生效时间未接入，保持空值':fee?'费用独立列；实际手续费仅展示来源已提供值':'各字段独立展示 · 时间按订单国家转换');}

 function durationRows(groups,direction,cumulative){const rows=combineAging((groups||[]).filter(r=>r.direction===direction));if(rows.length)return rows.sort((a,b)=>Number(a.bucket)-Number(b.bucket));const bounds=[300000,1800000,3600000,10800000,21600000,43200000,86400000,172800000,259200000,null];return Array.from({length:cumulative?9:10},(_,i)=>({direction,bucket:i,threshold_ms:bounds[i],min_ms:i?bounds[i-1]:null,max_ms:bounds[i],count:0,amount:0,denominator_count:0,denominator_amount:0}))}
 function durationFooter(direction,rows,pending){const summaryRow=plus(L.results.flatMap(x=>x.summary||[]).filter(r=>r.direction===direction)),validCount=Math.max(0,...rows.map(r=>Number(r.denominator_count||0))),validAmount=rows.some(r=>r.denominator_amount===null)?null:Math.max(0,...rows.map(r=>Number(r.denominator_amount||0))),candidateCount=Number(summaryRow[pending?'pending_count':'success_count']||0),candidateAmount=summaryRow[pending?'pending_amount':'success_amount'],excludedCount=Math.max(0,candidateCount-validCount),excludedAmount=candidateAmount===null||candidateAmount===undefined||validAmount===null?null:Math.max(0,Number(candidateAmount)-validAmount),label=pending?'本期仍代付中':'成功订单';return [['<strong>'+label+'待核对</strong>',N(excludedAmount),C(excludedCount),'—','—'],['<strong>'+label+'合计</strong>',N(candidateAmount),C(candidateCount),'—','—']]}
 function latencyView(pending=false){const cumulative=L.view==='thresholds',name=(pending?'pending_age':'latency')+(cumulative?'_thresholds':''),groups=L.results.flatMap(x=>{const data=x.groups?.[name];return Array.isArray(data)?data:[]}),directions=pending?['withdraw']:visibleDirections(),headers=['耗时区间','金额 · '+E(L.currency),'笔数','笔数占比','金额占比'],tabs='<div class="live-tabs"><button class="'+(!cumulative?'on':'')+'" onclick="liveView(\'bands\')">互斥时长区间</button><button class="'+(cumulative?'on':'')+'" onclick="liveView(\'thresholds\')">超过指定时长</button></div>',panels=directions.map(direction=>{const rows=durationRows(groups,direction,cumulative),label=direction==='charge'?'充值 / 代收成功耗时':'提款 / 代付成功耗时',note=pending?'等待时长 = 各分段查询时间 − 创建时间；仅当前选定创建日期范围，非历史全部存量。':'按来源记录的成功时间 − 提交时间；时间无效订单不计入耗时分母。GAME66提款成功时间可能为源更新时间代理。';return box(label,table(headers,rows.map(r=>[E(durationLabel(r,cumulative)),N(r.amount),C(r.count),R(r.count,r.denominator_count),R(r.amount,r.denominator_amount)]),'',durationFooter(direction,rows,pending)),note)}).join('');return tabs+box(pending?'所选创建范围 · 仍待付订单等待时长':'充值 / 提款成功耗时分布','<div class="grid equal live-duration-paired">'+panels+'</div>',pending?'代付等待按当前创建日期范围统计；分段读取非同一冻结快照，源同步可能滞后。':'代收左、代付右分开显示；各方向占比分母为有效时间订单。')}
 function durationLabel(r,cumulative){const names={300000:'5分钟',1800000:'30分钟',3600000:'1小时',10800000:'3小时',21600000:'6小时',43200000:'12小时',86400000:'1天',172800000:'2天',259200000:'3天'};return cumulative?'超过 '+(names[r.threshold_ms]||r.threshold_ms+'毫秒'):r.min_ms==null?'5分钟以内':r.max_ms==null?'超过3天':(names[r.min_ms]||'0')+'–'+names[r.max_ms]}
 function combineAging(rows){const m=new Map();for(const r of rows){const key=[r.direction,r.bucket,r.kind].join('|');if(!m.has(key))m.set(key,{...r,count:0,amount:0,denominator_count:0,denominator_amount:0});const x=m.get(key);x.count+=Number(r.count||0);x.amount=x.amount===null||r.amount===null?null:x.amount+Number(r.amount||0);x.denominator_count+=Number(r.valid_count||0);x.denominator_amount=x.denominator_amount===null||r.valid_amount===null?null:x.denominator_amount+Number(r.valid_amount||0)}return [...m.values()]}
 function health(){return '<div class="live-health">'+[['正式订单','已连接生产库已采集订单。只读取账号范围内的平台；不代表采集前的源系统历史已完整入库。'],['成功率','同一平台、方向、币种、创建时间范围：成功笔数按成功时间；全部订单笔数按创建时间。跨币种分别查询。'],['费用','费率表展示当前正式配置原文；复杂阶梯费率尚未逐单匹配，不显示猜算费用。历史生效版本尚未入库。'],['待付与时效','待付只针对所选提交日期内仍待付记录。缺成功时间不会伪造耗时；源数据更新时间与查询时间分开。'],['工单','Google存款核对为读取快照。AR汇总仅有工单处理状态；新AR部分成功工单缺成功时间。'],['账号与在线','实际账号操作在右上角；当前尚未接入在线心跳，不展示模拟人数或虚构风险事件。']].map(([t,b])=>'<article><h3>'+t+'</h3><p>'+b+'</p></article>').join('')+'</div>'+pagedTable(['平台','来源','授权分组','时区','币种'],L.catalog.map(p=>[E(p.name),E(p.source),E(p.scopeGroup||p.country),E(p.timezone),E(p.currency)]),'当前授权内的正式平台','目录由数据库按当前账号数据范围返回。')}
 const gaps={dropped:['掉单核对','正式订单源没有已核对掉单标记；未成功订单不自动当作掉单。'],anomaly:['异常核对','金额、时间与状态缺失可在数据健康页查看；尚未连接真实异常事件流水。'],events:['风险事件','尚未连接持久风险事件；当前不会显示模拟预警。'],rules:['预警规则','自动风险调度未接入；规则设计样本保留在本地样本中。'],access:['账号与角色权限','右上角“查看授权”管理新版入口查看权限；实际账号与国家数据范围继续由现有管理后台控制。'],ip:['IP 白名单','此新版尚未接入正式IP策略，不能用本地勾选改变登录访问。'],login_logs:['登录日志','正式认证审计尚未接入本页，不展示样本账号登录记录。'],operation_logs:['操作日志','正式操作日志尚未接入本页，不展示模拟操作记录。'],teams:['团队平台配置','生产来源缺统一团队绑定，当前按源授权分组显示。原样本配置仍为本地草稿，不能改变正式数据授权。'],platform_systems:['平台包网系统配置','真实来源为AR / NEW_AR / GAME66，已加入全部业务筛选。业务包网名称绑定仍需正式配置表。']};
 function gapPage(key){return HensemLiveEmpty.render(key)}
 function ratesView(){if(L.feeView!=='normalized'&&window.HensemLiveRatesRestored)return HensemLiveRatesRestored.render();if(L.feeLoading)return '<div class="live-status">正在读取当前正式费率表…</div>';if(L.feeError)return '<div class="live-status live-error">'+E(L.feeError)+'</div>';if(!L.fees)return '<div class="live-empty">点击查询读取当前费率</div>';const rows=L.fees.rows||[],options=L.fees.options||{};const filter='<div class="live-filters">'+select('feeScope','费率范围',[['all','全部费率'],['country','国家通用'],['platform','指定平台']])+select('feeCountry','国家 / 授权分组',[['all','全部授权范围'],...(options.countries||[]).map(c=>[c.value,c.label])])+input('feeQuery','三方名称')+'<div class="live-actions"><button class="btn primary" onclick="liveRates(true,true)">查询</button></div></div>';return filter+box('当前三方费率表',table(['三方','范围','国家 / 分组','平台','代收费率','代收单笔费','代收限额','代付费率','代付单笔费','代付限额','状态','更新时间'],rows.map(r=>[E(r.provider),r.scopeType==='platform'?'平台专属':'国家通用',E(r.country||r.scopeGroup),E(r.platform||'—'),E(r.collectFee??'—'),E(r.collectSingleFee??'—'),E(r.collectLimit??'—'),E(r.payoutFee??'—'),E(r.payoutSingleFee??'—'),E(r.payoutLimit??'—'),E(r.status||r.rawStatus||'—'),E(r.updatedAt?formatTime(r.updatedAt,'Asia/Kolkata'):'—')]))+pager(Number(L.fees.total||0),L.feePage,L.feeSize,'fee'),'当前正式费率原文；通用费率与平台专属费率分列，不将复杂金额档简化为平均费率。历史生效版本暂缺。')}

 window.liveDurationSet=function(key,value){if(!['durationMode','durationGroup','durationThreshold','durationQuery','durationDetail','durationOrderQuery'].includes(key))return;L[key]=value;render()};
 window.liveReferenceSet=function(key,value){if(!['view','dailyView','dailyMetric','direction'].includes(key))return;if(key==='direction'){liveSet(key,value);liveLoad();return}L[key]=value;L.localPage=1;render()};
 window.liveReferenceDay=function(day){L.dailyDay=day;L.dailyView='selected';render()};
 window.liveReferenceEnd=function(day){if(!/^\d{4}-\d{2}-\d{2}$/.test(day))return;L.to=day+'T23:59:59';L.from=new Date(Date.parse(day+'T00:00:00Z')-30*86400000).toISOString().slice(0,10)+'T00:00:00';liveLoad()};
 function workorderRows(){return Array.isArray(L.workorders?.rows)?L.workorders.rows:[]}
 function workorderMetric(value,money=false){return money?N(value):C(value)}
 function workordersView(){
  if(L.workordersLoading)return '<div class="live-status">正在读取正式工单日汇总…</div>';
  if(L.workordersError)return '<div class="live-status live-error">'+E(L.workordersError)+'</div>';
  const result=L.workorders||{},summary=result.summary||{},by=result.byDirection||{},rows=workorderRows();
  const stats=[['提交金额',workorderMetric(summary.submittedAmount,true)],['提交笔数',workorderMetric(summary.submittedCount)],['到账成功金额',workorderMetric(summary.successAmount,true)],['到账成功笔数',workorderMetric(summary.successCount)],['未到账金额',workorderMetric(summary.notReceivedAmount,true)],['未到账笔数',workorderMetric(summary.notReceivedCount)]];
  const cards='<div class="live-metrics">'+stats.map(([label,value])=>metric(label,value)).join('')+'</div>';
  const directionRow=d=>{const x=by[d]||{};return [directionName(d),workorderMetric(x.submittedAmount,true),workorderMetric(x.submittedCount),workorderMetric(x.successAmount,true),workorderMetric(x.successCount),workorderMetric(x.notReceivedAmount,true),workorderMetric(x.notReceivedCount),R(x.successCount,x.submittedCount)]};
  const detailRows=rows.map(r=>[E(r.date),E(r.country||r.countryCode||'—'),E(r.platform),E(r.provider),E(r.channelType),directionName(r.direction),workorderMetric(r.submittedAmount,true),workorderMetric(r.submittedCount),workorderMetric(r.successAmount,true),workorderMetric(r.successCount),workorderMetric(r.notReceivedAmount,true),workorderMetric(r.notReceivedCount),R(r.successCount,r.submittedCount),E(formatTime(r.sourceUpdatedAt,'UTC'))]);
  const total=Number(result.total||0),page=Number(L.workordersPage||1),size=Number(L.workordersSize||20);
  return cards+box('代收 / 代付工单汇总',table(['方向','提交金额','提交笔数','到账成功金额','到账成功笔数','未到账金额','未到账笔数','笔数到账率'],[directionRow('charge'),directionRow('withdraw')]),'正式 AR 工单日汇总，代收与代付分开展示；金额、笔数、未到账字段独立计算。')+box('工单记录',table(['日期','国家','平台','三方','通道','方向','提交金额','提交笔数','到账成功金额','到账成功笔数','未到账金额','未到账笔数','笔数到账率','源更新时间'],detailRows,'workorder-columns-v4')+pager(total,page,size,'workorders'),'当前来源是按日期 / 平台 / 三方 / 通道汇总的正式工单事实；逐笔工单 ID 和提交秒级时间不在这张源表中，不伪造逐笔编号。')
 }
 async function workordersLoad(){if(!L.catalogReady)return;const serial=++L.workordersSerial;L.workordersLoading=true;L.workordersError='';L.workorders=null;render();try{const list=selected().filter(p=>['ar','newar'].includes(p.source));const request={action:'workorders',startAt:L.from.slice(0,10)+'T00:00:00.000Z',endAt:L.to.slice(0,10)+'T23:59:59.000Z',country:L.country,platforms:[...new Set(list.flatMap(p=>[p.name,p.sourceName].filter(Boolean)))],direction:L.direction,offset:(L.workordersPage-1)*L.workordersSize,limit:L.workordersSize};const providers=activeValues('provider');if(providers.length)request.providers=providers;const result=await window.hensemLiveRequest(request);if(serial!==L.workordersSerial)return;L.workorders={...result,unsupportedPlatforms:selected().filter(p=>!['ar','newar'].includes(p.source)).map(p=>p.name)};L.workordersLoading=false;render()}catch(e){if(serial!==L.workordersSerial)return;L.workordersLoading=false;L.workordersError=e.message||'正式工单读取失败';render()}}

 const withdrawPages=HensemLiveWithdrawPages.create({L,E,C,R,N,box,table,request:q=>window.hensemLiveRequest(q),render:()=>render(),page:()=>state.page});
 function autoWithdrawView(){return withdrawPages.render()}
 async function autoWithdrawLoad(reset=false){return withdrawPages.load(reset)}
  function depositIssueRows(){return Array.isArray(L.depositIssues?.rows)?L.depositIssues.rows:[]}
  function depositIssuesView(){
   if(L.depositIssuesLoading)return '<div class="live-status">正在读取 Supabase 存款未到账明细…</div>';
   if(L.depositIssuesError)return '<div class="live-status live-error">'+E(L.depositIssuesError)+'</div>';
   const result=L.depositIssues||{},rows=depositIssueRows(),summary=result.summary||{},total=Number(result.total||0),page=Number(L.depositIssuesPage||1),size=Number(L.depositIssuesSize||20);
   const countries=[...new Set(L.catalog.map(p=>p.country).filter(Boolean))].sort(),platforms=[...new Set(L.catalog.filter(p=>L.country==='all'||p.country===L.country).map(p=>p.name).filter(Boolean))].sort(),providers=[...new Set((result.facets?.providers||[]).filter(Boolean))].sort();
   const toolbar='<section class="panel deposit-issues-toolbar"><div class="panel-head"><h2>存款未到账明细</h2><button class="btn" onclick="depositIssuesLoad(true)">刷新正式数据</button></div><form onsubmit="event.preventDefault();depositIssuesLoad(true)"><div class="live-filters"><div class="live-field"><label>开始日期</label><input type="date" value="'+E(L.from.slice(0,10))+'" onchange="depositIssuesDate(\'from\',this.value)"></div><div class="live-field"><label>结束日期</label><input type="date" value="'+E(L.to.slice(0,10))+'" onchange="depositIssuesDate(\'to\',this.value)"></div><div class="live-field"><label>国家 / 地区</label><select onchange="depositIssuesSet(\'country\',this.value)"><option value="all">全部授权范围</option>'+countries.map(v=>'<option value="'+E(v)+'" '+(v===L.country?'selected':'')+'>'+E(v)+'</option>').join('')+'</select></div><div class="live-field wide"><label>平台</label><select onchange="depositIssuesSet(\'platformName\',this.value)"><option value="all">全部平台</option>'+platforms.map(v=>'<option value="'+E(v)+'" '+(v===L.depositIssuesPlatform?'selected':'')+'>'+E(v)+'</option>').join('')+'</select></div><div class="live-field"><label>三方</label><select onchange="depositIssuesSet(\'provider\',this.value)"><option value="">全部三方</option>'+providers.map(v=>'<option value="'+E(v)+'" '+(v===L.depositIssuesProvider?'selected':'')+'>'+E(v)+'</option>').join('')+'</select></div><div class="live-field"><label>状态</label><select onchange="depositIssuesSet(\'status\',this.value)"><option value="all" '+(L.depositIssuesStatus==='all'?'selected':'')+'>全部状态</option><option value="未入款" '+(L.depositIssuesStatus==='未入款'?'selected':'')+'>未入款</option><option value="已入款" '+(L.depositIssuesStatus==='已入款'?'selected':'')+'>已入款</option><option value="待核对" '+(L.depositIssuesStatus==='待核对'?'selected':'')+'>待核对</option></select></div><div class="live-field wide"><label>订单号 / UTR</label><input maxlength="200" placeholder="精确值或片段" value="'+E(L.depositIssuesQuery)+'" oninput="depositIssuesSet(\'query\',this.value)"></div><div class="live-actions"><button class="btn primary" type="submit">查询</button></div></div></form></section>';
   const cards='<div class="live-metrics">'+metric('记录数',C(summary.count||0))+metric('未入款金额',N(summary.amount))+metric('未入款笔数',C(summary.unreceivedCount||0))+metric('最大未入款天数',C(summary.maxUnreceivedDays||0))+metric('最近同步',E(result.updatedAt?formatTime(result.updatedAt,'UTC'):'—'))+'</div>';
   const tableRows=rows.map(r=>[E(r.recordDate||'—'),E(r.country||'—'),E(r.platform||'—'),E(r.provider||'—'),E(r.orderNumber||'—'),E(r.utr||'—'),N(r.amount),C(r.unreceivedDays||0),E(r.matchStatus||'—'),E(r.status||'—'),E(r.sourceUpdatedAt?formatTime(r.sourceUpdatedAt,'UTC'):'—')]);
   return toolbar+cards+box('存款未到账明细（Supabase 正式同步）',table(['日期','国家','平台','三方','订单号','UTR','金额','未入款天数','对账状态','状态','源更新时间'],tableRows,'deposit-issues-columns')+pager(total,page,size,'deposit-issues'),'来源：Google Sheet「UPI核对」→ Supabase admin_deposit_issue_rows；页面只读 Supabase，不在查询时直接扫 Google。无数据时保留空表。');
  }
  async function depositIssuesLoad(reset=false){if(!L.catalogReady)return;if(reset)L.depositIssuesPage=1;const serial=++L.depositIssuesSerial;L.depositIssuesLoading=true;L.depositIssuesError='';L.depositIssues=null;L.dirty=false;render();try{const p=L.depositIssuesPlatform&&L.depositIssuesPlatform!=='all'?L.catalog.find(x=>x.name===L.depositIssuesPlatform):null,zone=p?.timezone||selected()[0]?.timezone||'Asia/Kolkata',request={action:'depositIssues',startAt:instant(L.from,zone),endAt:instant(L.to,zone,true),offset:(L.depositIssuesPage-1)*L.depositIssuesSize,limit:L.depositIssuesSize};if(L.country!=='all')request.country=L.country;if(p)request.platform=p.name;if(L.depositIssuesProvider)request.provider=L.depositIssuesProvider;if(L.depositIssuesStatus!=='all')request.status=L.depositIssuesStatus;if(L.depositIssuesQuery)request.query=L.depositIssuesQuery;const result=await window.hensemLiveRequest(request);if(serial!==L.depositIssuesSerial)return;L.depositIssues=result;L.depositIssuesLoading=false;render()}catch(e){if(serial!==L.depositIssuesSerial)return;L.depositIssuesLoading=false;L.depositIssuesError=e.message||'存款未到账明细读取失败';render()}}
  function providerConfigView(){return configuration.providerView()}
  window.providerConfigSet=function(key,value){if(!['providerConfigRaw','providerConfigCanonical','providerConfigCountry','providerConfigPlatform','providerConfigDirection','providerConfigStatus'].includes(key))return;L[key]=String(value||'').slice(0,200);if(key==='providerConfigCountry'){L.providerConfigPlatform='all';providerConfigLoad(true)}};
  window.providerConfigReset=function(){Object.assign(L,{providerConfigRaw:'',providerConfigCanonical:'',providerConfigCountry:L.country,providerConfigPlatform:'all',providerConfigDirection:'all',providerConfigStatus:'all',providerConfigPage:1});providerConfigLoad()}
  async function providerConfigLoad(reset=false){if(!L.catalogReady)return;if(L.providerConfigCountry==='all')L.providerConfigCountry=L.country;if(reset)L.providerConfigPage=1;const serial=++L.providerConfigSerial;L.providerConfigLoading=true;L.providerConfigError='';render();try{const request={action:'providerConfig',offset:(L.providerConfigPage-1)*L.providerConfigSize,limit:L.providerConfigSize};for(const [key,name] of [['providerConfigRaw','rawProvider'],['providerConfigCanonical','canonicalProvider']])if(L[key])request[name]=L[key];if(L.providerConfigCountry!=='all')request.country=L.providerConfigCountry;if(L.providerConfigPlatform!=='all')request.platform=L.providerConfigPlatform;if(L.providerConfigDirection!=='all')request.direction=L.providerConfigDirection;if(L.providerConfigStatus!=='all')request.status=L.providerConfigStatus;const result=await window.hensemLiveRequest(request);if(serial!==L.providerConfigSerial)return;L.providerConfig=result;L.providerConfigLoading=false;render()}catch(e){if(serial!==L.providerConfigSerial)return;L.providerConfigLoading=false;L.providerConfigError=e.message||'三方归类读取失败';render()}}

  function platformAssignmentsView(){return configuration.platformView()}
  window.platformAssignmentsSet=function(key,value){if(!['teamPlatformTeam','teamPlatformCountry','teamPlatformSystem','teamPlatformQuery','teamPlatformStatus'].includes(key))return;L[key]=String(value||'').slice(0,200)};
  window.platformAssignmentsReset=function(){Object.assign(L,{teamPlatformTeam:'all',teamPlatformCountry:'all',teamPlatformSystem:'all',teamPlatformQuery:'',teamPlatformStatus:'all',platformAssignmentsPage:1});platformAssignmentsLoad()}
  async function platformAssignmentsLoad(reset=false){if(!L.catalogReady)return;if(reset)L.platformAssignmentsPage=1;const serial=++L.platformAssignmentsSerial;L.platformAssignmentsLoading=true;L.platformAssignmentsError='';render();try{const request={action:'platformAssignments',offset:(L.platformAssignmentsPage-1)*L.platformAssignmentsSize,limit:L.platformAssignmentsSize};for(const [key,name] of [['teamPlatformTeam','team'],['teamPlatformCountry','country'],['teamPlatformSystem','system'],['teamPlatformQuery','platform']])if(L[key]&&L[key]!=='all')request[name]=L[key];if(L.teamPlatformStatus!=='all')request.status=L.teamPlatformStatus;const result=await window.hensemLiveRequest(request);if(serial!==L.platformAssignmentsSerial)return;L.platformAssignments=result;L.platformAssignmentsLoading=false;render()}catch(e){if(serial!==L.platformAssignmentsSerial)return;L.platformAssignmentsLoading=false;L.platformAssignmentsError=e.message||'团队平台归属读取失败';render()}}
 window.providerConfigLoad=providerConfigLoad;window.platformAssignmentsLoad=platformAssignmentsLoad;
 const configuration=HensemLiveConfiguration.create({L,E,C,metric,box,table,pager,request:q=>window.hensemLiveRequest(q),render:()=>render(),changed:async type=>{
   const catalog=await window.hensemLiveRequest({action:'catalog'});L.catalog=catalog.platforms||[];L.dirty=true;L.results=[];L.providerOptionsKey='';
   await loadProviderOptions(true);if(type==='platform')await platformAssignmentsLoad();else if(state.page==='teams')await platformAssignmentsLoad();else await providerConfigLoad();
 }});
 function referencePage(){return HensemLivePages.create({L,E,N,C,R,plus,combine,groupRows,empty,table,box,pager,totals,comparisonRows,compareMetric,chart,matrixBody,latencyView,detailsView,providersView,platformsView,pagedTable,overviewChart,overviewAmounts,businessHeaders,businessCells,unknownProviderNotice,feeForRow,ensureFeeLookup}).render(state.page)}
  function content(){if(state.page==='payout_config')return HensemLivePayoutConfig.render();if(isWithdrawPage(state.page))return autoWithdrawView();if(state.page==='teams'||state.page==='platform_systems')return platformAssignmentsView();if(state.page==='workorders')return workordersView();if(gaps[state.page])return gapPage(state.page);if(state.page==='rates')return ratesView();if(state.page==='data_health')return health();if(L.error)return '<div class="live-status live-error">'+E(L.error)+'</div>';if(L.dirty)return '<div class="live-status">筛选条件已修改，点击查询读取对应的正式数据。</div>';if(!L.catalogReady)return '<div class="live-status">正在验证权限并读取正式平台目录…</div>';if(L.loading)return '<div class="live-status">'+E(L.progress||'正在读取正式订单…')+'</div>';const duration=window.HensemLiveDuration?.create({L,E,N,C,R,box,table}).render(state.page);if(duration!=null)return duration;if(providerDirection(state.page))return HensemProviderSummary.render({L,E,N,C,R,plus,combine,groupRows,box,table,pager,feeForRow,ensureFeeLookup,render:()=>render()},providerDirection(state.page));const reference=referencePage();if(reference!==null)return reference;if(state.page==='orders')return totals()+detailsView();if(state.page==='overview')return overview();if(state.page==='time')return timeView();if(state.page==='amount')return amountView();if(state.page==='matrix')return matrixView();if(state.page==='provider_daily')return dailyView();if(state.page==='latency')return totals()+latencyView(false);if(state.page==='stuck')return totals()+latencyView(true);if(['teamops','teamcountries','teamplatforms','merchants'].includes(state.page))return totals()+platformsView();if(state.page==='payout')return totals()+providersView()+latencyView(true)+latencyView(false);if(state.page==='collection')return totals()+providersView()+latencyView(false);if(['risk','channelquality'].includes(state.page))return totals()+providersView()+box('加量判断','<div class="live-empty">先结合成功率、待付和耗时比较三方表现；当前缺少历史费率版本、持续稳定性与容量证据，不自动生成加量结论。</div>');return totals()+providersView()}
  function chrome(){const page=pages.find(p=>p[0]===state.page)||pages[0],g=groupForV3(page[0]);document.title='Hensem · '+page[4]+' · 正式数据';document.getElementById('pageTitle').textContent=page[4];document.getElementById('pageSubtitle').textContent='';document.getElementById('eyebrow').textContent=page[3];document.getElementById('crumbTitle').textContent=g[2]+' / '+page[2];document.getElementById('nav').innerHTML=navGroupsV3.map(n=>'<div class="nav-center"><button class="center-button '+(g[0]===n[0]?'current':'')+'" onclick="toggleCenterV3(\''+n[0]+'\')"><span class="ico">'+n[1]+'</span><span class="nav-label">'+n[2]+'</span><span class="nav-arrow">'+(state.navGroup===n[0]?'⌄':'›')+'</span></button>'+(state.navGroup===n[0]?'<div class="subnav">'+n[3].filter(id=>id!=='platform_systems').map(id=>{const p=pages.find(p=>p[0]===id);return '<button class="'+(state.page===id?'active':'')+'" onclick="setPage(\''+id+'\')"><span class="sub-dot"></span>'+p[2]+'</button>'}).join('')+'</div>':'')+'</div>').join('');document.querySelector('.title-actions').innerHTML='<button class="btn" onclick="liveLoad()">读取最新数据</button><button class="btn primary" onclick="liveExport()">导出当前表</button>';document.querySelector('.title-actions').style.display='';document.getElementById('filters').style.display='none';document.getElementById('scope').style.display='none';document.querySelector('.bottom-note').innerHTML='<span>Hensem · 正式数据只读工作台</span><span>手动查询更新 · 已采集数据范围 · 金额按币种分开</span>';liveHeader();}
 function dateRange(){return '<div class="live-date-range"><label>统计时间 · '+E([...new Set(selected().map(p=>p.timezone))].length===1?selected()[0]?.timezone:'各订单国家当地时间（跨国统计日期）')+'</label><div class="live-date-controls">'+[['from','起始'],['to','截止']].map(([key,label],i)=>(i?'<span>至</span>':'')+'<input aria-label="'+label+'日期" type="date" value="'+E(L[key].slice(0,10))+'" onchange="liveDateSet(\''+key+'\',\'date\',this.value)"><input aria-label="'+label+'时间（含秒）" type="time" step="1" value="'+E(L[key].slice(11)|| (i?'23:59:59':'00:00:00'))+'" onchange="liveDateSet(\''+key+'\',\'time\',this.value)">').join('')+'</div></div>'}
 window.liveDateSet=function(key,part,value){const current=L[key]||'T00:00:00';liveSet(key,part==='date'?value+'T'+(current.slice(11)||'00:00:00'):current.slice(0,10)+'T'+(value.length===5?value+':00':value))};
 function filters(){syncCurrency();let mount=document.getElementById('liveFilters');if(!mount){mount=document.createElement('section');mount.id='liveFilters';document.getElementById('filters').after(mount)}mount.style.display=gaps[state.page]||['data_health','rates','deposit_tracking','payout_config','auto_withdraw','withdraw_operators','workorders'].includes(state.page)?'none':'';const list=L.catalog.filter(p=>(!!L.country&&p.country===L.country)&&matchesFilter('source',p.source)&&matchesFilter('team',p.team||'__unassigned__')),zones=[...new Set(selected().map(p=>p.timezone))],systems={ar:'AR系统',newar:'新AR系统',game66:'AA包网'};
 mount.innerHTML='<div class="live-filters">'+multiSelect('team','所属团队',[['all','全部团队'],...[...new Set(L.catalog.filter(p=>p.country===L.country).map(p=>p.team||'__unassigned__'))].map(t=>[t,t==='__unassigned__'?'未绑定团队':t])])+select('country','国家 / 地区（必选）',[...new Set(L.catalog.map(p=>p.country).filter(Boolean))].map(c=>[c,c]))+multiSelect('platform','商户（平台）',[['all','全部平台'],...list.map(p=>[p.id,p.name])],true)+multiSelect('source','包网系统',[['all','全部系统'],...[...new Set(L.catalog.filter(p=>p.country===L.country).map(p=>p.source))].map(c=>[c,systems[c]||c])])+multiSelect('provider','三方',[['','全部三方'],...L.providerOptions.map(p=>[p,p])])+(providerDirection(state.page)?'<div class="live-field"><label>业务方向</label><span class="live-badge">'+directionName(providerDirection(state.page))+'</span></div>':multiSelect('direction','业务方向',[['all','全部'],['charge','代收'],['withdraw','代付']]))+dateRange()+'<div class="live-actions">'+[['yesterday','昨日'],['before','前日'],['week','近1周'],['month','近1个月']].map(([k,l])=>'<button class="btn" onclick="livePeriod(\''+k+'\')">'+l+'</button>').join('')+'<button class="btn primary" onclick="liveLoad()">查询</button><button class="btn" onclick="liveReset()">重置</button></div>'+(state.page==='orders'?'<div class="live-search-row">'+input('systemOrderId','系统 ID','text',selected().length===1&&selected()[0]?.source==='newar'?'':'disabled title="当前来源未提供可检索的源系统ID"')+input('orderNumber','订单号')+input('thirdPartyOrderNumber','三方订单号','text',selected().some(p=>p.source==='ar')?'disabled title="AR源未提供可检索的三方订单号"':'')+input('utr','UTR 交易参考','text','disabled title="源数据未提供 UTR"')+input('memberId','会员 ID')+select('status','订单状态',[['all','全部状态'],['success','成功'],['pending','处理中'],['failed','失败'],['rejected','拒绝'],['unknown','未知']])+'</div>':'')+'</div><div class="live-scope"><span>覆盖：</span><span>'+C(selected().length)+' 平台</span><span>'+(L.providerOptionsBusy?'读取中':L.providerOptionsError?'目录读取失败':C(activeValues('provider','').length||L.providerOptions.length))+' 三方</span><span>'+C(new Set(selected().map(p=>p.team).filter(Boolean)).size)+' 团队</span><span>'+C(new Set(selected().map(p=>p.country)).size)+' 国家</span><span>'+E(zones.length===1?zones[0]:'各国家当地时间')+'</span><span>手动查询更新</span></div>';}

  window.liveHeader=function(){const host=document.querySelector('.top-right');const sample=host.querySelector('.sample');if(sample){sample.textContent=state.page==='deposit_tracking'?'存款未到账明细':isWithdrawPage(state.page)?(state.page==='withdraw_operators'?'操作人统计':'自动出款'):state.page==='provider_config'||state.page==='teams'||state.page==='platform_systems'?'Supabase归类':'正式数据';sample.title='Supabase 生产只读数据'}const currency=host.querySelector('span:nth-of-type(3)');if(currency)currency.textContent=L.currency;let mount=document.getElementById('headerActivityV3');if(!mount){mount=document.createElement('div');mount.id='headerActivityV3';mount.className='header-activity-v3';host.appendChild(mount)}mount.innerHTML='<button class="live-header-button" title="在线心跳尚未接入" onclick="liveHeaderInfo(\'online\')">'+headerIconV3('people')+'<span>在线 —</span></button><button id="headerBellV3" class="live-header-button" aria-label="数据提醒" onclick="liveHeaderInfo(\'alerts\')">'+headerIconV3('bell')+'</button>';};
  window.liveHeaderInfo=function(kind){let p=document.getElementById('live-header-pop');if(p){p.remove();return}p=document.createElement('div');p.id='live-header-pop';p.className='live-header-pop';p.innerHTML='<b>'+(kind==='online'?'在线人数':'正式数据提醒')+'</b><button class="link" style="float:right" onclick="this.parentNode.remove()">关闭</button><p>'+(kind==='online'?'真实在线心跳尚未接入，因此显示 —。':'正式订单已连接。历史费率版本、部分成功时间和风险事件仍有缺项；详见采集与数据健康。')+'</p>';document.querySelector('.topbar').appendChild(p)};
  render=function(){document.body.classList.add('live-admin');if(state.page==='deposit_tracking'){chrome();document.getElementById('liveFilters')?.style.setProperty('display','none');document.getElementById('page').innerHTML=depositIssuesView();liveHeader();document.querySelector('.bottom-note').innerHTML='<span>Google Sheet「UPI核对」已同步至 Supabase</span><span>页面只读 Supabase，不在查询时直接读取 Google</span>';return}if(state.page==='provider_config'){chrome();document.getElementById('liveFilters')?.style.setProperty('display','none');document.getElementById('page').innerHTML=providerConfigView();liveHeader();document.querySelector('.bottom-note').innerHTML='<span>Supabase 正式归类读模型</span><span>代收、代付共用分类；冲突与未归类单独列出</span>';return}if(state.page==='teams'||state.page==='platform_systems'){chrome();document.getElementById('liveFilters')?.style.setProperty('display','none');document.getElementById('page').innerHTML=platformAssignmentsView();liveHeader();document.querySelector('.bottom-note').innerHTML='<span>Supabase 团队 / 平台归属</span><span>映射可见；未配置平台单独列出</span>';return}chrome();filters();document.getElementById('page').innerHTML=content();};
 syncFilters=function(){};
 toggleCenterV3=function(id){state.navGroup=state.navGroup===id?'':id;render()};
  setPage=function(key){if(key==='platform_systems')key='teams';if(!pages.some(p=>p[0]===key))return;const old=L.direction;if(isWithdrawPage(state.page))withdrawPages.cancel();L.serial++;L.detailSerial++;L.loading=false;L.detailBusy=false;if(state.page==='orders'&&key!=='orders'){L.status='all';L.orderNumber='';L.thirdPartyOrderNumber='';L.memberId='';L.systemOrderId='';L.utr='';L.dirty=true}state.page=key;state.navGroup=groupForV3(key)?.[0];L.view='business';L.localPage=1;if(['collection','providers'].includes(key))L.direction='charge';if(['payout','stuck','provider_payout'].includes(key))L.direction='withdraw';L.multi.direction=L.direction==='all'?[]:[L.direction];L.openMulti='';location.hash=key;render();window.scrollTo(0,0);if(key==='orders')liveDetails();else if(key==='rates')liveRates();else if(key==='provider_config')providerConfigLoad();else if(key==='teams')platformAssignmentsLoad();else if(key==='payout_config')HensemLivePayoutConfig.ensureLoaded();else if(isWithdrawPage(key))autoWithdrawLoad();else if(key==='deposit_tracking')depositIssuesLoad();else if(key==='workorders')workordersLoad();else if((old!==L.direction||L.dirty||L.loadedView!==(providerDirection(key)?'providers':'full'))&&!gaps[key]&&!['deposit_tracking','teams','platform_systems'].includes(key))liveLoad();};
  window.liveSet=function(key,value){if(!Object.prototype.hasOwnProperty.call(L,key))return;if(key==='country'&&!new Set(L.catalog.map(p=>p.country).filter(Boolean)).has(value))return;if(key==='direction'&&!['all','charge','withdraw'].includes(value))return;if(key==='direction'&&['collection','payout'].includes(state.page)){state.page=value==='charge'?'collection':value==='withdraw'?'payout':'overview';location.hash=state.page}if(key==='direction'&&(state.page==='stuck'&&value!=='withdraw'||providerDirection(state.page)&&value!==providerDirection(state.page)))return;if(key==='country')L.countryTouched=true;L[key]=value;if(['team','source','platform','provider','direction'].includes(key))L.multi[key]=value&&value!=='all'?[value]:[];if(key==='country'){L.multi.platform=[];L.platform='all';L.multi.source=[];L.source='all';L.multi.team=[];L.team='all';}if(key.startsWith('fee')){L.feeSerial++;return;}L.serial++;L.detailSerial++;L.loading=false;L.detailBusy=false;if(['country','source','team'].includes(key)){L.platform='all';L.multi.platform=[];}if(['country','source','team','platform','direction'].includes(key)){L.provider='';L.multi.provider=[];L.providerOptions=[]}syncCurrency();L.page=1;L.localPage=1;L.dirty=true;render();if(['country','source','team','platform','direction'].includes(key))loadProviderOptions();};
 function setMultiValues(key,next){
  if(!['team','platform','source','provider','direction'].includes(key))return;
  if(key==='direction'&&providerDirection(state.page))return;
  L.multi[key]=next;L[key]=next.length===1?next[0]:key==='provider'?'':'all';
  if(key==='direction'&&state.page==='stuck'){L.multi.direction=['withdraw'];L.direction='withdraw'}
  if(['team','source'].includes(key)){L.platform='all';L.multi.platform=[]}
  if(['team','source','platform','direction'].includes(key)){L.provider='';L.multi.provider=[];L.providerOptions=[]}
  L.serial++;L.detailSerial++;L.workordersSerial++;L.workorders=null;L.loading=false;L.detailBusy=false;syncCurrency();L.page=1;L.localPage=1;L.dirty=true;render();
  if(key!=='provider')loadProviderOptions();
 }
 window.liveSetMultiOption=function(key,element){if(!element)return;const current=activeValues(key),value=String(element.value||'');setMultiValues(key,element.checked?[...new Set([...current,value])]:current.filter(v=>v!==value))};

 window.livePeriod=function(mode,query=true){const zone=selected()[0]?.timezone||'Asia/Kolkata',today=localClock(Date.now(),zone).slice(0,10),date=new Date(today+'T00:00:00Z'),end=new Date(date);if(mode==='yesterday'||mode==='before'){date.setUTCDate(date.getUTCDate()-(mode==='before'?2:1));end.setTime(date.getTime())}if(mode==='week')date.setUTCDate(date.getUTCDate()-6);if(mode==='month')date.setUTCDate(date.getUTCDate()-30);L.from=date.toISOString().slice(0,10)+'T00:00:00';L.to=end.toISOString().slice(0,10)+'T23:59:59';L.serial++;L.detailSerial++;L.dirty=true;L.loading=false;render();if(query)liveLoad()};
 window.liveReset=function(){const base=L.catalog.find(p=>String(p.name||'').toUpperCase()==='91CLUB')||L.catalog[0]||{};const resetDirection=providerDirection(state.page)||(state.page==='collection'?'charge':['payout','stuck'].includes(state.page)?'withdraw':'all');Object.assign(L,{team:'all',country:base.country||L.country,countryTouched:false,platform:'all',source:base.source||'all',provider:'',direction:resetDirection,status:'all',orderNumber:'',thirdPartyOrderNumber:'',memberId:'',systemOrderId:'',utr:'',page:1,localPage:1,multi:{team:[],platform:[],source:base.source?[base.source]:[],provider:[],direction:resetDirection==='all'?[]:[resetDirection]}});livePeriod('yesterday');};
 function query(p,action,previous=false){if(!L.country||L.country==='all')throw Error('请选择国家 / 地区');if(!['all','charge','withdraw'].includes(L.direction))throw Error('请选择代收或代付');const range=HensemLiveCompare.windowFor(L.from,L.to,p.timezone,L.queryNow);if(!range.valid)throw Error(range.error);if(!previous)L.comparisonLabel=range.label;const q={action,...(action==='aggregate'&&providerDirection(state.page)?{view:'providers'}:{}),platformId:p.id,startAt:instant(previous?range.previousFrom:range.currentFrom,p.timezone),endAt:instant(previous?range.previousTo:range.currentTo,p.timezone,true),direction:L.direction,status:L.status,currency:p.currency||null,offset:(L.page-1)*L.size,limit:L.size};if(range.calendarDays>31)throw Error('每次最多31个当地日');for(const key of ['orderNumber','thirdPartyOrderNumber','memberId','systemOrderId','utr'])if(L[key])q[key]=L[key];const providers=activeValues('provider','');if(providers.length)q.providers=providers;return q}
 function mergeParts(parts){if(parts.length===1)return {...parts[0],_parts:parts};const first=parts[0],merged={...first,startAt:parts[0]?.startAt,endAt:parts.at(-1)?.endAt,total:parts.reduce((n,r)=>n+Number(r.total||0),0),summary:combine(parts.flatMap(p=>p.summary||[]),['direction','currency']),groups:{},rows:[],_parts:parts};const dimensions={provider:['provider'],daily:['provider','date'],hourly:['hour'],amount:['bucket'],matrix:['hour','bucket'],amount_range:['bucket'],matrix_range:['hour','bucket']};for(const [key,dims]of Object.entries(dimensions))merged.groups[key]=combine(parts.flatMap(p=>p.groups?.[key]||[]),['direction','currency',...dims]);for(const key of ['latency','latency_thresholds','pending_age','pending_age_thresholds']){const groups=new Map();for(const r of parts.flatMap(p=>p.groups?.[key]||[])){const id=[r.direction,r.currency,r.bucket].join('|');if(!groups.has(id))groups.set(id,{...r,count:0,amount:0,valid_count:0,valid_amount:0});const g=groups.get(id);g.count+=Number(r.count||0);g.amount=g.amount===null||r.amount===null?null:g.amount+Number(r.amount||0);g.valid_count+=Number(r.valid_count||0);g.valid_amount=g.valid_amount===null||r.valid_amount===null?null:g.valid_amount+Number(r.valid_amount||0)}merged.groups[key]=[...groups.values()]}merged.latencySummary=[];merged.pendingSummary=[];return merged}
 async function readAggregate(request,serial){const start=Date.parse(request.startAt),end=Date.parse(request.endAt),parts=[];async function read(q){if(serial!==L.serial)throw Error('查询已替换');try{const result=await window.hensemLiveRequest(q);parts.push({...result,startAt:q.startAt,endAt:q.endAt})}catch(e){const from=Date.parse(q.startAt),to=Date.parse(q.endAt);if(/超时|timeout/i.test(e.message)&&to-from>3600000){const mid=new Date(Math.floor((from+to)/2000)*1000).toISOString();await read({...q,endAt:mid});await read({...q,startAt:mid})}else throw e}}for(let at=start;at<end;at+=21600000)await read({...request,startAt:new Date(at).toISOString(),endAt:new Date(Math.min(end,at+21600000)).toISOString()});return mergeParts(parts)}

  window.liveLoad=async function(){if(state.page==='payout_config'){await HensemLivePayoutConfig.refresh();return}if(isWithdrawPage(state.page)){await autoWithdrawLoad(true);return}if(state.page==='deposit_tracking'){await depositIssuesLoad(true);return}if(state.page==='provider_config'){await providerConfigLoad();return}if(state.page==='teams'||state.page==='platform_systems'){await platformAssignmentsLoad();return}if(state.page==='workorders'){await workordersLoad();return}if(state.page==='rates'){await liveRates(true);return}if(!L.catalogReady)return;loadProviderOptions();const serial=++L.serial;L.detailSerial++;L.workordersSerial++;L.workorders=null;L.workordersLoading=false;L.queryNow=Date.now();L.comparisonResults=[];L.comparisonStatus='idle';L.comparisonError='';L.error='';L.dirty=false;L.loading=true;L.progress='正在读取正式订单…';L.detail=null;L.page=1;L.localPage=1;L.tablePages={};L.results=[];render();const platforms=selected();let index=0,done=0,failed=false;const results=[];try{const requests=platforms.map(p=>query(p,'aggregate'));async function worker(){while(index<requests.length&&!failed&&serial===L.serial){const i=index++;try{const r=await readAggregate(requests[i],serial);if(serial!==L.serial||failed)return;results[i]=r;done++;L.progress='正式数据读取 '+done+' / '+requests.length+' 个平台';document.getElementById('page').innerHTML='<div class="live-status">'+E(L.progress)+'</div>'}catch(e){failed=true;throw e}}}await Promise.all([worker(),worker()]);if(serial!==L.serial)return;L.results=results;L.loadedView=providerDirection(state.page)?'providers':'full';L.providerOptions=[...new Set([...L.providerOptions,...results.flatMap(r=>(r.groups?.provider||[]).map(g=>g.provider)).filter(Boolean)])].sort();L.loading=false;render();await Promise.all([state.page==='orders'?liveDetails():Promise.resolve(),liveComparison(serial),workordersLoad()]);}catch(e){if(serial!==L.serial)return;L.error=e.message||'读取失败';L.results=[];L.loading=false;render()}};
 async function liveComparison(serial){if(serial!==L.serial)return;L.comparisonStatus='loading';render();let index=0,failed=false;const results=[];try{const requests=selected().map(p=>query(p,'aggregate',true));async function worker(){while(index<requests.length&&!failed&&serial===L.serial){const i=index++;try{const r=await readAggregate(requests[i],serial);if(serial!==L.serial||failed)return;results[i]=r}catch(e){failed=true;throw e}}}await Promise.all([worker(),worker()]);if(serial!==L.serial)return;L.comparisonResults=results;L.comparisonStatus='ready';render()}catch(e){if(serial!==L.serial)return;L.comparisonResults=[];L.comparisonStatus='error';L.comparisonError='前期数据读取未完成：'+(e.message||'请重试');render()}}
 async function readDetails(p){const cached=L.results.find(r=>r.platform?.id===p.id),parts=cached?._parts;if(!parts||parts.length<2)return window.hensemLiveRequest(query(p,'details'));const ordered=[...parts].sort((a,b)=>Date.parse(b.startAt)-Date.parse(a.startAt)),total=ordered.reduce((n,r)=>n+Number(r.total||0),0),rows=[];let skip=(L.page-1)*L.size;for(const part of ordered){const n=Number(part.total||0);if(skip>=n){skip-=n;continue}const request={...query(p,'details'),startAt:part.startAt,endAt:part.endAt,offset:skip};const response=await window.hensemLiveRequest(request);if(Number(response.total)!==n)throw Error('源订单已更新，请重新查询以同步总数与分页');rows.push(...(response.rows||[]).slice(0,L.size-rows.length));skip=0;if(rows.length>=L.size)break;}return {platform:p,total,rows,limit:L.size,offset:(L.page-1)*L.size,hasMore:L.page*L.size<total};}
 window.liveDetails=async function(){if(L.platform==='all'||!L.catalogReady)return;const p=selected().find(p=>p.id===L.platform);if(!p)return;const serial=++L.detailSerial;L.error='';L.detailBusy=true;L.detail=null;render();try{const r=await readDetails(p);if(serial!==L.detailSerial)return;const max=Math.max(1,Math.ceil(Number(r.total||0)/L.size));if(L.page>max){L.page=max;L.detailBusy=false;return liveDetails()}L.detail=r;L.detailBusy=false;render()}catch(e){if(serial!==L.detailSerial)return;L.detailBusy=false;L.error=e.message;render()}};
 L.detailSerial=0;
 window.liveChoosePlatform=function(id){L.platform=id;L.multi.platform=[id];L.page=1;state.page='orders';state.navGroup='analysis';location.hash='orders';liveLoad();};
 window.liveProvider=function(name){L.provider=name;L.multi.provider=name?[name]:[];L.page=1;liveLoad()};
 window.liveView=function(view){L.view=view;L.localPage=1;render()};
  window.livePage=function(page,kind){if(!Number.isInteger(page)||page<1)return;if(kind.startsWith('ref-')){const id=kind.slice(4);L.tablePages=L.tablePages||{};L.tablePages[id]=page;render()}else if(kind==='fee'){L.feePage=Math.min(page,Math.max(1,Math.ceil(Number(L.fees?.total||0)/L.feeSize)));liveRates(true)}else if(kind==='server'){L.page=Math.min(page,Math.max(1,Math.ceil(Number(L.detail?.total||0)/L.size)));liveDetails()}else if(kind==='workorders'){L.workordersPage=page;workordersLoad()}else if(kind==='auto-withdraw'){L.autoWithdrawPage=page;autoWithdrawLoad()}else if(kind==='deposit-issues'){L.depositIssuesPage=page;depositIssuesLoad()}else if(kind==='provider-config'){L.providerConfigPage=page;providerConfigLoad()}else if(kind==='platform-assignments'){L.platformAssignmentsPage=page;platformAssignmentsLoad()}else{L.localPage=page;render()}};
  window.livePageSize=function(size,kind){if(![20,30,50,100,500].includes(Number(size)))return;if(kind.startsWith('ref-')){const id=kind.slice(4);L.tableSizes=L.tableSizes||{};L.tablePages=L.tablePages||{};L.tableSizes[id]=Number(size);L.tablePages[id]=1;render()}else if(kind==='fee'){L.feeSize=Number(size);L.feePage=1;liveRates(true)}else if(kind==='server'){L.size=Number(size);L.page=1;liveDetails()}else if(kind==='workorders'){L.workordersSize=Number(size);L.workordersPage=1;workordersLoad()}else if(kind==='auto-withdraw'){L.autoWithdrawSize=Number(size);L.autoWithdrawPage=1;autoWithdrawLoad()}else if(kind==='deposit-issues'){L.depositIssuesSize=Number(size);L.depositIssuesPage=1;depositIssuesLoad()}else if(kind==='provider-config'){L.providerConfigSize=Number(size);L.providerConfigPage=1;providerConfigLoad()}else if(kind==='platform-assignments'){L.platformAssignmentsSize=Number(size);L.platformAssignmentsPage=1;platformAssignmentsLoad()}else{L.localSize=Number(size);L.localPage=1;render()}};
  window.depositIssuesDate=function(key,value){if(!['from','to'].includes(key)||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(value))return;if(key==='from')L.from=value+'T00:00:00';else L.to=value+'T23:59:59';L.depositIssuesPage=1;render()};
  window.depositIssuesSet=function(key,value){if(key==='country'){if(!['all',...new Set(L.catalog.map(p=>p.country).filter(Boolean))].includes(value))return;L.country=value;L.depositIssuesPlatform='all'}else if(key==='platformName'){L.depositIssuesPlatform=String(value).slice(0,200)}else if(key==='provider'){L.depositIssuesProvider=String(value).slice(0,200)}else if(key==='status'){if(!['all','未入款','已入款','待核对'].includes(value))return;L.depositIssuesStatus=value}else if(key==='query'){L.depositIssuesQuery=String(value).slice(0,200)}else return;L.depositIssuesPage=1;render()};
 window.liveJump=function(kind,max){const n=Number(document.getElementById('live-jump-'+kind)?.value);if(Number.isInteger(n)&&n>=1&&n<=max)livePage(n,kind)};
 window.liveOrder=function(index){const r=L.detail?.rows?.[index];if(!r)return;const p=L.detail.platform,zone=p?.timezone;openDrawer('订单详情 · '+(r.order_number||r.order_no||''),box('订单与关联字段',table(['字段','值'],[['订单号',E(r.order_number||r.order_no||'—')],['系统 ID',E(r.system_order_id||r.id||'—')],['三方订单号',E(r.third_party_order_number||r.provider_order_number||'—')],['会员 ID',E(r.member_id||'—')],['UTR',E(r.utr||'未提供')],['平台',E(p?.name)],['团队',E(p?.team||'未绑定团队')],['国家',E(p?.country)],['包网系统',E(p?.source)],['三方',E(r.provider)],['方向',directionName(r.direction)],['订单金额',N(r.amount)],['实际金额',N(r.actual_amount)],['订单状态',E(statName(r.status_group||r.status))]]))+box('提交与成功时间',table(['创建时间','成功时间','数据同步时间','时区'],[[E(formatTime(r.created_at,zone)),E(formatTime(r.success_at,zone)),E(formatTime(r.synced_at,zone)),E(zone)]]))+box('费用与费率依据',table(['估算手续费','实际手续费','费率版本','费率生效时间'],[['—',N(r.withdraw_fee),'—','—']]),'当前源数据未提供历史费率匹配结果；不将空值当作零费用'))};

 window.liveRates=async function(force=false,reset=false){if(L.feeView!=='normalized'&&window.HensemLiveRatesRestored){render();if(force||!HensemLiveRatesRestored.snapshot().hasGrid)await HensemLiveRatesRestored.load();return}if(L.fees&&!force){render();return}if(reset)L.feePage=1;const serial=++L.feeSerial;L.feeLoading=true;L.feeError='';L.dirty=false;render();try{const request={action:'rates',scopeType:L.feeScope,offset:(L.feePage-1)*L.feeSize,limit:L.feeSize};if(L.feeCountry!=='all')request.country=L.feeCountry;if(L.feeQuery)request.query=L.feeQuery;const result=await window.hensemLiveRequest(request);if(serial!==L.feeSerial)return;const max=Math.max(1,Math.ceil(Number(result.total||0)/L.feeSize));if(L.feePage>max){L.feePage=max;L.feeLoading=false;return liveRates(true)}L.fees=result;}catch(e){if(serial!==L.feeSerial)return;L.feeError=e.message}finally{if(serial===L.feeSerial){L.feeLoading=false;render()}}};
 window.liveExport=function(){const page=document.getElementById('page'),tables=[...page.querySelectorAll('table')];if(!tables.length){toast('当前没有可导出的表格');return}const rows=tables.flatMap(t=>[...t.querySelectorAll('tr')].map(tr=>[...tr.cells].map(td=>td.innerText)));const quote=v=>'"'+String(/^[=+@\-\t\r]/.test(v)?"'"+v:v).replace(/"/g,'""')+'"',url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Hensem-当前页-'+state.page+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出当前可见表格页')};
  (async()=>{try{const r=await window.hensemLiveRequest({action:'catalog'});L.catalog=r.platforms||[];L.catalogReady=true;const preferred=L.catalog.find(p=>String(p.name||'').toUpperCase()==='91CLUB')||L.catalog[0]||{};L.country=preferred.country||L.catalog.find(p=>p.country)?.country||'';L.platform='all';L.source=preferred.source||'all';L.multi={team:[],platform:[],source:preferred.source?[preferred.source]:[],provider:[],direction:L.direction==='all'?[]:[L.direction]};syncCurrency();L.providerConfigCountry=L.country;livePeriod('yesterday',false);loadProviderOptions();if(state.page==='rates')await liveRates();else if(state.page==='provider_config')await providerConfigLoad();else if(state.page==='teams'||state.page==='platform_systems')await platformAssignmentsLoad();else if(state.page==='workorders')await workordersLoad();else if(state.page==='payout_config')await HensemLivePayoutConfig.ensureLoaded();else if(isWithdrawPage(state.page))await autoWithdrawLoad();else if(state.page==='deposit_tracking')await depositIssuesLoad();else if(!gaps[state.page])await liveLoad();else render();}catch(e){L.error=e.message;render()}})();
})();
