const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../admin-preview/live-channel-status.js'),'utf8');
const P={id:'11111111-1111-4111-8111-111111111111',source:'kb',name:'YASH.BET',country:'印度',currency:'INR',team:'M8',timezone:'Asia/Kolkata',capabilities:{channelStatusAvailable:true}};
const O={...P,id:'22222222-2222-4222-8222-222222222222',name:'Other',source:'ar',capabilities:{}};
const NOW='2026-10-09T05:00:00.000Z';
function channel(extra={}){return {channel_id:'channel-1',channel_name:'UPI 主通道',provider:'PayOne',priority:1,weight:40,enabled:true,status_text:'开启',is_present:true,balance:'125.25',balance_currency:'USDT',min_amount:'100',max_amount:'50000',limit_currency:'INR',success_rate_10m:'44.99',success_rate_30m:'45',success_rate_1h:'0',success_rate_4h:null,success_rate_8h:'99.99',success_rate_24h:'50',success_rate_today:'75',success_rate_total:'80',observed_at:NOW,last_seen_at:NOW,...extra};}
function response(rows=[channel()],extra={}){return {version:1,queriedAt:NOW,platforms:[P],snapshots:[{platformId:P.id,direction:'charge',observedAt:NOW,receivedAt:NOW,sourceCount:rows.length,complete:true,channels:rows},{platformId:P.id,direction:'withdraw',observedAt:null,receivedAt:null,sourceCount:null,complete:false,channels:[]}],...extra};}
function fixture(options={}){let page='channel_status',clock=Date.parse(NOW),handler=options.handler||(()=>response());const calls=[],paints=[],timers=[];const context={Intl,console,setTimeout:(fn,ms)=>{const t={fn,ms,active:true};timers.push(t);return t;},clearTimeout:t=>{t.active=false;},Date:class extends Date{constructor(...args){super(...(args.length?args:[clock]))}static now(){return clock}}};context.window=context;vm.createContext(context);vm.runInContext(source,context);const L={dirty:false,pageQueried:false,country:'印度',team:'all',source:'all',direction:'all',multi:{},provider:''},selected=options.selected||[P],allowed=options.allowed||(()=>true);const mod=context.HensemLiveChannelStatus.create({L,getPage:()=>page,selected:()=>selected,activeValues:()=>L.provider?[L.provider]:[],roleAllowed:allowed,request:async q=>{calls.push(JSON.parse(JSON.stringify(q)));return handler(q)},render:()=>paints.push(mod.render())});return {context,L,mod,calls,paints,timers,setPage:v=>page=v,setNow:v=>clock=Date.parse(v),setHandler:v=>handler=v};}

test('queries only supported native IDs and latest direction/provider scope; unsupported platform is explicit',async()=>{const h=fixture({selected:[P,O]});h.L.direction='charge';h.L.provider='PayOne';h.setHandler(()=>response([channel()],{snapshots:response().snapshots.slice(0,1)}));await h.mod.load();assert.deepEqual(h.calls,[{action:'channelStatus',platformIds:[P.id],direction:'charge',providers:['PayOne']}]);assert.match(h.mod.render(),/未接入通道快照：Other/);assert.doesNotMatch(h.mod.render(),/提现通道/);});
test('single-platform rows keep one readable line; platform names repeat only for a multi-platform comparison',async()=>{const h=fixture();await h.mod.load();assert.match(h.mod.render(),/class="channel-name">UPI 主通道<\/th>/);const second={...P,id:O.id,name:'Second KB'},multi=fixture({selected:[P,second],handler:()=>response([channel()],{platforms:[P,second]})});await multi.mod.load();assert.match(multi.mod.render(),/UPI 主通道<small>YASH.BET<\/small>/);});

test('source rates use black at 45, red below; missing/invalid percentages stay unknown without average',async()=>{const h=fixture();await h.mod.load();const html=h.mod.render();assert.match(html,/channel-rate channel-rate-low">44\.99%/);assert.match(html,/class="channel-rate">45\.00%/);assert.match(html,/channel-rate channel-rate-low">0\.00%/);assert.match(html,/>—<\/td>/);assert.doesNotMatch(html,/平均|汇总成功率|tfoot/);const x=fixture({handler:()=>response([channel({success_rate_10m:'101',success_rate_total:'bad'})])});await x.mod.load();assert.doesNotMatch(x.mod.render(),/101\.00%|NaN/);});
test('balance currency is independent from INR limits and zero/negative balance is retained',async()=>{const h=fixture({handler:()=>response([channel({balance:'-2.5',min_amount:'0',weight:0,priority:0})])});await h.mod.load();const html=h.mod.render();assert.match(html,/>-2\.50<\/td><td>USDT<\/td><td class="num">0\.00/);assert.match(html,/50,000\.00<\/td><td>INR/);const exported=h.mod.exportRows();assert.equal(exported[3][8],-2.5);assert.equal(exported[3][9],'USDT');assert.equal(exported[3][12],'INR');});
test('enabled channels precede disabled by explicit priority and unknown statuses never become disabled',async()=>{const h=fixture({handler:()=>response([channel({channel_id:'off',channel_name:'Disabled first',enabled:false,priority:0}),channel({channel_id:'on2',channel_name:'Enabled second',priority:4}),channel({channel_id:'on1',channel_name:'Enabled first',priority:1}),channel({channel_id:'unknown',channel_name:'Unknown status',enabled:null})])});await h.mod.load();const html=h.mod.render();assert(html.indexOf('Enabled first')<html.indexOf('Enabled second'));assert(html.indexOf('Enabled second')<html.indexOf('Disabled first'));assert.match(html,/Unknown status[\s\S]*?channel-state ">未提供/);});
test('disappeared channel retains last seen timestamp and never becomes disabled',async()=>{const old='2026-10-09T04:30:00.000Z',h=fixture({handler:()=>response([channel({is_present:false,last_seen_at:old})])});await h.mod.load();const html=h.mod.render();assert.match(html,/本次未出现/);assert.match(html,/超过 5 分钟未更新/);assert.doesNotMatch(html,/已停用/);assert.equal(h.mod.exportRows()[3].at(-2),old);});
test('no snapshot differs from a verified empty snapshot and neither fabricates rates',async()=>{const h=fixture();await h.mod.load();assert.match(h.mod.render(),/当前通道 —/);assert.match(h.mod.render(),/尚未收到快照/);const empty=fixture({handler:()=>response([],{snapshots:[...response([]).snapshots.slice(0,1),{...response([]).snapshots[1],observedAt:NOW,complete:true}]})});await empty.mod.load();assert.match(empty.mod.render(),/0 个当前通道/);assert.match(empty.mod.render(),/已采集，暂无通道/);assert.doesNotMatch(empty.mod.render(),/0\.00%/);});
test('details expand inline and escape business notes/channel names; no drawer or fee inference',async()=>{const h=fixture({handler:()=>response([channel({channel_name:'<img src=x onerror=alert(1)>',notes:'<script>bad</script> 4% 业务说明',payment_method:'UPI',balance_threshold:'5',balance_threshold_currency:'USDT'})])});await h.mod.load();h.context.liveChannelToggle(0);const html=h.mod.render();assert.match(html,/class="channel-detail"><td colspan="20"/);assert.match(html,/&lt;script&gt;bad&lt;\/script&gt;/);assert.doesNotMatch(html,/<script>|<img|openDrawer|手续费/);assert.match(html,/4% 业务说明/);h.context.liveChannelToggle(0);assert.doesNotMatch(h.mod.render(),/channel-detail"><td/);});
test('detail/query/export permissions are checked even direct handler calls',async()=>{const view=fixture({allowed:a=>a==='view'});await view.mod.load();assert.equal(view.calls.length,0);const h=fixture({allowed:a=>['view','query'].includes(a)});await h.mod.load();h.context.liveChannelToggle(0);assert.doesNotMatch(h.mod.render(),/onclick="liveChannelToggle|channel-detail"><td/);assert.equal(h.mod.canExport(),false);assert.deepEqual(Array.from(h.mod.exportRows()),[]);});
test('scope change and navigation cancellation reject old responses and exports',async()=>{let finish;const pending=new Promise(resolve=>finish=resolve),h=fixture({handler:()=>pending}),loading=h.mod.load();h.L.provider='Other';h.L.dirty=true;h.mod.cancel();finish(response());await loading;assert.equal(h.mod.canExport(),false);assert.equal(h.mod.capture().response,null);h.setHandler(()=>response());h.L.provider='';await h.mod.load();assert.equal(h.mod.canExport(),true);h.setPage('overview');h.context.liveChannelToggle(0);assert.equal(h.mod.render(),'');assert.equal(h.mod.canExport(),false);});
test('response identity, duplicates and direction mismatches fail closed',async()=>{for(const value of [response([],{platforms:[O]}),response([channel(),channel()]),response([],{snapshots:[{platformId:O.id,direction:'charge',observedAt:NOW,channels:[]}]}),response([],{queriedAt:null})]){const h=fixture({handler:()=>value});await h.mod.load();assert.equal(h.mod.capture().status,'error');assert.equal(h.mod.canExport(),false);}});
test('unknown balance currency stays explicit and never inherits the platform INR currency',async()=>{const h=fixture({handler:()=>response([channel({balance:'100',balance_currency:null})])});await h.mod.load();assert.match(h.mod.render(),/100\.00<\/td><td>未提供<\/td>/);assert.equal(h.mod.exportRows()[3][9],'未提供');});

test('freshness changes locally after five minutes without network reads, and navigation cancellation clears its timer',async()=>{const h=fixture();await h.mod.load();const timer=h.timers.findLast(t=>t.active);assert.equal(timer.ms,300001);h.setNow('2026-10-09T05:05:01Z');timer.fn();assert.match(h.paints.at(-1),/超过 5 分钟未更新/);assert.equal(h.calls.length,1);await h.mod.load();h.setNow(NOW);h.mod.render();const latest=h.timers.findLast(t=>t.active);h.setPage('overview');h.mod.cancel();assert.equal(latest.active,false);});

test('snapshot restore keeps result without refetch and stale badge uses server time plus elapsed',async()=>{const h=fixture();await h.mod.load();const saved=h.mod.capture();h.mod.clear();h.mod.restore(saved);assert.equal(h.calls.length,1);assert.match(h.mod.render(),/>已更新/);h.setNow('2026-10-09T05:06:00Z');assert.match(h.mod.render(),/超过 5 分钟未更新/);assert.match(h.mod.exportRows()[0][1],/不合并平均/);});

const prefix=fs.readFileSync(path.join(__dirname,'admin-navigation-performance.test.cjs'),'utf8').split(/\ntest\(/)[0].replace('vm.runInContext(source,context',"vm.runInContext(fs.readFileSync(path.join(__dirname,'../admin-preview/live-channel-status.js'),'utf8'),context);vm.runInContext(source,context");
const {harness,settle,deferred}=new Function('require','__dirname',prefix+';return {harness,settle,deferred};')(require,__dirname);
const owner={mode:'owner',canView:true,permissions:[]};
function integrated(options={}){return harness({page:'channel_status',roleAccess:owner,roleAllowed:()=>true,...options,handler:options.handler||((q)=>q.action==='catalog'?{platforms:[P,O]}:q.action==='channelStatus'?response():{})});}

test('production route navigates under provider center, has no date UI and never reads orders/fees on entry/query',async()=>{const h=integrated();await settle();assert.equal(h.c.state.page,'channel_status');assert(h.c.navGroupsV3.find(g=>g[3].includes('providers'))[3].includes('channel_status'));assert.deepEqual(h.calls.map(q=>q.action),['catalog']);const filters=h.nodes.get('liveFilters').innerHTML;assert.match(filters,/最新通道快照/);assert.match(filters,/业务方向/);assert.doesNotMatch(filters,/快捷日期|datetime-local|liveDateTrigger/);await h.c.liveQuery();assert.deepEqual(h.calls.map(q=>q.action),['catalog','channelStatus']);assert.match(h.html(),/充值通道/);assert.match(h.html(),/提现通道/);assert.doesNotMatch(h.html(),/手续费|订单成功金额/);});
test('live route respects explicit role query/export and prevents legacy page access',async()=>{const legacy=integrated({roleAccess:{mode:'legacy',canView:true,permissions:[]}});await settle();assert.notEqual(legacy.c.state.page,'channel_status');assert(!legacy.c.pages.some(p=>p[0]==='channel_status'));const h=integrated({roleAccess:{mode:'assigned',canView:true,permissions:['channel_status.view','channel_status.export']}});await settle();await h.c.liveQuery();h.c.liveExport();assert.deepEqual(h.calls.map(q=>q.action),['catalog']);assert.equal(h.blobs.length,0);assert.match(h.html(),/未获查询权限/);});
test('manual channel export retains source basis and snapshot times; dirty scope forbids export',async()=>{const h=integrated();await settle();await h.c.liveQuery();h.c.liveExport();assert.equal(h.blobs.length,1);const csv=await h.blobs[0].text();assert.match(csv,/源站通道快照/);assert.match(csv,/USDT/);assert.match(csv,/2026-10-09T05:00:00/);h.c.liveSet('provider','PayOne');assert.equal(h.L.dirty,true);h.c.liveExport();assert.equal(h.blobs.length,1);assert.equal(h.calls.filter(q=>q.action==='providerOptions').length,0);});
test('channel tab restores snapshot locally; reset and close discard it without any background query',async()=>{const h=integrated();await settle();await h.c.liveQuery();h.c.setPage('overview');h.c.setPage('channel_status');await settle();assert.match(h.html(),/UPI 主通道/);assert.equal(h.calls.filter(q=>q.action==='channelStatus').length,1);h.c.liveReset();assert.match(h.html(),/点击查询/);assert.doesNotMatch(h.html(),/UPI 主通道/);await h.c.liveQuery();h.c.liveClosePage('channel_status');h.c.setPage('channel_status');await settle();assert.match(h.html(),/点击查询/);assert.equal(h.calls.filter(q=>q.action==='channelStatus').length,2);});
test('pending channel read cannot repaint the destination or resume after leaving the tab',async()=>{const wait=deferred(),h=integrated({handler:q=>q.action==='catalog'?{platforms:[P]}:wait.promise});await settle();const read=h.c.liveQuery();h.c.setPage('overview');const before=h.html();wait.resolve(response());await read;assert.equal(h.html(),before);h.c.setPage('channel_status');await settle();assert.match(h.html(),/查询已暂停/);assert.equal(h.calls.filter(q=>q.action==='channelStatus').length,1);h.c.liveExport();assert.equal(h.blobs.length,0);});
test('bundle sources include new page styles and sticky readable table has no cramped global overrides',()=>{const build=fs.readFileSync(path.join(__dirname,'../admin-preview/build-restoration.py'),'utf8'),css=fs.readFileSync(path.join(__dirname,'../admin-preview/live-channel-status.css'),'utf8');assert.match(build,/'live-channel-status.js'/);assert.match(build,/'live-channel-status.css'/);assert.match(css,/\.channel-table thead th\{position:sticky;top:0/);assert.match(css,/\.channel-table \.channel-name\{position:sticky;left:0/);assert.match(css,/padding:10px 9px;line-height:1\.45/);assert.match(css,/\.channel-rate\{color:#161616\}/);});
