// Synthetic grouped-rule fixtures; no database, credentials, or production records.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../admin-preview/live-withdraw-pages.js'),'utf8');
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fixture(response){let html='',page;const calls=[],root={Intl,Date,document:{querySelector(){return null},getElementById(){return null}},HensemLiveFilters:{multi(){return ''}}};root.window=root;vm.createContext(root);vm.runInContext(source,root);const draw=()=>{html=page.render()};page=root.HensemLiveWithdrawPages.create({L:{catalogReady:true,catalog:[{country:'印度',name:'SYNTHETIC'}],country:'印度',from:'2026-09-26T00:00:00',to:'2026-09-26T23:59:59'},E:escape,N:String,C:String,R:(n,d)=>d?(100*n/d).toFixed(2)+'%':'—',page:()=> 'auto_withdraw',box:(_,body)=>body,table:(headers,rows)=>'<table>'+headers.join('|')+rows.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</table>',request:async q=>{calls.push(q);return typeof response==='function'?response(q):response},render:draw});page.state.data={country:'印度',rows:[{country:'印度',platform:'SYNTHETIC'}],totals:{},notes:[]};page.state.reason={country:'印度',platform:'SYNTHETIC',date:'2026-09-26',kind:'blocking'};page.state.reasonData=typeof response==='function'?response({offset:0}):response;draw();return {root,page,calls,html:()=>html,draw};}
const settle=async()=>{for(let i=0;i<3;i++)await new Promise(setImmediate)};
const grouped={available:true,source:'Synthetic',noteCount:120,total:2,canViewOrders:true,coverage:{collected:160},rows:[{reason:'首存金额超过19999',reasonKey:'a'.repeat(32),sourceReason:'首存金额大于19999,首存金额:25000',sourceVariantCount:7,count:90},{reason:'首存金额超过29999',reasonKey:'b'.repeat(32),sourceReason:'首存金额大于29999,首存金额:35000',sourceVariantCount:3,count:30}]};
test('grouped first-deposit thresholds stay distinct while the full original remains readable',()=>{const h=fixture(grouped);assert.match(h.html(),/>首存金额超过19999<\/button>/);assert.match(h.html(),/>首存金额超过29999<\/button>/);assert.match(h.html(),/已合并 7 种原文/);assert.match(h.html(),/75\.00%/);assert.match(h.html(),/25\.00%/);assert.match(h.html(),/共 2 条/);h.root.withdrawReasonOriginal(grouped.rows[0].sourceReason,'自动出款拦截原文（代表样本）');assert.match(h.html(),/aria-label="自动出款拦截原文（代表样本）"/);assert.match(h.html(),/<pre>首存金额大于19999,首存金额:25000<\/pre>/);});
test('reason paging uses grouped category count and keeps the total-note denominator',async()=>{const h=fixture(q=>({...grouped,total:21,rows:q.offset?[grouped.rows[1]]:grouped.rows}));h.root.withdrawReasonPage(2);await settle();assert.equal(h.calls[0].kind,'blocking');assert.equal(h.calls[0].offset,20);assert.equal(h.calls[0].limit,20);assert.match(h.html(),/共 21 条 · 21–21/);assert.match(h.html(),/2 \/ 2/);assert.match(h.html(),/25\.00%/);assert.match(h.html(),/disabled onclick="withdrawReasonPage\(3\)"/);});
test('existing rejection-original order drilldown retains its own key and source scope',async()=>{const reasonKey='c'.repeat(32),h=fixture({...grouped,rows:[{reason:'原始驳回说明',sourceReason:'原始驳回说明',reasonKey,count:12}]});h.page.state.reason.kind='rejection';h.root.withdrawReasonDrill(0,'reason');await settle();assert.equal(h.calls[0].kind,'orders');assert.equal(h.calls[0].reasonKey,reasonKey);assert.equal(h.calls[0].country,'印度');assert.equal(h.calls[0].platform,'SYNTHETIC');assert.equal(h.calls[0].date,'2026-09-26');assert.equal(h.calls[0].offset,0);});
test('a rule opens every original variant and keeps its canonical key for real blocking orders',async()=>{const rule=grouped.rows[0],h=fixture(q=>q.kind==='blockingVariants'?{...grouped,canViewBlockingOrders:true,rows:[{reason:rule.sourceReason,sourceReason:rule.sourceReason,reasonKey:rule.reasonKey,canonicalReason:rule.reason,count:70,success:20,rejected:45,other:5}]}:q.kind==='blockingOrders'?{...grouped,canViewBlockingOrders:true,rows:[{orderNumber:'SYNTHETIC-SUCCESS',amount:25000,status:'已通过',manualRemark:rule.sourceReason,blockingReason:rule.reason,blockingThreshold:'19999',blockingActualField:'首存金额',blockingActualValue:'25000'}]}:{...grouped,canViewBlockingOrders:true});h.root.withdrawBlockingDrill(0,'blockingVariants');await settle();assert.equal(h.calls[0].kind,'blockingVariants');assert.equal(h.calls[0].reasonKey,rule.reasonKey);assert.match(h.html(),/完整原文\|笔数\|成功\|驳回\|其他状态/);assert.match(h.html(),/返回规则分类/);h.root.withdrawBlockingView('blockingOrders');await settle();assert.equal(h.calls.at(-1).kind,'blockingOrders');assert.equal(h.calls.at(-1).reasonKey,rule.reasonKey);assert.match(h.html(),/SYNTHETIC-SUCCESS/);assert.match(h.html(),/首存金额：25000/);assert.match(h.html(),/19999/);assert.match(h.html(),/已通过/);assert.doesNotMatch(h.html(),/当日驳回订单|笔驳回订单计算/);h.root.withdrawReasonQuery('SYNTHETIC');h.root.withdrawReasonSearch();await settle();assert.equal(h.calls.at(-1).query,'SYNTHETIC');h.root.withdrawBlockingView('blockingVariants');await settle();assert.equal(h.page.state.reason.query,undefined);h.root.withdrawReasonRetry();await settle();assert.equal(h.calls.at(-1).query,undefined);assert.equal(h.calls.at(-1).reasonKey,rule.reasonKey);});
test('snapshot variants never fabricate order access and changing day clears the previous rule',async()=>{const h=fixture({...grouped,canViewBlockingOrders:false});const n=h.calls.length;h.root.withdrawBlockingDrill(0,'blockingOrders');await settle();assert.equal(h.calls.length,n);h.root.withdrawBlockingDrill(0,'blockingVariants');await settle();assert.equal(h.calls.at(-1).kind,'blockingVariants');assert.match(h.html(),/无法还原逐笔订单/);h.root.withdrawBlockingView('blockingOrders');await settle();assert.equal(h.calls.at(-1).kind,'blockingVariants');h.root.withdrawReasonDate('2026-09-25');await settle();assert.equal(h.calls.at(-1).kind,'blocking');assert.equal(h.calls.at(-1).reasonKey,undefined);assert.equal(h.calls.at(-1).date,'2026-09-25');});
test('reason size is bounded and shrinking results cannot strand a later page',async()=>{let total=137;const h=fixture(q=>({...grouped,total}));h.root.withdrawReasonSize('50');await settle();assert.equal(h.calls.at(-1).limit,50);h.root.withdrawReasonPage(999);await settle();assert.equal(h.calls.at(-1).offset,100);h.root.withdrawReasonSize('100');await settle();assert.equal(h.calls.at(-1).limit,100);h.root.withdrawReasonSize('999');assert.equal(h.page.state.reasonSize,100);h.root.withdrawReasonPage(2);await settle();total=0;h.root.withdrawReasonRetry();await settle();assert.equal(h.page.state.reasonPage,1);assert.equal(h.calls.at(-1).offset,0);});
test('manual reason percentages exclude system and unknown notes and explain unknown in one compact line',()=>{const h=fixture({...grouped,noteCount:90,total:1,rows:[{...grouped.rows[0],count:90}],summary:{blockingCounts:{raw:120,manual:90,system:25,unknown:5}}});assert.match(h.html(),/人工处理记录/);assert.match(h.html(),/90 笔人工处理记录计算，含未记录拦截说明的记录/);assert.match(h.html(),/系统说明已排除 25 笔/);assert.match(h.html(),/操作人未明 5 笔未计入/);assert.match(h.html(),/100\.00%/);assert.doesNotMatch(h.html(),/75\.00%|占已记录说明/);assert.equal((h.html().match(/class="withdraw-denominator"/g)||[]).length,1);});
test('zero unknown does not add an empty warning and rejection view keeps its own denominator',()=>{const h=fixture({...grouped,summary:{blockingCounts:{raw:120,manual:120,system:0,unknown:0}}});assert.doesNotMatch(h.html(),/操作人未明 0 笔|系统说明已排除/);h.page.state.reason.kind='rejection';h.draw();assert.match(h.html(),/120 笔驳回订单计算/);assert.doesNotMatch(h.html(),/人工拦截订单|操作人未明|系统说明已排除/);});

test('manual blank reasons join the blocking total and share its denominator',()=>{const h=fixture({...grouped,noteCount:4271,total:2,canViewBlockingOrders:true,rows:[{...grouped.rows[0],count:2868},{reason:'检测没备注',reasonKey:'d'.repeat(32),sourceReason:null,sourceVariantCount:1,count:1403}],summary:{operatorCounts:{total:6188,manual:4271,system:1917,unknown:0,manualWithReason:2868,manualWithoutReason:1403},blockingCounts:{raw:4785,manual:2868,system:1917,unknown:0}}});assert.match(h.html(),/<span>人工总数<\/span><strong>4271<\/strong>/);assert.match(h.html(),/<span>已采集到说明<\/span><strong>2868<\/strong>/);assert.match(h.html(),/<span>未记录拦截说明<\/span><strong>1403<\/strong>/);assert.match(h.html(),/<span>已采集提现订单<\/span><strong>6188<\/strong>/);assert.match(h.html(),/系统订单 1917 笔已排除/);assert.match(h.html(),/4271 笔人工处理记录计算，含未记录拦截说明的记录/);assert.match(h.html(),/67\.15%/);assert.match(h.html(),/32\.85%/);assert.match(h.html(),/>未记录拦截说明<\/button>/);assert.doesNotMatch(h.html(),/已采集到说明的人工订单计算/);});
test('blank category drilldown preserves blank source notes and shows successful manual orders',async()=>{const key='d'.repeat(32),h=fixture(q=>({...grouped,noteCount:1,total:1,canViewBlockingOrders:true,rows:q.kind==='blockingVariants'?[{canonicalReason:'检测没备注',reason:'检测没备注',sourceReason:null,count:1,success:1,rejected:0,other:0}]:q.kind==='blockingOrders'?[{orderNumber:'SYNTHETIC-EMPTY',amount:100,status:'已通过',operator:'manual-agent',manualRemark:null,rawManualRemark:null,blockingReason:'检测没备注'}]:[{reason:'检测没备注',reasonKey:key,count:1}]}));h.root.withdrawBlockingDrill(0,'blockingVariants');await settle();assert.equal(h.calls.at(-1).reasonKey,key);assert.match(h.html(),/（当前采集记录未提供拦截说明）/);h.root.withdrawBlockingView('blockingOrders');await settle();assert.equal(h.calls.at(-1).reasonKey,key);assert.match(h.html(),/SYNTHETIC-EMPTY/);assert.match(h.html(),/已通过/);assert.match(h.html(),/未记录拦截说明/);assert.doesNotMatch(h.html(),/检测没备注/);assert.match(h.html(),/（当前采集记录未提供拦截说明）/);});
test('snapshot operator totals stay unknown even when its reason coverage has a count',()=>{const h=fixture({...grouped,coverage:{unique_count:999},summary:{operatorCounts:{total:null,manual:null,system:null,unknown:null,manualWithReason:120,manualWithoutReason:null}}});assert.match(h.html(),/<span>人工总数<\/span><strong>—<\/strong>/);assert.match(h.html(),/<span>未记录拦截说明<\/span><strong>—<\/strong>/);assert.match(h.html(),/<span>已采集提现订单<\/span><strong>—<\/strong>/);assert.match(h.html(),/当前来源只提供已记录分类，完整人工总数未提供/);assert.match(h.html(),/<span>已采集到说明<\/span><strong>120<\/strong>/);});
test('known zero manual coverage displays zero without being labeled unknown',()=>{const h=fixture({...grouped,noteCount:0,total:0,rows:[],summary:{operatorCounts:{total:10,manual:0,system:10,unknown:0,manualWithReason:0,manualWithoutReason:0}}});assert.match(h.html(),/<span>人工总数<\/span><strong>0<\/strong>/);assert.match(h.html(),/<span>未记录拦截说明<\/span><strong>0<\/strong>/);assert.doesNotMatch(h.html(),/当前来源只提供已记录分类/);assert.match(h.html(),/系统订单 10 笔已排除/);});

test('snapshot blank-note coverage is explained without inventing a blocking rule, failed outcome, or source omission',()=>{
 const key='e'.repeat(32),h=fixture({...grouped,noteCount:634,total:2,canViewBlockingOrders:false,rows:[{reason:'充提差额未达免审要求',reasonKey:'f'.repeat(32),count:547},{reason:'检测没备注',reasonKey:key,sourceReason:null,count:87,success:86,rejected:1,other:0}],summary:{operatorBasis:'snapshot_classification',operatorCounts:{manual:null,total:null,manualWithReason:547,manualWithoutReason:87}}});
 assert.match(h.html(),/>未记录拦截说明<\/button>/);assert.match(h.html(),/13\.72%/);assert.match(h.html(),/当前采集记录没有可用拦截说明/);assert.match(h.html(),/具体转人工原因待核对，不代表提现失败/);
 assert.doesNotMatch(h.html(),/检测没备注|源站没有填写|采集漏掉了|87 笔提现失败/);
 assert.equal(h.page.state.reasonData.rows[1].reasonKey,key);assert.equal(h.page.state.reasonData.rows[1].success,86);assert.equal(h.page.state.reasonData.summary.operatorCounts.manual,null);
});

test('unknown explanation counts stay unknown instead of inheriting the whole manual denominator',()=>{
 const h=fixture({...grouped,summary:{operatorCounts:{manual:120,manualWithoutReason:30}}});
 assert.match(h.html(),/<span>已采集到说明<\/span><strong>—<\/strong>/);assert.doesNotMatch(h.html(),/<span>已采集到说明<\/span><strong>120<\/strong>/);
});

test('withheld blocking originals remain unavailable while their distinct coverage and drill key are retained',async()=>{
 const key='9'.repeat(32),base={...grouped,noteCount:100,total:3,summary:{operatorCounts:{manual:100,manualWithReason:70,manualWithoutReason:20,manualWithheldReason:10}},rows:[{reason:'拦截说明已隐藏',reasonKey:key,count:10,blockingNoteState:'withheld'}]};
 const h=fixture(q=>q.kind==='blockingVariants'?{...base,rows:[{canonicalReason:'拦截说明已隐藏',sourceReason:'SYNTHETIC-HIDDEN-DO-NOT-DISPLAY',reasonKey:key,blockingNoteState:'withheld',count:10}]}:base);
 assert.match(h.html(),/<span>说明已隐藏<\/span><strong>10<\/strong>/);assert.match(h.html(),/10\.00%/);assert.match(h.html(),/当前来源未提供可查看的原文/);
 h.root.withdrawBlockingDrill(0,'blockingVariants');await settle();assert.equal(h.calls.at(-1).reasonKey,key);assert.match(h.html(),/拦截说明已隐藏，具体原因待核对/);assert.doesNotMatch(h.html(),/SYNTHETIC-HIDDEN-DO-NOT-DISPLAY/);
});

test('empty and uncollected blocking states retain different provenance explanations',()=>{
 const h=fixture({...grouped,rows:[{canonicalReason:'检测没备注',sourceReason:null,blockingNoteState:'empty',count:3},{canonicalReason:'检测没备注',sourceReason:null,blockingNoteState:'missing',count:4}]});h.page.state.reason.kind='blockingVariants';h.draw();
 assert.match(h.html(),/采集字段为空，具体转人工原因待核对/);assert.match(h.html(),/未采集到明确拦截说明/);assert.doesNotMatch(h.html(),/源站没有填写|检测没备注/);
});

test('a present note with the same text as the hidden-state label remains an available original',()=>{
 const h=fixture({...grouped,rows:[{canonicalReason:'拦截说明已隐藏',sourceReason:'SYNTHETIC-LITERAL-PRESENT-NOTE',blockingNoteState:'present',count:1}]});h.page.state.reason.kind='blockingVariants';h.draw();
 assert.match(h.html(),/SYNTHETIC-LITERAL-PRESENT-NOTE/);assert.doesNotMatch(h.html(),/（拦截说明已隐藏，具体原因待核对）/);
});

test('mixed unavailable coverage exposes only evidenced empty and missing subtotals',()=>{
 const h=fixture({...grouped,rows:[{reason:'检测没备注',reasonKey:'0'.repeat(32),count:7,blockingNoteState:'mixed',blockingNoteStates:{empty:3,missing:4,present:0,withheld:0}}]});
 assert.match(h.html(),/采集字段为空 3 笔 · 未取得说明 4 笔/);assert.doesNotMatch(h.html(),/源站没有填写|已隐藏 0/);assert.match(h.html(),/>未记录拦截说明<\/button>/);
});
