// Synthetic fixtures only. Verify manual query boundaries and independent data sources.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../admin-preview/live-workorder-operations.js'),'utf8');
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const record={platform:'SYNTHETIC',country:'印度',currency:'INR',workorderId:'ID-1',workorderNo:'WORK-1',orderNo:'RC20260901SYNTHETIC',amount:'1234567890123456.12345678',statusCode:4,issueKind:'deposit',attachmentTypes:['pdf'],fieldGaps:['payment_order_no_missing'],provider:'<script>bad</script>'};
function harness(){let active='workorders',html='',drawer='',renders=0,response={sourceStatus:'ready',rows:[record],total:1,platforms:['SYNTHETIC']};const calls=[],root={},L={catalogReady:true,country:'印度',catalog:[{name:'SYNTHETIC',country:'印度',timezone:'Asia/Kolkata'}],from:'2026-09-01T00:00:00',to:'2026-09-27T23:59:59'};vm.runInNewContext(source,{window:root});let module;
 module=root.HensemLiveWorkorderOperations.create({L,E:escape,C:v=>String(v??0),formatTime:v=>v,box:(title,body)=>'<h2>'+title+'</h2>'+body,table:(headers,rows)=>'<table>'+headers.join('|')+rows.map(r=>r.join('|')).join('\n')+'</table>',request:async q=>{calls.push(q);return typeof response==='function'?response(q):response},render:()=>{renders++;html=module.render()},page:()=>active,openDrawer:(title,body)=>{drawer=title+body},renderDaily:()=>'OLD_DAILY_ONLY',loadDaily:async()=>{calls.push({action:'workorders'})}});
 return {root,module,L,calls,html:()=>html,drawer:()=>drawer,renders:()=>renders,setPage:p=>{active=p},respond:r=>{response=r}};
}
test('records are an independent read-only list and preserve source status and exact amount',async()=>{const h=harness();await h.module.load();assert.equal(h.calls[0].action,'workorderRecords');assert.equal(h.calls[0].view,'records');assert.equal(h.calls[0].country,'印度');assert.match(h.html(),/逐笔采集工单/);assert.match(h.html(),/1,234,567,890,123,456\.12345678/);assert.match(h.html(),/已处理/);assert.match(h.html(),/不代表支付订单已到账/);assert.match(h.html(),/&lt;script&gt;bad/);assert.doesNotMatch(h.html(),/<script>|编辑|保存/);});
test('typing stays local until query and querying a complete identifier permits cleared dates',async()=>{const h=harness();await h.module.load();const calls=h.calls.length,renders=h.renders();h.root.workorderOperationsSet('orderNo','ORDER-EXACT',false);assert.equal(h.calls.length,calls);assert.equal(h.renders(),renders);h.root.workorderOperationsClearDates();await h.module.load(true);assert.equal(h.calls.at(-1).filters.orderNo,'ORDER-EXACT');assert.equal(h.calls.at(-1).filters.from,'');assert.equal(h.calls.at(-1).filters.to,'');});
test('detail is scoped by country platform and internal ID and never renders attachment URLs',async()=>{const h=harness();await h.module.load();h.respond({row:record});await h.root.workorderOperationsDetail(0);const q=h.calls.at(-1);assert.equal(q.operation,'detail');assert.equal(q.filters.platform,'SYNTHETIC');assert.equal(q.filters.workorderId,'ID-1');assert.match(h.drawer(),/支付订单号缺失/);assert.match(h.drawer(),/附件查看尚未接入/);assert.doesNotMatch(h.drawer(),/payment_order_no_missing|https?:/);});
test('missing and workload keep separate query state and explicit source limitations',async()=>{const h=harness();h.setPage('workorder_reconciliation');h.respond({sourceStatus:'ready',rows:[],total:0,summary:{unknownOperationCount:4}});await h.module.load();assert.equal(h.calls.at(-1).view,'missing');assert.equal(h.calls.at(-1).filters.dateBasis,'operation');assert.match(h.html(),/当前授权范围内另有 4 条操作时间未确认/);h.root.workorderOperationsSet('registrationStatus','review');h.setPage('workorder_workload');await h.module.load();assert.equal(h.calls.at(-1).view,'workload');assert.equal(h.calls.at(-1).filters.registrationStatus,undefined);assert.match(h.html(),/不代表员工完整操作事件流水/);assert.doesNotMatch(h.html(),/onchange="workorderOperationsSet\('statusCode'/);});
test('operation logs have their own action and only supported filters; detail does not issue a new read',async()=>{const h=harness();h.setPage('workorder_operation_logs');h.respond({sourceStatus:'ready',rows:[{id:'event',createdAt:'2026-09-27T01:00:00Z',actorName:'synthetic',action:'follow',platform:'SYNTHETIC',workorders:['WORK-1'],orderNo:'ORDER-1',note:'<note>',before:{outcome:'pending'},after:{outcome:'success',untrusted:'should not show'}}],total:1});await h.module.load();assert.equal(h.calls[0].action,'portalOperationLogs');assert.deepEqual(Object.keys(h.calls[0].filters).sort(),['from','to','platform','operator','action','orderNo','workorderNo','utr'].sort());const n=h.calls.length;await h.root.workorderOperationsDetail(0);assert.equal(h.calls.length,n);assert.match(h.drawer(),/变更前.*变更后/);assert.match(h.drawer(),/&lt;note&gt;/);assert.doesNotMatch(h.drawer(),/untrusted|should not show/);});
test('pagination uses bounded size and an empty last page resets safely',async()=>{const h=harness();h.respond({sourceStatus:'ready',rows:[record],total:137});await h.module.load();h.module.state().current=7;h.respond({sourceStatus:'ready',rows:[],total:0});await h.module.load();assert.equal(h.module.state().current,1);assert.match(h.html(),/0–0/);h.root.workorderOperationsSize('500');assert.equal(h.module.state().size,20);assert.match(h.html(),/20 条 \/ 页/);assert.match(h.html(),/50 条 \/ 页/);assert.match(h.html(),/100 条 \/ 页/);});
