const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const code=fs.readFileSync(path.join(__dirname,'../admin-preview/live-analysis-drilldown.js'),'utf8');
const E=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const metric=(a=100,c=10,s=70,n=7)=>({direction:'charge',currency:'INR',all_amount:a,all_count:c,created_success_count:4,success_amount:s,success_count:n,pending_amount:20,pending_count:2,failed_amount:10,failed_count:1,rejected_amount:0,rejected_count:0,unknown_amount:0,unknown_count:0});
const segment={kind:'hourly',direction:'charge',hour:8};
function setup(request){const platforms=[{id:'a',name:'SAME',source:'ar',timezone:'Asia/Kolkata',currency:'INR'},{id:'b',name:'SAME',source:'newar',timezone:'Asia/Kolkata',currency:'INR'}],L={serial:1,queryScope:'x',from:'2026-09-20T00:00:00',to:'2026-09-24T23:59:59',currency:'INR',direction:'all',status:'all',catalog:platforms,results:platforms.map((p,i)=>({platform:p,summary:[metric()],groups:{hourly:[{...metric(100,10,i?30:70,i?3:7),hour:8}],amount_range:[{...metric(),bucket:'100–200'}],matrix_range:[{...metric(),bucket:'100–200',hour:8}],latency:[{direction:'charge',currency:'INR',bucket:0,count:i?2:8,amount:i?20:80}],latency_thresholds:[{direction:'charge',currency:'INR',bucket:0,threshold_ms:300000,count:2,amount:20}]}}))};let calls=[],renders=0;const root={};vm.runInNewContext(code,{window:root,console,Intl,Date});const instance=root.HensemAnalysisDrilldown.create({L,E,N:n=>n==null?'—':Number(n).toFixed(2),C:n=>String(n),R:(n,d)=>d>0?(n/d*100).toFixed(2)+'%':'—',query:p=>({action:'aggregate',platformId:p.id,startAt:'2026-09-19T18:30:00Z',endAt:'2026-09-24T18:30:00Z',status:'all',providers:['ORIGINAL'],currency:'INR'}),request:q=>{calls.push(q);return request?request(q):Promise.resolve({complete:true,hasMore:false,summary:[],groups:{daily:[{...metric(),date:'2026-09-20'}]}})},render:()=>renders++});const action=(s,op,value)=>root.liveAnalysisAction(encodeURIComponent(JSON.stringify(s)),op,value===undefined?undefined:encodeURIComponent(value));return {root,L,instance,action,calls,get renders(){return renders}}}
const flush=async()=>{for(let i=0;i<15;i++)await new Promise(r=>setImmediate(r))};
test('platform expansion stays local, keeps same-name sources distinct and uses segment denominators',()=>{const h=setup();h.instance.button(segment,'8时');h.action(segment,'toggle');const html=h.instance.panel(segment);assert.equal(h.calls.length,0);assert.match(html,/70\.00%/);assert.match(html,/30\.00%/);assert.match(html,/>ar</);assert.match(html,/>newar</);assert.match(html,/40\.00%/);assert.equal(h.instance.platformRows(segment).length,2);});
test('missing amounts and unavailable latency direction stay unknown, never zero success',()=>{const h=setup();h.L.results[0].groups.hourly[0].success_amount=null;h.instance.open(segment,'8时');const html=h.instance.panel(segment);assert.match(html,/—/);const cells=[...html.matchAll(/<tr>(.*?)<\/tr>/gs)].slice(1).map(m=>[...m[1].matchAll(/<td>(.*?)<\/td>/gs)].map(x=>x[1]));assert(cells.every(row=>row[5]==='—'));h.L.results[0].groups.latency=[{direction:'withdraw',bucket:0,count:1,amount:1}];const row=h.instance.platformRows({kind:'latency',direction:'charge',bucket:0}).find(r=>r.platformId==='a');assert.equal(row.success_count,null);assert.equal(row.success_amount,null);});
test('latency and cross-segment matches exclude other hours and directions',()=>{const h=setup();h.L.results[0].groups.matrix_range.push({...metric(9000,900,9000,900),hour:9,bucket:'100–200'});const rows=h.instance.platformRows({kind:'matrix_range',direction:'charge',hour:8,bucket:'100–200'});assert.equal(rows[0].all_count,10);const latency=h.instance.platformRows({kind:'latency',direction:'charge',bucket:0,cumulative:true});assert.equal(latency[0].success_count,2);});
test('single-day expansion does not offer daily comparison and escapes source labels',()=>{const h=setup();h.L.to='2026-09-20T23:59:59';h.L.results[0].platform.name='<script>alert(1)</script>';h.instance.open(segment,'<img>');const html=h.instance.panel(segment);assert.doesNotMatch(html,/每日对比|查看每天|<script>|<img>/);assert.match(html,/&lt;script&gt;/);assert.equal(h.calls.length,0);});
test('daily comparison queries one range per platform, caches results and shows every selected day',async()=>{const h=setup();h.instance.open(segment,'8时');h.action(segment,'daily');await flush();assert.equal(h.calls.length,2);assert(h.calls.every(q=>q.view==='drilldown'&&q.kind==='hourly'&&q.hour===8&&q.providers[0]==='ORIGINAL'));const html=h.instance.panel(segment);for(let d=20;d<=24;d++)assert.match(html,new RegExp('2026-09-'+d));h.action(segment,'platform');h.action(segment,'daily');await flush();assert.equal(h.calls.length,2);});
test('choosing one platform first requests only that platform and preserves partial-day bounds',async()=>{const h=setup();h.instance.open(segment,'8时');h.action(segment,'platformDaily','b');await flush();assert.equal(h.calls.length,1);assert.equal(h.calls[0].platformId,'b');assert.equal(h.calls[0].startAt,'2026-09-19T18:30:00Z');});
test('failed daily results remain partial and retry only failed platform',async()=>{let failed=true;const h=setup(q=>q.platformId==='b'&&failed?Promise.reject(Error('timeout')):Promise.resolve({complete:true,hasMore:false,summary:[],groups:{daily:[{...metric(),date:'2026-09-20'}]}}));h.instance.open(segment,'8时');h.action(segment,'daily');await flush();assert.match(h.instance.panel(segment),/每日对比尚不完整/);failed=false;h.action(segment,'retry');await flush();assert.equal(h.calls.length,3);assert.equal(h.calls[2].platformId,'b');assert.doesNotMatch(h.instance.panel(segment),/每日对比尚不完整/);});
test('old async results cannot refill a new query scope',async()=>{let resolve;const h=setup(()=>new Promise(r=>{resolve=r}));h.instance.open(segment,'8时');h.action(segment,'daily');h.L.serial=2;h.L.results=[];h.instance.table({headers:[],rows:[],cells:()=>[],segment:()=>segment,label:()=>''});resolve({complete:true,hasMore:false,summary:[],groups:{daily:[{...metric(99999),date:'2026-09-20'}]}});await flush();assert.equal(h.instance.snapshot().states.size,0);assert.doesNotMatch(h.instance.panel(segment),/99999/);});
test('closing an unrelated expansion does not cancel the active daily request',async()=>{const waiting=[];const h=setup(()=>new Promise(r=>waiting.push(r)));h.instance.open(segment,'8时');h.action(segment,'daily');const other={...segment,hour:9};h.instance.open(other,'9时');h.action(other,'toggle');waiting.forEach(r=>r({complete:true,hasMore:false,summary:[],groups:{daily:[]}}));await flush();const s=h.instance.snapshot().states.get(JSON.stringify(segment));assert.equal(s.daily.get('all').loading,false);assert.equal(s.daily.get('all').results.size,2);});
test('tables keep all main rows operable after more than 32 segment buttons render',()=>{const h=setup();const rows=Array.from({length:48},(_,i)=>({kind:'hourly',direction:i<24?'charge':'withdraw',hour:i%24}));h.instance.table({id:'many',headers:['时段'],rows,cells:r=>[r.hour],segment:r=>r,label:r=>r.hour+'时'});h.action(rows[0],'toggle');assert.match(h.instance.panel(rows[0]),/analysis-drilldown/);assert.equal(h.calls.length,0);});
test('switching daily ranges never runs more than two actual requests and skips stale queued work',async()=>{const waiting=[];const h=setup(q=>new Promise(resolve=>waiting.push({q,resolve})));h.instance.open(segment,'8时');h.action(segment,'daily');assert.equal(h.calls.length,2);const second={...segment,hour:9},third={...segment,hour:10};h.instance.open(second,'9时');h.action(second,'daily');h.instance.open(third,'10时');h.action(third,'daily');assert.equal(h.calls.length,2);waiting.slice(0,2).forEach(x=>x.resolve({complete:true,hasMore:false,summary:[],groups:{daily:[]}}));await flush();assert.equal(h.calls.length,4);assert(h.calls.slice(2).every(q=>q.hour===10));waiting.slice(2).forEach(x=>x.resolve({complete:true,hasMore:false,summary:[],groups:{daily:[]}}));await flush();});
