// Offline synthetic fixtures only; no production values or credentials.
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const sql=fs.readFileSync(path.join(__dirname,'../supabase/admin-live-payout-config.sql'),'utf8');
const scopeSQL=fs.readFileSync(path.join(__dirname,'../supabase/admin-live-query.sql'),'utf8').match(/create function private\.dashboard_admin_live_scope\(\)[\s\S]+?revoke all on function private\.dashboard_admin_live_scope\(\) from public,anon,authenticated;/)[0];
let db;const uid='10000000-0000-0000-0000-000000000002';
const call=(r={})=>db.query('select public.dashboard_admin_live_payout_config($1::jsonb) as value',[JSON.stringify(r)]).then(r=>r.rows[0].value);
const snap=(system,platform,country='IN')=>call({operation:'snapshot',system,country,platform});
async function mutate(statement,fn){await db.exec('reset role');await db.exec(statement);await db.exec('set role authenticated');try{await fn()}finally{await db.exec(`reset role;update dashboard_profiles set active=true,permissions='{"auto_withdraw":true}',data_scope='{"mode":"all"}';update dashboard_admin_preview_grants set can_view=true;set role authenticated`);}}
before(async()=>{db=new PGlite();await db.exec(`
create schema auth;create schema private;create role authenticated;create role anon;grant usage on schema auth,private to authenticated;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create table dashboard_profiles(auth_user_id uuid,role text,active boolean,permissions jsonb,data_scope jsonb);
create table dashboard_admin_preview_grants(auth_user_id uuid,can_view boolean);
insert into dashboard_profiles values('${uid}','viewer',true,'{"auto_withdraw":true}','{"mode":"all"}');insert into dashboard_admin_preview_grants values('${uid}',true);
create function private.dashboard_current_data_scope() returns jsonb language sql security definer set search_path='' as $$select data_scope from public.dashboard_profiles where auth_user_id=auth.uid() and active$$;
create function public.dashboard_has_permission(text) returns boolean language sql security definer set search_path='' as $$select active and coalesce((permissions->>$1)::boolean,false) from public.dashboard_profiles where auth_user_id=auth.uid()$$;
create function private.dashboard_scope_allows(jsonb,text,text) returns boolean language sql immutable as $$select coalesce($1->>'mode'='all' or ($1->'platforms' ? ($2||':'||$3)),false)$$;
create function private.dashboard_data_group(text,text) returns text language sql immutable as $$select case when $2='PANGHU' then 'BR_PANGHU' else $1 end$$;
create table ar_config_targets(country_code text,country_name text,platform text,timezone text,currency text,source_system text);
create table panda_config_targets(country_code text,country_name text,platform text,timezone text,currency text);
create table wg_config_targets(country_code text,country_name text,platform text,timezone text,site_code text,members jsonb);
create table ar_config_daily(country_code text,platform text,timezone text,observed_at timestamptz,observed_local_date date,received_at timestamptz,parser_version text,configuration jsonb);
create table panda_config_daily(like ar_config_daily including all);create table wg_config_daily(like ar_config_daily including all);
create table panda_config_dictionary_daily(country_code text,platform text,timezone text,observed_at timestamptz,dictionary jsonb);
create table test_game_targets(value jsonb);create table test_game_rules(value jsonb);
create function public.dashboard_game66_review_rules() returns jsonb language plpgsql security definer set search_path='' as $$declare s jsonb:=private.dashboard_current_data_scope();begin
if public.dashboard_has_permission('auto_withdraw') is not true then raise exception 'legacy_denied' using errcode='42501';end if;
return jsonb_build_object('targets',(select coalesce(jsonb_agg(value),'[]') from public.test_game_targets where private.dashboard_scope_allows(s,'印度',value->>'platform_name')),'rules',(select coalesce(jsonb_agg(r.value),'[]') from public.test_game_rules r join public.test_game_targets t on t.value->>'platform_id'=r.value->>'platform_id' where private.dashboard_scope_allows(s,'印度',t.value->>'platform_name')));end$$;
insert into ar_config_targets values('IN','印度','AR-A','Asia/Kolkata','INR','AR'),('IN','印度','NEW-A','Asia/Kolkata','INR','NEW_AR'),('IN','印度','EMPTY','Asia/Kolkata','INR','AR');
insert into panda_config_targets values('IN','印度','PANDA-A','Asia/Kolkata','INR'),('BR','巴西','PANGHU','America/Sao_Paulo','BRL');
insert into wg_config_targets values('IN','印度','WG-A','Asia/Kolkata','10','[{"site_code":"11","name":"Brand A","token":"SECRET"}]');
`);await db.exec(scopeSQL);await db.exec(sql);
const add=async(table,platform,configuration,day='22')=>db.query(`insert into ${table} values('IN',$1,'Asia/Kolkata',$2::timestamptz,$3::date,$2::timestamptz,'fixture-v1',$4::jsonb)`,[platform,`2026-09-${day}T12:00:00+05:30`,`2026-09-${day}`,JSON.stringify(configuration)]);
await add('ar_config_daily','AR-A',{fields:[{key:'autoWithdraw',kind:'boolean',value:true,available:true,label:'启用',token:'SECRET'},{key:'withdrawAmount',kind:'number',value:0,available:true},{key:'totalLoss',value:null,available:false},{key:'password',value:'SECRET'}],groups:[{key:'userGroups',options:[{value:'a',label:'A',selected:true,phone:'SECRET'}]}],raw_payload:{cookie:'SECRET'}});
await add('ar_config_daily','AR-A',{fields:[{key:'autoWithdraw',kind:'boolean',value:false,available:true}]},'21');
await add('ar_config_daily','NEW-A',{fields:[{key:'autoWithdraw',value:false,available:true}],channels:[{id:'1',channelName:'Channel',channelType:'bank',channelUrl:'https://private.example',token:'SECRET'}],channelRules:[{id:'2',name:'Rule',phone:'SECRET',bankAccount:'SECRET'}],settingGroups:[{id:1,configName:'Group',maxWithdrawAmount:200,token:'SECRET',password:'SECRET'}]});
await add('panda_config_daily','PANDA-A',{values:{autoWithdrawalSwitch:false,autoWithdrawalAmountMix:12345,autoWithdrawalChannel:[{withdrawalChannelId:1,tenantWithdrawTypeId:2,token:'SECRET',channelUrl:'https://private.example'}],auditGameLimit:{safe:1,accountNumber:'SECRET'},password:'SECRET'},unavailable_fields:['minSuccessRate','password']});
await add('wg_config_daily','WG-A',{settings:{0:{exemptSwitch:0,otherCondition:{amount:10,token:'SECRET',note:'Bearer SECRET'}},11:{exemptSwitch:1},bad:{exemptSwitch:1}},dictionaries:{levels:[{id:1,name:'L1',phone:'SECRET'}],token:'SECRET'},completeness:{available:[],unavailable:['tags']}});
await db.query('insert into panda_config_dictionary_daily values($1,$2,$3,$4,$5)', ['IN','PANDA-A','Asia/Kolkata','2026-09-22T12:00Z',JSON.stringify({country_code:'IN',platform:'PANDA-A',channels:[{id:1,withdraw_type_id:2,name:'Safe',token:'SECRET'}],levels:[]})]);
await db.query('insert into panda_config_dictionary_daily values($1,$2,$3,$4,$5)', ['IN','PANDA-A','Asia/Kolkata','2026-09-23T12:00Z',JSON.stringify({country_code:'IN',platform:'OTHER',channels:[{name:'WRONG'}]})]);
for(const [id,name,team]of [['1','HK-A','hong_kong'],['2','RC-A','red_crab'],['3','GEM7','hong_kong']]){await db.query('insert into test_game_targets values($1)',[JSON.stringify({platform_id:id,platform_name:name,team_code:team,team_name:team,timezone:'Asia/Kolkata',updated_at:'2026-09-22T12:00Z',rule_count:1})]);await db.query('insert into test_game_rules values($1)',[JSON.stringify({platform_id:id,rule_id:'1',title:'Threshold',value:100,enabled:true,last_seen_at:'2026-09-20T12:00:00Z',raw_payload:{token:'SECRET'},remark:'SECRET',description:'SECRET'})]);}
await db.query("select set_config('test.uid',$1,false)",[uid]);await db.exec('set role authenticated');});
after(async()=>{await db?.close()});
test('new standalone functions only, fixed table identifiers, no source writes',()=>{assert.doesNotMatch(sql,/create or replace|alter table|create policy|insert into|update public\.|delete from/i);assert(!sql.includes('execute p_request'));});
test('AR/NEW_AR distinct target registries and latest snapshot zero/false/null preserved',async()=>{assert.deepEqual((await call({system:'AR'})).targets.map(x=>x.platform),['AR-A','EMPTY']);assert.deepEqual((await call({system:'NEW_AR'})).targets.map(x=>x.platform),['NEW-A']);const r=await snap('AR','AR-A');assert.equal(r.snapshot.observed_local_date,'2026-09-22');assert.equal(r.snapshot.configuration.fields[0].value,true);assert.equal(r.snapshot.configuration.fields[1].value,0);assert.equal(r.snapshot.configuration.fields[2].value,null);assert.equal((await snap('AR','EMPTY')).snapshot,null);await assert.rejects(()=>snap('AR','NEW-A'),/config_target_denied/);});
test('every response strips credentials, arbitrary contact fields, URLs and raw payloads without source mutation',async()=>{for(const [s,p]of [['AR','AR-A'],['NEW_AR','NEW-A'],['PANDA','PANDA-A'],['WG','WG-A'],['GAME66_HK','HK-A']]){const text=JSON.stringify(await snap(s,p,s.startsWith('GAME')?s:'IN'));assert.doesNotMatch(text,/SECRET|private\.example|channelUrl|raw_payload|bankAccount|phone|password/);}await db.exec('reset role');assert((await db.query("select configuration from ar_config_daily where platform='NEW-A'")).rows[0].configuration.channels[0].token);await db.exec('set role authenticated');});
test('Panda dictionary identity checked; WG brands remain separate; known display group preserved',async()=>{const p=await snap('PANDA','PANDA-A');assert.equal(p.snapshot.dictionary.channels[0].name,'Safe');assert.equal((await call({system:'PANDA'})).targets.find(t=>t.platform==='PANGHU').display_group,'BR_PANGHU');const w=await snap('WG','WG-A');assert.deepEqual(Object.keys(w.snapshot.configuration.settings),['0','11']);assert.equal(w.snapshot.configuration.settings['0'].exemptSwitch,0);assert.equal(w.snapshot.configuration.settings['11'].exemptSwitch,1);});
test('G66 preserves old scope, teams and excluded platforms; only safe rule columns',async()=>{const r=await call({system:'GAME66_HK'});assert.deepEqual(r.targets.map(t=>t.platform),['HK-A']);assert.deepEqual((await call({system:'GAME66_RED_CRAB'})).targets.map(t=>t.platform),['RC-A']);await mutate(`update dashboard_profiles set data_scope='{"mode":"selected","platforms":["HK_TEAM:HK-A"]}'`,async()=>assert.equal((await call({system:'GAME66_HK'})).targets.length,0));await mutate(`update dashboard_profiles set data_scope='{"mode":"selected","platforms":["印度:HK-A"]}'`,async()=>assert.equal((await call({system:'GAME66_HK'})).targets.length,1));});
test('fresh preview grant, active profile and old auto_withdraw permission are all required',async()=>{await mutate('update dashboard_admin_preview_grants set can_view=false',()=>assert.rejects(()=>call(),/preview_denied/));await mutate('update dashboard_profiles set active=false',()=>assert.rejects(()=>call(),/preview_denied/));await mutate("update dashboard_profiles set permissions='{}'",()=>assert.rejects(()=>call(),/auto_withdraw_permission_denied/));await db.query("select set_config('test.uid','',false)");try{await assert.rejects(()=>call(),/login_required/)}finally{await db.query("select set_config('test.uid',$1,false)",[uid]);}});
test('index, summaries and snapshot all honor updated platform scope; direct denied target cannot leak',async()=>{await mutate(`update dashboard_profiles set data_scope='{"mode":"selected","platforms":["IN:EMPTY"]}'`,async()=>{const r=await call();assert.deepEqual(r.targets.map(t=>t.platform),['EMPTY']);assert.deepEqual(r.summaries,[]);await assert.rejects(()=>snap('AR','AR-A'),/config_target_denied/);assert.equal((await snap('AR','EMPTY')).snapshot,null);});});
test('strict request schema and target validation block selector injection and null ambiguity',async()=>{for(const r of [null,[],1,{system:'ar'},{operation:'delete'},{system:'AR',table:'ar_config_daily'},{platform:'AR-A'},{system:null},{operation:'snapshot',system:'AR'},{operation:'snapshot',system:'AR',country:'IN',platform:'x\n'},{operation:'snapshot',system:'AR',country:'IN',platform:"x';select 1;--"}])await assert.rejects(()=>call(r),/invalid_|config_target_denied/);});
test('helper ACL and anonymous access closed',async()=>{await assert.rejects(()=>db.query("select private.dashboard_admin_config_projection('AR','{}')"),/permission denied/);await db.exec('reset role;set role anon');try{await assert.rejects(()=>call(),/permission denied/)}finally{await db.exec('reset role;set role authenticated');}});

test('AR to NewAR target reclassification cannot silently accept a stale old-format snapshot',async()=>{await db.exec("reset role;update ar_config_targets set source_system='NEW_AR' where platform='AR-A';set role authenticated");try{await assert.rejects(()=>snap('NEW_AR','AR-A'),/config_snapshot_incomplete/);}finally{await db.exec("reset role;update ar_config_targets set source_system='AR' where platform='AR-A';set role authenticated");}});

test('G66 observation uses rule last_seen, never platform metadata time; zero rules means unavailable',async()=>{const r=await snap('GAME66_HK','HK-A','GAME66_HK');assert.equal(r.snapshot.observed_local_date,'2026-09-20');assert.equal((await call({system:'GAME66_HK'})).summaries[0].observed_local_date,'2026-09-20');await db.exec("reset role;begin;delete from test_game_rules where value->>'platform_id'='1';update test_game_targets set value=jsonb_set(value,'{rule_count}','0') where value->>'platform_id'='1';set role authenticated");try{assert.equal((await snap('GAME66_HK','HK-A','GAME66_HK')).snapshot,null);assert.equal((await call({system:'GAME66_HK'})).summaries.length,0);}finally{await db.exec('reset role;rollback;set role authenticated');}});
test('single-function deployment correction exactly matches tested canonical definition and reapplies safely',async()=>{const patch=fs.readFileSync(path.join(__dirname,'../supabase/admin-live-payout-config-shape-fix.sql'),'utf8');const extract=s=>s.match(/create(?: or replace)? function private\.dashboard_admin_live_payout_config\([\s\S]+?\n\$\$;/)[0].replace('create or replace function','create function');assert.equal(extract(patch),extract(sql));await db.exec('reset role');try{await db.exec(patch)}finally{await db.exec('set role authenticated')}assert.equal((await snap('AR','AR-A')).snapshot.configuration.fields[1].value,0);await assert.rejects(()=>snap('AR','NEW-A'),/config_target_denied/);});
