/* Synthetic current-scope facts only: no network, credentials or source orders. */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const base=path.join(__dirname,'../admin-preview'),renderer=fs.readFileSync(path.join(base,'live-success-analysis.js'),'utf8');
function api(){const c={};c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(base,'live-provider-aliases.js'),'utf8'),c);vm.runInContext(renderer,c);return c.HensemLiveSuccessAnalysis;}
const A={id:'native-ar',name:'Same platform',source:'AR',country:'印度'},B={...A,id:'native-newar',source:'NEW_AR'},W={...A,id:'native-wg',source:'WG'};
const row=(direction='charge',all=10,success=4,provider='ATPay')=>({direction,all_count:all,success_count:success,provider,currency:'INR'});
const payment=(platform,rows)=>({platform,groups:{provider:rows}});
const ticket=(platform,direction='charge',total=10,success=4,provider='ATPay',complete=true)=>({platformId:platform.id,country:platform.country,source:platform.source,provider,direction,uniqueOrderCount:total,uniqueSuccessCount:success,uniqueCoverage:{status:complete?'complete':'partial',complete}});
function props(overrides={}){const L={pageQueried:true,dirty:false,from:'2026-10-03T00:00:00',to:'2026-10-03T23:59:59',queryPlatforms:[A,B],results:[payment(A,[row()]),payment(B,[row('charge',5,1,'ATPay-QR')])],queryFailures:[],workorders:{startDate:'2026-10-03',endDate:'2026-10-03',byPlatformProvider:[ticket(A),ticket(A,'withdraw',5,5),ticket(B,'charge',6,1,'ATPay-QR',false)]},...overrides};return {L,scopeMatches:true,workordersScopeMatches:true};}
test('canonical provider rows keep native platform identity and three vertical rate-only matrices',()=>{
 const a=api(),p=props(),before=JSON.stringify(p),model=a.buildModel(p);assert.equal(model.rows.length,1);assert.equal(model.rows[0].provider,'ATPay');assert.deepEqual(Array.from(model.rows[0].charge,v=>v.value),[40,20]);assert.equal(model.rows[0].workorder[0].value,60);assert.equal(model.rows[0].workorder[0].partial,false);assert(Math.abs(model.rows[0].workorder[1].value-100/6)<1e-10);assert.equal(model.rows[0].workorder[1].partial,true);
 const html=a.render(p);assert.equal((html.match(/<table /g)||[]).length,3);assert.equal((html.match(/<th scope="row">ATPay<\/th>/g)||[]).length,3);assert.match(html,/新AR/);assert.match(html,/状态 4/);assert.match(html,/不代表实际到账/);assert.match(html,/完整原单号去重/);assert.doesNotMatch(html,/全部金额|手续费|到账成功金额/);assert.equal(JSON.stringify(p),before);
});
test('strict below-40 color applies to all matrices, unknown neutral and above-100 rates are preserved',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[payment(A,[row('charge',100,39),row('withdraw',10,4)])],workorders:{byPlatformProvider:[ticket(A,'charge',100,39),ticket(A,'withdraw',0,0)]}});let html=a.render(p);assert.equal((html.match(/class="success-rate-low"/g)||[]).length,2);assert.match(html,/>40\.00%<\/span>/);assert.match(html,/>39\.00%/);
 p.L.results=[payment(A,[row('charge',10,12),row('withdraw',10,null)])];p.L.workorders.byPlatformProvider=[ticket(A,'charge',0,0)];html=a.render(p);assert.match(html,/>120\.00%<\/span>/);assert.doesNotMatch(html,/success-rate-low/);assert.match(html,/>—<\/span>/);
});
test('workorder combined rate uses dedup original counts and preserves absent, unknown and duplicate cohort evidence',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[payment(A,[row()])],workorders:{byPlatformProvider:[ticket(A,'charge',8,4),ticket(A,'withdraw',2,2)]}}),work=()=>a.buildModel(p).rows[0].workorder[0];assert.equal(work().value,60);assert.equal(work().partial,false);
 p.L.workorders.byPlatformProvider.pop();assert.equal(work().value,50);assert.equal(work().partial,true);p.L.workorders.byPlatformProvider.push(ticket(A,'withdraw',null,0));assert.equal(work().value,null);p.L.workorders.byPlatformProvider=[ticket(A),ticket(A,'charge',10,3,'ATPay-QR')];assert.equal(work().value,null);
 p.L.workorders.byPlatformProvider=[{...ticket(A),uniqueOrderCount:null,submittedCount:999,successCount:999}];assert.equal(work().value,null);p.L.workorders.byPlatformProvider=[ticket(A,'charge',1,2)];assert.equal(work().value,null);
});
test('WG success time gaps affect its own withdrawal column and invalid or missing payment counts remain unknown',()=>{
 const a=api(),p=props({queryPlatforms:[A,W],results:[payment(A,[row('withdraw',10,6)]),payment(W,[row('withdraw',10,6),row('charge',10,3)])],workorders:null}),m=a.buildModel(p);assert.equal(m.rows[0].withdraw[0].value,60);assert.equal(m.rows[0].withdraw[1].value,null);assert.equal(m.rows[0].charge[1].value,30);p.L.results[0].platform={...A,capabilities:{withdrawSuccessTimeAvailable:false}};assert.equal(a.buildModel(p).rows[0].withdraw[0].value,null);p.L.results[0].platform=A;p.L.results[0].groups.provider[0].success_count='';assert.equal(a.buildModel(p).rows[0].withdraw[0].value,null);
});
test('each matrix ranks its own submitted volume across native platforms, with empty rows last',()=>{
 const a=api(),p=props({results:[payment(A,[row('charge',3,1,'A small'),row('charge',90,20,'Z busiest'),row('withdraw',200,100,'P payout'),row('charge',null,null,'Empty')]),payment(B,[row('charge',20,10,'Z busiest'),row('withdraw',5,1,'A small')])],workorders:{byPlatformProvider:[ticket(A,'charge',2,1,'Z busiest'),ticket(A,'charge',30,3,'T tickets'),ticket(B,'withdraw',40,4,'T tickets'),ticket(A,'withdraw',20,8,'A small')]}}),before=JSON.stringify(p),m=a.buildModel(p);
 assert.deepEqual(Array.from(a.rankedRows(m,'charge'),r=>r.provider),['Z busiest','A small','Empty','P payout','T tickets']);
 assert.deepEqual(Array.from(a.rankedRows(m,'withdraw'),r=>r.provider),['P payout','A small','Empty','T tickets','Z busiest']);
 assert.deepEqual(Array.from(a.rankedRows(m,'workorder'),r=>r.provider),['T tickets','A small','Z busiest','Empty','P payout']);
 const tables=a.render(p).match(/<tbody>.*?<\/tbody>/g),names=html=>Array.from(html.matchAll(/<th scope="row">(.*?)<\/th>/g),x=>x[1]);
 assert.equal(names(tables[0])[0],'Z busiest');assert.equal(names(tables[1])[0],'P payout');assert.equal(names(tables[2])[0],'T tickets');
 assert.equal(m.rows.find(r=>r.provider==='Z busiest').volumes.charge,110);assert.equal(m.rows.find(r=>r.provider==='T tickets').volumes.workorder,70);assert.equal(JSON.stringify(p),before);
});
test('known WG submission volume ranks ahead of smaller flows even when its rate cannot be verified',()=>{
 const a=api(),p=props({queryPlatforms:[A,W],results:[payment(A,[row('withdraw',10,5,'Small'),row('withdraw',0,0,'Zero')]),payment(W,[row('withdraw',50,20,'Busy WG')])],workorders:null}),m=a.buildModel(p);
 assert.deepEqual(Array.from(a.rankedRows(m,'withdraw'),r=>r.provider),['Busy WG','Small','Zero']);assert.equal(m.rows.find(r=>r.provider==='Busy WG').withdraw[1].value,null);assert.equal(m.rows.find(r=>r.provider==='Busy WG').volumes.withdraw,50);
 const html=a.render(p);assert.match(html,/提交笔数从多到少/);assert.match(html,/空数据置后/);assert.match(html,/>—<\/span>/);
});
test('dirty, foreign scope, multi-day and invalid-date snapshots never reveal rates',()=>{
 const a=api();for(const p of [props({dirty:true}),{...props(),scopeMatches:false},props({to:'2026-10-04T23:59:59'}),props({from:'2026-99-03',to:'2026-99-03'})]){assert.equal(a.buildModel(p).ready,false);assert.doesNotMatch(a.render(p),/<table|40\.00%|ATPay/);}
 const p={...props(),workordersScopeMatches:false};assert.equal(a.buildModel(p).rows[0].workorder[0].value,null);p.workordersScopeMatches=true;p.L.workorders.startDate='2026-10-02';assert.equal(a.buildModel(p).rows[0].workorder[0].value,null);
});
test('unknown native identity or cross-country/source rows cannot be assigned by shared display names',()=>{
 const a=api(),p=props();p.L.results=[payment({...A,source:'WG'},[row()])];p.L.workorders.byPlatformProvider=[{...ticket(A),platformId:null,platform:A.name},{...ticket(B),country:'巴西'},{...ticket(A),source:'NEW_AR'}];const m=a.buildModel(p);assert.equal(m.rows.length,0);assert.equal(m.ignored,3);assert.doesNotMatch(a.render(p),/40\.00%/);
 p.L.results=[payment(A,[row()]),payment(A,[row()])];p.L.workorders=null;assert.equal(a.buildModel(p).rows.length,0,'ambiguous duplicate aggregate platform is not summed');
});

// Reuse the established synthetic DOM fixture without registering its tests.
function harness(options={}){
 const fixture=fs.readFileSync(path.join(__dirname,'admin-live-ui.test.cjs'),'utf8'),start=fixture.indexOf('const P='),end=fixture.indexOf("test('team country",start),source=fs.readFileSync(path.join(base,'live-data.js'),'utf8');assert(start>0&&end>start);
 const moduleNames=['live-amount-bands.js','live-member-counts.js','live-submission-analysis.js','live-analysis-drilldown.js','live-matrix-custom-range.js','live-reference-layout.js','live-pages-reference.js','live-pending-snapshot.js','live-pending-analysis.js','live-empty-pages.js','live-duration-reference.js','live-payout-config.js','live-filter-controls.js','live-configuration.js','live-provider-aliases.js','live-provider-summary.js','live-provider-orders.js','live-provider-sticky.js','live-collected-data.js','live-report-data.js','live-withdraw-pages.js','live-workorder-operations.js','live-deposit-issues.js','live-success-analysis.js'];
 const sandbox={console,Intl,Date,URL,Blob,vm,source,comparisonSource:fs.readFileSync(path.join(base,'live-comparison.js'),'utf8'),layoutSources:moduleNames.map(name=>({name,source:fs.readFileSync(path.join(base,name),'utf8')}))};
 vm.createContext(sandbox);vm.runInContext(fixture.slice(start,end).replace('hensemRoleAllowed:options.roleAllowed,','hensemRoleAccess:options.roleAccess,hensemRoleAllowed:options.roleAllowed,')+'\nglobalThis.fixture={harness,P,aggregate,renderedTables};',sandbox);
 return sandbox.fixture.harness(options);
}
async function settle(){for(let i=0;i<25;i++)await new Promise(resolve=>setImmediate(resolve));}
const owner={mode:'owner',canView:true,permissions:[]};
async function ready(options={}){const h=harness({initialPage:'success_analysis',roleAccess:owner,roleAllowed:()=>true,...options});await settle();return h;}
test('single-date production adapter uses one aggregate per platform plus existing workorders and skips unrelated reads',async()=>{
 const h=await ready({adaptive:true,ancillaryHandler:true});assert.equal(h.c.state.page,'success_analysis');assert.equal(h.L.pageQueried,false);assert.match(h.nodes.get('liveFilters').innerHTML,/id="liveSuccessDate"/);assert.doesNotMatch(h.nodes.get('liveFilters').innerHTML,/livePeriod\('week'|livePeriod\('month'|liveDate-from|liveDate-to/);
 h.c.liveSuccessDate('2026-09-22');h.L.amountBandProfiles={charge:{edges:[0,1]}};h.L.multi.provider=['ATPay'];h.L.provider='ATPay';h.setHandler(q=>{if(q.action==='providerOptions')return {providers:['ATPay']};if(q.action==='workorders')return {startDate:'2026-09-22',endDate:'2026-09-22',byPlatformProvider:[],byProvider:[],byDirection:{},rows:[]};return {platform:h.L.catalog[0],groups:{provider:[row()]},summary:[],rows:[]};});h.calls.length=0;await h.c.liveQuery();await settle();
 const aggregates=h.calls.filter(q=>q.action==='aggregate');assert.equal(aggregates.length,1);assert.equal(aggregates[0].view,'providers');assert.equal(aggregates[0].direction,'all');assert.equal(aggregates[0].status,'all');assert.equal(aggregates[0].startAt,'2026-09-21T18:30:00.000Z');assert.equal(aggregates[0].endAt,'2026-09-22T18:30:00.000Z');assert.equal(aggregates[0].amountBands,undefined);assert.equal(h.calls.filter(q=>q.action==='workorders').length,1);assert(h.calls.every(q=>['providerOptions','aggregate','workorders'].includes(q.action)));assert.equal(h.L.comparisonResults.length,0);assert.match(h.html(),/代收成功率/);
});
test('new-page catalog ACL never inherits legacy or sibling analysis grants, and query/retry/export require own action',async()=>{
 for(const options of [{roleAccess:undefined,roleAllowed:()=>true},{roleAccess:{mode:'legacy',canView:true,permissions:[]},roleAllowed:()=>true},{roleAccess:{mode:'assigned',canView:true,permissions:['matrix.view','matrix.query']},roleAllowed:()=>true}]){const h=await ready(options);assert.notEqual(h.c.state.page,'success_analysis');assert(!h.c.pages.some(p=>p[0]==='success_analysis'));const n=h.calls.length;h.c.setPage('success_analysis');assert.notEqual(h.c.state.page,'success_analysis');assert.equal(h.calls.length,n);}
 const h=await ready({roleAccess:{mode:'assigned',canView:true,permissions:['success_analysis.view','success_analysis.export']}}),n=h.calls.length;assert.equal(h.c.state.page,'success_analysis');assert.match(h.html(),/未获查询权限/);await h.c.liveQuery();await h.c.liveLoad(true,true);await h.c.liveRetryFailed(true);await h.c.liveProviderWorkordersRetry();h.c.livePage(2,'workorders');h.c.liveExport();assert.equal(h.calls.length,n);assert.equal(h.blobs.length,0);assert.doesNotMatch(h.nodes.get('.title-actions').innerHTML,/liveExport/);
});
test('navigation normalizes inherited range visibly; explicit multiday query and dirty workorder retry are blocked',async()=>{
 const h=await ready({initialPage:'overview'});h.L.from='2026-09-20T00:00:00';h.L.to='2026-09-22T12:00:00';const n=h.calls.length;h.c.setPage('success_analysis');assert.equal(h.L.from,'2026-09-22T00:00:00');assert.equal(h.L.to,'2026-09-22T23:59:59');assert.match(h.L.successDateNotice,/已选择 2026-09-22 全天/);assert.equal(h.calls.length,n);h.L.to='2026-09-23T23:59:59';await h.c.liveQuery();assert.equal(h.calls.length,n);assert.match(h.L.error,/一个当地日/);assert.equal(h.L.dirty,true);await h.c.liveProviderWorkordersRetry();assert.equal(h.calls.length,n);
});
test('late workorder response after filter change cannot render old cohorts and independent retry rejects wrong day',async()=>{
 const h=await ready({ancillaryHandler:true});let resolveWork;h.setHandler(q=>q.action==='providerOptions'?{providers:['ATPay']}:q.action==='workorders'?new Promise(resolve=>resolveWork=resolve):{platform:h.L.catalog[0],groups:{provider:[row()]},summary:[],rows:[]});h.c.liveSuccessDate('2026-09-22');const pending=h.c.liveQuery();await settle();assert(resolveWork);h.c.liveSuccessDate('2026-09-21');resolveWork({startDate:'2026-09-22',endDate:'2026-09-22',byPlatformProvider:[ticket(h.L.catalog[0])],byProvider:[],byDirection:{}});await pending;assert.equal(h.L.workorders,null);assert.doesNotMatch(h.html(),/<table|40\.00%/);
 h.setHandler(q=>q.action==='providerOptions'?{providers:[]}:q.action==='workorders'?{startDate:'2026-09-20',endDate:'2026-09-20',byPlatformProvider:[],byProvider:[],byDirection:{}}:{platform:h.L.catalog[0],groups:{provider:[row()]},summary:[],rows:[]});await h.c.liveQuery();assert.equal(h.L.workorders,null);assert.match(h.L.workordersError,/日期响应不完整/);assert.match(h.html(),/重试工单/);
});
test('partial platform retry preserves known columns, rereads only failures, and tab restore does not read extra data',async()=>{
 const ps=[{...A,timezone:'Asia/Kolkata',currency:'INR'},{...B,timezone:'Asia/Kolkata',currency:'INR'}],h=await ready({platforms:ps,ancillaryHandler:true});let fail=true;
 h.setHandler(q=>{if(q.action==='providerOptions')return {providers:['ATPay']};if(q.action==='workorders')return {startDate:'2026-09-22',endDate:'2026-09-22',byPlatformProvider:[],byProvider:[],byDirection:{}};if(q.platformId===B.id&&fail)throw Error('Synthetic unavailable');return payment(ps.find(p=>p.id===q.platformId),[row('charge',10,q.platformId===A.id?4:3)]);});h.c.liveSuccessDate('2026-09-22');await h.c.liveQuery();assert.equal(h.L.queryFailures.length,1);assert.match(h.html(),/40\.00%/);assert.match(h.html(),/部分平台读取失败/);const n=h.calls.length;fail=false;await h.c.liveRetryFailed();const retry=h.calls.slice(n);assert.equal(retry.filter(q=>q.action==='aggregate').length,1);assert.equal(retry.find(q=>q.action==='aggregate').platformId,B.id);assert(retry.every(q=>q.action==='aggregate'));assert.equal(h.L.queryFailures.length,0);assert.match(h.html(),/30\.00%/);
 const frozen=h.L.results,n2=h.calls.length;h.c.setPage('overview');h.c.setPage('success_analysis');assert.strictEqual(h.L.results,frozen);assert.equal(h.calls.length,n2);assert.match(h.html(),/40\.00%/);assert.match(h.html(),/30\.00%/);
});
test('Today success query freezes the existing local elapsed-time cutoff and escapes source labels',async()=>{
 const h=await ready({ancillaryHandler:true});h.setHandler(q=>q.action==='providerOptions'?{providers:[]}:q.action==='workorders'?{startDate:'2026-09-23',endDate:'2026-09-23',byPlatformProvider:[],byProvider:[],byDirection:{}}:payment(h.L.catalog[0],[row('charge',10,4,'<script>bad</script>')]));h.c.livePeriod('today');assert.equal(h.L.from,'2026-09-23T00:00:00');assert.equal(h.L.to,'2026-09-23T23:59:59');h.calls.length=0;await h.c.liveQuery();const q=h.calls.find(q=>q.action==='aggregate');assert.equal(q.startAt,'2026-09-22T18:30:00.000Z');assert.equal(q.endAt,'2026-09-23T12:00:01.000Z');assert.equal(h.calls.filter(q=>q.action==='aggregate').length,1);assert.match(h.html(),/&lt;script&gt;bad&lt;\/script&gt;/);assert.doesNotMatch(h.html(),/<script/);assert.equal(h.L.to,'2026-09-23T23:59:59');
});
