/* Synthetic published source grids. No business values or direct network reads. */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../admin-preview/live-rates-restored.js'),'utf8');
const sheet=id=>({sheetId:id,title:'Synthetic Sheet '+id,index:id-1,rowCount:44,columnCount:8});
const metadata=(at='2026-10-01T00:00:00Z')=>({title:'Synthetic workbook',fetchedAt:at,sheets:[sheet(1),sheet(2)]});
function grid(id=1,at='2026-10-01T00:00:00Z',fee='4% + 2/笔'){const rows=[['三方名称','类型 / 钱包','代收合计%+单笔','代付合计%+单笔','总计费率','备注','PLATFORM-A','PLATFORM-B']];for(let i=0;i<42;i++)rows.push(['Synthetic-'+i,i%2?'Wallet B':'Wallet A',fee,'2%','6% + 2/笔','REF-'+i,i%2?'暂停':'开启',i%2?'维护':'未接入']);return {sheet:sheet(id),fetchedAt:at,cells:rows.map(row=>row.map(text=>({text}))),rowCount:rows.length,columnCount:8,merges:[],hiddenRows:[],hiddenColumns:[]};}
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {resolve,promise};};
function setup(options={}){const timers=new Map(),calls=[],flags={active:true,dirty:false,editing:false,restricted:options.restricted===true,identity:options.identity||'Synthetic Actor:IN'},scroller={scrollTop:0,scrollLeft:0};let id=0,handler=async q=>q.sheetId===undefined?metadata():grid(q.sheetId),focused=false,mounted=true;const host={clientWidth:1000,contains:()=>focused,querySelector:()=>scroller,innerHTML:''};const document={visibilityState:'visible',activeElement:null,getElementById:()=>mounted?host:null,querySelector:()=>null};const window={document,setTimeout:(f,ms)=>{timers.set(++id,{f,ms});return id},clearTimeout:id=>timers.delete(id)};const context={window};for(const forbidden of ['fetch','XMLHttpRequest','localStorage'])Object.defineProperty(context,forbidden,{get(){throw Error('Unexpected '+forbidden)}});vm.createContext(context);vm.runInContext(source,context);const api=window.HensemLiveRatesRestored;api.configure({request:q=>{calls.push(JSON.parse(JSON.stringify(q)));return handler(q)},isActive:()=>flags.active,isDirty:()=>flags.dirty,isEditing:()=>flags.editing,isRestrictedScope:()=>flags.restricted,scopeKey:()=>flags.identity});return {api,calls,timers,flags,document,scroller,setHandler:f=>handler=f,setFocused:v=>focused=v,setMounted:v=>mounted=v,async tick(){const entry=[...timers.entries()][0];assert(entry,'scheduled timer exists');timers.delete(entry[0]);entry[1].f();for(let i=0;i<5;i++)await new Promise(r=>setImmediate(r));}};}

test('query stays in filter bar; original field search combines with wallet/platform/status',async()=>{const h=setup();assert.equal(h.calls.length,0);assert.equal(h.timers.size,0);await h.api.load();const html=h.api.render();assert.doesNotMatch(html,/授权范围费率/);assert.match(html,/original-rates-filters[^]*HensemLiveRatesRestored.load[^]*original-rates-filter-actions/);h.api.set('query','REF-0');h.api.set('type','Wallet A');h.api.set('platform','6');h.api.set('status','good');assert.deepEqual([...h.api.model().rows],[1]);assert.equal(h.api.snapshot().filterDirty,true);assert.equal(h.calls.length,2);h.api.set('status','paused');assert.equal(h.api.model().rows.length,0);});

test('manual same-sheet refresh retains all filters, view, page, selected cell and scroll',async()=>{const h=setup();await h.api.load();h.api.set('view','full');h.api.set('query','REF');h.api.set('type','Wallet A');h.api.set('platform','6');h.api.set('status','good');h.api.page(2);h.api.cell(41,5);h.scroller.scrollTop=90;h.scroller.scrollLeft=450;h.setHandler(async q=>q.sheetId===undefined?metadata('2026-10-01T01:00:00Z'):grid(q.sheetId,'2026-10-01T01:00:00Z','5%'));await h.api.load();const s=h.api.snapshot();assert.deepEqual([s.query,s.type,s.platform,s.status,s.view,s.page,s.filterDirty],['REF','Wallet A','6','good','full',2,false]);assert.match(h.api.render(),/原单元格完整内容/);assert.match(h.api.render(),/5%/);assert.deepEqual([h.scroller.scrollTop,h.scroller.scrollLeft],[90,450]);});

test('automatic checks unchanged publication lightly; new publication refreshes same sheet without resetting view or page',async()=>{const h=setup();await h.api.load();h.api.page(2);assert.equal([...h.timers.values()][0].ms,60000);await h.tick();assert.deepEqual(h.calls.at(-1),{action:'ratesSheet'});assert.equal(h.calls.length,3);assert.equal(h.api.snapshot().page,2);h.setHandler(async q=>q.sheetId===undefined?metadata('2026-10-01T02:00:00Z'):grid(q.sheetId,'2026-10-01T02:00:00Z','7%'));await h.tick();assert.deepEqual(h.calls.slice(-2),[{action:'ratesSheet'},{action:'ratesSheet',sheetId:1}]);assert.equal(h.api.snapshot().page,2);assert.match(h.api.render(),/7%/);assert.equal(h.timers.size,1);});

test('hidden, detached, inactive, dirty, editing, focused and selected-content states skip automatic reads',async()=>{const h=setup();await h.api.load();const checks=[()=>h.document.visibilityState='hidden',()=>h.setMounted(false),()=>h.flags.active=false,()=>h.flags.dirty=true,()=>h.flags.editing=true,()=>h.setFocused(true),()=>h.api.cell(1,0),()=>h.api.set('query','Synthetic')];for(const activate of checks){h.document.visibilityState='visible';h.setMounted(true);h.flags.active=true;h.flags.dirty=false;h.flags.editing=false;h.setFocused(false);h.api.cell();await h.api.load();activate();const n=h.calls.length;await h.tick();assert.equal(h.calls.length,n);} });

test('draft changes or new focus during a poll prevent replacing the displayed grid',async()=>{const h=setup();await h.api.load();const newer=deferred();h.setHandler(q=>q.sheetId===undefined?Promise.resolve(metadata('2026-10-01T03:00:00Z')):newer.promise);await h.tick();assert.equal(h.api.snapshot().loading,true);h.api.set('query','REF-0');newer.resolve(grid(1,'2026-10-01T03:00:00Z','9%'));for(let i=0;i<4;i++)await new Promise(r=>setImmediate(r));assert.equal(h.api.snapshot().query,'REF-0');assert.equal(h.api.snapshot().filterDirty,true);assert.doesNotMatch(h.api.render(),/9%/);assert.match(h.api.render(),/4% \+ 2/);});

test('pause stops timer and in-flight response; resume does not read until a scheduled eligible check',async()=>{const h=setup();await h.api.load();const pending=deferred();h.setHandler(q=>q.sheetId===undefined?Promise.resolve(metadata('2026-10-01T04:00:00Z')):pending.promise);await h.tick();h.api.pause();assert.equal(h.timers.size,0);pending.resolve(grid(1,'2026-10-01T04:00:00Z','99%'));for(let i=0;i<3;i++)await new Promise(r=>setImmediate(r));assert.doesNotMatch(h.api.render(),/99%/);const count=h.calls.length;h.api.resume();assert.equal(h.calls.length,count);assert.equal(h.timers.size,1);h.api.clear();assert.equal(h.timers.size,0);assert.equal(h.api.snapshot().hasGrid,false);});

test('transient failures retain only same-sheet previous values; permission/session rejection clears all source cache',async()=>{const h=setup();await h.api.load();h.api.set('query','Synthetic');h.setHandler(async()=>{throw Error('Synthetic timeout')});await h.api.load();assert.equal(h.api.snapshot().hasGrid,true);assert.equal(h.api.snapshot().query,'Synthetic');assert.match(h.api.render(),/保留上次成功原表/);h.api.selectSheet(2);await h.api.load();assert.equal(h.api.snapshot().hasGrid,false);assert.doesNotMatch(h.api.render(),/4% \+ 2/);h.setHandler(async q=>q.sheetId===undefined?metadata():grid(q.sheetId));await h.api.load();h.api.set('query','Sensitive input');h.setHandler(async()=>{throw Error('正式数据读取未获授权，或会话已失效')});await h.api.load();assert.equal(h.api.snapshot().hasGrid,false);assert.equal(h.api.snapshot().sheetId,null);assert.equal(h.api.snapshot().query,'');assert.doesNotMatch(h.api.render(),/Synthetic Sheet|4% \+ 2|Sensitive input/);assert.equal(h.timers.size,0);});

test('schema changes preserve platform identity rather than silently mapping the old column index',async()=>{const h=setup();await h.api.load();h.api.set('platform','6');const swapped=grid();for(const row of swapped.cells)[row[6],row[7]]=[row[7],row[6]];h.setHandler(async q=>q.sheetId===undefined?metadata('2026-10-01T05:00:00Z'):swapped);await h.api.load();assert.equal(h.api.snapshot().platform,'7');assert.match(h.api.render(),/<option value="7" selected>PLATFORM-A/);const absent=grid();absent.cells[0][6].text='PLATFORM-C';h.setHandler(async q=>q.sheetId===undefined?metadata('2026-10-01T06:00:00Z'):absent);await h.api.load();assert.match(h.api.render(),/所选平台列在新版原表中待核对/);assert.equal(h.api.snapshot().platform,'7');assert.match(h.api.render(),/保留上次成功原表/);});

test('reconfigure and sheet changes reject stale responses without restarting old scopes',async()=>{const h=setup(),wait=deferred();h.setHandler(q=>q.sheetId===undefined?Promise.resolve(metadata()):wait.promise);const loading=h.api.load();for(let i=0;i<2;i++)await new Promise(r=>setImmediate(r));h.api.selectSheet(2);wait.resolve(grid(1));await loading;assert.equal(h.api.snapshot().sheetId,2);assert.equal(h.api.snapshot().hasGrid,false);h.setHandler(async q=>q.sheetId===undefined?metadata():grid(q.sheetId));await h.api.load();assert.equal(h.api.snapshot().sheetId,2);h.api.configure({request:async()=>{throw Error('New role permission_denied')}});assert.equal(h.api.snapshot().hasGrid,false);assert.equal(h.timers.size,0);await h.api.load();assert.doesNotMatch(h.api.render(),/Synthetic Sheet/);});

const scopedRow=i=>({id:'synthetic:'+i,provider:'ScopedPay-'+String(i).padStart(2,'0'),scopeType:i%2?'platform':'country',country:'印度',scopeGroup:'IN',platform:i%2?'SyntheticAlpha':null,category:'source category',collectFee:i===0?'0':'100–200: 4%; 201+: 3.5%',payoutFee:'0..8%',collectSingleFee:'2/笔',payoutSingleFee:null,collectLimit:'100/200',payoutLimit:'200/500',status:'active',rawStatus:null,updatedAt:'2026-10-01T00:00:00Z',sourceType:'Source Wallet',sourceTypeProvider:'ScopedPay-'+String(i).padStart(2,'0')});
function scoped(request,extra={}){let allowed=Array.from({length:42},(_,i)=>scopedRow(i));if(request.scopeType!=='all')allowed=allowed.filter(r=>r.scopeType===request.scopeType);if(request.country&&request.country!=='IN')allowed=[];if(request.platform)allowed=allowed.filter(r=>r.platform===request.platform);if(request.query)allowed=allowed.filter(r=>r.provider.toLowerCase().includes(request.query.toLowerCase()));return {version:1,basis:'current_rate_table',asOf:'2026-10-02T10:00:00Z',rows:allowed.slice(request.offset,request.offset+request.limit),total:allowed.length,offset:request.offset,limit:request.limit,hasMore:allowed.length>request.offset+request.limit,options:{countries:[{value:'IN',label:'印度'}],platforms:[{value:'SyntheticAlpha',country:'印度',scopeGroup:'IN'}],providers:allowed.map(r=>r.provider)},capabilities:{historicalFeeVersions:false,feeEstimate:false},...extra};}

test('restricted accounts use only server-projected rates, never read original metadata/grid or recover the removed button',async()=>{const h=setup({restricted:true});h.setHandler(async q=>{assert.equal(q.action,'rates');return scoped(q)});await h.api.load();assert.deepEqual(h.calls,[{action:'rates',scopeType:'all',offset:0,limit:20}]);assert.equal(h.api.snapshot().sourceMode,'scoped');assert.equal(h.api.snapshot().hasGrid,true);assert.match(h.api.render(),/ScopedPay-00|当前账号可见范围/);assert.match(h.api.render(),/100–200: 4%; 201\+: 3\.5%/);assert.match(h.api.render(),/0\.\.8%/);assert.doesNotMatch(h.api.render(),/授权范围费率|Google 原表页签|Synthetic Sheet|PLATFORM-B/);assert.match(h.api.render(),/共 42 条 · 当前 20 条/);});

test('scoped searches and server pagination preserve the exact confirmed filters without faking local full-table totals',async()=>{const h=setup({restricted:true});h.setHandler(async q=>scoped(q));await h.api.load();h.api.set('query','ScopedPay');h.api.set('scopeType','platform');h.api.set('country','IN');h.api.set('platform','SyntheticAlpha');await h.api.load();assert.deepEqual(h.calls.at(-1),{action:'rates',scopeType:'platform',country:'IN',platform:'SyntheticAlpha',query:'ScopedPay',offset:0,limit:20});assert.match(h.api.render(),/共 21 条 · 当前 20 条/);await h.api.page(2);assert.deepEqual(h.calls.at(-1),{action:'rates',scopeType:'platform',country:'IN',platform:'SyntheticAlpha',query:'ScopedPay',offset:20,limit:20});assert.match(h.api.render(),/当前 1 条/);assert.equal(h.api.snapshot().page,2);h.api.set('query','ScopedPay-01');const n=h.calls.length;await h.api.page(1);assert.equal(h.calls.length,n);await h.api.load();assert.match(h.api.render(),/共 1 条/);const before=h.api.snapshot();h.api.set('country','PK');h.api.set('platform','FOREIGN');assert.equal(h.api.snapshot().platform,before.platform);assert.equal(h.api.snapshot().filterDirty,false);});

test('scoped automatic refresh keeps the same page/filter request and transient same-query cache; changed query never shows old values',async()=>{const h=setup({restricted:true});h.setHandler(async q=>scoped(q));await h.api.load();await h.api.page(2);await h.tick();assert.deepEqual(h.calls.at(-1),{action:'rates',scopeType:'all',offset:20,limit:20});assert.equal(h.api.snapshot().page,2);h.setHandler(async()=>{throw Error('Synthetic scoped timeout')});await h.api.load();assert.match(h.api.render(),/保留上次同条件成功结果/);assert.match(h.api.render(),/ScopedPay-20/);h.api.set('query','DifferentQuery');await h.api.load();assert.equal(h.api.snapshot().hasGrid,false);assert.doesNotMatch(h.api.render(),/ScopedPay-20/);assert.match(h.api.render(),/Synthetic scoped timeout/);assert.doesNotMatch(h.api.render(),/没有符合查询条件的记录/);});

test('identity/scope changes immediately clear prior original or projected cache and reject in-flight older results',async()=>{const h=setup();await h.api.load();assert.match(h.api.render(),/Synthetic-0/);h.flags.restricted=true;h.flags.identity='Synthetic Actor:PK';assert.doesNotMatch(h.api.render(),/Synthetic-0|Synthetic Sheet/);assert.equal(h.api.snapshot().hasGrid,false);h.setHandler(async q=>scoped(q));await h.api.load();assert(h.calls.at(-1).action==='rates');const wait=deferred();h.setHandler(()=>wait.promise);const loading=h.api.load();h.flags.identity='Another Actor:IN';h.flags.restricted=false;assert.doesNotMatch(h.api.render(),/ScopedPay-/);wait.resolve(scoped({scopeType:'all',offset:0,limit:20}));await loading;assert.equal(h.api.snapshot().hasGrid,false);assert.equal(h.api.snapshot().sourceMode,'original');assert.equal(h.timers.size,0);});

test('scope changes during original metadata read stop the wider grid request even before rerender',async()=>{const h=setup(),wait=deferred();h.setHandler(()=>wait.promise);const loading=h.api.load();h.flags.restricted=true;h.flags.identity='Synthetic Restricted Actor';wait.resolve(metadata());await loading;assert.deepEqual(h.calls,[{action:'ratesSheet'}]);assert.equal(h.api.snapshot().sourceMode,'scoped');assert.equal(h.api.snapshot().hasGrid,false);assert.equal(h.api.model().rows.length,0);assert.equal(h.timers.size,0);});

test('scoped permission rejection, invalid shapes and wrong-provider type evidence fail safely without source-wide fallback',async()=>{const h=setup({restricted:true});h.setHandler(async q=>scoped(q));await h.api.load();h.setHandler(async()=>{throw Error('当前角色没有此页面或操作权限，请联系管理员')});await h.api.load();assert.equal(h.api.snapshot().hasGrid,false);assert.doesNotMatch(h.api.render(),/ScopedPay-/);assert(h.calls.every(q=>q.action==='rates'));const malformed=setup({restricted:true});malformed.setHandler(async q=>scoped(q,{total:1}));await malformed.api.load();assert.match(malformed.api.render(),/分页待核对/);assert.equal(malformed.api.snapshot().hasGrid,false);const wrong=setup({restricted:true});wrong.setHandler(async q=>scoped(q,{rows:[{...scopedRow(0),provider:'<img src=x onerror=alert(1)>',sourceType:'WRONG_PROVIDER_TYPE',sourceTypeProvider:'DifferentPay'}],total:1,hasMore:false}));await wrong.api.load();assert.match(wrong.api.render(),/&lt;img/);assert.doesNotMatch(wrong.api.render(),/<img|WRONG_PROVIDER_TYPE/);assert.doesNotMatch(wrong.api.render(),/历史生效版本.*已|估算/);});


test('production host selects restricted rates before query and tracks scope changes',()=>{
 const host=fs.readFileSync(path.join(__dirname,'../src/components/OwnerAdminPreview.tsx'),'utf8'),glue=fs.readFileSync(path.join(__dirname,'../admin-preview/live-data.js'),'utf8');
 assert.match(host,/scopeIdentity=dashboardScopeIdentity\(profile\),dataScope=effectiveDashboardDataScope\(profile\)/);
 assert.match(host,/policy,\{mode:dataScope\.mode,identity:scopeIdentity\}/);assert.match(host,/readDrafts,owner,scopeIdentity\]/);
 assert.match(glue,/isActive:\(\)=>state\.page==='rates'/);assert.match(glue,/isRestrictedScope:\(\)=>window\.hensemDataScope\?\.mode!=='all'/);assert.match(glue,/scopeKey:\(\)=>window\.hensemDataScope\?\.identity/);
 assert.doesNotMatch(glue,/onUnavailable:\(\)=>\{L\.feeView='normalized'/);
});
