const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');let db;
const read=n=>fs.readFileSync(path.join(__dirname,'../supabase',n),'utf8');
const call=async q=>(await db.query('select public.dashboard_admin_deposit_statistics($1) value',[JSON.stringify(q||{})])).rows[0].value;
before(async()=>{db=new PGlite();await db.exec(`create schema private;create role anon;create role authenticated;create role service_role;
 create function private.dashboard_admin_live_scope() returns jsonb language sql as $$select '{"mode":"fixture"}'::jsonb$$;
 create function private.dashboard_scope_allows(jsonb,text,text) returns boolean language sql as $$select $2='IN' and $3<>'HIDDEN'$$;`);
 await db.exec(read('admin-live-deposit-issues.sql').split('create or replace function private.dashboard_admin_live_deposit_platform_key')[0]+'commit;');await db.exec(read('admin-deposit-statistics.sql'));
 const rows=[['a','RAJA','RC20260925SYNTHETIC','对得上','未入款','已确认',100],['b','RAJA','RC20260925SYNTHETIC2','对得上','未入款','待核实',200],['c','RAJA','RC20260926SYNTHETIC','对得上','已入款','已入款',300],['d','RAJA','RC26110308INVALID','对不上','未入款','待核实',400],['hidden','HIDDEN','RC20260925PRIVATE','对得上','未入款','已确认',999]];
 for(let i=0;i<rows.length;i++){const [id,platform,order,match,status,confirmation,amount]=rows[i];await db.query(`insert into admin_deposit_issue_rows(id,source_sheet,source_tab,source_row,country,platform,order_number,utr,amount,provider,canonical_provider,match_status,status,confirmation_status,record_date) values($1,'fixture','UPI核对',$2,'印度',$3,$4,'UTR-SYNTHETIC',$5,'Pay-QR','Pay',$6,$7,$8,'2611-03-08')`,[id,i+2,platform,order,amount,match,status,confirmation]);}
});after(async()=>db?.close());
test('four views share one scoped row base and never count sheet summaries as orders',async()=>{const r=await call();assert.equal(r.summary.count,4);assert.equal(r.summary.amount,1000);assert.equal(r.summary.confirmedCount,1);assert.equal(r.summary.confirmedAmount,100);assert.equal(r.summary.pendingVerificationAmount,200);assert.equal(r.summary.unmatchedCount,1);assert.equal(r.summary.undatedCount,1);assert.deepEqual(r.facets.platforms,['RAJALOTTERY']);assert(!JSON.stringify(r).includes('HIDDEN'));});
test('dates derive from valid RC dates and future formula dates do not leak into daily groups',async()=>{const r=await call({section:'daily'});assert.equal(r.total,3);assert(!JSON.stringify(r.rows).includes('2611'));assert(r.rows.some(r=>r.date==='2026-09-25'&&r.count===2));const range=await call({dateMode:'range',startAt:'2026-09-25T00:00:00Z',endAt:'2026-09-25T23:59:59Z'});assert.equal(range.summary.count,2);});
test('column filters AND together, details preserve source labels and pagination',async()=>{const r=await call({section:'details',platform:'RAJALOTTERY',provider:'Pay',confirmation:'已确认',orderNumber:'SYNTHETIC',limit:20});assert.equal(r.total,1);assert.equal(r.rows[0].rawProvider,'Pay-QR');assert.equal(r.rows[0].provider,'Pay');assert.equal((await call({section:'details',confirmation:'已确认',status:'已入款'})).total,0);assert.equal((await call({section:'details',offset:3,limit:20})).rows.length,1);});
test('archived rows excluded, public denied, invalid requests rejected',async()=>{await db.exec("update admin_deposit_issue_rows set stale_at=now() where id='d'");assert.equal((await call()).summary.count,3);await db.exec('set role anon');await assert.rejects(()=>call(),/permission denied/);await db.exec('reset role');for(const q of [{section:'raw'},{bank:'x'},{limit:500},{offset:-1},{dateMode:'range',startAt:'2026-02-30T00:00Z',endAt:'2026-03-01T00:00Z'}])await assert.rejects(()=>call(q));});

test('AS takes priority: 91 old paid labels for another order cannot inflate this-order received totals',async()=>{
 await db.exec(`insert into admin_deposit_issue_rows(id,source_sheet,source_tab,source_row,country,platform,order_number,amount,provider,canonical_provider,match_status,status,confirmation_status)
 select 'other-'||i,'fixture','UPI核对',100+i,'印度','RAJA','RC20260925OTHER'||i,1,'Pay-QR','Pay','对得上','已入款','入其他订单' from generate_series(1,91) i;
 insert into admin_deposit_issue_rows(id,source_sheet,source_tab,source_row,country,platform,order_number,amount,provider,canonical_provider,match_status,status,confirmation_status) values
 ('other-unpaid','fixture','UPI核对',300,'印度','RAJA','RC20260925OTHERUNPAID',9,'Pay-QR','Pay','对得上','未入款','入其他订单'),
 ('provider-transfer','fixture','UPI核对',301,'印度','RAJA','RC20260925TRANSFER',12,'Pay-QR','Pay','对得上','未入款','转其他三方'),
 ('missing-as','fixture','UPI核对',302,'印度','RAJA','RC20260925NOAS',7,'Pay-QR','Pay','对得上','已入款',null);`);
 const r=await call(),s=r.summary;assert.equal(s.receivedCount,1);assert.equal(s.receivedAmount,300);assert.equal(s.otherOrderCount,92);assert.equal(s.otherOrderAmount,100);assert.equal(s.otherProviderCount,1);assert.equal(s.otherProviderAmount,12);assert.equal(s.unreceivedCount,2);assert.equal(s.unreceivedAmount,300);assert.equal(s.unclassifiedCount,1);assert.equal(s.unclassifiedAmount,7);assert.equal(s.count,s.receivedCount+s.unreceivedCount+s.otherOrderCount+s.otherProviderCount+s.unclassifiedCount);assert.equal(s.amount,s.receivedAmount+s.unreceivedAmount+s.otherOrderAmount+s.otherProviderAmount+s.unclassifiedAmount);assert.equal(s.confirmedAmount,100);assert.equal(s.pendingVerificationAmount,200);
 const detail=await call({section:'details',orderNumber:'NOAS'});assert.equal(detail.rows[0].confirmation,'未分类');assert.equal(detail.rows[0].statisticsStatus,'unclassified');
 for(const section of ['providers','daily']){const data=await call({section,limit:100});for(const key of ['receivedCount','receivedAmount','otherOrderCount','otherOrderAmount','otherProviderCount','otherProviderAmount','unreceivedCount','unreceivedAmount','unclassifiedCount','unclassifiedAmount'])assert.equal(data.rows.reduce((sum,r)=>sum+r[key],0),s[key],section+' '+key);}
});
