/* Behavioral UI regressions using only synthetic observations. */
const test=require('node:test'),assert=require('node:assert/strict');
const {create}=require('../admin-preview/live-pending-analysis.js');
const {date,previous,id,platform,group,row,day,sample}=require('./fixtures/pending-compact-data.cjs');
const table=(html,label)=>html.split('aria-label="'+label+'"')[1]?.split('</table>')[0]||'';
async function setup(fixture=sample()) {const calls=[],opened=[],L={from:fixture.data.startDate,to:date,country:'印度',dirty:false,withdrawCatalog:[]};let renders=0;const ui=create({L,selected:()=>fixture.platforms,providers:()=>[],request:async q=>{calls.push(q);return fixture.data;},render:()=>renders++,canDetail:()=>true,openDetail:q=>opened.push(q)});await ui.load();return {ui,L,calls,opened,fixture,get renders(){return renders;}};}
test('single business day starts at provider priorities, keeps the next-midnight target and omits repeated daily matrices',async()=>{const h=await setup(),html=h.ui.page();assert.match(html,/2026-10-02 00:00（2026-10-01日结束）/);assert.match(html,/平台展开/);assert.match(html,/三方展开/);assert.match(html,/aria-label="当日三方平台分布"/);assert.doesNotMatch(html,/aria-label="每日三方平台占比"|aria-label="每日平台三方占比"|逐日对比|每日代付中趋势/);assert.equal(h.calls.length,1);});
test('13 of 16 observed platforms keep honest numeric shares and a named 3-platform gap, never a zero substitute',async()=>{const h=await setup(),html=h.ui.page(),body=table(html,'当日三方平台分布');assert.match(html,/已核实 13 \/ 16 平台/);assert.match(html,/分母：13 个已核实平台 · 其余不计入/);assert.match(body,/35,000.00/);assert.match(body,/38.46%/);assert.match(body,/30,000.00/);assert.match(body,/32.97%/);assert.match(html,/3 个平台未计入/);assert.doesNotMatch(body,/示例平台 14|范围未核实完整/);const coverage=table(html,'全部平台采集情况');assert.match(coverage,/示例平台 14/);const missingRow=coverage.split('示例平台 14')[1].split('</tr>')[0];assert.doesNotMatch(missingRow,/0\.00|0 笔/);});
test('an eight-platform gap stays independently inspectable while both entry dimensions preserve exact order scope',async()=>{const h=await setup(sample({total:21}));assert.match(h.ui.page(),/8 个平台未计入/);global.livePendingAnalysisExpandProvider('示例三方 2');assert.match(table(h.ui.page(),'当日三方平台分布'),/示例平台 01/);global.livePendingAnalysisDetail(date,id(1),'示例三方 2');assert.deepEqual(h.opened[0].platformIds,[id(1)]);assert.equal(h.opened[0].observedAt,date+'T18:32:00Z');global.livePendingAnalysisDimension('platform');global.livePendingAnalysisExpand(id(1));assert.match(table(h.ui.page(),'代付中平台与三方分布'),/示例三方 2/);global.livePendingAnalysisDetail(date,id(1),'');assert.equal(h.opened[1].provider,null);assert.equal(h.opened[1].mode,'midnight');assert.equal(h.calls.length,1);});
test('day deltas compare only the shared verified platform cohort, excluding coverage changes and source changes',async()=>{const f=sample({total:3,known:3});f.data.daily=[day(date,[row(1,date,150,3),row(2,date,9000,90),row(3,date,8000,80,{source:'newar'})])];f.data.baseline=day(previous,[row(1,previous,100,2),{...platform(2),state:'missing',groups:[]},row(3,previous,100,2)]);const h=await setup(f),body=table(h.ui.page(),'当日三方平台分布');assert.match(body,/\+50\.00（\+50\.00%）/);assert.match(body,/可比 1 平台/);assert.doesNotMatch(body,/\+9,000|\+7,900|可比 3 平台/);});
test('age columns include one, two and three days; absent thresholds and mismatched capture never become zero',async()=>{const f=sample({total:1,known:1}),age=f.data.aging.platforms[0];age.thresholds=age.thresholds.filter(t=>t.minHours!==48);age.groups[0].thresholds=age.groups[0].thresholds.filter(t=>t.minHours!==48);f.data.aging.thresholds=f.data.aging.thresholds.filter(t=>t.minHours!==48);const h=await setup(f);let body=table(h.ui.page(),'当日三方平台分布');assert.match(body,/≥1天笔数/);assert.match(body,/≥2天笔数/);assert.match(body,/≥3天笔数/);assert.match(body,/<td>1<\/td><td>—<\/td><td>0<\/td>/);age.snapshotAt=previous+'T18:32:00Z';age.observedAt=age.snapshotAt;body=table(h.ui.page(),'当日三方平台分布');assert.match(body,/<td>—<\/td><td>—<\/td><td>—<\/td><td>—<\/td>/);});
test('period frequency compares a fixed known cohort and remains hidden until requested',async()=>{const f=sample({total:3,known:2,multi:true});f.data.daily[0]=day(previous,[row(1,previous),{...platform(2),state:'missing',groups:[]},row(3,previous)]);const h=await setup(f),html=h.ui.page();assert.match(html,/<details class="pa-history"><summary>逐日对比 · 2 天/);assert.match(html,/共同已核实 1 平台/);assert.match(table(html,'三方高存量频次'),/2 \/ 2 天/);assert.doesNotMatch(table(html,'三方高存量频次'),/示例三方 3/);});
test('snapshot restoration retains date, independent dimension, expansion and denominator without re-reading',async()=>{const h=await setup(sample({multi:true}));global.livePendingAnalysisDate(previous);global.livePendingAnalysisDimension('platform');global.livePendingAnalysisExpand(id(1));global.livePendingAnalysisShare('scope');const saved=h.ui.capture();global.livePendingAnalysisDate(date);global.livePendingAnalysisDimension('provider');h.ui.restore(saved);const html=h.ui.page();assert.match(html,/2026-10-01 00:00（2026-09-30日结束）/);assert.match(table(html,'代付中平台与三方分布'),/class="pa-provider"/);assert.equal(h.ui.capture().share,'scope');assert.match(html,/该日等待明细未加载/);assert.equal(h.calls.length,1);h.L.dirty=true;const count=h.renders;global.livePendingAnalysisDimension('provider');assert.equal(h.renders,count);});
test('readable conclusions and age sorting use verified exact captures without triggering requests',async()=>{const f=sample({total:3,known:3});f.data.aging.platforms[0].groups[0].over24Count=1;f.data.aging.platforms[1].groups[0].over24Count=2;f.data.aging.platforms[2].groups[0].over24Count=3;f.data.aging.platforms[0].groups[0].thresholds[0].count=1;f.data.aging.platforms[1].groups[0].thresholds[0].count=2;f.data.aging.platforms[2].groups[0].thresholds[0].count=3;f.data.daily[0].rows[0].amount='9000';f.data.daily[0].rows[0].groups[0].amount='9000';f.data.daily[0].amount='14000';const h=await setup(f);let html=h.ui.page();assert.match(html,/待付集中<\/strong> 示例三方 2 64\.29%/);assert.match(html,/最长等待<\/strong> 示例三方 1 2天/);assert.match(table(html,'当日三方平台分布'),/class="pa-share-bar" aria-hidden="true"/);global.livePendingAnalysisAgeSort();html=table(h.ui.page(),'当日三方平台分布');assert(html.indexOf('示例三方 1')<html.indexOf('示例三方 2'));assert.equal(h.calls.length,1);const saved=h.ui.capture();h.ui.restore(saved);assert.equal(h.ui.capture().sort,'age');});
test('legacy tab snapshots retain their count sort and actual per-platform capture metadata stays accessible',async()=>{const h=await setup();global.livePendingAnalysisMetric('count');const old=h.ui.capture();delete old.sort;h.ui.restore(old);assert.equal(h.ui.capture().sort,'count');global.livePendingAnalysisDimension('platform');assert.match(table(h.ui.page(),'代付中平台与三方分布'),/title="零点窗内 · 实际采集 2026\/10\/2 00:02:00"/);});
test('all-platform collection diagnostics expose unknown-currency stock separately from verified totals, with no detail bypass',async()=>{
 const f=sample({total:4,known:1}),rows=f.data.daily[0].rows;
 for(let i=1;i<4;i++)Object.assign(rows[i],{diagnosticArchiveVerified:true,diagnosticObservedAmount:String(4000000+i),diagnosticObservedCount:900+i,diagnosticObservedAt:date+'T18:33:00Z',diagnosticCurrency:null,diagnosticTimingState:'on_time',diagnosticReasons:['currency_unverified']});
 const h=await setup(f),html=h.ui.page(),coverage=table(html,'全部平台采集情况'),main=table(html,'当日三方平台分布');
 assert.match(html,/<details class="pa-coverage pa-panel" open>/);assert.match(html,/当日应采 4 · 零点已核实 1/);
 assert.match(coverage,/4,000,001\.00<small>原值 · 币种待核实<\/small><\/td><td>901<\/td>/);assert.match(coverage,/已匹配采集归档/);assert.doesNotMatch(coverage,/逐笔收据已核实/);
 assert.match(html,/代付中金额<\/span><strong>1,000\.00/);assert.match(html,/代付中笔数<\/span><strong>1/);assert.doesNotMatch(main,/4,000,001|901/);
 const missingRow=coverage.split('示例平台 02')[1].split('</tr>')[0];assert.doesNotMatch(missingRow,/livePendingAnalysisDetail/);global.livePendingAnalysisDetail(date,id(2),'');assert.equal(h.opened.length,0);assert.equal(h.calls.length,1);
});
test('future launch is visible but excluded from expected coverage, groups and primary shares',async()=>{
 const f=sample({total:2,known:1}),d=f.data.daily[0];Object.assign(d.rows[1],{state:'not_launched',expectedForDate:false,launchDate:'2026-10-06'});d.expectedPlatformCount=1;d.complete=true;
 const h=await setup(f),html=h.ui.page(),coverage=table(html,'全部平台采集情况');assert.match(html,/当日应采 1 · 零点已核实 1 · 尚未上线 1/);assert.match(coverage,/尚未上线 · 2026-10-06/);assert.doesNotMatch(table(html,'当日三方平台分布'),/示例平台 02/);assert.match(html,/已核实完整/);
 const allFuture=sample({total:1,known:0}),future=allFuture.data.daily[0];Object.assign(future.rows[0],{state:'not_launched',expectedForDate:false,launchDate:'2026-10-06'});future.expectedPlatformCount=0;future.amount=null;future.count=null;
 const empty=await setup(allFuture);assert.match(empty.ui.page(),/当日应采 0 · 零点已核实 0 · 尚未上线 1/);assert.doesNotMatch(empty.ui.page(),/已核实完整|代付中金额<\/span><strong>0\.00/);
});
test('amount and count occupy independent columns and use distinct verified and platform denominators',async()=>{
 const f=sample({total:2,known:2}),rows=f.data.daily[0].rows;rows[0]=row(1,date,80,2,{groups:[group('Small',20,1),group('Other',60,1)]});rows[1]=row(2,date,20,8,{groups:[group('Third',20,8)]});f.data.daily[0].amount='100';f.data.daily[0].count=10;
 const h=await setup(f);global.livePendingAnalysisDimension('platform');global.livePendingAnalysisExpand(id(1));let body=table(h.ui.page(),'代付中平台与三方分布');
 assert.match(body,/<th>待付金额<\/th><th>待付笔数<\/th><th>金额占比<\/th><th>笔数占比<\/th>/);assert.match(body,/aria-label="金额 80\.00%"/);assert.match(body,/aria-label="笔数 20\.00%"/);assert.match(body,/aria-label="金额 25\.00%"/);assert.match(body,/aria-label="笔数 50\.00%"/);
 global.livePendingAnalysisShare('scope');body=table(h.ui.page(),'代付中平台与三方分布');const small=body.split('<td>Small</td>')[1].split('</tr>')[0];assert.match(small,/aria-label="金额 20\.00%"/);assert.match(small,/aria-label="笔数 10\.00%"/);assert.equal(h.calls.length,1);
});
