const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../admin-preview/live-collected-data.js'),'utf8');
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const plain=x=>JSON.parse(JSON.stringify(x));
const feed=(i=0,extra={})=>({id:'f'+i,dataset:'volume',system:'REPORT',sourceKind:'direct',rawCountry:'IN',rawPlatform:'RAW-'+i,country:'印度',name:'PLATFORM-'+i,team:'M8',direction:'charge',timezone:'Asia/Kolkata',defaultEnd:'2026-09-25',lastDate:'2026-09-24',...extra});
function day(feedId,date,status='received',extra={}){return {feedId,date,status,received:['received','partial','complete'].includes(status),complete:['complete','zero_complete'].includes(status),zeroConfirmed:status==='zero_complete',expected:status!=='not_expected',evidence:'source_full_day_not_published',recordReceivedAt:status==='not_received'?null:'2026-09-26T01:00:00Z',...extra}}
function response(q,feeds,custom,checkedAt='2026-09-26T01:00:00Z'){return {version:1,complete:true,checkedAt,feedIds:q.feedIds,startAt:q.startAt,endAt:q.endAt,rows:q.feedIds.flatMap(id=>{const f=feeds.find(x=>x.id===id);if(!f.defaultEnd)return [day(id,null,'unverified',{expected:false,received:false})];const rows=[];for(let t=Date.parse(q.startAt),end=Date.parse(q.endAt<f.defaultEnd?q.endAt:f.defaultEnd);t<=end;t+=86400000){const date=new Date(t).toISOString().slice(0,10);rows.push(custom?custom(id,date):day(id,date))}return rows})}}
function fixture(feeds=[feed()],handler,options={}){class Clock extends Date{constructor(...args){super(...(args.length?args:[options.now||Date.now()]))}static now(){return Date.parse(options.now)||Date.now()}}const calls=[],navigation=[],c={Date:Clock,document:{activeElement:null,querySelector:()=>null},liveSet:(...x)=>navigation.push(['set',...x]),liveChoosePlatform:x=>navigation.push(['orders',x]),setPage:x=>navigation.push(['page',x])};vm.createContext(c);vm.runInContext(source,c);const page=c.HensemLiveCollectedData.create({L:{catalog:[],to:'2026-09-25T23:59:59'},E,C:String,N:String,table:()=>'',box:(t,b,n)=>'<h2>'+t+'</h2>'+b+'<p>'+n+'</p>',render:()=>{},request:async q=>{calls.push(plain(q));if(q.operation==='catalog')return {version:1,complete:true,feeds};if(q.action==='collectedData')return options.detailHandler?options.detailHandler(q):{total:0,rows:[]};return handler?handler(q):response(q,feeds)}});return {page,c,calls,navigation}}
const tick=()=>new Promise(setImmediate);
test('source-record Today stages the source local day without changing complete-day coverage',async()=>{
 for(const [timezone,date]of [['Asia/Kolkata','2026-10-01'],['America/Sao_Paulo','2026-09-30'],['Pacific/Auckland','2026-10-01']]){
  const f=feed(0,{timezone}),h=fixture([f],q=>response(q,[f],undefined,'2026-09-26T05:00:00Z'),{now:'2026-09-30T18:30:00Z'});await h.page.load();await h.c.collectedCoverageQuery();h.c.collectedOpenDay('f0','2026-09-24');await tick();
  const prior=plain(h.page.state.coverage),from=h.page.state.rangeFrom,to=h.page.state.rangeTo,reads=h.calls.length;
  assert.match(h.page.render(),/onclick="collectedToday\(\)">今天/);h.c.collectedToday();assert.equal(h.calls.length,reads);assert.equal(h.page.state.from,date);assert.equal(h.page.state.to,date);assert.equal(h.page.state.detailRows,null);
  assert.deepEqual(plain(h.page.state.coverage),prior);assert.equal(h.page.state.rangeFrom,from);assert.equal(h.page.state.rangeTo,to);assert.match(h.page.render(),/各来源当地昨日截止/);
  await h.c.collectedQuery();const q=h.calls.at(-1);assert.equal(q.action,'collectedData');assert.equal(q.startAt,date);assert.equal(q.endAt,date);assert.equal(q.country,'IN');assert.equal(q.platform,'RAW-0');assert.equal(q.sourceKind,'direct');
 }
});
test('source-record Today refuses unverified timezones and ignores late old-date detail',async()=>{
 let resolve;const h=fixture([feed()],undefined,{now:'2026-09-30T18:30:00Z',detailHandler:()=>new Promise(r=>{resolve=r})});await h.page.load();h.page.state.detail={...feed(),timezone:null};h.page.state.from=h.page.state.to='2026-09-24';
 assert.match(h.page.render(),/disabled title="来源时区未确认" onclick="collectedToday/);h.c.collectedToday();assert.equal(h.page.state.from,'2026-09-24');
 h.page.state.detail={...feed(),timezone:'Invalid/Zone'};h.c.collectedToday();assert.equal(h.page.state.from,'2026-09-24');
 h.page.state.detail=feed();const loading=h.c.collectedQuery();assert.equal(h.page.state.detailBusy,true);h.c.collectedToday();assert.equal(h.page.state.detailRows,null);assert.equal(h.page.state.detailBusy,false);assert.equal(h.page.state.from,'2026-10-01');resolve({total:5,rows:[{date:'2026-09-24'}]});await loading;assert.equal(h.page.state.detailRows,null,'the old detail cannot become Today records');
});
test('default coverage starts September 1, uses source local yesterday, and clips every source independently',async()=>{const feeds=[feed(1),feed(2,{defaultEnd:'2026-09-24',timezone:'America/Sao_Paulo'})],h=fixture(feeds);await h.page.load();await h.c.collectedCoverageQuery();assert.equal(h.page.state.rangeFrom,'2026-09-01');assert.equal(h.page.state.rangeTo,'2026-09-25');assert.equal(h.page.state.coverage.f1.length,25);assert.equal(h.page.state.coverage.f2.length,24);assert.equal(h.calls[1].action,'intakeCoverage');assert.equal(h.calls[1].startAt,'2026-09-01');assert.match(h.page.render(),/各来源当地昨日截止/)});
test('bounded batches have at most eight feeds and two in flight, with completed-source progress',async()=>{const feeds=Array.from({length:25},(_,i)=>feed(i)),pending=[];let active=0,max=0;const h=fixture(feeds,q=>new Promise(resolve=>{active++;max=Math.max(max,active);pending.push(()=>{active--;resolve(response(q,feeds))})}));const done=(async()=>{await h.page.load();await h.c.collectedCoverageQuery()})();await tick();assert.equal(pending.length,2);assert.equal(active,2);assert(h.calls.filter(q=>q.operation==='rows').every(q=>q.feedIds.length<=8));pending.shift()();await tick();assert.equal(h.page.state.coverageDone,8);assert.equal(active,2);while(pending.length){pending.shift()();await tick()}await done;assert.equal(max,2);assert.equal(h.page.state.coverageDone,25);assert.equal(h.page.state.coverageBusy,false);assert.equal(h.calls.filter(q=>q.operation==='rows').length,4)});
test('a failed batch is unknown, not missing, and retry requests only its failed feeds',async()=>{const feeds=Array.from({length:17},(_,i)=>feed(i));let fail=true;const h=fixture(feeds,q=>{if(fail&&q.feedIds.includes('f8'))throw Error('synthetic timeout');return response(q,feeds)});await h.page.load();await h.c.collectedCoverageQuery();assert.equal(h.page.state.coverageFailed.length,8);assert.match(h.page.render(),/读取失败 · 未判缺失/);assert.equal(h.page.state.coverage.f8,undefined);const before=h.calls.length,failed=plain(h.page.state.coverageFailed);fail=false;await h.c.collectedCoverageRetry();assert.equal(h.calls.length,before+1);assert.deepEqual(h.calls.at(-1).feedIds,failed);assert.equal(h.page.state.coverageFailed.length,0);assert.equal(h.page.state.coverageDone,17)});
test('received, complete zero, before-onboarding, missing, partial and failed remain distinct',async()=>{const feeds=[feed()],states=['not_expected','zero_complete','complete','received','not_received','partial','failed','not_started'];const h=fixture(feeds,q=>response(q,feeds,(id,date)=>day(id,date,states[Number(date.slice(-2))-1]||'complete')));await h.page.load();await h.c.collectedCoverageQuery();const html=h.page.render();assert.match(html,/<td>24<\/td><td>21<\/td><td>19<\/td>/);assert.match(html,/09-05、09-08/);assert.doesNotMatch(html,/09-01、/);for(const text of ['部分收到','采集失败','未见采集任务','零笔已确认','接入前 · 不计缺失'])assert.match(html,new RegExp(text));h.c.collectedExpand('f0');assert.match(h.page.render(),/2026-09-08/);assert.doesNotMatch(h.page.render(),/collectedOpenDay\(&quot;f0&quot;,&quot;2026-09-01/)});
test('unverified current-only data does not invent expected days or claim one unknown day',async()=>{const feeds=[feed(0,{defaultEnd:null,timezone:null})],h=fixture(feeds);await h.page.load();await h.c.collectedCoverageQuery();assert.equal(h.page.state.coverage.f0[0].date,null);assert.match(h.page.render(),/<td>0<\/td><td>0<\/td><td>0<\/td>/);assert.doesNotMatch(h.page.render(),/待核对 1天/);h.c.collectedExpand('f0');assert.match(h.page.render(),/日期待核对/);assert.doesNotMatch(h.page.render(),/collectedOpenDay\(/)});
test('missing or contradictory result rows reject the batch instead of silently undercounting',async()=>{for(const mutate of [r=>r.rows.pop(),r=>r.rows.push({...r.rows[0]}),r=>r.feedIds.push('forbidden'),r=>r.rows[0].status='invented',r=>Object.assign(r.rows[0],{status:'zero_complete',zeroConfirmed:false,complete:true}),r=>r.rows[0].date='2026-08-31']){const feeds=[feed()],h=fixture(feeds,q=>{const r=response(q,feeds);mutate(r);return r});await h.page.load();await h.c.collectedCoverageQuery();assert.deepEqual(plain(h.page.state.coverageFailed),['f0']);assert.equal(h.page.state.coverage.f0,undefined);assert.match(h.page.render(),/读取失败/)} });
test('changed dates and platform scope invalidate old results and discard in-flight work',async()=>{const feeds=Array.from({length:18},(_,i)=>feed(i));let hold=false,pending=[];const h=fixture(feeds,q=>hold?new Promise(resolve=>pending.push(()=>resolve(response(q,feeds)))):response(q,feeds));await h.page.load();await h.c.collectedCoverageQuery();hold=true;const active=h.c.collectedCoverageQuery();await tick();h.c.collectedRange('from','2026-09-20');h.c.collectedSearch('PLATFORM-1');const count=h.calls.length;pending.forEach(resolve=>resolve());await active;assert.equal(h.calls.length,count,'no queued batches continue after scope invalidation');assert.equal(h.page.state.coverageDirty,true);assert.match(h.page.render(),/待重新查询/);const old=h.calls.length;h.c.collectedOpenDay('f0','2026-09-24');assert.equal(h.calls.length,old);await h.c.collectedCoverageRetry();assert.equal(h.calls.length,old);assert.match(h.page.render(),/筛选已修改/)});
test('queries use filtered feeds only while status filters reuse the verified range',async()=>{const feeds=[feed(0),feed(1,{team:'香港'}),feed(2,{country:'巴西',team:'胖虎'}),feed(3,{dataset:'panda_success'})],h=fixture(feeds);await h.page.load();await h.c.collectedCoverageQuery();h.c.collectedSet('team','M8');h.c.collectedSet('country','印度');h.c.collectedSet('dataset','volume');h.c.collectedSearch('PLATFORM-0');h.c.collectedRange('from','2026-09-20');await h.c.collectedCoverageQuery();assert.deepEqual(h.calls.at(-1).feedIds,['f0']);assert.equal(h.calls.at(-1).startAt,'2026-09-20');assert.equal(h.page.state.coverage.f0.length,6);const reads=h.calls.length;h.c.collectedSet('status','needs');assert.equal(h.calls.length,reads);assert.match(h.page.render(),/<td>PLATFORM-0<\/td>/);h.c.collectedSet('status','not_received');assert.match(h.page.render(),/没有匹配来源/)});
test('invalid dates and ranges above 93 days never send a query',async()=>{const h=fixture();await h.page.load();await h.c.collectedCoverageQuery();for(const [from,to] of [['2026-02-30','2026-09-25'],['2026-09-25','2026-09-20'],['2026-01-01','2026-09-25']]){h.c.collectedRange('from',from);h.c.collectedRange('to',to);const n=h.calls.length;await h.c.collectedCoverageQuery();assert.equal(h.calls.length,n);assert.match(h.page.render(),/单次最多核对 93 天/)}});
test('reset restores source-aware defaults without silently submitting or preserving stale statistics',async()=>{const h=fixture();await h.page.load();await h.c.collectedCoverageQuery();h.c.collectedRange('from','2026-09-10');h.c.collectedSet('team','M8');h.c.collectedSet('status','needs');const n=h.calls.length;h.c.collectedReset();assert.equal(h.calls.length,n);assert.equal(h.page.state.rangeFrom,'2026-09-01');assert.equal(h.page.state.rangeTo,'2026-09-25');assert.equal(h.page.state.team,'all');assert.equal(h.page.state.status,'all');assert.equal(h.page.state.coverageDirty,true);assert.match(h.page.render(),/待查询/)});
test('LG automatic report receipt cannot hide missing order and third-party amount sources for the same day',async()=>{const feeds=[feed(0,{name:'SYNTHETIC-LG',system:'LG',rawPlatform:'LG-RAW',country:'菲律宾',rawCountry:'PH',dataset:'auto',direction:'withdraw',defaultEnd:'2026-09-26'}),feed(1,{name:'SYNTHETIC-LG',system:'LG',rawPlatform:'LG-RAW',country:'菲律宾',rawCountry:'PH',dataset:'orders',direction:'withdraw',defaultEnd:'2026-09-26'}),feed(2,{name:'SYNTHETIC-LG',system:'LG',rawPlatform:'LG-RAW',country:'菲律宾',rawCountry:'PH',dataset:'volume',direction:'withdraw',defaultEnd:'2026-09-26'})];const h=fixture(feeds,q=>response(q,feeds,(id,date)=>day(id,date,id==='f0'?'received':id==='f1'?'not_started':'not_received'),'2026-09-27T01:00:00Z'));await h.page.load();await h.c.collectedCoverageQuery();h.c.collectedRange('from','2026-09-26');await h.c.collectedCoverageQuery();const html=h.page.render();assert.equal((html.match(/<td>SYNTHETIC-LG<\/td>/g)||[]).length,3);assert.match(html,/自动出款日报/);assert.match(html,/未见采集任务/);assert.match(html,/未收到/);assert.equal(h.page.state.coverage.f0[0].status,'received');assert.equal(h.page.state.coverage.f1[0].status,'not_started');assert.equal(h.page.state.coverage.f2[0].status,'not_received')});
test('initial intake opens the authorized directory without scanning every date or source until Query',async()=>{const h=fixture(Array.from({length:120},(_,i)=>feed(i)));await h.page.load();assert.equal(h.calls.length,1);assert.equal(h.calls[0].operation,'catalog');assert.equal(h.page.state.coverageApplied,null);assert.match(h.page.render(),/点击查询核对缺失日期/);h.c.collectedSearch('PLATFORM-119');assert.equal(h.calls.length,1);await h.c.collectedCoverageQuery();assert.deepEqual(h.calls[1].feedIds,['f119'])});
test('timestamps use the source timezone with exact raw evidence in a tooltip',async()=>{const h=fixture([feed()]);await h.page.load();await h.c.collectedCoverageQuery();const html=h.page.render();assert.match(html,/2026-09-26 06:30/);assert.match(html,/title="2026-09-26T01:00:00Z · Asia\/Kolkata/);assert.doesNotMatch(html,/>2026-09-26T01:00:00Z</);assert.match(html,/已收到 ≠ 已完整/)});
test('an overnight tab validates newly available dates against response time, not cached catalog yesterday',async()=>{
 const feeds=[feed(0,{defaultEnd:'2026-09-24'}),feed(1,{timezone:'America/Sao_Paulo',defaultEnd:'2026-09-24'})];
 const h=fixture(feeds,q=>({version:1,complete:true,checkedAt:'2026-09-27T00:05:00Z',feedIds:q.feedIds,startAt:q.startAt,endAt:q.endAt,rows:q.feedIds.flatMap(id=>id==='f0'?[day(id,'2026-09-25'),day(id,'2026-09-26')]:[day(id,'2026-09-25')])}));
 await h.page.load();assert.equal(h.page.state.rangeTo,'2026-09-24','catalog remains only an initial date default');h.c.collectedRange('from','2026-09-25');h.c.collectedRange('to','2026-09-26');await h.c.collectedCoverageQuery();assert.deepEqual(plain(h.page.state.coverageFailed),[]);assert.deepEqual(plain(h.page.state.coverage.f0.map(r=>r.date)),['2026-09-25','2026-09-26']);assert.deepEqual(plain(h.page.state.coverage.f1.map(r=>r.date)),['2026-09-25']);
});
test('crossing the source midnight admits the completed day while missing that new day still fails closed',async()=>{
 const feeds=[feed(0,{defaultEnd:'2026-09-24'})];let checkedAt='2026-09-25T18:29:59Z',includeNew=false;
 const h=fixture(feeds,q=>({version:1,complete:true,checkedAt,feedIds:q.feedIds,startAt:q.startAt,endAt:q.endAt,rows:[day('f0','2026-09-24'),...(includeNew?[day('f0','2026-09-25')]:[])]}));await h.page.load();h.c.collectedRange('from','2026-09-24');h.c.collectedRange('to','2026-09-25');await h.c.collectedCoverageQuery();assert.equal(h.page.state.coverage.f0.length,1);
 checkedAt='2026-09-25T18:30:00Z';await h.c.collectedCoverageQuery();assert.deepEqual(plain(h.page.state.coverageFailed),['f0'],'the new source-local day must be present after midnight');includeNew=true;await h.c.collectedCoverageRetry();assert.equal(h.page.state.coverage.f0.length,2);assert.deepEqual(plain(h.page.state.coverageFailed),[]);
});
test('a stale default date never permits dated coverage without a known source timezone',async()=>{const feeds=[feed(0,{timezone:null})],h=fixture(feeds);await h.page.load();await h.c.collectedCoverageQuery();assert.deepEqual(plain(h.page.state.coverageFailed),['f0']);assert.equal(h.page.state.coverage.f0,undefined)});
