const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../src/lib/adminWorkorderRecordsRequest.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:m,exports:m.exports});const validate=m.exports.validateWorkorderRecordsRequest;
const q={action:'workorderRecords',view:'missing',operation:'list',country:'IN',filters:{from:'2026-10-01',to:'2026-10-04',issueKind:'deposit',dateBasis:'submission'}};
test('India deposit reconciliation carries explicit reversible success basis and submission date',()=>{let r=validate(q);assert.equal(r.filters.successBasis,'receipt');assert.equal(r.filters.dateBasis,'submission');for(const successBasis of ['receipt','processed'])assert.equal(validate({...q,filters:{...q.filters,successBasis}}).filters.successBasis,successBasis);for(const statusCode of ['1','2','3','4','5'])assert.equal(validate({...q,filters:{...q.filters,statusCode}}).filters.statusCode,statusCode)});
test('reconciliation additions cannot broaden old country/business/records/workload contracts',()=>{for(const extra of [{country:'BR'},{view:'records'},{view:'workload'},{filters:{issueKind:'withdraw',successBasis:'receipt'}}])assert.throws(()=>validate({...q,filters:{...q.filters,successBasis:'receipt'},...extra}));assert.equal(validate({...q,country:'BR',filters:{dateBasis:'operation',statusCode:'3'}}).filters.dateBasis,'operation');for(const filters of [{successBasis:'paid'},{dateBasis:'operation',successBasis:'receipt'},{operator:'x'},{sourceOrderNo:'x'},{utrMatch:'yes'},{successBasis:null}])assert.throws(()=>validate({...q,filters:{...q.filters,...filters}}));});

test('old open pages retain operation-date missing contract without adopting the new defaults',()=>{
 const r=validate({...q,filters:{...q.filters,dateBasis:'operation',statusCode:'3',operator:'source-user'}});assert.equal(r.filters.dateBasis,'operation');assert.equal(r.filters.operator,'source-user');assert(!('successBasis' in r.filters));
 const omitted=validate({...q,filters:{issueKind:'deposit'}});assert(!('dateBasis' in omitted.filters));assert(!('successBasis' in omitted.filters));assert.throws(()=>validate({...q,filters:{...q.filters,dateBasis:'operation',statusCode:'1'}}));
});
