const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../admin-preview/live-payout-config.js'),'utf8');
const target=(platform='P1',country='IN')=>({platform,country_code:country,country_name:'印度',display_group:country,display_name:'印度',timezone:'Asia/Kolkata',members:[{site_code:'11',name:'品牌一'}]});
const index=(system,targets=[target()])=>({version:1,system,targets,summaries:targets.map(t=>({...t,observed_local_date:'2026-09-22'})),readOnly:true});
const snap=(system,t,configuration,dictionary=null)=>({version:1,system,target:t,snapshot:{country_code:t.country_code,platform:t.platform,timezone:t.timezone,observed_local_date:'2026-09-22',observed_at:'2026-09-22T06:00:00Z',configuration,dictionary},readOnly:true});
function harness(request){const context={window:{}};vm.runInNewContext(source,context);const api=context.window.HensemLivePayoutConfig;let changes=0;api.configure({request,onChange:()=>changes++});return {api,changes:()=>changes};}
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject}};
const normalize=x=>JSON.parse(JSON.stringify(x));
test('only host request API, no fetch/storage/auth/write controls or embedded source values',()=>{assert.doesNotMatch(source,/\bfetch\s*\(|localStorage|sessionStorage|access_token|supabaseUrl|\.rpc\(/);assert.doesNotMatch(source,/action:'(save|update|delete)'/);assert(source.includes("action:'payoutConfig'"));});
test('index + exact selected target only; default pagination 20 and readonly AR values preserve zero, false and unknown',async()=>{const calls=[];const targets=Array.from({length:25},(_,i)=>target('P'+i));const {api}=harness(async r=>{calls.push(normalize(r));return r.operation==='index'?index(r.system,targets):snap(r.system,targets.find(t=>t.platform===r.platform),{fields:[{key:'autoWithdraw',kind:'boolean',value:false,available:true},{key:'withdrawAmount',kind:'number',value:0,available:true},{key:'totalLoss',value:null,available:false}],groups:[]})});await api.ensureLoaded();assert.deepEqual(calls,[{action:'payoutConfig',operation:'index',system:'AR'},{action:'payoutConfig',operation:'snapshot',system:'AR',country:'IN',platform:'P0'}]);let html=api.render();assert(html.includes('观测日期 2026-09-22'));assert(html.includes('采集时配置快照'));assert(html.includes('1–20'));assert(!html.includes('<strong>P24</strong>'));assert(html.includes('>0</span>'));assert(html.includes('否（只读）'));assert(html.includes('页面未提供'));api.setPage(2);html=api.render();assert(html.includes('21–25'));assert(html.includes('<strong>P24</strong>'));assert.equal(calls.length,2);});
test('escaped platform/field strings cannot create elements or attribute callbacks',async()=>{const t=target('<img src=x onerror=alert(1)>');const {api}=harness(async r=>r.operation==='index'?index(r.system,[t]):snap(r.system,t,{fields:[{key:'autoWithdraw',kind:'boolean',available:true,value:true},{key:'withdrawAmount',available:true,value:'</script><svg onload=alert(1)>'}],groups:[]}));await api.loadIndex();const h=api.render();assert(h.includes('&lt;img'));assert(h.includes('&lt;/script&gt;'));assert(!h.includes('<svg'));assert(!h.includes('<img'));assert(!/onclick="[^"]*alert/.test(h));});
test('Panda amount unit conversion only verified fields; channel dictionary requires same target and withdrawal type',async()=>{const t=target();const c={values:{autoWithdrawalSwitch:false,autoWithdrawalAmountMix:12345,autoWithdrawDailyLimit:12345.9,autoWithdrawalLimitType:'validBet',autoWithdrawalLimitAmount:3,successRateType:'Number',autoWithdrawalChannel:[{withdrawalChannelId:1,tenantWithdrawTypeId:2,tenantWithdrawTypeName:'BANK',pullOffType:'Manual'}]},unavailable_fields:[]};let dictionary={country_code:'IN',platform:'OTHER',channels:[{id:1,withdraw_type_id:2,name:'WRONG'}]};const {api}=harness(async r=>r.operation==='index'?index(r.system,[t]):snap(r.system,t,c,dictionary));await api.loadIndex('PANDA');let h=api.render();assert(h.includes('123.45'));assert(h.includes('>3</span>'));assert(h.includes('按接单量成功率'));assert(!h.includes('WRONG'));assert(h.includes('通道 ID：1'));dictionary={country_code:'IN',platform:'P1',channels:[{id:1,withdraw_type_id:3,name:'WRONG-TYPE'},{id:1,withdraw_type_id:2,name:'Correct'}]};await api.refresh();h=api.render();assert(h.includes('Correct'));assert(!h.includes('WRONG-TYPE'));});
test('NewAR displays safe channels and rule groups without source URL column',async()=>{const t=target();const {api}=harness(async r=>r.operation==='index'?index(r.system,[t]):snap(r.system,t,{fields:[{key:'autoWithdraw',kind:'boolean',available:true,value:true}],channels:[{id:1,channelName:'Channel',channelType:'BANK'}],channelRules:[{id:2,name:'Rule'}],settingGroups:[{id:3,configName:'Group',maxWithdrawAmount:100}]}));await api.loadIndex('NEW_AR');const h=api.render();assert(h.includes('渠道列表'));assert(h.includes('Group'));assert(h.includes('提现金额'));assert(!h.includes('渠道地址'));});
test('WG brand switching is local; values do not inherit; unverified codes not labeled on/off',async()=>{let calls=0;const t=target();const {api}=harness(async r=>{calls++;return r.operation==='index'?index(r.system,[t]):snap(r.system,t,{settings:{0:{exemptSwitch:0,unavoidableCauseRemarkSwitch:1,registerTime:2},11:{exemptSwitch:1,levelIds:[1]}},dictionaries:{levels:[{level_id:1,name:'LV1'}],tags:[]},completeness:{unavailable:['games']}})});await api.loadIndex('WG');let h=api.render();assert(h.includes('开关映射未核实'));assert(h.includes('时间选项原码未核实'));assert(h.includes('关闭（只读）'));api.selectBrand(1);h=api.render();assert(h.includes('开启（只读）'));assert(h.includes('LV1'));assert(h.includes('接口未提供'));assert.equal(calls,2);});
test('Game66 safe table renders rule flags and values with no payload/remarks columns',async()=>{const t=target('HK1','GAME66_HK');const {api}=harness(async r=>r.operation==='index'?index(r.system,[t]):snap(r.system,t,{rules:[{rule_id:1,title:'Threshold',operator:'>=',value:0,effective_type_text:'所有',enabled:false}]}));await api.loadIndex('GAME66_HK');const h=api.render();assert(h.includes('自动出款审核规则'));assert(h.includes('Threshold'));assert(h.includes('关闭（只读）'));assert(!h.includes('raw_payload'));});
test('null snapshot stays unavailable; unknown response does not masquerade as successful empty config',async()=>{const t=target();let valid=true;const {api}=harness(async r=>r.operation==='index'?index(r.system,[t]):valid?{...snap(r.system,t,{}),snapshot:null}:{version:1,system:'BAD',readOnly:true,target:t});await api.loadIndex();assert(api.render().includes('尚未采集到配置快照'));valid=false;await api.refresh();assert.equal(api.state().snapshotStatus,'error');assert(api.render().includes('配置读取失败'));});
test('switching sources and revocation discard late snapshot responses; errors clear cached source data',async()=>{const late=deferred(),t=target();let sequence=0;const {api}=harness(async r=>{if(r.operation==='index')return index(r.system,[t]);if(++sequence===1)return late.promise;if(sequence===2)return snap(r.system,t,{values:{autoWithdrawalSwitch:true},unavailable_fields:[]});throw new Error('403 permission denied');});const first=api.loadIndex('AR');await new Promise(resolve=>setImmediate(resolve));assert.equal(sequence,1);await api.loadIndex('PANDA');late.resolve(snap('AR',t,{fields:[{key:'withdrawAmount',value:'STALE',available:true}],groups:[]}));await first;assert.equal(api.state().system,'PANDA');assert(!api.render().includes('STALE'));await api.refresh();assert.equal(api.state().snapshotStatus,'error');assert(api.render().includes('授权已失效'));assert(!api.render().includes('开启（只读）'));});
test('clear invalidates pending requests and search uses current country/platform scope only',async()=>{const pending=deferred();const {api}=harness(()=>pending.promise);const p=api.loadIndex();api.clear();pending.resolve(index('AR'));await p;assert.equal(api.state().indexStatus,'idle');const calls=[];api.configure({request:async r=>{calls.push(normalize(r));return r.operation==='index'?index(r.system,[target('ONE'),target('TWO','BR')]):snap(r.system,target(r.platform,r.country),{fields:[],groups:[]})}});await api.loadIndex();await api.setSearch('TWO');assert.equal(api.state().platform,null);await api.selectCountry(1);assert.equal(api.state().platform,'TWO');assert.equal(calls.at(-1).country,'BR');});
test('openTarget loads only the exact requested configuration and refresh keeps it selected',async()=>{
 const calls=[],targets=[target('DEFAULT'),target('EXACT'),target('EXACT','BR')];const {api}=harness(async r=>{calls.push(normalize(r));return r.operation==='index'?index(r.system,targets):snap(r.system,targets.find(t=>t.platform===r.platform&&t.country_code===r.country),{fields:[],groups:[]})});
 await api.openTarget({system:'ar',country:'IN',platform:'EXACT'});assert.deepEqual(calls,[{action:'payoutConfig',operation:'index',system:'AR'},{action:'payoutConfig',operation:'snapshot',system:'AR',country:'IN',platform:'EXACT'}]);assert.equal(api.state().platform,'EXACT');assert.equal(api.state().country,'IN');await api.refresh();assert.equal(calls.length,4);assert.equal(calls.at(-1).platform,'EXACT');assert.equal(calls.at(-1).country,'IN');assert(!calls.some(c=>c.operation==='snapshot'&&c.platform==='DEFAULT'));
});
test('openTarget resolves Panghu display country to the authorized raw BR configuration',async()=>{
 const fat={...target('PANGHU','BR'),country_name:'巴西',display_group:'BR_PANGHU',display_name:'胖虎巴西'},normal={...target('OTHER','BR'),country_name:'巴西',display_name:'巴西'};const calls=[];const {api}=harness(async r=>{calls.push(normalize(r));return r.operation==='index'?index(r.system,[normal,fat]):snap(r.system,fat,{values:{},unavailable_fields:[]})});await api.openTarget({system:'PANDA',country:'胖虎巴西',platform:'PANGHU'});assert.equal(calls.length,2);assert.deepEqual(calls[1],{action:'payoutConfig',operation:'snapshot',system:'PANDA',country:'BR',platform:'PANGHU'});assert.equal(api.state().platform,'PANGHU');assert(api.render().includes('胖虎巴西'));
});
test('a missing or ambiguous exact target never falls back to the first configuration',async()=>{
 const calls=[];let targets=[target('DEFAULT')];const {api}=harness(async r=>{calls.push(normalize(r));return index(r.system,targets)});await api.openTarget({system:'NEW_AR',country:'印度',platform:'MISSING'});assert.equal(calls.length,1);assert.equal(calls[0].system,'NEW_AR');assert.equal(api.state().platform,null);assert.equal(api.state().snapshotStatus,'error');assert(api.render().includes('未找到该平台'));await api.refresh();assert.equal(calls.length,2);assert.equal(api.state().platform,null);targets=[target('SAME'),target('SAME')];await api.openTarget({system:'AR',country:'IN',platform:'SAME'});assert.equal(calls.length,3);assert(api.render().includes('多个配置来源'));assert(!calls.some(r=>r.operation==='snapshot'));
});
test('an invalid exact source is rejected instead of defaulting to AR',async()=>{
 const calls=[];const {api}=harness(async r=>{calls.push(r);return index(r.system)});await api.openTarget({system:'REPORT',country:'IN',platform:'P1'});await api.ensureLoaded();assert.equal(calls.length,0);assert.equal(api.state().indexStatus,'error');assert(api.render().includes('来源信息不完整'));await api.openTarget({system:'PANDA',country:'BR',platform:''});assert.equal(calls.length,0);
});
test('rapid exact-target navigation discards a stale index and does not start its snapshot',async()=>{
 const first=deferred(),calls=[];let count=0;const targets=[target('FIRST'),target('SECOND')];const {api}=harness(async r=>{calls.push(normalize(r));return r.operation==='index'?(++count===1?first.promise:index(r.system,targets)):snap(r.system,targets.find(t=>t.platform===r.platform),{fields:[],groups:[]})});const old=api.openTarget({system:'AR',country:'IN',platform:'FIRST'});await api.openTarget({system:'AR',country:'IN',platform:'SECOND'});first.resolve(index('AR',targets));await old;assert.equal(api.state().platform,'SECOND');assert.deepEqual(calls.filter(c=>c.operation==='snapshot').map(c=>c.platform),['SECOND']);await api.selectSystem(0);assert.equal(api.state().platform,'FIRST','ordinary system selection retains its original default behavior');
});
