'use strict';
// Executes the exact current publisher and trigger in offline PostgreSQL WASM.
// No network, production data, member identifiers, or real credentials.
const {test,before,after,beforeEach,afterEach}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {PGlite}=require('@electric-sql/pglite');
const read=f=>fs.readFileSync(path.join(__dirname,f),'utf8');
const schema=read('fixtures/pending-analysis/pending-capture-publisher-schema.sql');
const baseline=read('fixtures/pending-analysis/pending-capture-publisher-baseline.sql');
const migration=read('../supabase/migrations/20261002065625_pending_capture_archive.sql');
const signatures=['public.publish_withdraw_pending_details(text,jsonb,jsonb)','public.publish_withdraw_pending_snapshot(text,jsonb)','public.refresh_withdraw_pending_backlog()'];
const token='1'.repeat(64),capture='2026-09-26T18:30:20Z',days=Array.from({length:7},(_,i)=>'2026-09-'+String(20+i).padStart(2,'0'));
let db,control,metadata;
const meta=async d=>(await d.query(`select p.proname,pg_get_userbyid(proowner) owner,proacl::text acl,prosecdef,proconfig,provolatile,
 md5(pg_get_functiondef(oid)) definition_hash,md5(prosrc) body_hash from pg_proc p where oid=any($1::regprocedure[]) order by proname`,[signatures])).rows;
async function setup(){const d=new PGlite();await d.exec(schema);await d.exec(baseline);
 for(const sig of signatures)await d.exec(`revoke all on function ${sig} from public,anon,authenticated;grant execute on function ${sig} to service_role;`);
 await d.exec(`create trigger withdraw_pending_backlog_refresh after insert on withdraw_pending_order_receipts for each row execute function public.refresh_withdraw_pending_backlog();
 grant select,insert,update,delete on all tables in schema public to service_role;`);
 await d.query('insert into withdraw_pending_credentials(token_hash,source_system,allowed_scopes,expires_at) values($1,$2,$3::jsonb,now()+interval \'1 day\')',
  [token,'WITHDRAW_REVIEW',JSON.stringify([{country_code:'IN',platform:'SYNTHETIC',timezone:'Asia/Kolkata'},{country_code:'BR',platform:'SYNTHETIC',timezone:'America/Sao_Paulo'}])]);return d;}
const scope=s=>Object.fromEntries(Object.entries(s).filter(([k])=>!['schema_version','coverage','totals','groups'].includes(k)));
function make(day,options={}){const rows=options.rows??[{order_no:'SYNTHETIC_'+day.replaceAll('-',''),member_id:'SYNTHETIC_MEMBER',amount:'100.00',applied_at:day+' 12:00:00',raw_channel:'SYNTHETIC_PAY',channel_type:'BANK',status:'已提交'}];
 const count=rows.length,amount=rows.reduce((n,r)=>n+Number(r.amount),0),groups=new Map();for(const r of rows){const k=JSON.stringify([r.raw_channel,r.channel_type]);if(!groups.has(k))groups.set(k,{raw_channel:r.raw_channel,channel_type:r.channel_type,pending_count:0,pending_amount:0});groups.get(k).pending_count++;groups.get(k).pending_amount+=Number(r.amount);}
 return {rows,snapshot:{schema_version:1,source_system:'WITHDRAW_REVIEW',country_code:options.country||'IN',platform:options.platform||'SYNTHETIC',stat_date:day,timezone:options.zone||'Asia/Kolkata',snapshot_id:randomUUID(),snapshot_at:options.at||capture,
 coverage:{complete:true,expected_count:count,fetched_count:count,unique_count:count},totals:{pending_count:count,pending_amount:amount},groups:[...groups.values()]}};}
async function publish(d,value,{service=false}={}){const {snapshot:s,rows}=value;
 if(rows.length)await d.query(`insert into withdraw_pending_order_chunks(snapshot_id,chunk_index,chunk_count,scope,orders,order_count,payload_bytes,chunk_hash,expires_at)
 values($1,0,1,$2::jsonb,$3::jsonb,$4,$5,encode(extensions.digest($3::text,'sha256'),'hex'),now()+interval '1 hour')`,[s.snapshot_id,JSON.stringify(scope(s)),JSON.stringify(rows),rows.length,Buffer.byteLength(JSON.stringify(rows))]);
 if(service)await d.exec('set role service_role');try{return(await d.query('select public.publish_withdraw_pending_details($1,$2::jsonb,$3::jsonb) ack',[token,JSON.stringify(s),JSON.stringify({details_version:1,chunk_count:rows.length?1:0,order_count:rows.length})])).rows[0].ack;}finally{if(service)await d.exec('reset role');}}
async function window(d,options={}){const values=days.map((day,i)=>make(day,{...options,rows:options.zero?[]:options.rows?.(day,i)}));for(const v of values)await publish(d,v,{service:!!options.service});return values;}
const heads=async(d=db)=>(await d.query('select * from private.withdraw_pending_capture_archive order by snapshot_at')).rows;
const archive=async(platform='SYNTHETIC',country='IN',at=capture,d=db)=>(await d.query('select private.archive_withdraw_pending_capture($1,$2,$3,$4) id',['WITHDRAW_REVIEW',country,platform,at])).rows[0].id;
async function identity(d=db,{country='IN',team='M8',zone='Asia/Kolkata',currency=null,source='AR'}={}){const map=randomUUID(),id=randomUUID();
 await d.query('insert into dashboard_platform_team_map(id,team_name,system_name,source_system,country_name,country_code,source_country,platform_name,source_platform) values($1,$2,$3,$3,$4,$4,$4,$5,$5)',[map,team,source,country,'SYNTHETIC']);
 await d.query('insert into private.collector_platform_identities values($1,$2,$3,$4,$5,$6,$4,$7,$8)',[id,map,source,country,'SYNTHETIC',team,zone,currency]);
 if(source==='AR')await d.query('insert into ar_config_targets(country_code,platform,country_name,timezone,currency) values($1,$2,$1,$3,$4)',[country,'SYNTHETIC',zone,currency]);
 else await d.query('insert into newar_detail_platforms(platform,country_code,country,timezone,currency) values($1,$2,$2,$3,$4)',['SYNTHETIC',country,zone,currency]);return{id,map};}
before(async()=>{db=await setup();control=await setup();metadata=await meta(db);await db.exec(migration);});
beforeEach(async()=>{await db.exec('begin');await control.exec('begin');});
afterEach(async()=>{await db.exec('rollback;reset role');await control.exec('rollback;reset role');});
after(async()=>{await db?.close();await control?.close();});

test('exact production guards execute and preserve publisher owner/ACL/signature/volatility',async()=>{const current=await meta(db);for(let i=0;i<current.length;i++){
 const old=metadata[i],now=current[i];assert.deepEqual({...now,definition_hash:old.definition_hash,body_hash:old.body_hash},old);
 if(now.proname==='publish_withdraw_pending_details')assert.notEqual(now.body_hash,old.body_hash);else assert.equal(now.body_hash,old.body_hash);
}assert.equal(metadata.find(r=>r.proname==='publish_withdraw_pending_details').definition_hash,'b89cbb48b69d781ccb26073d8318be18');});
test('final publication hook sees final replaced detail and preserves legacy ACK under service role',async()=>{await identity();const values=days.map(day=>make(day));for(let i=0;i<values.length;i++){
 const a=await publish(db,values[i],{service:true}),b=await publish(control,values[i],{service:true});assert.deepEqual(a,b);assert.equal(a.status,'accepted');assert.equal((await heads()).length,i===6?1:0);
}const h=(await heads())[0];assert.equal(h.pending_count,7);assert.equal(Number(h.pending_amount),700);assert.equal(h.identity_status,'resolved');assert.equal(h.team_name,'M8');assert.equal(h.currency,null);assert.equal(h.capture_basis,'actual_capture');assert.equal(h.within_midnight_window,true);assert.equal(h.partition_snapshots.length,7);
 const rows=(await db.query('select * from private.withdraw_pending_capture_orders')).rows;assert.equal(rows.length,7);assert(rows.every(r=>!('member_id'in r)));assert.equal((await db.query('select count(*) n from withdraw_pending_order_chunks')).rows[0].n,0);});
test('receipt replay remains unchanged and creates no second capture or detail',async()=>{const values=await window(db);const ack=(await db.query('select public.publish_withdraw_pending_details($1,$2::jsonb,$3::jsonb) ack',[token,JSON.stringify(values.at(-1).snapshot),JSON.stringify({details_version:1,chunk_count:1,order_count:1})])).rows[0].ack;
 assert.equal(ack.status,'unchanged');assert.equal((await heads()).length,1);assert.equal((await db.query('select count(*) n from private.withdraw_pending_capture_orders')).rows[0].n,7);assert.equal(await archive(),(await heads())[0].id);});
test('late same-day rerun replaces mutable head but cannot overwrite the earlier immutable capture',async()=>{await window(db);await window(db,{at:'2026-09-27T10:00:00Z',rows:day=>[{...make(day).rows[0],amount:'200.00'}]});const h=await heads();assert.equal(h.length,2);assert.equal(Number(h[0].pending_amount),700);assert.equal(Number(h[1].pending_amount),1400);assert.equal(h[0].within_midnight_window,true);assert.equal(h[1].within_midnight_window,false);assert.equal((await db.query('select snapshot_at from withdraw_pending_backlog_daily')).rows[0].snapshot_at.toISOString(),'2026-09-27T10:00:00.000Z');});
test('zero partitions require receipts and exact matching capture times; uneven captures retain ACK without archive',async()=>{for(let i=0;i<days.length;i++){const v=make(days[i],{rows:[],at:i===0?'2026-09-26T18:30:19Z':capture});assert.equal((await publish(db,v)).ok,true);}assert.equal((await heads()).length,0);assert.equal((await db.query('select count(*) n from withdraw_pending_backlog_daily')).rows[0].n,1);});
test('all seven proved zero partitions form a real immutable zero observation',async()=>{await window(db,{zero:true});const h=(await heads())[0];assert.equal(h.pending_count,0);assert.equal(Number(h.pending_amount),0);assert.equal(h.partition_snapshots.length,7);assert.equal((await db.query('select count(*) n from private.withdraw_pending_capture_orders')).rows[0].n,0);});
test('duplicate identifiers across creation days do not invent deduplicated amounts or block valid old publication',async()=>{await window(db,{rows:day=>[{...make(day).rows[0],order_no:'SYNTHETIC_DUPLICATE'}]});assert.equal((await heads()).length,0);assert.equal((await db.query('select count(*) n from withdraw_pending_orders')).rows[0].n,7);});
test('missing summary-only receipt does not become an archived zero',async()=>{const values=days.map(day=>make(day,{rows:[]}));for(const v of values)await db.query('select public.publish_withdraw_pending_snapshot($1,$2::jsonb)',[token,JSON.stringify(v.snapshot)]);assert.equal(await archive(),null);assert.equal((await heads()).length,0);});
test('unknown or changed identity remains legacy_unbound and never guesses team or currency',async()=>{await window(db);let h=(await heads())[0];assert.equal(h.identity_status,'legacy_unbound');assert.equal(h.platform_id,null);assert.equal(h.currency,null);
 const i=await identity();await db.query('update dashboard_platform_team_map set team_name=$1 where id=$2',['OTHER',i.map]);await window(db,{at:'2026-09-26T18:31:00Z'});h=(await heads()).at(-1);assert.equal(h.identity_status,'legacy_unbound');assert.equal(h.team_name,null);});
test('a later second registry mapping cannot silently choose the previously verified team',async()=>{await identity();await db.query('insert into dashboard_platform_team_map(team_name,system_name,source_system,country_name,country_code,source_country,platform_name,source_platform) values($1,$2,$2,$3,$3,$4,$5,$5)',['OTHER','AR','IN','India alias','SYNTHETIC']);await window(db);assert.equal((await heads())[0].identity_status,'legacy_unbound');});
test('same platform name in another country has independent immutable IDs and captures',async()=>{const a=await identity(),b=await identity(db,{country:'BR',team:'OTHER',zone:'America/Sao_Paulo',currency:'BRL'});await window(db);await window(db,{country:'BR',zone:'America/Sao_Paulo',at:'2026-09-27T03:00:20Z'});const h=await heads();assert.equal(h.length,2);assert.equal(h[0].platform_id,a.id);assert.equal(h[1].platform_id,b.id);assert.equal(h[0].country_code,'IN');assert.equal(h[1].country_code,'BR');});
test('midnight interval includes exactly 300 seconds and excludes 301 seconds',async()=>{await window(db,{zero:true,at:'2026-09-26T18:30:00Z'});await window(db,{zero:true,at:'2026-09-26T18:35:00Z'});await window(db,{zero:true,at:'2026-09-26T18:35:01Z'});assert.deepEqual((await heads()).map(h=>h.within_midnight_window),[true,true,false]);});
test('provider detail mismatch cannot archive despite unchanged aggregate count and amount',async()=>{for(const day of days.slice(0,-1))await publish(db,make(day));await db.query('update withdraw_pending_orders set raw_channel=$1 where stat_date=$2',['OTHER_PROVIDER',days[0]]);assert.equal((await publish(db,make(days.at(-1)))).ok,true);assert.equal((await heads()).length,0);});
test('daily receipt metadata amount mismatch cannot manufacture a complete archive',async()=>{for(const day of days.slice(0,-1))await publish(db,make(day));await db.query("update withdraw_pending_daily set snapshot=jsonb_set(jsonb_set(snapshot,'{totals,pending_amount}','101'::jsonb),'{groups,0,pending_amount}','101'::jsonb) where stat_date=$1",[days[0]]);assert.equal((await publish(db,make(days.at(-1)))).ok,true);assert.equal((await heads()).length,0);});
for(const value of ['NaN','Infinity','-Infinity'])test('legacy nonfinite '+value+' evidence skips archival without changing valid final publisher ACK',async()=>{
 // Infinity is impossible in the production numeric(20,2) column. This isolated
 // unconstrained fixture also tests future/corrupt legacy metadata defensively.
 await db.exec('alter table withdraw_pending_orders alter column amount type numeric');await control.exec('alter table withdraw_pending_orders alter column amount type numeric');
 const values=days.map(day=>make(day));for(const v of values.slice(0,-1)){await publish(db,v);await publish(control,v);}
 for(const d of [db,control]){await d.query('update withdraw_pending_orders set amount=$1::numeric where stat_date=$2',[value,days[0]]);
  await d.query("update withdraw_pending_daily set snapshot=jsonb_set(jsonb_set(snapshot,'{totals,pending_amount}',to_jsonb($1::text)),'{groups,0,pending_amount}',to_jsonb($1::text)) where stat_date=$2",[value,days[0]]);}
 const actual=await publish(db,values.at(-1)),old=await publish(control,values.at(-1));assert.deepEqual(actual,old);assert.equal(actual.status,'accepted');
 assert.equal((await heads()).length,0);assert.equal((await db.query('select count(*) n from withdraw_pending_order_receipts')).rows[0].n,7);
});
test('nonfinite application time skips archive and retains unchanged valid legacy publication',async()=>{const values=days.map(day=>make(day));for(const v of values.slice(0,-1)){await publish(db,v);await publish(control,v);}
 for(const d of [db,control])await d.query("update withdraw_pending_orders set applied_at='infinity'::timestamp where stat_date=$1",[days[0]]);
 const actual=await publish(db,values.at(-1));assert.deepEqual(actual,await publish(control,values.at(-1)));assert.equal(actual.status,'accepted');assert.equal((await heads()).length,0);});
test('private storage CHECK constraints reject NaN and both infinities independently of the writer',async()=>{await window(db);const h=(await heads())[0];
 for(const value of ['NaN','Infinity','-Infinity']){await db.exec('savepoint nonfinite');await assert.rejects(()=>db.query(`insert into private.withdraw_pending_capture_orders
 (archive_id,order_no,source_system,country_code,platform,stat_date,amount,applied_at,timezone,raw_channel,channel_type,status,snapshot_id,snapshot_at)
 select archive_id,'SYNTHETIC_NONFINITE',source_system,country_code,platform,stat_date,$1::numeric,applied_at,timezone,raw_channel,channel_type,status,snapshot_id,snapshot_at
 from private.withdraw_pending_capture_orders where archive_id=$2 limit 1`,[value,h.id]),/check constraint/);await db.exec('rollback to nonfinite;release nonfinite');
 await db.exec('savepoint nonfinite');await assert.rejects(()=>db.query(`insert into private.withdraw_pending_capture_archive
 select (jsonb_populate_record(null::private.withdraw_pending_capture_archive,to_jsonb(a)||jsonb_build_object('id',gen_random_uuid(),'snapshot_at',a.snapshot_at+interval '1 second','pending_amount',$1::text))).*
 from private.withdraw_pending_capture_archive a where id=$2`,[value,h.id]),/check constraint/);await db.exec('rollback to nonfinite;release nonfinite');}
});
test('a genuine unknown application time is retained as NULL instead of inventing an age',async()=>{const local=await setup();try{await window(local);await local.exec('alter table withdraw_pending_orders alter column applied_at drop not null');await local.query('update withdraw_pending_orders set applied_at=null where stat_date=$1',[days[0]]);await local.exec(migration);assert.equal((await heads(local)).length,1);const rows=(await local.query('select applied_at from private.withdraw_pending_capture_orders order by stat_date')).rows;assert.equal(rows.length,7);assert.equal(rows[0].applied_at,null);}finally{await local.close();}});
test('archive tables are private/RLS protected and immutable even to their owner',async()=>{await window(db);for(const table of ['private.withdraw_pending_capture_archive','private.withdraw_pending_capture_orders']){const a=(await db.query(`select has_table_privilege('anon',$1,'select,insert,update,delete') anon,has_table_privilege('authenticated',$1,'select,insert,update,delete') authenticated,has_table_privilege('service_role',$1,'select,insert,update,delete') service`,[table])).rows[0];assert.deepEqual(a,{anon:false,authenticated:false,service:false});assert.equal((await db.query('select relrowsecurity r from pg_class where oid=$1::regclass',[table])).rows[0].r,true);
 for(const statement of [`update ${table} set platform='CHANGED'`,`delete from ${table}`]){await db.exec('savepoint mutation');await assert.rejects(()=>db.exec(statement),/PENDING_CAPTURE_IMMUTABLE/);await db.exec('rollback to mutation;release mutation');}}
 const f=(await db.query("select has_function_privilege('anon',$1,'execute') anon,has_function_privilege('authenticated',$1,'execute') authenticated,has_function_privilege('service_role',$1,'execute') service",['private.archive_withdraw_pending_capture(text,text,text,timestamptz)'])).rows[0];assert.deepEqual(f,{anon:false,authenticated:false,service:true});});
test('real archive storage errors propagate and atomically roll back receipt/current detail publication',async()=>{for(const day of days.slice(0,-1))await publish(db,make(day));await db.exec('savepoint broken_storage;alter table private.withdraw_pending_capture_archive rename to deliberately_unavailable');const v=make(days.at(-1));await assert.rejects(()=>publish(db,v),/withdraw_pending_capture_archive/);await db.exec('rollback to broken_storage;release broken_storage');assert.equal((await db.query('select count(*) n from withdraw_pending_order_receipts')).rows[0].n,6);assert.equal((await heads()).length,0);});
test('source definition drift fails before any archive schema or publisher mutation',async()=>{await control.exec("create or replace function public.refresh_withdraw_pending_backlog() returns trigger language plpgsql set search_path='' as $$begin return NEW;end$$;");await assert.rejects(()=>control.exec(migration),/pending_capture_source_contract_drift/);await control.exec('rollback;begin');assert.equal((await control.query("select to_regclass('private.withdraw_pending_capture_archive') a")).rows[0].a,null);});
test('limited initial backfill keeps only exact complete actual capture, never overwritten history',async()=>{await window(control);await window(control,{at:'2026-09-27T10:00:00Z'});await control.exec('commit');await control.exec(migration);await control.exec('begin');const h=await heads(control);assert.equal(h.length,1);assert.equal(h[0].snapshot_at.toISOString(),'2026-09-27T10:00:00.000Z');assert.equal(h[0].capture_basis,'actual_capture');assert.equal(h[0].within_midnight_window,false);});
test('backfill skips an old head whose details were overwritten by the next calendar capture',async()=>{const local=await setup();try{await window(local);for(const day of [...days.slice(1),'2026-09-27'])await publish(local,make(day,{at:'2026-09-27T18:30:20Z'}));assert.equal((await local.query('select count(*) n from withdraw_pending_backlog_daily')).rows[0].n,2);await local.exec(migration);const h=await heads(local);assert.equal(h.length,1);assert.equal(h[0].stat_date.toISOString().slice(0,10),'2026-09-27');assert.equal(h[0].snapshot_at.toISOString(),'2026-09-27T18:30:20.000Z');}finally{await local.close();}});
