/* Synthetic current-scope facts only: no network, credentials or source orders. */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const base=path.join(__dirname,'../admin-preview'),renderer=fs.readFileSync(path.join(base,'live-success-analysis.js'),'utf8');
function api(){const c={};c.window=c;vm.createContext(c);for(const name of ['live-provider-aliases.js','live-report-data.js','live-provider-summary.js'])vm.runInContext(fs.readFileSync(path.join(base,name),'utf8'),c);vm.runInContext(renderer,c);return c.HensemLiveSuccessAnalysis;}
const A={id:'native-ar',name:'Same platform',source:'AR',country:'印度'},B={...A,id:'native-newar',source:'NEW_AR'},W={...A,id:'native-wg',source:'WG'};
const row=(direction='charge',all=10,success=4,provider='ATPay')=>({direction,all_count:all,success_count:success,provider,currency:'INR'});
const payment=(platform,rows,summary)=>({platform,groups:{provider:rows},...(summary===undefined?{}:{summary})});
const ticket=(platform,direction='charge',total=10,success=4,provider='ATPay',complete=true)=>({platformId:platform.id,country:platform.country,source:platform.source,provider,direction,uniqueOrderCount:total,uniqueSuccessCount:success,uniqueCoverage:{status:complete?'complete':'partial',complete}});
function props(overrides={}){const L={pageQueried:true,dirty:false,from:'2026-10-03T00:00:00',to:'2026-10-03T23:59:59',queryPlatforms:[A,B],results:[payment(A,[row()]),payment(B,[row('charge',5,1,'ATPay-QR')])],queryFailures:[],feeLookupRows:[],feeLookupLoading:false,feeLookupError:'',country:'印度',workorders:{startDate:'2026-10-03',endDate:'2026-10-03',byPlatformProvider:[ticket(A),ticket(A,'withdraw',5,5),ticket(B,'charge',6,1,'ATPay-QR',false)]},...overrides};return {L,scopeMatches:true,workordersScopeMatches:true};}
test('DUOLI current-status success never becomes a payment-time rate in either direction',()=>{
 const p={...A,id:'duoli-id',name:'UANG',source:'duoli',country:'印尼',capabilities:{chargeSuccessTimeAvailable:false,withdrawSuccessTimeAvailable:false}},rows=[row('charge',20,0,'ObservedPay'),row('withdraw',10,0,'ObservedPay')],a=api(),input=props({queryPlatforms:[p],results:[payment(p,rows,rows)],workorders:null});
 const model=a.buildModel(input);assert.equal(model.rows[0].charge[0].value,null);assert.equal(model.rows[0].withdraw[0].value,null);
 const html=a.render(input);assert.match(html,/多利/);assert.match(html,/代收成功时间/);assert.match(html,/代付成功时间/);assert.doesNotMatch(html,/>0\.00%/);
});
test('canonical provider rows keep native platform identity and three vertical rate-only matrices',()=>{
 const a=api(),p=props({successDateNotice:'成功率分析按一个当地日展示，已选择 2026-10-03 全天。'}),before=JSON.stringify(p),model=a.buildModel(p);assert.equal(model.rows.length,1);assert.equal(model.rows[0].provider,'ATPay');assert.deepEqual(Array.from(model.rows[0].charge,v=>v.value),[40,20]);assert.equal(model.rows[0].workorder[0].value,60);assert.equal(model.rows[0].workorder[0].partial,false);assert(Math.abs(model.rows[0].workorder[1].value-100/6)<1e-10);assert.equal(model.rows[0].workorder[1].partial,true);
 const html=a.render(p);assert.equal((html.match(/<table /g)||[]).length,3);assert.equal((html.match(/<th scope="row">ATPay<\/th>/g)||[]).length,2);assert.match(html,/新AR/);assert.match(html,/状态 4/);assert.match(html,/不代表实际到账/);assert.match(html,/完整原单号去重/);assert.doesNotMatch(html,/全部金额|手续费|到账成功金额/);assert.doesNotMatch(html,/按一个当地日展示|已选择 2026-10-03 全天|success-analysis-context|success-analysis-method|统计口径|平台当地日期 · 提交笔数从多到少/);assert.equal(JSON.stringify(p),before);
});
test('strict below-40 color applies to all matrices, unknown neutral and above-100 rates are preserved',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[payment(A,[row('charge',100,39),row('withdraw',10,4)])],workorders:{byPlatformProvider:[ticket(A,'charge',100,39),ticket(A,'withdraw',0,0)]}});let html=a.render(p);assert.equal((html.match(/<tbody>.*?<\/tbody>/g).join('').match(/class="success-rate-low"/g)||[]).length,2);assert.equal((html.match(/<tfoot.*?<\/tfoot>/g).join('').match(/class="success-rate-low"/g)||[]).length,1);assert.match(html,/>40\.00%<\/span>/);assert.match(html,/>39\.00%/);
 p.L.results=[payment(A,[row('charge',10,12),row('withdraw',10,null)])];p.L.workorders.byPlatformProvider=[ticket(A,'charge',0,0)];html=a.render(p);assert.match(html,/>120\.00%<\/span>/);assert.doesNotMatch(html,/success-rate-low/);assert.match(html,/>—<\/span>/);
});
test('workorder combined rate uses dedup original counts and preserves absent, unknown and duplicate cohort evidence',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[payment(A,[row()])],workorders:{byPlatformProvider:[ticket(A,'charge',8,4),ticket(A,'withdraw',2,2)]}}),work=()=>a.buildModel(p).rows[0].workorder[0];assert.equal(work().value,60);assert.equal(work().partial,false);
 p.L.workorders.byPlatformProvider.pop();assert.equal(work().value,50);assert.equal(work().partial,true);p.L.workorders.byPlatformProvider.push(ticket(A,'withdraw',null,0));assert.equal(work().value,null);p.L.workorders.byPlatformProvider=[ticket(A),ticket(A,'charge',10,3,'ATPay-QR')];assert.equal(work().value,null);
 p.L.workorders.byPlatformProvider=[{...ticket(A),uniqueOrderCount:null,submittedCount:999,successCount:999}];assert.equal(work().value,null);p.L.workorders.byPlatformProvider=[ticket(A,'charge',1,2)];assert.equal(work().value,null);
});
test('WG success time gaps affect its own withdrawal column and invalid or missing payment counts remain unknown',()=>{
 const a=api(),p=props({queryPlatforms:[A,W],results:[payment(A,[row('withdraw',10,6)]),payment(W,[row('withdraw',10,6),row('charge',10,3)])],workorders:null}),m=a.buildModel(p);assert.equal(m.rows[0].withdraw[0].value,60);assert.equal(m.rows[0].withdraw[1].value,null);assert.equal(m.rows[0].charge[1].value,30);p.L.results[0].platform={...A,capabilities:{withdrawSuccessTimeAvailable:false}};assert.equal(a.buildModel(p).rows[0].withdraw[0].value,null);p.L.results[0].platform=A;p.L.results[0].groups.provider[0].success_count='';assert.equal(a.buildModel(p).rows[0].withdraw[0].value,null);
});
test('each matrix ranks only its own active providers across native platforms, leaving unknown evidence in a disclosure',()=>{
 const a=api(),p=props({results:[payment(A,[row('charge',3,1,'A small'),row('charge',90,20,'Z busiest'),row('withdraw',200,100,'P payout'),row('charge',null,null,'Empty')]),payment(B,[row('charge',20,10,'Z busiest'),row('withdraw',5,1,'A small')])],workorders:{byPlatformProvider:[ticket(A,'charge',2,1,'Z busiest'),ticket(A,'charge',30,3,'T tickets'),ticket(B,'withdraw',40,4,'T tickets'),ticket(A,'withdraw',20,8,'A small')]}}),before=JSON.stringify(p),m=a.buildModel(p);
 assert.deepEqual(Array.from(a.rankedRows(m,'charge'),r=>r.provider),['Z busiest','A small']);
 assert.deepEqual(Array.from(a.rankedRows(m,'withdraw'),r=>r.provider),['P payout','A small']);
 assert.deepEqual(Array.from(a.rankedRows(m,'workorder'),r=>r.provider),['T tickets','A small','Z busiest']);
 const tables=a.render(p).match(/<tbody>.*?<\/tbody>/g),names=html=>Array.from(html.matchAll(/<th scope="row">(.*?)<\/th>/g),x=>x[1]);
 assert.deepEqual(names(tables[0]),['Z busiest','A small']);assert.deepEqual(names(tables[1]),['P payout','A small']);assert.deepEqual(names(tables[2]),['T tickets','A small','Z busiest']);assert.match(a.render(p),/<details class="success-analysis-other">.*活动未确认.*未按零处理：Empty/);
 assert.equal(m.rows.find(r=>r.provider==='Z busiest').volumes.charge,110);assert.equal(m.rows.find(r=>r.provider==='T tickets').volumes.workorder,70);assert.equal(JSON.stringify(p),before);
});
test('known WG submission volume ranks ahead of smaller flows even when its rate cannot be verified',()=>{
 const a=api(),p=props({queryPlatforms:[A,W],results:[payment(A,[row('withdraw',10,5,'Small'),row('withdraw',0,0,'Zero')]),payment(W,[row('withdraw',50,20,'Busy WG')])],workorders:null}),m=a.buildModel(p);
 assert.deepEqual(Array.from(a.rankedRows(m,'withdraw'),r=>r.provider),['Busy WG','Small']);assert.equal(m.rows.find(r=>r.provider==='Busy WG').withdraw[1].value,null);assert.equal(m.rows.find(r=>r.provider==='Busy WG').volumes.withdraw,50);
 const html=a.render(p);assert.match(html,/<th scope="row">Busy WG<\/th>.*<th scope="row">Small<\/th>/);assert.match(html,/>—<\/span>/);assert.doesNotMatch(html,/<th scope="row">Zero<\/th>/);
});
test('manual and unresolved labels never become provider rows while their native summary contribution and evidence remain available',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[payment(A,[row('charge',10,0,'Real failure'),row('charge',4,4,'人工确认'),row('charge',3,0,'无三方（驳回）'),row('charge',2,1,'未标记三方'),row('charge',1,0,'未识别通道'),row('withdraw',0,0,'人工确认')],[row('charge',20,5),row('withdraw',0,0)])],workorders:{byPlatformProvider:[ticket(A,'charge',8,4,'Real failure'),ticket(A,'charge',2,1,'未标记三方')],byPlatformDirection:[ticket(A,'charge',10,5),ticket(A,'withdraw',0,0)]}}),before=JSON.stringify(p),m=a.buildModel(p),html=a.render(p),sections=html.match(/<section class="success-analysis-panel">.*?<\/section>/g);
 assert.deepEqual(Array.from(a.rankedRows(m,'charge'),r=>r.provider),['Real failure']);assert.deepEqual(Array.from(a.rankedRows(m,'withdraw'),r=>r.provider),[]);assert.deepEqual(Array.from(a.rankedRows(m,'workorder'),r=>r.provider),['Real failure']);
 assert.equal(m.footers.charge[0].value,25);assert.equal(m.footers.charge[0].total,20);assert.equal(m.footers.charge[0].providerCount,1);assert.equal(m.footers.charge[0].providerCountPartial,true);assert.equal(m.footers.workorder[0].value,50);assert.equal(m.footers.workorder[0].total,10);
 assert.match(sections[0],/<th scope="row">Real failure<\/th>.*class="success-rate-low"[^>]*>0\.00%/);assert.doesNotMatch(html,/<th scope="row">(?:人工确认|无三方（驳回）|未标记三方|未识别通道)<\/th>/);assert.match(sections[0],/<details class="success-analysis-other">.*4 类非三方 \/ 未归属记录.*人工确认（已读提交 4 笔）.*不因收起这些记录而扣减/);assert.doesNotMatch(sections[1],/success-analysis-other/);assert.match(sections[2],/未标记三方（已读提交 2 笔）/);assert.equal(JSON.stringify(p),before);
});
test('activity visibility preserves real zero rates, cross-day successes and amount-only evidence without inventing zero for missing rates',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[payment(A,[row('charge',10,0,'FailedPay'),row('charge',0,2,'CrossDayPay'),{...row('charge',null,null,'AmountOnlyPay'),all_amount:25},row('charge',0,0,'DormantPay'),row('charge',null,null,'UnknownPay'),row('withdraw',99,80,'PayoutOnlyPay')],[row('charge',10,2)])],workorders:null}),m=a.buildModel(p),table=a.render(p).match(/<table[^>]*>.*?<\/table>/g)[0];
 assert.deepEqual(Array.from(a.rankedRows(m,'charge'),r=>r.provider),['FailedPay','CrossDayPay','AmountOnlyPay']);assert.equal(m.rows.find(r=>r.provider==='FailedPay').charge[0].value,0);assert.equal(m.rows.find(r=>r.provider==='CrossDayPay').charge[0].value,null);assert.equal(m.rows.find(r=>r.provider==='AmountOnlyPay').charge[0].value,null);assert.equal(m.footers.charge[0].value,20);
 assert.match(table,/<th scope="row">FailedPay<\/th>.*class="success-rate-low"[^>]*>0\.00%/);assert.doesNotMatch(table,/<th scope="row">(?:DormantPay|UnknownPay|PayoutOnlyPay)<\/th>/);assert.match(a.render(p),/分组未提供可确认的活动笔数或金额，未按零处理：UnknownPay/);
});
test('known raw workorder activity keeps an unverifiable original-order rate visible without using raw counts as the rate denominator',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[payment(A,[row('charge',50,25,'PaymentOnlyPay')])],workorders:{byPlatformProvider:[{...ticket(A,'charge',null,null,'RawTicketPay'),submittedCount:30,successCount:20},ticket(A,'charge',0,0,'DormantTicketPay')],byPlatformDirection:[ticket(A,'charge',null,null),ticket(A,'withdraw',0,0)]}}),m=a.buildModel(p),table=a.render(p).match(/<table[^>]*>.*?<\/table>/g)[2];
 assert.deepEqual(Array.from(a.rankedRows(m,'workorder'),r=>r.provider),['RawTicketPay']);assert.equal(m.rows.find(r=>r.provider==='RawTicketPay').workorder[0].value,null);assert.equal(m.rows.find(r=>r.provider==='RawTicketPay').volumes.workorder,null);assert.equal(m.footers.workorder[0].value,null);assert.match(table,/<th scope="row">RawTicketPay<\/th>.*原支付单去重笔数未完整提供.*>—<\/span>/);assert.doesNotMatch(table,/<th scope="row">(?:PaymentOnlyPay|DormantTicketPay)<\/th>|66\.67%/);
});
test('dirty, foreign scope, multi-day and invalid-date snapshots never reveal rates',()=>{
 const a=api();for(const p of [props({dirty:true}),{...props(),scopeMatches:false},props({to:'2026-10-04T23:59:59'}),props({from:'2026-99-03',to:'2026-99-03'})]){assert.equal(a.buildModel(p).ready,false);assert.doesNotMatch(a.render(p),/<table|40\.00%|ATPay/);}
 const p={...props(),workordersScopeMatches:false};assert.equal(a.buildModel(p).rows[0].workorder[0].value,null);p.workordersScopeMatches=true;p.L.workorders.startDate='2026-10-02';assert.equal(a.buildModel(p).rows[0].workorder[0].value,null);
});
test('unknown native identity or cross-country/source rows cannot be assigned by shared display names',()=>{
 const a=api(),p=props();p.L.results=[payment({...A,source:'WG'},[row()])];p.L.workorders.byPlatformProvider=[{...ticket(A),platformId:null,platform:A.name},{...ticket(B),country:'巴西'},{...ticket(A),source:'NEW_AR'}];const m=a.buildModel(p);assert.equal(m.rows.length,0);assert.equal(m.ignored,3);assert.match(a.render(p),/有 3 条工单汇总无法匹配已授权平台身份/);assert.doesNotMatch(a.render(p),/40\.00%/);
 p.L.results=[payment(A,[row()]),payment(A,[row()])];p.L.workorders=null;assert.equal(a.buildModel(p).rows.length,0,'ambiguous duplicate aggregate platform is not summed');
});

test('each matrix ranks platform columns independently without moving native cells or mutating the model inputs',()=>{
 const C={...A,id:'native-lg',source:'LG'},E={...A,id:'native-empty',source:'WG'},a=api(),p=props({queryPlatforms:[A,B,C,E],results:[payment(A,[row('charge',1,1)], [row('charge',10,4),row('withdraw',50,40)]),payment(B,[row('charge',2,1)],[row('charge',30,9),row('withdraw',10,4)]),payment(C,[row('charge',3,1)],[row('charge',20,10),row('withdraw',40,20)])],workorders:{byPlatformProvider:[],byPlatformDirection:[ticket(A,'charge',2,1),ticket(B,'charge',4,1),ticket(C,'charge',8,3),ticket(C,'withdraw',2,1)]}}),before=JSON.stringify(p),m=a.buildModel(p);
 assert.deepEqual(Array.from(m.columns,p=>p.id),[A.id,B.id,C.id,E.id]);
 assert.deepEqual(Array.from(a.rankedColumnIndexes(m,'charge'),i=>m.columns[i].id),[B.id,C.id,A.id,E.id]);assert.deepEqual(Array.from(a.rankedColumnIndexes(m,'withdraw'),i=>m.columns[i].id),[A.id,C.id,B.id,E.id]);assert.deepEqual(Array.from(a.rankedColumnIndexes(m,'workorder'),i=>m.columns[i].id),[C.id,B.id,A.id,E.id]);
 assert.equal(m.rows[0].charge[0].value,100);assert.equal(m.rows[0].charge[1].value,50);assert(Math.abs(m.rows[0].charge[2].value-100/3)<1e-10);assert.equal(m.rows[0].charge[3].value,null);
 const tables=a.render(p).match(/<table[^>]*>.*?<\/table>/g),headIds=html=>Array.from(html.matchAll(/<th scope="col" title="[^"]* · (native-[\w-]+) · 已读取/g),match=>match[1]);
 assert.deepEqual(headIds(tables[0]),[B.id,C.id,A.id,E.id]);assert.deepEqual(headIds(tables[1]),[A.id,C.id,B.id,E.id]);assert.deepEqual(headIds(tables[2]),[C.id,B.id,A.id,E.id]);
 assert.match(tables[0],/<th scope="row">ATPay<\/th><td class="success-provider-type">.*?<\/td><td[^>]*><span[^>]*>50\.00%/);assert.equal(JSON.stringify(p),before);
});
test('equal known platform volumes use stable native IDs and known zero sorts ahead of missing data',()=>{
 const Z={...A,id:'z-native'},N={...A,id:'a-native'},Zero={...A,id:'zero-native'},Missing={...A,id:'missing-native'},a=api(),m=a.buildModel(props({queryPlatforms:[Z,Missing,Zero,N],results:[payment(Z,[row()], [row('charge',10,4)]),payment(N,[row()],[row('charge',10,3)]),payment(Zero,[],[row('charge',0,0)])],workorders:null}));
 assert.deepEqual(Array.from(a.rankedColumnIndexes(m,'charge'),i=>m.columns[i].id),[N.id,Z.id,Zero.id,Missing.id]);assert.equal(m.footers.charge[2].value,null);assert.equal(m.footers.charge[2].volume,0);
});
test('payment footers weight authoritative direction summary counts instead of averaging provider percentages or losing omitted providers',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[payment(A,[row('charge',1,1,'Tiny 100'),row('charge',9,0,'Big 0')],[{...row('charge',10,1),currency:'INR'},{...row('charge',90,45),currency:'USDT'},row('withdraw',20,8)])],workorders:null}),m=a.buildModel(p),value=m.footers.charge[0];
 assert.equal(value.total,100);assert.equal(value.success,46);assert.equal(value.value,46);assert.equal(value.partial,false);assert.notEqual(value.value,50);assert.equal(m.footers.withdraw[0].value,40);
 const tables=a.render(p).match(/<table[^>]*>.*?<\/table>/g);assert.match(tables[0],/<tfoot[^>]*>.*汇总成功率.*>46\.00%<\/span>/);assert.doesNotMatch(tables[0].match(/<tfoot.*?<\/tfoot>/)[0],/aria-label="部分来源"/);
 const noProviders=props({queryPlatforms:[A],results:[{platform:A,summary:[row('charge',200,100)]}],workorders:null});assert.equal(a.buildModel(noProviders).rows.length,0);assert.equal(a.buildModel(noProviders).footers.charge[0].value,50);assert.match(a.render(noProviders),/汇总成功率.*>50\.00%/);
});
test('missing payment summary uses only known provider counts as explicit partial while invalid native summary never borrows those groups',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[payment(A,[row('charge',3,1),row('charge',7,null,'Unknown')])],workorders:null}),value=()=>a.buildModel(p).footers.charge[0];assert.equal(value().total,3);assert.equal(value().success,1);assert.equal(value().partial,true);assert.equal(value().volume,10);assert.match(value().note,/仅按.*三方分组/);assert.match(a.render(p),/汇总成功率.*33\.33%<sup/);
 p.L.results[0].summary=[row('charge',20,null)];assert.equal(value().value,null);assert.equal(value().volume,20);assert.equal(value().partial,false);
 p.L.results[0].summary=[row('charge',10,4),row('charge',10,4)];assert.equal(value().value,null);assert.equal(value().volume,null);assert.match(value().note,/重复币种/);
 p.L.results[0].summary=[row('charge',Number.MAX_SAFE_INTEGER,1),{...row('charge',1,1),currency:'USDT'}];assert.equal(value().value,null);assert.equal(value().volume,null);
 for(const all_count of [null,true,-1,1.5,'']){p.L.results[0].summary=[{...row(),all_count}];assert.equal(value().value,null);assert.equal(value().volume,null);}
});
test('workorder footers consume platform-direction original cohorts across providers and never sum provider unique totals',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[payment(A,[row()])],workorders:{byPlatformProvider:[ticket(A,'charge',10,4,'First'),ticket(A,'charge',10,8,'Second')],byPlatformDirection:[ticket(A,'charge',11,4),ticket(A,'withdraw',9,6)]}}),value=()=>a.buildModel(p).footers.workorder[0];assert.equal(value().total,20);assert.equal(value().success,10);assert.equal(value().value,50);assert.equal(value().partial,false);assert.equal(value().volume,20);assert.notEqual(value().success,12);
 delete p.L.workorders.byPlatformDirection;assert.equal(value().value,null);assert.equal(value().volume,null);assert.match(value().note,/不能将三方原单笔数相加/);assert.match(a.render(p).match(/<table[^>]*>.*?<\/table>/g)[2],/<tfoot[^>]*>.*汇总成功率.*>—<\/span>/);
});
test('workorder platform footers preserve partial direction/source evidence and reject identity, duplicate, unsafe or inconsistent counts',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[payment(A,[row()])],workorders:{byPlatformProvider:[],byPlatformDirection:[ticket(A,'charge',8,4)]}}),value=()=>a.buildModel(p).footers.workorder[0];assert.equal(value().value,50);assert.equal(value().partial,true);assert.match(value().note,/取款平台原单汇总未提供/);assert.match(a.render(p),/汇总成功率.*50\.00%<sup/);
 p.L.workorders.byPlatformDirection=[ticket(A,'charge',8,4),{...ticket(A,'withdraw',2,1),uniqueCoverage:{status:'complete',complete:true,sourceCoverage:{complete:false}}}];assert.equal(value().value,50);assert.equal(value().partial,true);
 for(const extra of [{country:'巴西'},{source:'WG'},{platformId:null},{country:null},{source:null}]){p.L.workorders.byPlatformDirection=[{...ticket(A),...extra}];assert.equal(value().value,null);assert.equal(value().volume,null);}
 for(const extra of [{uniqueOrderCount:null},{uniqueOrderCount:true},{uniqueOrderCount:-1},{uniqueOrderCount:Number.MAX_SAFE_INTEGER+1},{uniqueSuccessCount:11},{uniqueCoverage:{status:'unavailable',complete:false}}]){p.L.workorders.byPlatformDirection=[{...ticket(A),...extra}];assert.equal(value().value,null);assert.equal(value().volume,null);}
 p.L.workorders.byPlatformDirection=[ticket(A),ticket(A)];assert.equal(value().value,null);assert.match(value().note,/多条去重汇总/);
});
test('platform footer rates keep strict red threshold, above-100 payment rates, zero denominators and WG withdrawal unknown',()=>{
 const a=api(),p=props({queryPlatforms:[A,W],results:[payment(A,[row()],[row('charge',10,12),row('withdraw',10,4)]),payment(W,[row('withdraw',99,98)],[row('charge',100,39),row('withdraw',99,98)])],workorders:{byPlatformProvider:[],byPlatformDirection:[ticket(A,'charge',100,39),ticket(A,'withdraw',0,0),ticket(W,'charge',0,0)]}}),m=a.buildModel(p);assert.equal(m.footers.charge[0].value,120);assert.equal(m.footers.withdraw[0].value,40);assert.equal(m.footers.withdraw[1].value,null);assert.equal(m.footers.withdraw[1].volume,99);assert.equal(m.footers.workorder[0].value,39);assert.equal(m.footers.workorder[1].value,null);
 const footerHtml=a.render(p).match(/<tfoot.*?<\/tfoot>/g).join('');assert.match(footerHtml,/>120\.00%<\/span>/);assert.match(footerHtml,/>40\.00%<\/span>/);assert.equal((footerHtml.match(/class="success-rate-low"/g)||[]).length,2);
});
test('footer provider counts use positive same-section submissions and canonical identity, excluding non-payment labels',()=>{
 const a=api(),p=props({queryPlatforms:[A,B],results:[payment(A,[row('charge',10,4),row('charge',5,2,'ATPay-QR'),row('charge',20,5,'OtherPay'),row('withdraw',0,5,'ATPay'),row('withdraw',2,1,'PayoutPay'),row('withdraw',5,2,'人工确认')],[row('charge',35,11),row('withdraw',7,8)]),payment(B,[],[row('charge',9,4),row('withdraw',0,0)])],workorders:null}),m=a.buildModel(p);
 assert.equal(m.footers.charge[0].providerCount,2);assert.equal(m.footers.charge[0].providerCountPartial,false);assert.equal(m.footers.withdraw[0].providerCount,1);assert.equal(m.footers.withdraw[0].providerCountPartial,false);
 assert.equal(m.footers.charge[1].providerCount,null);assert.equal(m.footers.withdraw[1].providerCount,0);assert.equal(m.footers.withdraw[1].providerCountPartial,false);
 const html=a.render(p);assert.match(html,/success-analysis-provider-count[^>]*>2 三方<\/small>/);assert.match(html,/success-analysis-provider-count[^>]*>三方数未提供<\/small>/);assert.match(html,/success-analysis-provider-count[^>]*>0 三方<\/small>/);
});
test('footer provider counts preserve missing breakdown, unknown submission counts and unidentified providers as partial instead of zero',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[payment(A,[row('charge',10,4)],[row('charge',20,8)])],workorders:null}),value=()=>a.buildModel(p).footers.charge[0];assert.equal(value().providerCount,1);assert.equal(value().providerCountPartial,true);assert.match(a.render(p),/1 三方<sup aria-label="已识别三方小计">\*/);
 p.L.results[0].groups.provider=[row('charge',10,4),row('charge',null,null,'OtherPay')];assert.equal(value().providerCount,1);assert.equal(value().providerCountPartial,true);
 for(const name of ['（三方未提供）','未识别通道','USDT']){p.L.results[0].groups.provider=[row('charge',20,8,name)];assert.equal(value().providerCount,null);assert.equal(value().providerCountPartial,true);}
 p.L.results[0].groups.provider=[row('charge',0,0)];assert.equal(value().providerCount,null);
 p.L.results[0].groups.provider=[row('charge',20,8,'人工充值')];assert.equal(value().providerCount,0);assert.equal(value().providerCountPartial,false);
 delete p.L.results[0].summary;p.L.results[0].groups.provider=[row('charge',0,0)];assert.equal(value().providerCount,null,'provider zero alone does not prove a platform has no other running provider');
});
test('workorder footer provider counts are canonical activity subtotals, without inventing names for conflicting or unresolved originals',()=>{
 const a=api(),p=props({queryPlatforms:[A],results:[],workorders:{byPlatformProvider:[ticket(A,'charge',7,4),ticket(A,'withdraw',2,1,'ATPay-QR')],byPlatformDirection:[ticket(A,'charge',10,5),ticket(A,'withdraw',2,1)]}}),value=()=>a.buildModel(p).footers.workorder[0];assert.equal(value().providerCount,1);assert.equal(value().providerCountPartial,true);assert.equal(value().value,50);assert.match(value().providerCountNote,/未归属原单/);
 p.L.workorders.byPlatformDirection=[ticket(A,'charge',7,4),ticket(A,'withdraw',2,1)];assert.equal(value().providerCount,1);assert.equal(value().providerCountPartial,false);
 for(const key of ['providerConflictCount','unresolvedProviderOrderCount']){p.L.workorders.byPlatformDirection[0].uniqueCoverage[key]=1;assert.equal(value().providerCount,1);assert.equal(value().providerCountPartial,true);delete p.L.workorders.byPlatformDirection[0].uniqueCoverage[key];}
 p.L.workorders.byPlatformProvider=[];p.L.workorders.byPlatformDirection=[ticket(A,'charge',0,0),ticket(A,'withdraw',0,0)];assert.equal(value().providerCount,0);assert.equal(value().providerCountPartial,false);p.L.workorders.byPlatformDirection.pop();assert.equal(value().providerCount,null);
 p.L.workorders.byPlatformProvider=[{...ticket(A),uniqueCoverage:{status:'unavailable',complete:false}}];p.L.workorders.byPlatformDirection=[ticket(A),ticket(A,'withdraw',0,0)];assert.equal(value().providerCount,null);assert.equal(value().providerCountPartial,true);
});

const typeRate=(extra={})=>({country:'印度',scopeType:'country',provider:'ATPay',category:'UPI',sourceType:'跑分',sourceTypeProvider:'ATPay-QR',sheetName:'Synthetic original type sheet',sourceTypeCell:'B2',...extra});
test('payment matrices show original business types after provider using the actual shared source-type helper, without inventing workorder types',()=>{
 const a=api(),p=props({feeLookupRows:[typeRate()],results:[payment(A,[{...row(),channel_type:'QR'},row('withdraw',10,4)])]}),before=JSON.stringify(p),model=a.buildModel(p),html=a.render(p),tables=html.match(/<table[^>]*>.*?<\/table>/g);
 assert.equal(model.rows[0].typeItems.charge[0].country,'印度');assert.equal(model.rows[0].typeItems.charge[0].platformId,A.id);assert.equal(model.rows[0].typeItems.charge[0].source,'AR');
 for(const table of tables.slice(0,2)){assert.match(table,/<th scope="col">三方<\/th><th scope="col" class="success-provider-type">类型<\/th>/);assert.match(table,/<th scope="row">ATPay<\/th><td class="success-provider-type"><span class="provider-business-type known" title="[^"]*B2[^"]*">跑分<\/span><\/td>/);assert.match(table,/<tfoot[^>]*>.*<th scope="row">汇总成功率<\/th><td class="success-provider-type">—<\/td>/);}
 assert.doesNotMatch(tables[2],/success-provider-type|>类型</);assert.doesNotMatch(html,/>UPI<|>QR</);assert.equal(JSON.stringify(p),before);
});
test('business types keep country, canonical source-provider and original platform precedence, exposing unresolved or mixed type evidence',()=>{
 const a=api(),Alpha={...A,name:'Alpha'},Beta={...B,name:'Beta'},p=props({queryPlatforms:[Alpha,Beta],results:[payment(Alpha,[row()]),payment(Beta,[row()])],workorders:null,feeLookupRows:[typeRate({country:'巴西',sourceType:'BRAZIL ONLY'}),typeRate({sourceType:'跑分'}),typeRate({scopeType:'platform',platform:'Alpha',sourceType:'钱包'})]}),typeBody=()=>a.render(p).match(/<tbody>.*?<\/tbody>/)[0];
 assert.match(typeBody(),/provider-business-type mixed[^>]*>多种类型</);assert.match(typeBody(),/B2：钱包/);assert.match(typeBody(),/B2：跑分/);assert.doesNotMatch(typeBody(),/BRAZIL ONLY/);
 p.L.feeLookupRows=[typeRate({country:'巴西',sourceType:'BRAZIL ONLY'})];assert.match(typeBody(),/>未标注</);assert.doesNotMatch(typeBody(),/BRAZIL ONLY/);
 p.L.feeLookupRows=[typeRate({sourceTypeProvider:'OtherPay',sourceType:'WRONG SOURCE TYPE'})];assert.match(typeBody(),/>待核对</);assert.doesNotMatch(typeBody(),/WRONG SOURCE TYPE/);
 p.L.feeLookupRows=[typeRate({scopeType:'platform',platform:'Alpha',sourceType:'钱包'})];assert.match(typeBody(),/>类型未齐</);assert.doesNotMatch(typeBody(),/provider-business-type known/);
 p.L.feeLookupRows=[typeRate({sourceType:'<img src=x onerror=bad>'})];assert.match(typeBody(),/&lt;img src=x onerror=bad&gt;/);assert.doesNotMatch(typeBody(),/<img/);
 p.L.results=[payment(Alpha,[row('withdraw')])];assert.match(typeBody(),/暂无已确认活动的支付三方/,'a provider present only in the other direction does not create an empty charge row');assert.doesNotMatch(typeBody(),/success-provider-type/);
});
test('type lookup loads only for a current queried scope, then renders loading, error and actual source types without refetching restored results',()=>{
 const a=api(),p=props({feeLookupRows:null});let reads=0;p.ensureFeeLookup=()=>{reads++;p.L.feeLookupLoading=true;};let html=a.render(p);assert.equal(reads,1);assert.match(html,/>读取中…</);a.render(p);assert.equal(reads,1);
 p.L.feeLookupLoading=false;p.L.feeLookupRows=[typeRate()];assert.match(a.render(p),/>跑分</);assert.equal(reads,1);p.L.feeLookupRows=[];p.L.feeLookupError='Synthetic type read failure';html=a.render(p);assert.match(html,/>读取失败</);assert.doesNotMatch(html,/>未标注</);assert.equal(reads,1);
 for(const state of [{loading:true},{restoredPage:true},{dirty:true},{pageQueried:false}]){const q={...props({feeLookupRows:null,...state}),ensureFeeLookup:()=>reads++};a.render(q);}a.render({...props({feeLookupRows:null}),scopeMatches:false,ensureFeeLookup:()=>reads++});assert.equal(reads,1);
});
test('type column width, empty colspan and footer cell preserve the native payment and workorder matrix alignment',()=>{
 const C={...A,id:'third-native'},D={...A,id:'fourth-native'},a=api(),tables=a.render(props({queryPlatforms:[A,B,C,D],results:[],workorders:null})).match(/<table[^>]*>.*?<\/table>/g);
 for(const table of tables.slice(0,2)){assert.match(table,/min-width:504px/);assert.match(table,/<tbody><tr><td colspan="6">/);assert.equal((table.match(/class="success-provider-type"/g)||[]).length,2);}
 assert.match(tables[2],/min-width:424px/);assert.match(tables[2],/<tbody><tr><td colspan="5">/);assert.doesNotMatch(tables[2],/success-provider-type/);
});

// Reuse the established synthetic DOM fixture without registering its tests.
function harness(options={}){
 const fixture=fs.readFileSync(path.join(__dirname,'admin-live-ui.test.cjs'),'utf8'),start=fixture.indexOf('const P='),end=fixture.indexOf("test('team country",start),source=fs.readFileSync(path.join(base,'live-data.js'),'utf8');assert(start>0&&end>start);
 const moduleNames=['live-amount-bands.js','live-member-counts.js','live-submission-analysis.js','live-analysis-drilldown.js','live-matrix-custom-range.js','live-reference-layout.js','live-pages-reference.js','live-pending-snapshot.js','live-pending-analysis.js','live-empty-pages.js','live-duration-reference.js','live-payout-config.js','live-filter-controls.js','live-configuration.js','live-provider-aliases.js','live-provider-summary.js','live-provider-orders.js','live-provider-sticky.js','live-collected-data.js','live-report-data.js','live-withdraw-pages.js','live-workorder-operations.js','live-deposit-issues.js','live-success-analysis.js'];
 const sandbox={console,Intl,AbortController,Date,URL,Blob,vm,source,comparisonSource:fs.readFileSync(path.join(base,'live-comparison.js'),'utf8'),layoutSources:moduleNames.map(name=>({name,source:fs.readFileSync(path.join(base,name),'utf8')}))};
 vm.createContext(sandbox);vm.runInContext(fixture.slice(start,end).replace('hensemRoleAllowed:options.roleAllowed,','hensemRoleAccess:options.roleAccess,hensemRoleAllowed:options.roleAllowed,')+'\nglobalThis.fixture={harness,P,aggregate,renderedTables};',sandbox);
 return sandbox.fixture.harness(options);
}
async function settle(){for(let i=0;i<25;i++)await new Promise(resolve=>setImmediate(resolve));}
const owner={mode:'owner',canView:true,permissions:[]};
async function ready(options={}){const h=harness({initialPage:'success_analysis',roleAccess:owner,roleAllowed:()=>true,...options});await settle();return h;}
test('single-date production adapter uses one aggregate per platform plus existing workorders and skips unrelated reads',async()=>{
 const h=await ready({adaptive:true,ancillaryHandler:true});assert.equal(h.c.state.page,'success_analysis');assert.equal(h.L.pageQueried,false);assert.match(h.nodes.get('liveFilters').innerHTML,/id="liveSuccessDate"/);assert.doesNotMatch(h.nodes.get('liveFilters').innerHTML,/livePeriod\('week'|livePeriod\('month'|liveDate-from|liveDate-to/);
 h.c.liveSuccessDate('2026-09-22');h.L.amountBandProfiles={charge:{edges:[0,1]}};h.L.multi.provider=['ATPay'];h.L.provider='ATPay';h.setHandler(q=>{if(q.action==='providerOptions')return {providers:['ATPay']};if(q.action==='rates')return {rows:[typeRate()],total:1};if(q.action==='workorders')return {startDate:'2026-09-22',endDate:'2026-09-22',byPlatformProvider:[],byProvider:[],byDirection:{},rows:[]};return {platform:h.L.catalog[0],groups:{provider:[row()]},summary:[],rows:[]};});h.calls.length=0;await h.c.liveQuery();await settle();
 const aggregates=h.calls.filter(q=>q.action==='aggregate');assert.equal(aggregates.length,1);assert.equal(aggregates[0].view,'providers');assert.equal(aggregates[0].direction,'all');assert.equal(aggregates[0].status,'all');assert.equal(aggregates[0].startAt,'2026-09-21T18:30:00.000Z');assert.equal(aggregates[0].endAt,'2026-09-22T18:30:00.000Z');assert.equal(aggregates[0].amountBands,undefined);assert.equal(h.calls.filter(q=>q.action==='workorders').length,1);assert.equal(h.calls.filter(q=>q.action==='rates').length,1);assert(h.calls.every(q=>['providerOptions','aggregate','workorders','rates'].includes(q.action)));assert.equal(h.L.comparisonResults.length,0);assert.match(h.html(),/代收成功率/);assert.match(h.html(),/>跑分</);const loadedCalls=h.calls.length;h.c.setPage('overview');h.c.setPage('success_analysis');assert.equal(h.calls.length,loadedCalls);
});
test('new-page catalog ACL never inherits legacy or sibling analysis grants, and query/retry/export require own action',async()=>{
 for(const options of [{roleAccess:undefined,roleAllowed:()=>true},{roleAccess:{mode:'legacy',canView:true,permissions:[]},roleAllowed:()=>true},{roleAccess:{mode:'assigned',canView:true,permissions:['matrix.view','matrix.query']},roleAllowed:()=>true}]){const h=await ready(options);assert.notEqual(h.c.state.page,'success_analysis');assert(!h.c.pages.some(p=>p[0]==='success_analysis'));const n=h.calls.length;h.c.setPage('success_analysis');assert.notEqual(h.c.state.page,'success_analysis');assert.equal(h.calls.length,n);}
 const h=await ready({roleAccess:{mode:'assigned',canView:true,permissions:['success_analysis.view','success_analysis.export']}}),n=h.calls.length;assert.equal(h.c.state.page,'success_analysis');assert.match(h.html(),/未获查询权限/);await h.c.liveQuery();await h.c.liveLoad(true,true);await h.c.liveRetryFailed(true);await h.c.liveProviderWorkordersRetry();h.c.livePage(2,'workorders');h.c.liveExport();assert.equal(h.calls.length,n);assert.equal(h.blobs.length,0);assert.doesNotMatch(h.nodes.get('.title-actions').innerHTML,/liveExport/);
});
test('navigation normalizes inherited range visibly; explicit multiday query and dirty workorder retry are blocked',async()=>{
 const h=await ready({initialPage:'overview'});h.L.from='2026-09-20T00:00:00';h.L.to='2026-09-22T12:00:00';const n=h.calls.length;h.c.setPage('success_analysis');assert.equal(h.L.from,'2026-09-22T00:00:00');assert.equal(h.L.to,'2026-09-22T23:59:59');assert.match(h.L.successDateNotice,/已选择 2026-09-22 全天/);assert.equal(h.calls.length,n);h.L.to='2026-09-23T23:59:59';await h.c.liveQuery();assert.equal(h.calls.length,n);assert.match(h.L.error,/一个当地日/);assert.equal(h.L.dirty,true);await h.c.liveProviderWorkordersRetry();assert.equal(h.calls.length,n);
});
test('late workorder response after filter change cannot render old cohorts and independent retry rejects wrong day',async()=>{
 const h=await ready({ancillaryHandler:true});let resolveWork;h.setHandler(q=>q.action==='providerOptions'?{providers:['ATPay']}:q.action==='workorders'?new Promise(resolve=>resolveWork=resolve):{platform:h.L.catalog[0],groups:{provider:[row()]},summary:[],rows:[]});h.c.liveSuccessDate('2026-09-22');const pending=h.c.liveQuery();await settle();assert(resolveWork);h.c.liveSuccessDate('2026-09-21');resolveWork({startDate:'2026-09-22',endDate:'2026-09-22',byPlatformProvider:[ticket(h.L.catalog[0])],byProvider:[],byDirection:{}});await pending;assert.equal(h.L.workorders,null);assert.doesNotMatch(h.html(),/<table|40\.00%/);
 h.setHandler(q=>q.action==='providerOptions'?{providers:[]}:q.action==='workorders'?{startDate:'2026-09-20',endDate:'2026-09-20',byPlatformProvider:[],byProvider:[],byDirection:{}}:{platform:h.L.catalog[0],groups:{provider:[row()]},summary:[],rows:[]});await h.c.liveQuery();assert.equal(h.L.workorders,null);assert.match(h.L.workordersError,/日期响应不完整/);assert.match(h.html(),/重试工单/);
});
test('partial platform retry preserves known columns, rereads only failures, and tab restore does not read extra data',async()=>{
 const notices=api().render(props({loading:true,progress:'正在读取其余授权平台',error:'仍有平台尚未返回',queryPaused:true}));assert.match(notices,/正在读取其余授权平台/);assert.match(notices,/仍有平台尚未返回/);assert.match(notices,/查询已暂停/);assert.match(notices,/liveRetryFailed\(true\)/);
 const ps=[{...A,timezone:'Asia/Kolkata',currency:'INR'},{...B,timezone:'Asia/Kolkata',currency:'INR'}],h=await ready({platforms:ps,ancillaryHandler:true});let fail=true;
 h.setHandler(q=>{if(q.action==='providerOptions')return {providers:['ATPay']};if(q.action==='workorders')return {startDate:'2026-09-22',endDate:'2026-09-22',byPlatformProvider:[],byProvider:[],byDirection:{}};if(q.platformId===B.id&&fail)throw Error('Synthetic unavailable');return payment(ps.find(p=>p.id===q.platformId),[row('charge',10,q.platformId===A.id?4:3)]);});h.c.liveSuccessDate('2026-09-22');await h.c.liveQuery();assert.equal(h.L.queryFailures.length,1);assert.match(h.html(),/40\.00%/);assert.match(h.html(),/部分平台读取失败/);const n=h.calls.length;fail=false;await h.c.liveRetryFailed();const retry=h.calls.slice(n);assert.equal(retry.filter(q=>q.action==='aggregate').length,1);assert.equal(retry.find(q=>q.action==='aggregate').platformId,B.id);assert(retry.every(q=>q.action==='aggregate'));assert.equal(h.L.queryFailures.length,0);assert.match(h.html(),/30\.00%/);
 const frozen=h.L.results,n2=h.calls.length;h.c.setPage('overview');h.c.setPage('success_analysis');assert.strictEqual(h.L.results,frozen);assert.equal(h.calls.length,n2);assert.match(h.html(),/40\.00%/);assert.match(h.html(),/30\.00%/);
});
test('Today success query freezes the existing local elapsed-time cutoff and escapes source labels',async()=>{
 const h=await ready({ancillaryHandler:true});h.setHandler(q=>q.action==='providerOptions'?{providers:[]}:q.action==='workorders'?{startDate:'2026-09-23',endDate:'2026-09-23',byPlatformProvider:[],byProvider:[],byDirection:{}}:payment(h.L.catalog[0],[row('charge',10,4,'<script>bad</script>')]));h.c.livePeriod('today');assert.equal(h.L.from,'2026-09-23T00:00:00');assert.equal(h.L.to,'2026-09-23T23:59:59');h.calls.length=0;await h.c.liveQuery();const q=h.calls.find(q=>q.action==='aggregate');assert.equal(q.startAt,'2026-09-22T18:30:00.000Z');assert.equal(q.endAt,'2026-09-23T12:00:01.000Z');assert.equal(h.calls.filter(q=>q.action==='aggregate').length,1);assert.match(h.html(),/&lt;script&gt;bad&lt;\/script&gt;/);assert.doesNotMatch(h.html(),/<script/);assert.equal(h.L.to,'2026-09-23T23:59:59');
});


test('DUOLI supported updated-time success displays rates and clearly labels the basis in mixed matrices',()=>{
 const p={...A,id:'duoli-current',name:'UANG',source:'duoli',capabilities:{successTimeBasis:'order_updated_at',chargeSuccessTimeAvailable:true,withdrawSuccessTimeAvailable:true,paymentSuccessTimeAvailable:false,latencyAvailable:false}},a=api(),rows=[row('charge',20,12,'ObservedPay'),row('withdraw',10,8,'ObservedPay')],input=props({queryPlatforms:[p,A],results:[payment(p,rows,rows),payment(A,[row('charge',10,3,'ObservedPay')])],workorders:null});const model=a.buildModel(input);assert.equal(model.rows[0].charge[0].value,60);assert.equal(model.rows[0].withdraw[0].value,80);assert.equal(model.rows[0].charge[1].value,30);assert.match(a.render(input),/多利成功按成功状态＋订单更新时间统计/);assert.match(a.render(input),/>80\.00%/);
});
