const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../admin-preview/live-channel-status.js'),'utf8');
const P={id:'11111111-1111-4111-8111-111111111111',source:'kb',name:'YASH.BET',country:'印度',currency:'INR',team:'M8',timezone:'Asia/Kolkata',capabilities:{channelStatusAvailable:true}};
const O={...P,id:'22222222-2222-4222-8222-222222222222',name:'Other',source:'ar',capabilities:{}};
const A={...O,name:'VEERGAME',capabilities:{channelStatusAvailable:true,channelStatusSource:'ar_middle'}};
const NOW='2026-10-09T05:00:00.000Z';
function channel(extra={}){return {channel_id:'channel-1',channel_name:'UPI 主通道',provider:'PayOne',priority:1,weight:40,enabled:true,status_text:'开启',is_present:true,balance:'125.25',balance_currency:'USDT',min_amount:'100',max_amount:'50000',limit_currency:'INR',success_rate_10m:'44.99',success_rate_30m:'45',success_rate_1h:'0',success_rate_4h:null,success_rate_8h:'99.99',success_rate_24h:'50',success_rate_today:'75',success_rate_total:'80',observed_at:NOW,last_seen_at:NOW,...extra};}
function response(rows=[channel()],extra={}){return {version:1,queriedAt:NOW,platforms:[P],snapshots:[{platformId:P.id,direction:'charge',observedAt:NOW,receivedAt:NOW,sourceCount:rows.length,complete:true,channels:rows},{platformId:P.id,direction:'withdraw',observedAt:null,receivedAt:null,sourceCount:null,complete:false,channels:[]}],...extra};}
function middleResponse(rows=[channel({success_rate_10m:null,success_rate_15m:'68.4'})],extra={}){const data=response(rows,{platforms:[A]});data.snapshots=data.snapshots.map(s=>({...s,platformId:A.id,source:'ar_middle'}));return {...data,...extra};}
function fixture(options={}){let page='channel_status',clock=Date.parse(NOW),handler=options.handler||(()=>response());const calls=[],paints=[],timers=[];const context={Intl,console,setTimeout:(fn,ms)=>{const t={fn:()=>{t.active=false;fn();},ms,active:true};timers.push(t);return t;},clearTimeout:t=>{t.active=false;},Date:class extends Date{constructor(...args){super(...(args.length?args:[clock]))}static now(){return clock}}};context.window=context;vm.createContext(context);vm.runInContext(source,context);const L={dirty:false,pageQueried:false,country:'印度',team:'all',source:'all',direction:'all',multi:{},provider:''},selected=options.selected||[P],allowed=options.allowed||(()=>true);const mod=context.HensemLiveChannelStatus.create({L,getPage:()=>page,selected:()=>selected,catalog:options.catalog||(()=>selected),activeValues:()=>L.provider?[L.provider]:[],roleAllowed:allowed,request:async q=>{calls.push(JSON.parse(JSON.stringify(q)));return handler(q)},render:()=>paints.push(mod.render())});return {context,L,mod,calls,paints,timers,setPage:v=>page=v,setNow:v=>clock=Date.parse(v),now:()=>new Date(clock).toISOString(),setHandler:v=>handler=v};}

function exported(h,index=0){const rows=h.mod.exportRows(),i=rows.findIndex(r=>r[0]==='平台');return Object.fromEntries(Array.from(rows[i],(key,col)=>[key,rows[i+1+index][col]]));}
function platformResponse(p,rows=[channel()]){const data=p.source==='ar'?middleResponse(rows):response(rows);data.platforms=[p];data.snapshots=data.snapshots.map(x=>({...x,platformId:p.id}));return data;}
async function flush(){for(let i=0;i<8;i++)await Promise.resolve();}
function headers(html){return [...html.matchAll(/<th[^>]*scope="col"[^>]*>([^<]*)<\/th>/g)].map(m=>m[1]);}

test('queries one native platform with all directions; provider and status filters remain local and unsupported platforms are explicit',async()=>{const h=fixture({selected:[P,O]});h.L.direction='charge';h.L.provider='PayOne';await h.mod.load();assert.equal(h.calls.length,0);assert.match(h.mod.render(),/未接入通道快照：Other/);assert.equal(h.mod.canExport(),false);h.context.liveChannelSource(1);await h.mod.load();assert.deepEqual(h.calls,[{action:'channelStatus',platformIds:[P.id],direction:'all'}]);h.context.liveChannelProvider('PayOne');h.context.liveChannelStatus('on');assert.equal(h.calls.length,1);assert.equal(exported(h)['支付供应商'],'PayOne');assert.equal(h.mod.capture().provider,'PayOne');assert.match(h.mod.render(),/>提现通道<\/button>/);});
test('single-platform rows stay readable and selecting another platform replaces the table without mixing names or identities',async()=>{const second={...P,id:O.id,name:'Second KB'},h=fixture({selected:[P,second],handler:q=>platformResponse(q.platformIds[0]===P.id?P:second,[channel({channel_name:q.platformIds[0]===P.id?'UPI 主通道':'Second channel'})])});await h.mod.load();assert.match(h.mod.render(),/class="channel-name"[^>]*>UPI 主通道<\/th>/);assert.doesNotMatch(h.mod.render(),/UPI 主通道<small>YASH.BET/);h.context.liveChannelSelect(1);await h.mod.load();assert.deepEqual(h.calls.map(x=>x.platformIds),[[P.id],[second.id]]);const body=h.mod.render().match(/<tbody>([\s\S]*?)<\/tbody>/)[1];assert.match(body,/Second channel/);assert.doesNotMatch(body,/UPI 主通道/);assert.equal(exported(h)['平台'],'Second KB');});

test('source rates use black at 45, red below; missing/invalid percentages stay unknown without average',async()=>{const h=fixture();await h.mod.load();const html=h.mod.render();assert.match(html,/channel-rate channel-rate-low">44\.99%/);assert.match(html,/class="channel-rate">45\.00%/);assert.match(html,/channel-rate channel-rate-low">0\.00%/);assert.match(html,/>—<\/td>/);assert.doesNotMatch(html,/平均|汇总成功率|tfoot/);const x=fixture({handler:()=>response([channel({success_rate_10m:'101',success_rate_total:'bad'})])});await x.mod.load();assert.doesNotMatch(x.mod.render(),/101\.00%|NaN/);});
test('balance currency is independent from INR limits and zero/negative balance is retained',async()=>{const h=fixture({handler:()=>response([channel({balance:'-2.5',min_amount:'0',weight:0,priority:0})])});await h.mod.load();const html=h.mod.render();assert.match(html,/>-2\.50<\/td><td>USDT<\/td>/);assert.match(html,/最小交易金额 \(INR\)/);const row=exported(h);assert.equal(row['余额'],-2.5);assert.equal(row['余额币种'],'USDT');assert.equal(row['限额币种'],'INR');assert.equal(row['最小交易金额'],0);});
test('enabled channels precede disabled by explicit priority and unknown statuses never become disabled',async()=>{const h=fixture({handler:()=>response([channel({channel_id:'off',channel_name:'Disabled first',enabled:false,priority:0}),channel({channel_id:'on2',channel_name:'Enabled second',priority:4}),channel({channel_id:'on1',channel_name:'Enabled first',priority:1}),channel({channel_id:'unknown',channel_name:'Unknown status',enabled:null,status_text:null})])});await h.mod.load();const html=h.mod.render();assert(html.indexOf('Enabled first')<html.indexOf('Enabled second'));assert(html.indexOf('Enabled second')<html.indexOf('Disabled first'));assert.match(html,/Unknown status[\s\S]*?channel-state "[^>]*>未提供/);});
test('disappeared channel retains last seen timestamp and never becomes disabled',async()=>{const old='2026-10-09T04:30:00.000Z',h=fixture({handler:()=>response([channel({is_present:false,last_seen_at:old})])});await h.mod.load();assert.doesNotMatch(h.mod.render(),/<tbody>/);h.context.liveChannelAbsent(true);const html=h.mod.render();assert.match(html,/本次未出现/);assert.match(html,/2026\/10\/09 10:00:00/);assert.doesNotMatch(html,/channel-state (?:disabled|enabled)[^>]*>已(?:禁用|停用)</);assert.equal(exported(h)['最近出现时间'],old);assert.equal(exported(h)['更新状态'],'超过 15 分钟未更新');});
test('no snapshot differs from a verified empty snapshot and neither fabricates rates',async()=>{const h=fixture();await h.mod.load();h.context.liveChannelTab('withdraw');assert.match(h.mod.render(),/当前通道 —/);assert.match(h.mod.render(),/尚未收到快照/);const empty=fixture({handler:()=>response([],{snapshots:[...response([]).snapshots.slice(0,1),{...response([]).snapshots[1],observedAt:NOW,complete:true}]})});await empty.mod.load();assert.match(empty.mod.render(),/0 个当前通道/);assert.match(empty.mod.render(),/已采集，暂无通道/);assert.doesNotMatch(empty.mod.render(),/0\.00%/);});
test('all business fields are directly visible; long notes expand safely in their cell, never a drawer or fee edit',async()=>{const note='<script>bad</script> 4% '+ '业务说明'.repeat(30),h=fixture({handler:()=>response([channel({channel_name:'<img src=x onerror=alert(1)>',notes:note,payment_method:'UPI',channel_type:'原生通道',required_deposit_count:3,status_text:'<b>已启用</b>'})])});await h.mod.load();assert.match(h.mod.render(),/channel-notes-text collapsed/);assert.match(h.mod.render(),/原生通道/);assert.match(h.mod.render(),/UPI<\/td>/);h.context.liveChannelToggle(0);const html=h.mod.render();assert.doesNotMatch(html,/channel-notes-text collapsed|<script>|<img|<b>已启用|openDrawer|手续费/);assert.match(html,/&lt;script&gt;bad&lt;\/script&gt;/);assert.match(html,/4%/);assert.match(html,/收起备注/);h.context.liveChannelToggle(0);assert.match(h.mod.render(),/channel-notes-text collapsed/);});
test('detail/query/export permissions are checked even direct handler calls',async()=>{const view=fixture({allowed:a=>a==='view'});await view.mod.load();assert.equal(view.calls.length,0);const h=fixture({allowed:a=>['view','query'].includes(a)});await h.mod.load();h.context.liveChannelToggle(0);assert.doesNotMatch(h.mod.render(),/onclick="liveChannelToggle|channel-detail"><td/);assert.equal(h.mod.canExport(),false);assert.deepEqual(Array.from(h.mod.exportRows()),[]);});
test('scope change and navigation cancellation reject old responses and exports',async()=>{let finish;const pending=new Promise(resolve=>finish=resolve),h=fixture({handler:()=>pending}),loading=h.mod.load();h.L.provider='Other';h.L.dirty=true;h.mod.cancel();finish(response());await loading;assert.equal(h.mod.canExport(),false);assert.equal(h.mod.capture().response,null);h.setHandler(()=>response());h.L.provider='';await h.mod.load();assert.equal(h.mod.canExport(),true);h.setPage('overview');h.context.liveChannelToggle(0);assert.equal(h.mod.render(),'');assert.equal(h.mod.canExport(),false);});
test('response identity, duplicates and direction mismatches fail closed',async()=>{for(const value of [response([],{platforms:[O]}),response([channel(),channel()]),response([],{snapshots:[{platformId:O.id,direction:'charge',observedAt:NOW,channels:[]}]}),response([],{queriedAt:null})]){const h=fixture({handler:()=>value});await h.mod.load();assert.equal(h.mod.capture().status,'error');assert.equal(h.mod.canExport(),false);}});
test('bound AR and YASH platforms retain native catalog identities in separate single-platform requests and exports',async()=>{const h=fixture({selected:[P,A],handler:q=>platformResponse(q.platformIds[0]===A.id?A:P,[channel({channel_name:q.platformIds[0]===A.id?'AR charge':'YASH charge'})])});await h.mod.load();assert.deepEqual(h.calls[0],{action:'channelStatus',platformIds:[A.id],direction:'all'});assert.equal(h.mod.capture().status,'ready');assert.equal(exported(h)['平台'],A.name);assert.match(h.mod.render(),/AR charge/);h.context.liveChannelSource(1);await h.mod.load();assert.deepEqual(h.calls[1],{action:'channelStatus',platformIds:[P.id],direction:'all'});assert.equal(exported(h)['平台'],P.name);assert.doesNotMatch(h.mod.render().match(/<tbody>([\s\S]*?)<\/tbody>/)[1],/AR charge/);});
test('matching display names never authorize a changed or missing response source',async()=>{
 const ar={...O,name:P.name,capabilities:{channelStatusAvailable:true}};for(const returned of [{...ar,source:'kb'},{...ar,source:undefined}]){const h=fixture({selected:[ar],handler:()=>response([],{platforms:[returned],snapshots:[]})});await h.mod.load();assert.equal(h.mod.capture().status,'error');assert.match(h.mod.render(),/平台范围不匹配/);assert.equal(h.mod.canExport(),false);}
});
test('AR source fifteen-minute rates never populate a ten-minute window and unknown rates remain blank',async()=>{const h=fixture({selected:[A],handler:()=>middleResponse([channel({success_rate_10m:'80',success_rate_15m:'44.8',success_rate_30m:'68.4',success_rate_24h:null})])});await h.mod.load();const html=h.mod.render(),list=headers(html),row=exported(h);assert.equal(h.mod.capture().status,'ready');assert(list.includes('近15分钟成功率'));assert(!list.includes('近10分钟成功率'));assert.match(html,/channel-rate channel-rate-low">44\.80%/);assert.doesNotMatch(html,/80\.00%/);assert.equal(row['近10分钟成功率'],undefined);assert.equal(row['近15分钟成功率'],'44.80%');assert.equal(row['近30分钟成功率'],'68.40%');assert.equal(row['近24小时成功率'],'—');assert.equal(h.mod.exportRows()[3].length,h.mod.exportRows()[4].length);const invalid=fixture({selected:[A],handler:()=>middleResponse([channel({success_rate_15m:'101'})])});await invalid.mod.load();assert.equal(exported(invalid)['近15分钟成功率'],'—');assert.doesNotMatch(invalid.mod.render(),/101\.00%|平均|汇总成功率/);});
test('source switching keeps YASH and AR windows separate in each table and export',async()=>{const h=fixture({selected:[P,A],handler:q=>q.platformIds[0]===A.id?middleResponse([channel({channel_name:'AR channel',success_rate_10m:'80',success_rate_15m:'68.4'})]):response([channel({success_rate_15m:'99'})])});await h.mod.load();assert.equal(h.mod.capture().status,'ready');const ar=exported(h);assert.equal(ar['平台'],A.name);assert.equal(ar['近10分钟成功率'],undefined);assert.equal(ar['近15分钟成功率'],'68.40%');h.context.liveChannelSource(1);await h.mod.load();const yash=exported(h);assert.equal(yash['平台'],P.name);assert.equal(yash['近10分钟成功率'],'44.99%');assert.equal(yash['近15分钟成功率'],undefined);assert.doesNotMatch(h.mod.render(),/99\.00%|平均|tfoot/);assert.deepEqual(h.calls.map(q=>q.platformIds),[[A.id],[P.id]]);});
test('AR binding requires the middle source marker and it cannot be attached to YASH',async()=>{
 const missing=middleResponse();missing.snapshots=missing.snapshots.map(s=>({...s,source:undefined}));for(const [selected,data] of [[[A],missing],[[P],response([channel()],{snapshots:response().snapshots.map(s=>({...s,source:'ar_middle'}))})]]){const h=fixture({selected,handler:()=>data});await h.mod.load();assert.equal(h.mod.capture().status,'error');assert.equal(h.mod.canExport(),false);assert.match(h.mod.render(),/来源不匹配/);}
});
test('unknown balance currency stays explicit and never inherits the platform INR currency',async()=>{const h=fixture({handler:()=>response([channel({balance:'100',balance_currency:null})])});await h.mod.load();assert.match(h.mod.render(),/100\.00<\/td><td>未提供<\/td>/);assert.equal(exported(h)['余额币种'],'未提供');});

test('five-minute automatic reads preserve the source fifteen-minute deadline and all timers cancel on navigation',async()=>{
 const h=fixture({handler:()=>response([channel()],{queriedAt:h.now()})});await h.mod.load();const auto=h.timers.find(t=>t.active&&t.ms===300000);assert(auto);assert.equal(h.timers.findLast(t=>t.active).ms,900001);
 h.setNow('2026-10-09T05:05:00Z');auto.fn();await flush();assert.equal(h.calls.length,2);
 for(const time of ['2026-10-09T05:10:00Z','2026-10-09T05:15:00Z']){h.setNow(time);assert.match(h.mod.render(),/>已更新/);assert.doesNotMatch(h.mod.render(),/超过 15 分钟未更新/);await flush();assert.equal(exported(h)['更新状态'],'已更新');}
 assert.equal(h.calls.length,4);assert(h.calls.every(q=>q.platformIds.length===1&&q.platformIds[0]===P.id&&q.direction==='all'));
 const freshness=h.timers.findLast(t=>t.active);h.setNow('2026-10-09T05:15:00.001Z');freshness.fn();await flush();assert.match(h.paints.at(-1),/超过 15 分钟未更新/);assert.equal(exported(h)['更新状态'],'超过 15 分钟未更新');assert.equal(h.calls.length,4);
 const active=h.timers.filter(t=>t.active);assert(active.length);h.setPage('overview');h.mod.cancel();assert(active.every(t=>!t.active));
});

test('snapshot restore keeps its original source deadline and resumes the five-minute read schedule',async()=>{const h=fixture({handler:()=>response([channel()],{queriedAt:h.now()})});await h.mod.load();const saved=h.mod.capture();h.mod.clear();h.setNow('2026-10-09T05:04:00Z');h.mod.restore(saved);assert.match(h.mod.render(),/>已更新/);await flush();assert.equal(h.calls.length,1);assert(h.timers.some(t=>t.active&&t.ms===60000));assert.equal(h.timers.findLast(t=>t.active).ms,660001);h.setNow('2026-10-09T05:16:00Z');assert.match(h.mod.render(),/超过 15 分钟未更新/);await flush();assert.equal(h.calls.length,2);assert.equal(exported(h)['更新状态'],'超过 15 分钟未更新');assert.equal(exported(h)['最近出现时间'],NOW);assert.match(h.mod.exportRows()[0][1],/不合并平均/);});

const prefix=fs.readFileSync(path.join(__dirname,'admin-navigation-performance.test.cjs'),'utf8').split(/\ntest\(/)[0].replace('vm.runInContext(source,context',"vm.runInContext(fs.readFileSync(path.join(__dirname,'../admin-preview/live-channel-status.js'),'utf8'),context);vm.runInContext(source,context");
const {harness,settle,deferred}=new Function('require','__dirname',prefix+';return {harness,settle,deferred};')(require,__dirname);
const owner={mode:'owner',canView:true,permissions:[]};
function integrated(options={}){return harness({page:'channel_status',roleAccess:owner,roleAllowed:()=>true,...options,handler:options.handler||((q)=>q.action==='catalog'?{platforms:[P]}:q.action==='channelStatus'?response():{})});}

test('production route navigates under operations, automatically reads one platform, and never reads orders or fees',async()=>{const h=integrated();await settle();assert.equal(h.c.state.page,'channel_status');const keys=h.c.navGroupsV3.find(g=>g[0]==='merchant')[3];assert.equal(keys.indexOf('channel_status'),keys.indexOf('daily_comparison')+1);assert.equal(h.c.pages.find(p=>p[0]==='channel_status')[2],'平台通道调整');assert(!h.c.navGroupsV3.find(g=>g[3].includes('providers'))[3].includes('channel_status'));assert.deepEqual(h.calls.map(q=>q.action),['catalog','channelStatus']);assert.deepEqual(h.calls[1],{action:'channelStatus',platformIds:[P.id],direction:'all'});assert.equal(h.nodes.get('liveFilters').innerHTML,'');assert.match(h.html(),/channel-local-filters/);assert.match(h.html(),/支付三方|通道状态/);assert.match(h.html(),/充值通道/);assert.match(h.html(),/提现通道/);assert.doesNotMatch(h.html(),/快捷日期|datetime-local|liveDateTrigger|手续费|订单成功金额/);await h.c.liveQuery();assert.deepEqual(h.calls.map(q=>q.action),['catalog','channelStatus','channelStatus']);});
test('live route respects explicit role query/export and prevents legacy page access',async()=>{const legacy=integrated({roleAccess:{mode:'legacy',canView:true,permissions:[]}});await settle();assert.notEqual(legacy.c.state.page,'channel_status');assert(!legacy.c.pages.some(p=>p[0]==='channel_status'));const h=integrated({roleAccess:{mode:'assigned',canView:true,permissions:['channel_status.view','channel_status.export']}});await settle();await h.c.liveQuery();h.c.liveExport();assert.deepEqual(h.calls.map(q=>q.action),['catalog']);assert.equal(h.blobs.length,0);assert.match(h.html(),/未获查询权限/);});
test('manual channel export retains source basis and times; local filters avoid requests and dirty scopes forbid export',async()=>{const h=integrated();await settle();h.c.liveExport();assert.equal(h.blobs.length,1);const csv=await h.blobs[0].text();assert.match(csv,/源站通道快照/);assert.match(csv,/USDT/);assert.match(csv,/2026-10-09T05:00:00/);h.c.liveChannelProvider('PayOne');assert.equal(h.L.dirty,false);h.c.liveExport();assert.equal(h.blobs.length,2);h.L.dirty=true;h.c.liveExport();assert.equal(h.blobs.length,2);assert.equal(h.calls.filter(q=>q.action==='providerOptions').length,0);assert.equal(h.calls.filter(q=>q.action==='channelStatus').length,1);});
test('channel tab restores fresh cached snapshots; reset and close discard them and automatically read on reentry',async()=>{const h=integrated();await settle();assert.equal(h.calls.filter(q=>q.action==='channelStatus').length,1);h.c.setPage('overview');h.c.setPage('channel_status');await settle();assert.match(h.html(),/UPI 主通道/);assert.equal(h.calls.filter(q=>q.action==='channelStatus').length,1);h.c.liveReset();await settle();assert.match(h.html(),/UPI 主通道/);assert.equal(h.calls.filter(q=>q.action==='channelStatus').length,2);h.c.liveClosePage('channel_status');h.c.setPage('channel_status');await settle();assert.match(h.html(),/UPI 主通道/);assert.equal(h.calls.filter(q=>q.action==='channelStatus').length,3);assert(h.calls.filter(q=>q.action==='channelStatus').every(q=>q.platformIds.length===1&&q.platformIds[0]===P.id&&q.direction==='all'));});
test('pending channel read cannot repaint the destination; returning starts a new authorized read',async()=>{const wait=deferred(),h=integrated({handler:q=>q.action==='catalog'?{platforms:[P]}:wait.promise});await settle();assert.equal(h.calls.filter(q=>q.action==='channelStatus').length,1);h.c.setPage('overview');const before=h.html();h.c.liveExport();assert.equal(h.blobs.length,0);wait.resolve(response());await settle();assert.equal(h.html(),before);h.c.setPage('channel_status');await settle();assert.match(h.html(),/UPI 主通道/);assert.equal(h.calls.filter(q=>q.action==='channelStatus').length,2);h.c.liveExport();assert.equal(h.blobs.length,1);});
test('bundle sources include new page styles and sticky readable table has no cramped global overrides',()=>{const build=fs.readFileSync(path.join(__dirname,'../admin-preview/build-restoration.py'),'utf8'),css=fs.readFileSync(path.join(__dirname,'../admin-preview/live-channel-status.css'),'utf8');assert.match(build,/'live-channel-status.js'/);assert.match(build,/'live-channel-status.css'/);assert.match(css,/\.channel-table thead th\{position:sticky;top:0/);assert.match(css,/\.channel-table \.channel-name,\.channel-table \.channel-provider\{position:sticky/);assert.match(css,/\.channel-table \.channel-provider\{left:180px/);assert.match(css,/padding:10px 9px;line-height:1\.45/);assert.match(css,/\.channel-rate\{color:#161616\}/);});

test('platform channel page follows original deposit/withdraw column order and displays all direction-specific fields',async()=>{
 const data=response([channel({channel_type:'充值通道',payment_method:'UPI',required_deposit_count:4})]);data.snapshots[1]={platformId:P.id,direction:'withdraw',observedAt:NOW,receivedAt:NOW,sourceCount:1,complete:true,channels:[channel({channel_id:'withdraw-only',channel_type:'提现通道',payment_method:null,balance_threshold:'1000',balance_threshold_currency:'INR',status_text:'可用'})]};
 const h=fixture({handler:()=>data});await h.mod.load();
 assert.deepEqual(headers(h.mod.render()),['通道名称','支付供应商','通道类型','支付方式','最小交易金额 (INR)','最大交易金额 (INR)','近10分钟成功率','近30分钟成功率','近1小时成功率','近4小时成功率','近8小时成功率','近24小时成功率','今日成功率','总成功率','余额','余额币种','代收次数要求','优先级','权重','状态','备注']);
 assert.equal((h.mod.render().match(/<table /g)||[]).length,1);assert.match(h.mod.render(),/UPI<\/td>/);assert.doesNotMatch(h.mod.render(),/余额阈值<\/th>/);
 h.context.liveChannelTab('withdraw');const html=h.mod.render();assert.equal(h.calls.length,1);assert.deepEqual(headers(html),['通道名称','支付供应商','通道类型','最小交易金额 (INR)','最大交易金额 (INR)','近10分钟成功率','近30分钟成功率','近1小时成功率','近4小时成功率','近8小时成功率','近24小时成功率','今日成功率','总成功率','余额','余额币种','余额阈值','阈值币种','优先级','权重','状态','备注']);assert.match(html,/>可用<\/span>/);assert.match(html,/>1,000\.00<\/td><td>INR/);assert.doesNotMatch(html,/代收次数要求|支付方式|channel-observed/);assert.match(html,/Asia\/Kolkata/);
 const row=exported(h);assert.equal(row['通道类型'],'提现通道');assert.equal(row['余额阈值'],1000);assert.equal(row['阈值币种'],'INR');assert.equal(row['源站状态'],'可用');assert.equal(row['快照采集时间'],NOW);assert.equal(row['服务器接收时间'],NOW);assert.equal(h.mod.exportRows()[3].length,h.mod.exportRows()[4].length);
});
test('original source position outranks status and priority, with legacy fallback when position unavailable',async()=>{const h=fixture({handler:()=>response([channel({channel_id:'a',channel_name:'Source second',source_position:2,priority:1}),channel({channel_id:'b',channel_name:'Source first',source_position:1,enabled:false,status_text:'已禁用',priority:99})])});await h.mod.load();const html=h.mod.render();assert(html.indexOf('Source first')<html.indexOf('Source second'));assert.match(html,/源页顺序/);assert.match(html,/>已禁用<\/span>/);assert.equal(exported(h)['源页顺序'],1);});
test('version 2 drafts retain local tabs/history and version 1 single-platform snapshots migrate without refetch',async()=>{const h=fixture();await h.mod.load();h.context.liveChannelTab('withdraw');h.context.liveChannelAbsent(true);const saved=h.mod.capture();assert.equal(saved.version,2);h.mod.clear();h.mod.restore(saved);assert.match(h.mod.render(),/aria-selected="true"[^>]*liveChannelTab\('withdraw'\)/);assert.equal(h.mod.capture().includeAbsent,true);const legacy={version:1,scope:{platforms:[P]},status:'ready',response:response(),receivedAt:Date.parse(NOW),error:''};h.mod.restore(legacy);assert.match(h.mod.render(),/aria-selected="true"[^>]*liveChannelTab\('charge'\)/);assert.equal(h.mod.capture().includeAbsent,false);assert.equal(h.mod.capture().version,2);assert.equal(exported(h)['平台'],P.name);assert.equal(h.calls.length,1);await flush();assert.equal(h.calls.length,1);});
test('unsupported platform directory stays in the sidebar and only the selected platform gets an explicit notice',async()=>{const extras=Array.from({length:8},(_,i)=>({...O,id:'other-'+i,name:'Unavailable '+i})),h=fixture({selected:[P,...extras]});await h.mod.load();const html=h.mod.render(),article=html.match(/<article>([\s\S]*?)<\/article>/)[1];assert.equal(h.calls.length,0);assert.match(html,/共 8 个/);for(let i=0;i<8;i++)assert.match(html,new RegExp('<strong>Unavailable '+i+'</strong>'));assert.match(article,/未接入通道快照：Unavailable 0/);assert.doesNotMatch(article,/Unavailable [1-7]/);assert.equal(h.mod.canExport(),false);h.context.liveChannelSource(1);await h.mod.load();assert.match(h.mod.render(),/YASH.BET · 最新采集/);assert.equal(h.calls.length,1);assert.equal(exported(h)['平台'],P.name);});
test('mixed or missing limit currency never labels every row INR',async()=>{const h=fixture({handler:()=>response([channel(),channel({channel_id:'usd',limit_currency:'USDT'}),channel({channel_id:'unknown',limit_currency:null})])});await h.mod.load();const list=headers(h.mod.render());assert(list.includes('限额币种'));assert(list.includes('最小交易金额'));assert(!list.includes('最小交易金额 (INR)'));assert.equal(h.mod.exportRows()[3].length,h.mod.exportRows()[4].length);});

test('export current table follows selected tab and history toggle without mixing hidden channels',async()=>{const old=channel({channel_id:'old',is_present:false}),data=response([channel(),old]);data.snapshots[1]={...data.snapshots[0],direction:'withdraw',channels:[channel({channel_id:'out',status_text:'禁用'})]};const h=fixture({handler:()=>data});await h.mod.load();assert.equal(h.mod.exportRows().length,5);assert.equal(exported(h)['方向'],'充值');assert.match(h.mod.exportRows()[2][1],/仅当前通道/);h.context.liveChannelAbsent(true);assert.equal(h.mod.exportRows().length,6);assert.equal(exported(h,1)['通道 ID'],'old');h.context.liveChannelTab('withdraw');assert.equal(h.mod.exportRows().length,5);assert.equal(exported(h)['方向'],'提现');assert.equal(exported(h)['通道 ID'],'out');});
