// Source amounts stay separate; only synthetic PostgreSQL rows are used.
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{createRequire}=require('node:module');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
let db,f,migration;
const scalar=async(q,args=[])=>Object.values((await db.query(q,args)).rows[0])[0];
async function rollback(fn){await db.exec('begin');try{await fn()}finally{await db.exec('rollback')}}
before(async()=>{const filename=path.join(__dirname,'fee-effective-versions.test.cjs'),req=createRequire(filename);let setup;
 const ctx={require:n=>n==='node:test'?{test(){},before:fn=>setup=fn,after(){}}:req(n),__dirname,process,console,structuredClone};vm.createContext(ctx);vm.runInContext(fs.readFileSync(filename,'utf8')+'\nglobalThis.fixture={get db(){return db},get f(){return f}};',ctx,{filename});await setup();db=ctx.fixture.db;f=ctx.fixture.f;
 const name=fs.readdirSync(path.join(root,'supabase/migrations')).find(n=>n.endsWith('_usdt_dual_amount_details.sql'));assert(name);migration=read('supabase/migrations/'+name);await db.exec(migration);
});
after(()=>db?.close());
async function row(){await f.add('ar','charge','DUAL-MONEY',1000,{created:'2026-09-19 02:00',success:'2026-09-19 04:00'});await db.exec("update ar_collected_orders set raw_channel='USDT(TRC20)-3',amount=null,amount_text='金额： 1000\\n兑换比例： 80\\nUSDT： 12.5' where order_no='DUAL-MONEY'");return (await f.call(f.request('ar',{action:'details',direction:'charge'}))).rows.find(r=>r.order_number==='DUAL-MONEY');}
test('AR source dual text yields fiat and native U amount, preserving aggregate amount and identity',async()=>rollback(async()=>{const r=await row();assert.equal(Number(r.amount),1000);assert.equal(r.member_currency,'INR');assert.equal(r.settlement_currency,'USDT');assert.equal(r.settlement_amount,'12.5');assert.equal(r.exchange_rate,'80');assert.equal(r.money_evidence,'source_dual_amount_text');assert.equal(r.raw_provider,'USDT(TRC20)-3');assert(!Object.hasOwn(r,'amount_text'));}));
test('wrong country/platform/native row ID never borrows monetary fields',async()=>rollback(async()=>{const r=await row(),base={rows:[{...r,settlement_currency:undefined,settlement_amount:undefined,exchange_rate:undefined,member_currency:undefined,money_evidence:undefined}]};
 for(const [country,platform,change] of [['VN','Synthetic',{}],['IN','Other',{}],['IN','AR-BANDS',{id:'other'}],['IN','AR-BANDS',{direction:'withdraw'}]]){const x={rows:[{...base.rows[0],...change}]};const got=await scalar('select private.dashboard_admin_ar_order_money($1,$2,$3)',[JSON.stringify(x),country,platform]);assert(!Object.hasOwn(got.rows[0],'settlement_amount'));assert.equal(got.rows.length,1);}
}));
test('missing, corrupt, oversized or changed source amounts stay missing without guessing U values',async()=>rollback(async()=>{const r=await row();const base={...r};for(const k of ['settlement_currency','settlement_amount','exchange_rate','member_currency','money_evidence'])delete base[k];
 for(const text of ['', '金额：1000 USDT：12.5','金额：1000 兑换比例：0 USDT：12.5','金额：999 兑换比例：80 USDT：12.5','金额：1000 兑换比例：80 USDT：NaN',' '.repeat(251)+'金额：1000 兑换比例：80 USDT：12.5']){await db.query("update ar_collected_orders set amount_text=$1 where order_no='DUAL-MONEY'",[text]);const got=await scalar("select private.dashboard_admin_ar_order_money($1,'IN','AR-BANDS')",[JSON.stringify({rows:[base]})]);assert(!Object.hasOwn(got.rows[0],'settlement_amount'),text);assert.equal(Number(got.rows[0].amount),1000);}
}));
test('private money reader has no direct API grants and query metadata remains unchanged',async()=>rollback(async()=>{assert.equal(await scalar("select proacl::text from pg_proc where oid='private.dashboard_admin_ar_order_money(jsonb,text,text)'::regprocedure"),'{postgres=X/postgres}');for(const role of ['anon','authenticated','service_role']){await db.exec('savepoint denied;set role '+role);await assert.rejects(scalar("select private.dashboard_admin_ar_order_money('{\"rows\":[]}', 'IN', 'Synthetic')"),/permission denied/);await db.exec('rollback to denied');}assert.equal(await scalar("select proacl::text from pg_proc where oid='private.dashboard_admin_live_query_raw(jsonb)'::regprocedure"),'{postgres=X/postgres}');assert.equal(await scalar("select proconfig from pg_proc where oid='private.dashboard_admin_live_query_raw(jsonb)'::regprocedure").then(x=>x.join(',')),'search_path="",jit=off');}));
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function money(){const c={Intl};c.window=c;vm.createContext(c);vm.runInContext(read('admin-preview/live-provider-orders.js'),c);return c.HensemProviderOrders;}
test('all detail entry points show both denominations without provider-name inference or amount conversion',()=>{const h=money(),r={amount:'1000',currency:'INR',member_currency:'INR',settlement_currency:'USDT',settlement_amount:'12.50001234',exchange_rate:'80'};const tools={E,N:v=>String(v??'—')};assert.match(h.moneyCell(r,tools),/1000 INR.*12\.50001234 USDT/);assert.equal(h.moneyRows(r,tools)[0][0],'法币金额');assert.equal(h.moneyRows(r,tools)[1][1],'12.50001234 USDT');assert.deepEqual(JSON.parse(JSON.stringify(r)),r);for(const n of ['live-data.js','live-analysis-drilldown.js'])assert.match(read('admin-preview/'+n),/moneyRows\(r,\{E,N\}\)/);});
test('unknown or invalid settlement currency cannot be relabelled as USDT',()=>{const h=money(),tools={E,N:v=>String(v??'—')};assert.doesNotMatch(h.moneyCell({amount:'100',currency:'VND',provider:'TronPay(USDT)'},tools),/USDT/);for(const amount of [null,'',false,'NaN','Infinity',-1])assert.equal(h.moneyRows({amount:100,currency:'INR',settlement_currency:'USDT',settlement_amount:amount},tools)[1][1],'—');assert.doesNotMatch(h.moneyCell({amount:100,settlement_currency:'<svg onload=x>',settlement_amount:1},tools),/<svg/);});
