// Indexed existence probes and collector receipts; all data synthetic, no network.
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');let db;
const root=path.join(__dirname,'..'),sql=fs.readFileSync(path.join(root,'supabase/admin-live-intake-coverage.sql'),'utf8'),fixture=fs.readFileSync(path.join(__dirname,'admin-sync-health.test.cjs'),'utf8').match(/await db\.exec\(`([\s\S]*?)`\);await feed/)[1].replaceAll('${id}','10000000-0000-4000-8000-000000000003');
const call=async request=>(await db.query('select public.dashboard_admin_live_intake_coverage($1::jsonb) data',[JSON.stringify(request)])).rows[0].data;
const catalog=async()=>(await call({operation:'catalog'})).feeds;
const check=async(name,dataset='orders',direction='charge',startAt='2026-09-01',endAt='2026-09-25')=>{const f=(await catalog()).find(f=>f.name===name&&f.dataset===dataset&&f.direction===direction);assert(f,name);return (await call({operation:'rows',feedIds:[f.id],startAt,endAt})).rows};
before(async()=>{db=new PGlite();await db.exec(fixture);await db.exec(`
 alter table ar_collected_orders add raw_channel text,add channel_type text;
 alter table collection_success_daily add snapshot jsonb,add snapshot_id uuid;
 alter table lg_orders add paid_at timestamptz;
 alter table lg_sync_runs add source_total bigint;update lg_sync_runs set source_total=expected_count;
 alter table game66_sync_runs add rows_upserted integer;alter table game66_sync_runs add rows_skipped integer;alter table game66_sync_runs add error_count integer;update game66_sync_runs set rows_upserted=rows_fetched,rows_skipped=0,error_count=0;
 alter table auto_withdraw_daily add source_sheet text;
 insert into fixture_feeds values('{"dataset":"volume","system":"REPORT","name":"SHEET","country":"印度","rawCountry":"印度","rawPlatform":"SHEET","directions":["charge"],"firstDate":"2026-09-23","lastDate":"2026-09-25","provenance":{"kind":"google_sheets"}}');
 insert into fixture_feeds values('{"dataset":"lg_orders","system":"LG","name":"LG","country":"印度","rawCountry":"印度","rawPlatform":"LG","directions":["charge"],"provenance":{"kind":"direct"}}');
 `);await db.exec(sql.replace(/do \$baseline\$[\s\S]*?end;\$baseline\$;/,'-- Synthetic baseline').replace('v_asof timestamptz:=statement_timestamp()','v_asof timestamptz:=\'2026-09-26T01:00Z\''));});
after(async()=>db?.close());
test('catalog uses authorized stable feed identities, distinct source/direction and per-country yesterday',async()=>{const a=await call({operation:'catalog'}),b=await catalog();assert(a.complete);assert.equal(a.defaultStart,'2026-09-01');assert.equal(a.maxDays,93);assert.equal(new Set(b.map(f=>f.id)).size,b.length);assert(b.some(f=>f.name==='NEVER-CONFIG'));assert.equal(b.find(f=>f.name==='NEVER-CONFIG').defaultEnd,'2026-09-24');assert.equal(b.find(f=>f.name==='AR').defaultEnd,'2026-09-25');assert.deepEqual(a.feeds.map(f=>f.id),b.map(f=>f.id));});
test('every selected day is checked; first received day never hides earlier gaps',async()=>{const rows=await check('SHEET','volume');assert.equal(rows.length,25);assert.equal(rows[0].date,'2026-09-01');assert(rows.slice(0,22).every(r=>r.expected&&r.status==='not_received'));assert.equal(rows.find(r=>r.date==='2026-09-23').status,'received');assert.equal(rows.find(r=>r.date==='2026-09-24').status,'not_received');assert(rows.every(r=>!r.complete&&!r.zeroConfirmed));});
test('only verified launch exempts earlier days; current-only configuration is unverified',async()=>{const rows=await check('NEW');assert.equal(rows.length,25);assert(rows.slice(0,24).every(r=>!r.expected&&r.status==='not_expected'));assert.equal(rows[24].status,'received');await db.exec(`insert into fixture_feeds values('{"dataset":"game66_config","system":"GAME66","name":"CURRENT","country":"香港","rawCountry":"香港","rawPlatform":"CURRENT","directions":[],"provenance":{"kind":"direct"}}')`);const current=await check('CURRENT','game66_config','config');assert.equal(current.length,1);assert.equal(current[0].date,null);assert.equal(current[0].status,'unverified');assert.equal(current[0].evidence,'configuration_history_unavailable');});
test('successful cross-day records cannot fill a missing creation day',async()=>{const rows=await check('AR');const r=rows.find(r=>r.date==='2026-09-24');assert.equal(r.status,'not_received');assert.equal(r.received,false);assert.equal(r.evidence,'only_success_day_records_received');});
test('complete zero requires verified full collector receipt; presence alone is insufficient',async()=>{const lg=await check('LG','lg_orders'),zero=lg.at(-1);assert.equal(zero.status,'zero_complete');assert(zero.complete&&zero.zeroConfirmed&&zero.received);assert.equal(lg[0].status,'not_started');const game=(await check('GAME')).at(-1);assert.equal(game.status,'unverified');assert(!game.complete&&!game.zeroConfirmed&&!game.received);assert.equal(game.evidence,'source_counts_not_verified');const failed=(await check('GAME','orders','withdraw')).at(-1);assert.equal(failed.status,'failed');assert(failed.received);assert(!failed.complete&&!failed.zeroConfirmed);});
test('published counts mismatch, collecting and zero conflicting with rows stay incomplete',async()=>{await db.exec(`insert into lg_sync_runs(country_code,platform,stat_date,order_kind,status,sync_mode,expected_count,fetched_count,source_total,published_at,observed_at) values('印度','LG','2026-09-24','recharge','published','full',2,1,2,now(),now()),('印度','LG','2026-09-23','recharge','collecting','full',2,2,2,null,now());insert into lg_orders values('印度','LG','recharge','2026-09-24T20:00Z',now(),null);`);const rows=await check('LG','lg_orders');assert.equal(rows.find(r=>r.date==='2026-09-24').status,'partial');assert.equal(rows.find(r=>r.date==='2026-09-23').status,'pending');assert.equal(rows.at(-1).status,'partial');assert(!rows.at(-1).zeroConfirmed);});
test('fresh authorization, batch bounds and private-helper ACLs fail closed',async()=>{const f=(await catalog()).find(f=>f.name==='GAME');await db.query("select set_config('test.scope',$1,false)",['{"countries":["印度"]}']);try{assert(!(await catalog()).some(f=>f.name==='GAME'));await assert.rejects(call({operation:'rows',feedIds:[f.id],startAt:'2026-09-01',endAt:'2026-09-25'}),/coverage_feed_denied/);}finally{await db.query("select set_config('test.scope',$1,false)",['{"mode":"all"}']);}for(const patch of [{feedIds:[]},{feedIds:Array(9).fill(f.id)},{feedIds:[f.id,f.id]},{feedIds:['x']},{endAt:'2027-01-01'},{startAt:'2026-02-30'},{asOf:'2030-01-01'}])await assert.rejects(call({operation:'rows',feedIds:[f.id],startAt:'2026-09-01',endAt:'2026-09-25',...patch}));const acl=(await db.query("select has_function_privilege('anon','public.dashboard_admin_live_intake_coverage(jsonb)','execute') a,has_function_privilege('authenticated','private.dashboard_admin_live_intake_feeds(timestamptz)','execute') b,has_function_privilege('authenticated','public.dashboard_admin_live_intake_coverage(jsonb)','execute') c")).rows[0];assert.deepEqual(acl,{a:false,b:false,c:true});});

test('configuration targets never inherit another source team or display name',async()=>{await db.exec(`insert into fixture_platforms values('10000000-0000-4000-8000-000000000099','WRONG-NATIVE-NAME','WRONG-TEAM','印度','IN','ar','Asia/Kolkata','INR','PANDA-SHARED');insert into panda_config_targets values('IN','印度','PANDA-SHARED','Asia/Kolkata','PANDA')`);try{const f=(await catalog()).find(f=>f.dataset==='panda_config'&&f.rawPlatform==='PANDA-SHARED');assert(f);assert.equal(f.name,'PANDA-SHARED');assert.notEqual(f.team,'WRONG-TEAM');}finally{await db.exec("delete from panda_config_targets where platform='PANDA-SHARED';delete from fixture_platforms where source_name='PANDA-SHARED'")}});
test('a newer collecting retry cannot be disguised by an older complete published run',async()=>{await db.exec(`insert into lg_sync_runs(country_code,platform,stat_date,order_kind,status,sync_mode,expected_count,fetched_count,source_total,published_at,observed_at) values('印度','LG','2026-09-22','recharge','published','full',1,1,1,'2026-09-23Z','2026-09-23Z'),('印度','LG','2026-09-22','recharge','collecting','full',2,2,2,null,'2026-09-24Z')`);const r=(await check('LG','lg_orders')).find(r=>r.date==='2026-09-22');assert.equal(r.status,'pending');assert(!r.complete);});

test('published nonzero receipt still requires corresponding official order data',async()=>{await db.exec(`insert into lg_sync_runs(country_code,platform,stat_date,order_kind,status,sync_mode,expected_count,fetched_count,source_total,published_at,observed_at) values('印度','LG','2026-09-21','recharge','published','full',2,2,2,'2026-09-22Z','2026-09-22Z')`);let r=(await check('LG','lg_orders')).find(r=>r.date==='2026-09-21');assert.equal(r.status,'partial');assert.equal(r.evidence,'published_records_not_received');assert(!r.complete&&!r.received);await db.exec(`insert into lg_orders values('印度','LG','recharge','2026-09-20T20:00Z','2026-09-22Z',null)`);r=(await check('LG','lg_orders')).find(r=>r.date==='2026-09-21');assert.equal(r.status,'complete');assert(r.complete&&r.received&&!r.zeroConfirmed);});
test('an unfinished partial-day task is visible without inventing a complete day',async()=>{await db.exec(`insert into game66_sync_runs(platform_id,data_type,window_start,window_end,status,started_at,rows_fetched) values('10000000-0000-4000-8000-000000000003','charge','2026-09-23T19:00Z','2026-09-23T20:00Z','running','2026-09-24Z',0)`);const r=(await check('GAME')).find(r=>r.date==='2026-09-24');assert.equal(r.status,'pending');assert(!r.complete&&!r.zeroConfirmed);});
