// Synthetic fixtures only. Verify manual query boundaries and independent data sources.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../admin-preview/live-workorder-operations.js'),'utf8');
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const record={platform:'SYNTHETIC',country:'印度',currency:'INR',workorderId:'ID-1',workorderNo:'WORK-1',orderNo:'RC20260901SYNTHETIC',amount:'1234567890123456.12345678',statusCode:4,issueKind:'deposit',attachmentTypes:['pdf'],fieldGaps:['payment_order_no_missing'],provider:'<script>bad</script>'};
function harness(){let active='workorders',html='',drawer='',renders=0,response={sourceStatus:'ready',rows:[record],total:1,platforms:['SYNTHETIC']};const calls=[],root={closeDrawer:()=>{drawer=''}},L={catalogReady:true,country:'印度',catalog:[{name:'SYNTHETIC',country:'印度',timezone:'Asia/Kolkata'}],from:'2026-09-01T00:00:00',to:'2026-09-27T23:59:59'};vm.runInNewContext(source,{window:root});let module;
 module=root.HensemLiveWorkorderOperations.create({L,E:escape,C:v=>String(v??0),formatTime:v=>v,box:(title,body)=>'<h2>'+title+'</h2>'+body,table:(headers,rows)=>'<table>'+headers.join('|')+rows.map(r=>r.join('|')).join('\n')+'</table>',request:async q=>{calls.push(q);return typeof response==='function'?response(q):response},render:()=>{renders++;html=module.render()},page:()=>active,openDrawer:(title,body)=>{drawer=title+body},renderDaily:()=>'OLD_DAILY_ONLY',loadDaily:async()=>{calls.push({action:'workorders'})}});
 return {root,module,L,calls,html:()=>html,drawer:()=>drawer,renders:()=>renders,setPage:p=>{active=p},respond:r=>{response=r}};
}
const summary=(overrides={})=>{const current={ticketCount:20,ticketAmount:'1000.00000000',processedTicketCount:8,processedTicketAmount:'400.00000000',uniqueOrderCount:12,uniqueOrderAmount:'600.00000000',uniqueProcessedCount:5,uniqueProcessedAmount:'250.00000000',coverage:{status:'complete',missingOrderNumberCount:0,amountConflictCount:0,missingAmountCount:0,missingTicketAmountCount:0}},previous={...current,ticketCount:10,ticketAmount:'500.00000000',processedTicketCount:4,processedTicketAmount:'200.00000000'};return {source:'AR',currency:'INR',sourceStatus:'ready',current,previous,startDate:'2026-09-27',endDate:'2026-09-27',comparison:{label:'昨日',startDate:'2026-09-26',endDate:'2026-09-26'},changes:Object.fromEntries(['ticketCount','ticketAmount','processedTicketCount','processedTicketAmount','uniqueOrderCount','uniqueOrderAmount','uniqueProcessedCount','uniqueProcessedAmount'].map(k=>[k,{delta:String(current[k]-previous[k]),percent:'100.00',previous:previous[k]}])),...overrides};};
const response=(h,s=summary())=>h.respond(q=>q.operation==='summary'?s:{sourceStatus:'ready',rows:[record],total:137,platforms:['SYNTHETIC'],summary:{unknownOperationCount:999}});
const flush=()=>new Promise(r=>setImmediate(r));
test('summary is separate full-range request after list, cached across paging, default calendar month preserved',async()=>{const h=harness();response(h);await h.module.load();assert.equal(h.calls.length,2);assert.equal(h.calls[0].operation,'list');assert.equal(h.calls[1].operation,'summary');assert.equal(h.calls[1].limit,undefined);assert.equal(h.calls[1].offset,undefined);assert.deepEqual(h.calls[1].filters,h.calls[0].filters);const month=h.root.HensemWorkorderUI.currentMonth('印度',h.L.catalog);assert.equal(h.calls[0].filters.from,month.from);assert.match(h.html(),/总工单|已处理所涉原单/);assert.match(h.html(),/笔数较昨日 \+10/);assert.match(h.html(),/金额较昨日 \+500\.00/);assert.doesNotMatch(h.html(),/999 条操作时间未确认/);h.module.state().current=2;await h.module.load();assert.equal(h.calls.filter(q=>q.operation==='summary').length,1);assert.equal(h.calls.at(-1).offset,20);});
test('missing original IDs affect unique comparisons without hiding accurate raw ticket comparisons',async()=>{const h=harness(),s=summary();s.current.coverage={...s.current.coverage,status:'partial',missingOrderNumberCount:2};response(h,s);await h.module.load();assert.match(h.html(),/笔数较昨日 \+10/);assert.match(h.html(),/金额较昨日 \+500\.00/);assert.match(h.html(),/部分数据，暂不计算增幅/);assert.match(h.html(),/2 张缺原单号，未去重/);assert.match(h.html(),/NEWAR 明细尚未纳入/);assert.doesNotMatch(h.html(),/已到账原单/);});
test('unavailable originals display dashes, zero prior means no collected records rather than fabricated growth',async()=>{const h=harness(),s=summary();Object.assign(s.current,{uniqueOrderCount:null,uniqueOrderAmount:null,uniqueProcessedCount:null,uniqueProcessedAmount:null});s.current.coverage={status:'unavailable',missingOrderNumberCount:20};s.previous={...s.previous,ticketCount:0};response(h,s);await h.module.load();assert.match(h.html(),/原支付订单（去重）<\/h3><div class="wo-analysis-values"><strong>—/);assert.match(h.html(),/前期无已采集工单/);assert.doesNotMatch(h.html(),/100.00%/);});
test('summary failure preserves record list and explicit retry recovers',async()=>{const h=harness();h.respond(q=>{if(q.operation==='summary')throw Error('统计暂时超时');return {sourceStatus:'ready',rows:[record],total:1}});await h.module.load();assert.match(h.html(),/WORK-1/);assert.match(h.html(),/统计读取失败/);response(h);await h.root.workorderOperationsSummaryRetry();assert.match(h.html(),/总工单/);assert.doesNotMatch(h.html(),/统计读取失败/);});
test('new filters isolate late summary responses and query does not reuse stale totals',async()=>{const h=harness();let complete;h.respond(q=>q.operation==='summary'?new Promise(r=>{complete=r}):{sourceStatus:'ready',rows:[record],total:1});const old=h.module.load();await flush();assert(complete);const late=complete;h.root.workorderOperationsSet('platform','NEW',false);const newer=summary();newer.current.ticketCount=77;response(h,newer);await h.module.load(true);late(summary());await old;assert.equal(h.module.state().analysis.current.ticketCount,77);assert.equal(h.calls.at(-1).filters.platform,'NEW');});
test('grouped original orders open scoped all-history drawer with stable full pagination',async()=>{const h=harness();h.respond(q=>q.operation==='summary'?summary():q.operation==='orderDetail'?{rows:Array.from({length:q.offset===100?5:20},(_,i)=>({...record,workorderId:'ASSOCIATED-'+(q.offset+i),submittedAt:'2026-08-01T00:00:00Z',sourcePlatform:'SYNTHETIC'})),total:105}:{sourceStatus:'ready',rows:[{...record,ticketCount:2,processedTicketCount:1,processed:true,providers:['<untrusted>'],operators:['operator'],amountStatus:'known'}],total:1});await h.root.workorderOperationsMode('orders');assert.equal(h.calls[0].view,'orders');assert.match(h.html(),/原支付订单号/);assert.match(h.html(),/&lt;untrusted&gt;/);await h.root.workorderOperationsOriginal(0);let q=h.calls.at(-1);assert.deepEqual(JSON.parse(JSON.stringify(q.filters)),{platform:'SYNTHETIC',issueKind:'deposit',orderNo:record.orderNo});assert.equal(q.operation,'orderDetail');assert.equal(q.filters.from,undefined);assert.match(h.drawer(),/包含列表日期之外的记录/);assert.match(h.drawer(),/共 <b>105<\/b>/);await h.root.workorderOriginalPage(6);q=h.calls.at(-1);assert.equal(q.offset,100);assert.match(h.drawer(),/101–105/);assert.match(h.drawer(),/ASSOCIATED-104/);});
test('query click and Enter, including page jump, avoid native form submission in sandbox',async()=>{const h=harness();response(h);await h.module.load();assert.match(h.html(),/<button type="button" onclick="workorderOperationsLoad\(true\)"/);assert.match(h.html(),/onkeydown="if\(event.key==='Enter'/);assert.match(h.html(),/workorderOperationsJump\(this.form.elements.page.value\)/);assert.doesNotMatch(h.html(),/type="submit"/);h.root.workorderOperationsSet('dateBasis','operation');await h.module.load(true);assert.match(h.html(),/999 条操作时间未确认/);});
test('Enter handlers ignore IME, key repeat and unrelated controls but retain valid query and page jumps',async()=>{const h=harness();response(h);await h.module.load();const handlers=[...h.html().matchAll(/onkeydown="([^"]+)"/g)].map(m=>m[1]);const query=handlers.find(x=>x.includes('workorderOperationsLoad')),jump=handlers.find(x=>x.includes('workorderOperationsJump'));let loads=0,jumps=0,prevented=0;const run=(code,extra={})=>vm.runInNewContext('(function(){'+code+'}).call(form)',{event:{key:'Enter',isComposing:false,repeat:false,keyCode:13,target:{tagName:'INPUT',name:'page'},preventDefault:()=>prevented++,...extra},form:{elements:{page:{value:'6'}}},workorderOperationsLoad:()=>loads++,workorderOperationsJump:()=>jumps++});for(const code of [query,jump]){run(code,{isComposing:true});run(code,{repeat:true});run(code,{keyCode:229});run(code,{key:'Escape'});}assert.equal(loads+jumps,0);run(query,{target:{tagName:'BUTTON'}});run(jump,{target:{tagName:'INPUT',name:'other'}});assert.equal(loads+jumps,0);run(query);run(jump);assert.equal(loads,1);assert.equal(jumps,1);assert.equal(prevented,2);});

test('closing original or ticket drawer prevents late reads from reopening it',async()=>{for(const original of [true,false]){const h=harness();response(h);await h.module.load();let finish;h.respond(()=>new Promise(r=>{finish=r}));const pending=original?h.root.workorderOperationsOriginal(0):h.root.workorderOperationsDetail(0);assert(h.drawer());h.root.closeDrawer();assert.equal(h.drawer(),'');finish(original?{rows:[record],total:1}:{row:record});await pending;assert.equal(h.drawer(),'');}});
