// Real merchant adapter, synthetic authorized native facts; no network or writes.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=fs.readFileSync(path.join(__dirname,'admin-navigation-performance.test.cjs'),'utf8').split(/\ntest\(/)[0];
const {ready,completeAggregate,P,settle}=new Function('require','__dirname',base+';return {ready,completeAggregate,P,settle};')(require,__dirname);
const plain=s=>String(s).replace(/<span\b[^>]*aria-hidden="true"[^>]*>[\s\S]*?<\/span>/g,'').replace(/<[^>]*>/g,'').trim();
function ledger(h){const html=h.html().match(/<div class="table-wrap merchant-unified-table"[\s\S]*?<\/table>/)?.[0]||'';return {html,headers:[...(html.match(/<thead>[\s\S]*?<\/thead>/)?.[0]||'').matchAll(/<th\b[^>]*>([\s\S]*?)<\/th>/g)].map(x=>plain(x[1])),entries:[...html.matchAll(/<tr\b([^>]*)>([\s\S]*?)<\/tr>/g)].filter(x=>!x[1].includes('scope=')&&!x[2].includes('<th')).map(x=>({attributes:x[1],html:x[0],cells:[...x[2].matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/g)].map(y=>y[1])}))};}
function inline(h,platform='Alpha',system='AR'){const t=ledger(h),parent=t.entries.findIndex(r=>!r.attributes.includes('merchant-provider-')&&plain(r.cells[0])===platform&&plain(r.cells[1])===system);assert(parent>=0);const note=t.entries[parent+1];assert.match(note.attributes,/merchant-provider-inline-note/);const rows=[];for(const row of t.entries.slice(parent+2)){if(!row.attributes.includes('merchant-provider-inline-row'))break;rows.push(row.cells);}return {headers:t.headers,rows,note:note.html,html:[note.html,...rows.map(r=>r.join(''))].join('')};}
const cell=(t,r,label)=>r[t.headers.indexOf(label)];
const rate=(extra={})=>({scopeType:'country',country:'印度',provider:'ExamplePay',collectFee:'4%',payoutFee:'3%',...extra});
async function setup(){const platforms=[{...P,name:'Alpha',source:'ar'},{...P,id:'22222222-2222-4222-8222-222222222222',name:'Alpha',source:'newar'}],h=await ready({platforms}),a=completeAggregate(platforms[0],30,12),b=completeAggregate(platforms[1],99,88),s=a.summary[0],w={...s,direction:'withdraw',all_count:20,all_amount:'2000',success_count:8,success_amount:'800'};
 a.summary.push(w);a.groups.provider=[{...s,provider:'ExamplePay',all_count:20,all_amount:'2000',success_count:10,success_amount:'1000'},{...s,provider:'ZetaPay',all_count:10,all_amount:'1000',success_count:2,success_amount:'200'},{...w,provider:'ZetaPay'}];b.groups.provider=[{...b.summary[0],provider:'Other native secret'}];
 h.c.setPage('merchants');Object.assign(h.L,{results:[a,b],queryPlatforms:platforms,direction:'all',comparisonStatus:'idle',dirty:false,loading:false,pageQueried:true,feeLookupLoading:false,feeLookupError:'',feeLookupRows:[rate(),rate({scopeType:'platform',platform:'Alpha',collectFee:'2%'}),rate({provider:'ZetaPay',collectFee:'5%',payoutFee:'2%'})],view:'business'});h.c.render();return h;
}
function toggle(h,platform='Alpha',system='AR'){const t=ledger(h),row=t.entries.find(r=>!r.attributes.includes('merchant-provider-')&&plain(r.cells[0])===platform&&plain(r.cells[1])===system);assert(row);const callback=row.cells[t.headers.indexOf('使用三方')].match(/liveMerchantProviderUsage\((\d+)\)/);assert(callback);h.c.liveMerchantProviderUsage(Number(callback[1]));}
function connected(h){let disconnected=false;const query=h.c.document.querySelector;h.c.document.querySelector=selector=>{if(selector.startsWith('[data-merchant-provider-inline=')){const marker=selector.match(/"(\d+)"/)?.[1];return !disconnected&&h.html().includes('data-merchant-provider-inline="'+marker+'"')?{isConnected:true}:null;}return query(selector);};return ()=>{disconnected=true;};}

test('native platform click expands aligned provider rows directly below it, sorted by combined submitted volume without a drawer',async()=>{
 const h=await setup(),calls=h.calls.length,before=JSON.stringify(h.L.results);toggle(h);const t=inline(h),z=t.rows[0],pay=t.rows[1];assert.equal(h.drawers.length,0);assert.equal(t.rows.length,2);assert.equal(plain(z[0]),'ZetaPay');assert.equal(plain(pay[0]),'ExamplePay');assert(t.rows.every(row=>row.length===t.headers.length));
 assert.equal(plain(cell(t,z,'代收全部金额')),'1,000.00');assert.equal(plain(cell(t,z,'代收全部笔数')),'10');assert.equal(plain(cell(t,z,'代付全部金额')),'2,000.00');assert.equal(plain(cell(t,z,'代付全部笔数')),'20');assert.doesNotMatch(t.html,/Other native secret|9,900|8,800/);assert.equal(JSON.stringify(h.L.results),before);assert.equal(h.calls.length,calls);assert.match(h.html(),/aria-expanded="true"/);
 toggle(h);assert.doesNotMatch(h.html(),/merchant-provider-inline-row/);assert.equal(h.drawers.length,0);assert.equal(h.calls.length,calls);
});
test('fee amounts and matching percentages occupy independent direction columns in parents, providers and subtotals',async()=>{
 const h=await setup();toggle(h);const t=inline(h),z=t.rows[0],pay=t.rows[1];assert.equal(plain(cell(t,z,'代收手续费')),'10.00');assert.equal(plain(cell(t,z,'代收匹配占比')),'100.00%');assert.equal(plain(cell(t,z,'代付手续费')),'16.00');assert.equal(plain(cell(t,z,'代付匹配占比')),'100.00%');assert.equal(plain(cell(t,pay,'代收手续费')),'20.00');assert.doesNotMatch(plain(cell(t,pay,'代收手续费')),/%/);assert.match(cell(t,pay,'代收手续费'),/已匹配 10 \/ 10 笔/);assert.match(pay[0],/代收当前参考费率：2.00%/);assert.equal(plain(cell(t,z,'代付实际人数')),'—');
 const main=ledger(h),parent=main.entries.find(r=>plain(r.cells[0])==='Alpha'&&plain(r.cells[1])==='AR');assert.equal(plain(cell(main,parent.cells,'代收手续费')),'30.00');assert.equal(plain(cell(main,parent.cells,'代收匹配占比')),'100.00%');assert.equal(h.calls.filter(q=>q.action==='details').length,0);
});
test('sort, paging and estimate-mode changes preserve the same native expansion while historical facts stay immutable',async()=>{
 const h=await setup();for(const row of h.L.results[0].groups.provider)Object.assign(row,{fee_version_state:'complete',fee_version_matched_count:row.success_count,fee_version_unmatched_count:0,fee_version_estimated_amount:row.provider==='ExamplePay'?77:row.direction==='withdraw'?55:33});h.c.render();toggle(h);const old=h.c.liveMerchantProviderUsage,calls=h.calls.length,before=JSON.stringify(h.L.results);
 h.c.liveMerchantFeeMode('historical');let t=inline(h);assert.equal(plain(cell(t,t.rows[1],'代收手续费')),'77.00');assert.equal(plain(cell(t,t.rows[0],'代付手续费')),'55.00');old(0);assert.equal(inline(h).rows.length,2,'old mode handler cannot collapse or reopen the current mode');
 h.c.liveReferenceTableSort(encodeURIComponent('merchant-platforms-unified'),ledger(h).headers.indexOf('代收全部笔数'));t=inline(h);assert.equal(plain(cell(t,t.rows[1],'代收手续费')),'77.00');h.c.liveMerchantFeeMode('current');assert.equal(plain(cell(inline(h),inline(h).rows[1],'代收手续费')),'20.00');assert.equal(JSON.stringify(h.L.results),before);assert.equal(h.calls.length,calls);
});
test('scope, native result, query serial, page, mode and detail permission invalidate stale click callbacks',async()=>{
 const changes=[h=>h.L.dirty=true,h=>h.L.loading=true,h=>h.L.from='2026-10-03T00:00:00',h=>h.L.results=[...h.L.results],h=>h.L.serial++,h=>h.c.state.page='overview',h=>h.L.view='providers',h=>h.L.feeEstimateMode='historical',h=>h.c.hensemRoleAllowed=(page,action)=>action!=='detail'];
 for(const change of changes){const h=await setup(),callback=h.c.liveMerchantProviderUsage,calls=h.calls.length;change(h);callback(0);assert.doesNotMatch(h.html(),/merchant-provider-inline-row/);assert.equal(h.drawers.length,0);assert.equal(h.calls.length,calls);}
 const h=await setup();h.c.hensemRoleAllowed=(page,action)=>action!=='detail';h.c.render();assert.doesNotMatch(ledger(h).html,/onclick="liveMerchantProviderUsage/);h.c.liveMerchantProviderUsage(0);assert.doesNotMatch(h.html(),/merchant-provider-inline-row/);
});
test('lazy reference completion refreshes already expanded native rows once and never fetches orders again',async()=>{
 const h=await setup();connected(h);let resolve;h.setHandler(q=>q.action==='rates'?new Promise(r=>resolve=r):{rows:[],total:0});h.L.feeLookupRows=null;h.c.render();toggle(h);assert.match(inline(h).html,/匹配中/);const calls=h.calls.length;
 resolve({rows:[rate({collectFee:'6%'}),rate({provider:'ZetaPay',collectFee:'5%',payoutFee:'2%'})],total:2});await settle();const t=inline(h);assert.equal(plain(cell(t,t.rows[1],'代收手续费')),'60.00');assert.equal(plain(cell(t,t.rows[1],'代收匹配占比')),'100.00%');assert.equal(h.calls.length,calls);assert.equal(h.calls.filter(q=>q.action==='rates').length,1);assert.equal(h.drawers.length,0);
});
test('detached inline markers, collapse, edited scope and navigation cannot trigger asynchronous refresh repaint',async()=>{
 for(const change of [(h,detach)=>detach(),h=>toggle(h),h=>h.L.dirty=true,h=>h.L.serial++,h=>h.c.state.page='overview',h=>h.c.hensemRoleAllowed=(page,action)=>action!=='detail']){const h=await setup(),detach=connected(h);toggle(h);const callback=h.c.liveMerchantFeeRefresh;change(h,detach);const writes=h.writes.length,calls=h.calls.length;h.L.feeLookupRows=[rate({collectFee:'7%'})];callback();assert.equal(h.writes.length,writes);assert.equal(h.calls.length,calls);assert.equal(h.drawers.length,0);}
});
test('unknown rules and currencies retain independent dash estimates and zero or unknown matching coverage',async()=>{
 const h=await setup();h.L.feeLookupRows=h.L.feeLookupRows.map(r=>r.platform==='Alpha'?{...r,collectFee:''}:r);h.c.render();toggle(h);const t=inline(h),pay=t.rows[1];assert.equal(plain(cell(t,pay,'代收手续费')),'—');assert.equal(plain(cell(t,pay,'代收匹配占比')),'0.00%');assert.match(pay[0],/代收当前参考费率：费率待核对/);assert.doesNotMatch(pay[0],/2\.00%|4\.00%/);
 h.L.results[0].groups.provider[0].currency=null;h.c.render();assert.doesNotMatch(inline(h).html,/ExamplePay/);assert.match(inline(h).note,/未完整返回三方分组/);assert.doesNotMatch(inline(h).html,/NaN|Infinity/);
});
test('numeric column sizing includes expanded provider facts and does not truncate billion-scale values or stack headers',async()=>{
 const h=await setup();h.L.results[0].groups.provider[0].all_amount='33809493149.00';h.c.render();toggle(h);const t=ledger(h),children=inline(h);assert.equal(plain(cell(children,children.rows[1],'代收全部金额')),'33,809,493,149.00');assert.doesNotMatch(t.html.match(/<thead>[\s\S]*?<\/thead>/)[0],/<br/);assert.match(t.html,/overflow:visible;text-overflow:clip/);assert(Number(t.html.match(/min-width:(\d+)px/)[1])<2200);assert(t.headers.includes('代收匹配占比')&&t.headers.includes('代付匹配占比'));const widths=[...t.html.matchAll(/<col style="width:(\d+)px">/g)].map(x=>Number(x[1]));assert(widths[t.headers.indexOf('代收全部金额')]>=118);
});
