// Synthetic grouped-rule fixtures; no database, credentials, or production records.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../admin-preview/live-withdraw-pages.js'),'utf8');
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fixture(response){let html='',page;const calls=[],root={Intl,Date,document:{querySelector(){return null},getElementById(){return null}},HensemLiveFilters:{multi(){return ''}}};root.window=root;vm.createContext(root);vm.runInContext(source,root);const draw=()=>{html=page.render()};page=root.HensemLiveWithdrawPages.create({L:{catalogReady:true,catalog:[{country:'印度',name:'SYNTHETIC'}],country:'印度',from:'2026-09-26T00:00:00',to:'2026-09-26T23:59:59'},E:escape,N:String,C:String,R:(n,d)=>d?(100*n/d).toFixed(2)+'%':'—',page:()=> 'auto_withdraw',box:(_,body)=>body,table:(headers,rows)=>'<table>'+headers.join('|')+rows.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</table>',request:async q=>{calls.push(q);return typeof response==='function'?response(q):response},render:draw});page.state.data={country:'印度',rows:[{country:'印度',platform:'SYNTHETIC'}],totals:{},notes:[]};page.state.reason={country:'印度',platform:'SYNTHETIC',date:'2026-09-26',kind:'blocking'};page.state.reasonData=typeof response==='function'?response({offset:0}):response;draw();return {root,page,calls,html:()=>html,draw};}
const settle=async()=>{for(let i=0;i<3;i++)await new Promise(setImmediate)};
const grouped={available:true,source:'Synthetic',noteCount:120,total:2,canViewOrders:true,coverage:{collected:160},rows:[{reason:'首存金额超过19999',reasonKey:'a'.repeat(32),sourceReason:'首存金额大于19999,首存金额:25000',sourceVariantCount:7,count:90},{reason:'首存金额超过29999',reasonKey:'b'.repeat(32),sourceReason:'首存金额大于29999,首存金额:35000',sourceVariantCount:3,count:30}]};
test('grouped first-deposit thresholds stay distinct while the full original remains readable',()=>{const h=fixture(grouped);assert.match(h.html(),/>首存金额超过19999<\/button>/);assert.match(h.html(),/>首存金额超过29999<\/button>/);assert.match(h.html(),/已合并 7 种原文/);assert.match(h.html(),/75\.00%/);assert.match(h.html(),/25\.00%/);assert.match(h.html(),/共 2 条/);h.root.withdrawReasonOriginal(grouped.rows[0].sourceReason,'自动出款拦截原文（代表样本）');assert.match(h.html(),/aria-label="自动出款拦截原文（代表样本）"/);assert.match(h.html(),/<pre>首存金额大于19999,首存金额:25000<\/pre>/);});
test('reason paging uses grouped category count and keeps the total-note denominator',async()=>{const h=fixture(q=>({...grouped,total:21,rows:q.offset?[grouped.rows[1]]:grouped.rows}));h.root.withdrawReasonPage(2);await settle();assert.equal(h.calls[0].kind,'blocking');assert.equal(h.calls[0].offset,20);assert.equal(h.calls[0].limit,20);assert.match(h.html(),/共 21 条 · 21–21/);assert.match(h.html(),/2 \/ 2/);assert.match(h.html(),/25\.00%/);assert.match(h.html(),/disabled onclick="withdrawReasonPage\(3\)"/);});
test('existing rejection-original order drilldown retains its own key and source scope',async()=>{const reasonKey='c'.repeat(32),h=fixture({...grouped,rows:[{reason:'原始驳回说明',sourceReason:'原始驳回说明',reasonKey,count:12}]});h.page.state.reason.kind='rejection';h.root.withdrawReasonDrill(0,'reason');await settle();assert.equal(h.calls[0].kind,'orders');assert.equal(h.calls[0].reasonKey,reasonKey);assert.equal(h.calls[0].country,'印度');assert.equal(h.calls[0].platform,'SYNTHETIC');assert.equal(h.calls[0].date,'2026-09-26');assert.equal(h.calls[0].offset,0);});
test('a rule opens every original variant and keeps its canonical key for real blocking orders',async()=>{const rule=grouped.rows[0],h=fixture(q=>q.kind==='blockingVariants'?{...grouped,canViewBlockingOrders:true,rows:[{reason:rule.sourceReason,sourceReason:rule.sourceReason,reasonKey:rule.reasonKey,canonicalReason:rule.reason,count:70,success:20,rejected:45,other:5}]}:q.kind==='blockingOrders'?{...grouped,canViewBlockingOrders:true,rows:[{orderNumber:'SYNTHETIC-SUCCESS',amount:25000,status:'已通过',manualRemark:rule.sourceReason,blockingReason:rule.reason,blockingThreshold:'19999',blockingActualField:'首存金额',blockingActualValue:'25000'}]}:{...grouped,canViewBlockingOrders:true});h.root.withdrawBlockingDrill(0,'blockingVariants');await settle();assert.equal(h.calls[0].kind,'blockingVariants');assert.equal(h.calls[0].reasonKey,rule.reasonKey);assert.match(h.html(),/完整原文\|笔数\|成功\|驳回\|其他状态/);assert.match(h.html(),/返回规则分类/);h.root.withdrawBlockingView('blockingOrders');await settle();assert.equal(h.calls.at(-1).kind,'blockingOrders');assert.equal(h.calls.at(-1).reasonKey,rule.reasonKey);assert.match(h.html(),/SYNTHETIC-SUCCESS/);assert.match(h.html(),/首存金额：25000/);assert.match(h.html(),/19999/);assert.match(h.html(),/已通过/);assert.doesNotMatch(h.html(),/当日驳回订单|笔驳回订单计算/);h.root.withdrawReasonQuery('SYNTHETIC');h.root.withdrawReasonSearch();await settle();assert.equal(h.calls.at(-1).query,'SYNTHETIC');h.root.withdrawBlockingView('blockingVariants');await settle();assert.equal(h.page.state.reason.query,undefined);h.root.withdrawReasonRetry();await settle();assert.equal(h.calls.at(-1).query,undefined);assert.equal(h.calls.at(-1).reasonKey,rule.reasonKey);});
test('snapshot variants never fabricate order access and changing day clears the previous rule',async()=>{const h=fixture({...grouped,canViewBlockingOrders:false});const n=h.calls.length;h.root.withdrawBlockingDrill(0,'blockingOrders');await settle();assert.equal(h.calls.length,n);h.root.withdrawBlockingDrill(0,'blockingVariants');await settle();assert.equal(h.calls.at(-1).kind,'blockingVariants');assert.match(h.html(),/无法还原逐笔订单/);h.root.withdrawBlockingView('blockingOrders');await settle();assert.equal(h.calls.at(-1).kind,'blockingVariants');h.root.withdrawReasonDate('2026-09-25');await settle();assert.equal(h.calls.at(-1).kind,'blocking');assert.equal(h.calls.at(-1).reasonKey,undefined);assert.equal(h.calls.at(-1).date,'2026-09-25');});
test('reason size is bounded and shrinking results cannot strand a later page',async()=>{let total=137;const h=fixture(q=>({...grouped,total}));h.root.withdrawReasonSize('50');await settle();assert.equal(h.calls.at(-1).limit,50);h.root.withdrawReasonPage(999);await settle();assert.equal(h.calls.at(-1).offset,100);h.root.withdrawReasonSize('100');await settle();assert.equal(h.calls.at(-1).limit,100);h.root.withdrawReasonSize('999');assert.equal(h.page.state.reasonSize,100);h.root.withdrawReasonPage(2);await settle();total=0;h.root.withdrawReasonRetry();await settle();assert.equal(h.page.state.reasonPage,1);assert.equal(h.calls.at(-1).offset,0);});
