const {test,before,after,beforeEach,afterEach}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {PGlite}=require('@electric-sql/pglite');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const migration=read('supabase/migrations/20260930180000_dashboard_roles.sql');
const listFix=read('supabase/migrations/20260930230000_role_management_list_fix.sql');
const retiredCatalog=read('supabase/migrations/20260930231000_retire_channelquality_role_permission.sql');
const OWNER='11111111-1111-4111-8111-111111111111',ADMIN='22222222-2222-4222-8222-222222222222',VIEWER='33333333-3333-4333-8333-333333333333',LEGACY='44444444-4444-4444-8444-444444444444';
let db,acl,profiles,roleFunctions;
const scalar=async(q,p=[])=>Object.values((await db.query(q,p)).rows[0])[0];
const as=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
const admin=()=>db.exec('reset role');
const manage=async r=>scalar('select public.dashboard_role_manage($1::jsonb)',[JSON.stringify(r)]);
const access=()=>scalar('select public.dashboard_role_access()');
const execute=(page,r)=>scalar('select public.dashboard_admin_execute($1,$2::jsonb)',[page,JSON.stringify(r)]);
const create=async permissions=>(await manage({operation:'create',name:'Role '+crypto.randomUUID(),description:' test ',permissions})).role;
const assign=(id,role,expectedVersion=0)=>manage({operation:'assign',accountId:id,roleId:role.id,expectedVersion});
async function granted(id,permissions){await as(OWNER);const r=await create(permissions);await assign(id,r);await as(id);return r;}
async function denied(fn,pattern=/denied|required|permission/){await db.exec('savepoint denied');try{await assert.rejects(fn,pattern);}finally{await db.exec('rollback to savepoint denied');}}
function fn(source,name){const start=source.indexOf('create '+(source.includes('create or replace function '+name)?'or replace ':'')+'function '+name);const end=source.indexOf('\n$$;',start);return source.slice(start,end+4);}
function originalRoleFunction(name){const start=migration.indexOf('create or replace function '+name+'('),delimiter=name==='private.dashboard_role_catalog'?'$catalog$;':'end;$$;';return migration.slice(start,migration.indexOf(delimiter,start)+delimiter.length);}
before(async()=>{
 db=new PGlite();await db.exec(`create schema private;create schema auth;create role anon;create role authenticated;create role service_role;
 grant usage on schema public,private,auth to authenticated;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant execute on function auth.uid() to authenticated;
 create table dashboard_profiles(auth_user_id uuid primary key,username text unique,role text,active boolean,permissions jsonb,data_scope jsonb,updated_at timestamptz default now());
 create table dashboard_admin_preview_grants(auth_user_id uuid primary key,can_view boolean,granted_by uuid,updated_at timestamptz default now());
 create table dashboard_audit_log(id bigint generated by default as identity primary key,actor_user_id uuid,actor_username text not null default '',action text not null,target_username text not null default '',details jsonb not null default '{}',created_at timestamptz not null default now());
 create function private.dashboard_current_data_scope() returns jsonb language sql stable security definer as $$select data_scope from public.dashboard_profiles where auth_user_id=auth.uid()$$;
 insert into dashboard_profiles(auth_user_id,username,role,active,permissions,data_scope) values
 ('${OWNER}','owner','owner',true,'{}','{"mode":"all"}'),('${ADMIN}','admin','admin',true,'{"auto_withdraw":true,"third_party":true}','{"mode":"restricted","platforms":["A"]}'),
 ('${VIEWER}','viewer','viewer',true,'{"auto_withdraw":true,"third_party":true}','{"mode":"restricted","platforms":["B"]}'),('${LEGACY}','legacy','viewer',true,'{"third_party":true}','{"mode":"restricted","platforms":["C"]}');
 insert into dashboard_admin_preview_grants select auth_user_id,true,'${OWNER}',now() from dashboard_profiles;`);
 await db.exec(fn(read('supabase/admin-live-query.sql'),'private.dashboard_admin_live_scope('));
 await db.exec(fn(read('supabase/dashboard-v250-owner-fast-query.sql'),'public.dashboard_has_permission('));
 await db.exec(`revoke all on function private.dashboard_admin_live_scope() from public;
 revoke all on function public.dashboard_has_permission(text) from public;grant execute on function public.dashboard_has_permission(text) to anon,authenticated,service_role;
 create function private.dashboard_admin_live_query(p_request jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$declare scope jsonb:=private.dashboard_admin_live_scope();begin if p_request ? 'fail' then raise exception 'fixture_failure';end if;return jsonb_build_object('request',p_request,'scope',scope,'context',private.dashboard_role_context_valid());end$$;
 create function public.dashboard_admin_live_query(p_request jsonb) returns jsonb language sql stable security invoker as $$select private.dashboard_admin_live_query(p_request)$$;
 grant execute on function private.dashboard_admin_live_query(jsonb),public.dashboard_admin_live_query(jsonb) to authenticated;`);
 for(const name of ['submission_analysis','member_daily','workorder_records','auto_withdraw','deposit_issues','configuration_access','provider_config','platform_assignments'])await db.exec(`create function private.dashboard_admin_live_${name}(p_request jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$begin perform private.dashboard_admin_live_scope();return jsonb_build_object('rpc','${name}','request',p_request);end$$;grant execute on function private.dashboard_admin_live_${name}(jsonb) to authenticated;`);
 await db.exec(`create function private.dashboard_admin_live_configuration_write(p_request jsonb) returns jsonb language plpgsql volatile security definer set search_path='' as $$begin perform private.dashboard_admin_live_scope();if not exists(select 1 from public.dashboard_profiles where auth_user_id=auth.uid() and role in ('owner','admin')) or p_request->>'operation'='grant' and not exists(select 1 from public.dashboard_profiles where auth_user_id=auth.uid() and role='owner') then raise exception 'configuration_denied';end if;return p_request;end$$;
 create function private.dashboard_admin_live_withdraw_note(p_request jsonb) returns jsonb language plpgsql volatile security definer set search_path='' as $$begin perform private.dashboard_admin_live_scope();if not exists(select 1 from public.dashboard_profiles where auth_user_id=auth.uid() and role in ('owner','admin')) or not public.dashboard_has_permission('auto_withdraw') then raise exception 'note_denied';end if;return p_request;end$$;
 grant execute on function private.dashboard_admin_live_configuration_write(jsonb),private.dashboard_admin_live_withdraw_note(jsonb) to authenticated;`);
 acl=await scalar("select jsonb_object_agg(oid::regprocedure::text,proacl::text) from pg_proc where oid in ('private.dashboard_admin_live_scope()'::regprocedure,'public.dashboard_has_permission(text)'::regprocedure)");
 profiles=await scalar('select jsonb_agg(to_jsonb(p) order by username) from dashboard_profiles p');await db.exec(migration);
 roleFunctions=await scalar("select jsonb_object_agg(oid::regprocedure::text,jsonb_build_object('acl',proacl::text,'owner',proowner,'config',proconfig,'secdef',prosecdef,'volatile',provolatile)) from pg_proc where oid in ('private.dashboard_role_catalog()'::regprocedure,'private.dashboard_role_access()'::regprocedure,'public.dashboard_role_manage(jsonb)'::regprocedure)");
 await db.exec(listFix);await db.exec(retiredCatalog);
 await admin();
 await db.exec(read('tests/fixtures/pending-analysis/production-gateway.sql'));
 await db.exec(read('tests/fixtures/pending-analysis/production-role-catalog.sql'));
 await db.exec(`revoke all on function private.dashboard_role_catalog()from public,anon,authenticated,service_role;
 revoke all on function public.dashboard_admin_execute(text,jsonb)from public,anon,authenticated,service_role;
 grant execute on function public.dashboard_admin_execute(text,jsonb)to authenticated;
 create table private.withdraw_pending_capture_archive(id uuid primary key,source_system text,country_code text,platform text,stat_date date,snapshot_at timestamptz,capture_basis text,within_midnight_window boolean,timezone text,window_start date,window_end date,identity_status text,native_source_system text,platform_id uuid,team_name text,currency text);
 create table private.withdraw_pending_capture_orders(archive_id uuid,order_no text,amount numeric,applied_at timestamp,stat_date date,timezone text,raw_channel text,channel_type text,status text);
 alter table private.withdraw_pending_capture_archive enable row level security;alter table private.withdraw_pending_capture_orders enable row level security;
 create function private.dashboard_admin_pending_platform_key(text,text)returns text language sql immutable as $$select upper(replace($2,'-ALIAS',''))$$;
 create function private.dashboard_scope_allows(jsonb,text,text)returns boolean language sql immutable as $$select coalesce($1->>'mode'='all'or ($1->'platforms')?$3,false)$$;
 create table public.order_catalog_fixture(value jsonb);
 insert into public.order_catalog_fixture values('[{"id":"55555555-5555-4555-8555-555555555555","scope_group":"IN","platform_key":"B","source":"ar","country":"印度","team":"M8","currency":"INR","timezone":"Asia/Kolkata","name":"Synthetic Platform","mapping_ambiguous":false}]');
 create function private.dashboard_admin_live_provider_canonical(text,text,text)returns text language sql immutable as $$select $3$$;
 create function private.dashboard_admin_pending_resolve(jsonb,jsonb)returns jsonb language plpgsql stable security invoker set search_path='' as $$begin
  if $1->'platformIds'<> '["55555555-5555-4555-8555-555555555555"]'::jsonb or ($2->>'mode'<>'all'and not($2->'platforms')?'B')then raise exception 'platform_denied';end if;
  return (select value from public.order_catalog_fixture);
 end$$;
 revoke all on function private.dashboard_admin_pending_resolve(jsonb,jsonb)from public,anon,authenticated,service_role;
 insert into private.withdraw_pending_capture_archive values('66666666-6666-4666-8666-666666666666','WITHDRAW_REVIEW','IN','B','2026-10-01','2026-10-01T18:31:00Z','actual_capture',true,'Asia/Kolkata','2026-09-25','2026-10-01','resolved','AR','55555555-5555-4555-8555-555555555555','M8','INR'),('77777777-7777-4777-8777-777777777777','WITHDRAW_REVIEW','IN','B','2026-10-01','2026-10-02T02:00:00Z','actual_capture',false,'Asia/Kolkata','2026-09-25','2026-10-01','resolved','AR','55555555-5555-4555-8555-555555555555','M8','INR');
 insert into private.withdraw_pending_capture_orders values('66666666-6666-4666-8666-666666666666','SYNTHETIC-001',200,'2026-09-30 23:00:00','2026-09-30','Asia/Kolkata','SyntheticPay','BANK','pending'),('66666666-6666-4666-8666-666666666666','SYNTHETIC-002',300,null,'2026-09-30','Asia/Kolkata','OtherPay','QR','pending'),('77777777-7777-4777-8777-777777777777','LATE-ONLY',700,'2026-10-01 23:00:00','2026-10-01','Asia/Kolkata','SyntheticPay','BANK','pending');`);
 await db.exec(orderMigration);
});
after(async()=>db?.close());beforeEach(async()=>{await db.exec('begin');await as(OWNER);});afterEach(async()=>{await db.exec('rollback');await admin();});


const orderMigration=read('supabase/migrations/20261002065755_pending_analysis_orders.sql');
const request={date:'2026-10-01',platformIds:['55555555-5555-4555-8555-555555555555'],observedAt:'2026-10-01T18:31:00Z',mode:'midnight',offset:0,limit:20};

const orders=r=>scalar('select public.dashboard_admin_live_pending_orders($1::jsonb)',[JSON.stringify({...request,...r})]);
test('owner exact capture returns stable originals with wait days and unknown dates preserved',async()=>{
 const r=await orders({});assert.equal(r.available,true);assert.equal(r.total,2);assert.equal(r.amount,'500');assert.deepEqual(r.rows.map(x=>x.orderNumber),['SYNTHETIC-001','SYNTHETIC-002']);assert(r.rows[0].waitHours>25);assert.equal(r.rows[1].waitHours,null);
});
test('provider filter and paging do not change observation or count other providers',async()=>{
 const r=await orders({provider:'SyntheticPay'});assert.equal(r.total,1);assert.equal(r.amount,'200');assert.equal(r.rows[0].orderNumber,'SYNTHETIC-001');assert.equal((await orders({offset:20})).rows.length,0);
});
test('unknown capture and late capture never substitute latest or manufacture zero',async()=>{
 const absent=await orders({observedAt:'2026-10-01T18:32:00Z'});assert.equal(absent.available,false);assert.equal(absent.total,null);
 assert.equal((await orders({observedAt:'2026-10-02T02:00:00Z'})).available,false);
 const late=await orders({observedAt:'2026-10-02T02:00:00Z',mode:'observed'});assert.equal(late.rows[0].orderNumber,'LATE-ONLY');assert.equal(late.amount,'700');
});
test('assigned role requires stuck detail and gateway and cannot use other page route',async()=>{
 await granted(VIEWER,['stuck.view','stuck.query']);await denied(()=>execute('stuck',{action:'pendingOrders',...request}),/role_permission_denied/);
});
test('fully authorized assigned role uses signed existing gateway and direct call is denied',async()=>{
 await granted(VIEWER,['stuck.view','stuck.query','stuck.detail']);const r=await execute('stuck',{action:'pendingOrders',...request});assert.equal(r.available,true);assert.equal(r.total,2);
 await denied(()=>orders({}),/role_gateway_required/);await denied(()=>execute('providers',{action:'pendingOrders',...request}),/page_action_denied/);
});
test('country or platform scope denial and malformed filters do not leak archives',async()=>{
 await as(LEGACY);await denied(()=>orders({}),/platform_denied/);await as(OWNER);
 for(const r of [{sql:'select secret'},{offset:-1},{limit:'20'},{mode:'latest'},{provider:' SyntheticPay'},{date:'2026-02-30'},{observedAt:'garbage'}])await denied(()=>orders(r),/invalid/);
});
test('new tables remain unreadable and role catalog changes only route and label',async()=>{
 await as(VIEWER);await denied(()=>scalar('select count(*) from private.withdraw_pending_capture_orders'),/permission/);
 await admin();const catalog=await scalar('select private.dashboard_role_catalog()'),p=catalog.pages.find(x=>x.id==='stuck');assert.equal(p.label,'代付中分析');assert(p.requests.includes('pendingOrders'));assert.deepEqual(p.actions.map(x=>x.id),['view','query','detail','export']);
});

test('canonical aliases cannot widen raw platform scope of order archives',async()=>{
 await admin();await db.exec("update private.withdraw_pending_capture_archive set platform='B-ALIAS'");
 await granted(VIEWER,['stuck.view','stuck.query','stuck.detail']);
 const r=await execute('stuck',{action:'pendingOrders',...request});assert.equal(r.available,false);assert.equal(r.amount,null);assert.equal(r.total,null);
});
test('unknown currency or timezone, conflicting teams and mismatched capture clock do not return money',async()=>{
 for(const key of ['currency','timezone']){
  await admin();await db.query("update public.order_catalog_fixture set value=jsonb_set(value,array['0',$1],'null'::jsonb)",[key]);await as(OWNER);
  const r=await orders({});assert.equal(r.available,false);assert.equal(r.amount,null);
  await admin();await db.query("update public.order_catalog_fixture set value=jsonb_set(value,array['0',$1],to_jsonb($2::text))",[key,key==='currency'?'INR':'Asia/Kolkata']);
 }
 await admin();await db.exec("update private.withdraw_pending_capture_archive set timezone='UTC'");await as(OWNER);assert.equal((await orders({})).available,false);
 await admin();await db.exec("update public.order_catalog_fixture set value=value||jsonb_build_array(jsonb_set(value->0,'{team}','\"OTHER\"'::jsonb))");await as(OWNER);
 await denied(()=>orders({}),/platform_denied/);
});

test('archive identity cannot be reassigned to a different team, platform ID, currency or source',async()=>{
 for(const [column,value]of [['team_name','OTHER'],['native_source_system','NEW_AR'],['platform_id','99999999-9999-4999-8999-999999999999'],['currency','USD'],['identity_status','legacy_unbound']]){
  await admin();await db.exec('savepoint identity_test');await db.query('update private.withdraw_pending_capture_archive set '+column+'=$1',[value]);await as(OWNER);
  const r=await orders({});assert.equal(r.available,false,column);assert.equal(r.amount,null);assert.equal(r.total,null);
  await admin();await db.exec('rollback to savepoint identity_test');
 }
});
