// Synthetic requests only; no production session or network.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const compiled=ts.transpileModule(fs.readFileSync(path.join(__dirname,'../src/lib/adminLiveBridge.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const feed={dataset:'volume',system:'REPORT',country:'胖虎巴西',platform:'BET6867',direction:'charge',sourceKind:'google_sheets'};
const base={action:'reportSummary',startAt:'2026-09-20',endAt:'2026-09-24',feeds:[feed]};
function load(){const mod={exports:{}},calls=[],auth=[];vm.runInNewContext(compiled,{module:mod,exports:mod.exports,URL,process:{env:{NEXT_PUBLIC_SUPABASE_URL:'https://offline.invalid',NEXT_PUBLIC_SUPABASE_ANON_KEY:'offline-public-key'}},require:name=>name==='./dashboardAuthClient'?{ensureDashboardSession:async s=>{auth.push(s);return {...s,access_token:'fresh-offline'}}}:{},fetch:async(url,init)=>{calls.push({url,init});return {ok:true,json:async()=>({feeds:[],complete:true})}}});return {api:mod.exports,calls,auth}}
test('report summary validates exact source identity and bounded date contract',()=>{const h=load();assert.equal(JSON.stringify(h.api.validateAdminLiveRequest(base)),JSON.stringify(base));
for(const patch of [{startAt:'2026-02-30'},{endAt:'2026-09-19'},{endAt:'2026-10-21'},{startAt:'2026-09-20T00:00:00Z'},{feeds:[]},{feeds:Array(251).fill(feed)},{feeds:[{...feed,sql:'select 1'}]},{feeds:[{...feed,dataset:'orders'}]},{feeds:[{...feed,direction:'all'}]},{feeds:[{...feed,sourceKind:undefined}]},{feeds:[{...feed,platform:'x\nsecret'}]},{providers:['X']},{currency:'BRL'}])assert.throws(()=>h.api.validateAdminLiveRequest({...base,...patch}),JSON.stringify(patch));
assert.throws(()=>h.api.validateAdminLiveRequest({action:'catalog',feeds:[feed]}));
for(const dataset of ['panda_success','lg_success','collection_success','newar_third_party_volume','auto'])assert.doesNotThrow(()=>h.api.validateAdminLiveRequest({...base,feeds:[{...feed,dataset,sourceKind:'direct'}]}));
});
test('report request refreshes auth and routes to its independent RPC without action payload',async()=>{const h=load();await h.api.adminLiveRequest({user:{id:'offline-user'},access_token:'old'},base);assert.equal(h.auth.length,1);assert.equal(h.calls.length,1);assert.equal(h.calls[0].url,'https://offline.invalid/rest/v1/rpc/dashboard_admin_live_report_summary');assert.equal(h.calls[0].init.headers.Authorization,'Bearer fresh-offline');assert.deepEqual(JSON.parse(h.calls[0].init.body),{p_request:{startAt:base.startAt,endAt:base.endAt,feeds:base.feeds}});assert.equal(h.calls[0].init.cache,'no-store');});
