// Offline synthetic immutable observations; no production API or business writes.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../admin-preview/live-pending-orders.js'),'utf8');
function fixture(){const root={closeDrawer:()=>{}},drawers=[],calls=[];let permission=true,active=true,scope='scope',handler;
 vm.runInNewContext(source,{window:root});
 const q={date:'2026-10-01',platformIds:['55555555-5555-4555-8555-555555555555'],observedAt:'2026-10-01T18:31:00Z',mode:'midnight'};
 const response=()=>({version:1,available:true,basis:'actual_capture',...q,timezone:'Asia/Kolkata',platform:{name:'Synthetic'},currency:'INR',total:1,amount:'500',offset:0,limit:50,hasMore:false,rows:[{orderNumber:'<synthetic>',provider:'Pay',rawProvider:'Original',channelType:'BANK',amount:'500',appliedAt:'2026-09-29T23:00:00',waitHours:49.5,status:'pending'}]});
 handler=async()=>response();const api=root.HensemPendingOrders.create({E:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),N:v=>Number(v).toFixed(2),C:v=>String(v),active:()=>active,scope:()=>scope,canDetail:()=>permission,request:async r=>{calls.push({...r});return handler(r)},open:(title,html)=>drawers.push({title,html})});
 return {root,api,q,response,calls,drawers,html:()=>drawers.at(-1)?.html||'',handler:fn=>handler=fn,deny:()=>permission=false,navigate:()=>active=false,changeScope:()=>scope='new'};
}
test('exact capture and provider are sent; names escape and day/hour waits display',async()=>{const h=fixture();await h.api.open({...h.q,provider:'Pay'});assert.equal(h.calls[0].action,'pendingOrders');assert.equal(h.calls[0].observedAt,h.q.observedAt);assert.equal(h.calls[0].provider,'Pay');assert.match(h.html(),/&lt;synthetic&gt;/);assert.match(h.html(),/2 天 1.5 时/);assert.doesNotMatch(h.html(),/<synthetic>/);});
test('permission denial never requests or opens; closing or navigation rejects pending responses',async()=>{const h=fixture();h.deny();await h.api.open(h.q);assert.equal(h.calls.length,0);for(const kind of ['close','navigate','scope']){const f=fixture();let resolve;f.handler(()=>new Promise(r=>resolve=r));const pending=f.api.open(f.q);const count=f.drawers.length;kind==='close'?f.root.closeDrawer():kind==='navigate'?f.navigate():f.changeScope();resolve(f.response());await pending;assert.equal(f.drawers.length,count);}});
test('historical missing capture remains unavailable, retry preserves known result and bad observations reject',async()=>{const h=fixture();h.handler(async()=>({...h.response(),available:false,total:null,amount:null,rows:[]}));await h.api.open(h.q);assert.match(h.html(),/统计不是 0/);await h.api.open(h.q);h.handler(async()=>h.response());await h.root.livePendingOrdersRetry();h.handler(async()=>{throw Error('test timeout')});await h.root.livePendingOrdersRetry();assert.match(h.html(),/test timeout/);assert.match(h.html(),/&lt;synthetic&gt;/);h.handler(async()=>({...h.response(),observedAt:'2026-10-01T18:32:00Z'}));await h.api.open(h.q);assert.match(h.html(),/响应不完整/);assert.doesNotMatch(h.html(),/&lt;synthetic&gt;/);});
