const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../admin-preview/live-duration-reference.js'),'utf8');
const limits=[300000,1800000,3600000,10800000,21600000,43200000,86400000,172800000,259200000];
function result(id,count=10,success=6,createdSuccess=5){return {platform:{id,name:'Platform '+id,team:'M8',country:'印度',source:'ar',timezone:'Asia/Kolkata'},summary:[{direction:'charge',currency:'INR',all_count:count,all_amount:count*100,success_count:success,success_amount:success*100,created_success_count:createdSuccess,pending_count:2,pending_amount:200}],groups:{latency:Array.from({length:10},(_,bucket)=>({direction:'charge',currency:'INR',bucket,count:bucket===0?success:0,amount:bucket===0?success*100:0,valid_count:success,valid_amount:success*100})),latency_thresholds:limits.map((threshold_ms,bucket)=>({direction:'charge',currency:'INR',bucket,threshold_ms,count:0,amount:0,valid_count:success,valid_amount:success*100})),pending_age:[],pending_age_thresholds:[]},latencySummary:[{direction:'charge',currency:'INR',valid_count:success,valid_amount:success*100,mean_ms:60000,p50_ms:60000,p95_ms:120000,max_ms:150000}]}}
function setup(results=[result('A')],extra={}){const tables=[],calls=[],context=vm.createContext({});vm.runInContext('window=globalThis',context);vm.runInContext(source,context);const L={results,direction:'charge',currency:'INR',from:'2026-09-24T00:00:00',to:'2026-09-25T23:59:59',...extra};const ctx={L,table:(headers,rows,classes='',footer=[])=>{tables.push({headers,rows,footer});return '<table><thead><tr>'+headers.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table>'},box:(title,body,note,actions)=>'<section><h2>'+title+'</h2>'+String(actions||'')+body+'<p>'+String(note||'')+'</p></section>'};return {L,ctx,tables,calls,context,render:page=>context.HensemLiveDuration.create(ctx).render(page)}}
test('successful duration follows the success-day cohort while non-success quality follows created orders',()=>{const h=setup([result('A',10,16,7)]),html=h.render('latency');assert.match(html,/所选成功日期范围/);assert.match(html,/按成功时间入选/);assert.match(html,/3 笔创建订单未成功/);assert.doesNotMatch(html,/-6 笔/);const distribution=h.tables.find(x=>x.headers[0]==='成功耗时区间');assert.equal(distribution.rows[0][2],'16');assert.equal(distribution.rows[0][3],'100.00%');});
test('missing or inconsistent creation-cohort success counts are unknown, never fabricated negative counts',()=>{for(const createdSuccess of [undefined,null,20]){const r=result('A',10,16,createdSuccess);if(createdSuccess===undefined)delete r.summary[0].created_success_count;const h=setup([r]),html=h.render('latency');assert.match(html,/— 笔创建订单未成功/);assert.doesNotMatch(html,/-10 笔|NaN|Infinity/);}});
test('P95 stays unavailable across platforms or split ranges; weighted means remain valid',()=>{for(const results of [[result('A'),result('B')],[{...result('A'),_parts:[{},{}]}]]){const h=setup(results),html=h.render('latency');assert.match(html,/<span>P95 耗时<\/span><strong>—<\/strong>/);assert.match(html,/<span>平均 \/ P50 耗时<\/span><strong>1分<\/strong>/);assert.match(html,/跨分段分位数不可合并/);}});
test('pending page keeps its creation-date stock basis and layout independent of successful duration',()=>{const r=result('A');r.summary[0].direction='withdraw';const h=setup([r],{direction:'withdraw'}),html=h.render('stuck');assert.match(html,/所选创建日期范围/);assert.doesNotMatch(html,/所选成功日期范围|平台每日明细/);assert.deepEqual(Array.from(h.tables.find(t=>t.headers[0]==='已等待时长').headers),['已等待时长','代付中金额 · INR','代付中笔数','笔数占比','金额占比']);});

test('duration distribution uses the shared expansion contract without additional reads',()=>{const r=result('A'),h=setup([r]);const original=JSON.stringify(h.L.results);let spec;h.ctx.analysis={table:value=>{spec=value;return '<table data-shared="expanded"></table>'}};const html=h.render('latency');assert.match(html,/data-shared="expanded"/);assert.equal(spec.id,'latency-distribution');assert.equal(spec.rows.length,10);assert.equal(spec.headers.length,5);assert.deepEqual(JSON.parse(JSON.stringify(spec.segment(spec.rows[0]))),{kind:'latency',direction:'charge',bucket:0,cumulative:false});assert.equal(spec.label(spec.rows[0]),'≤ 5 分钟');assert.equal(spec.cells(spec.rows[0])[1],'600.00');assert.equal(spec.footerRows[0][1],'600.00');assert.equal(JSON.stringify(h.L.results),original);
 h.L.durationMode='cumulative';h.L.direction='all';h.render('latency');assert.equal(spec.rows.length,9);assert.equal(spec.headers.length,9);assert.equal(spec.label(spec.rows[8]),'超过 3 天');assert.deepEqual(JSON.parse(JSON.stringify(spec.segment(spec.rows[8]))),{kind:'latency',direction:'all',bucket:8,cumulative:true});assert.equal(JSON.stringify(h.L.results),original);});
test('shared expanded rows preserve unknown timing cells and the valid-time denominator',()=>{const r=result('A',10,8,4);r.groups.latency[0].count=2;r.groups.latency[0].amount=200;r.groups.latency.forEach(row=>{row.valid_count=4;row.valid_amount=400});const h=setup([r]);let spec;h.ctx.analysis={table:value=>{spec=value;return ''}};h.render('latency');const cells=spec.cells(spec.rows[0]);assert.equal(cells[2],'2');assert.equal(cells[3],'50.00%');assert.equal(cells[4],'50.00%');r.groups.latency=[];r.groups.latency_thresholds=[];r.latencySummary=[];h.render('latency');assert(spec.rows.every(row=>spec.cells(row).slice(1).every(cell=>cell==='—')));});
test('waiting page never asks the success-distribution expansion to render',()=>{const h=setup();h.ctx.analysis={table:()=>{throw Error('success drilldown must not alter pending layout')}};assert.match(h.render('stuck'),/data-duration-page="stuck"/);});
