// Bridge validation uses synthetic requests only; no real auth session or network.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const compiled=ts.transpileModule(fs.readFileSync(path.join(__dirname,'../src/lib/adminLiveBridge.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const base={action:'aggregate',view:'drilldown',platformId:'11111111-1111-4111-8111-111111111111',startAt:'2026-09-20T00:00:00.000Z',endAt:'2026-09-25T00:00:00.000Z',direction:'charge',status:'all',offset:0,limit:20};
function load(){const mod={exports:{}},calls=[],auth=[];vm.runInNewContext(compiled,{module:mod,exports:mod.exports,URL,process:{env:{NEXT_PUBLIC_SUPABASE_URL:'https://offline.invalid',NEXT_PUBLIC_SUPABASE_ANON_KEY:'offline-public-key'}},require:name=>name==='./dashboardAuthClient'?{ensureDashboardSession:async s=>{auth.push(s);return {...s,access_token:'fresh-offline'}}}:{},fetch:async(url,init)=>{calls.push({url,init});return {ok:true,json:async()=>({summary:[],groups:{daily:[]},complete:true})}}});return {api:mod.exports,calls,auth}}
const request=extra=>({...base,...extra});
test('only correctly typed exact segment contracts are accepted and retain the full selected range',()=>{
 const h=load();for(const choice of [{kind:'hourly',hour:23},{kind:'amount',bucket:'other'},{kind:'amount',bucket:'unknown'},{kind:'amount_range',bucket:'≥5,001'},{kind:'matrix',hour:0,bucket:'1000'},{kind:'matrix_range',hour:7,bucket:'751–1,000'},{kind:'latency',bucket:9,cumulative:false},{kind:'latency',bucket:8,cumulative:true}]){
  const q=request(choice),result=h.api.validateAdminLiveRequest(q);assert.equal(JSON.stringify(result),JSON.stringify(q));assert.equal(result.startAt,base.startAt);assert.equal(result.endAt,base.endAt);
 }
 for(const choice of [{kind:'hourly'},{kind:'hourly',hour:'1'},{kind:'hourly',hour:1.1},{kind:'hourly',hour:24},{kind:'hourly',hour:1,bucket:'other'},{kind:'hourly',hour:1,cumulative:false},{kind:'amount',hour:1,bucket:'100'},{kind:'amount',bucket:100},{kind:'amount',bucket:'101'},{kind:'amount_range',bucket:'100-200'},{kind:'matrix',bucket:'200'},{kind:'latency',bucket:'0'},{kind:'latency',bucket:10},{kind:'latency',bucket:9,cumulative:true},{kind:'latency',bucket:0,cumulative:'false'},{kind:'latency',bucket:0,hour:1},{kind:'unknown'},{kind:'hourly',hour:0,status:'success'},{kind:'hourly',hour:0,offset:20},{kind:'hourly',hour:0,country:'印度'},{kind:'hourly',hour:0,platformIds:[]},{kind:'hourly',hour:0,sql:'select 1'}])assert.throws(()=>h.api.validateAdminLiveRequest(request(choice)),JSON.stringify(choice));
});
test('drilldown uses one independently authorized RPC with unchanged exact filters and existing views keep their endpoint',async()=>{
 const h=load(),session={user:{id:'offline-user'},access_token:'old-offline'},q=request({kind:'matrix_range',hour:1,bucket:'201–300',providers:['ExamplePay'],channelTypes:['BANK'],currency:'INR',memberId:'MEMBER',amountMin:200,amountMax:300});
 await h.api.adminLiveRequest(session,q);assert.equal(h.calls.length,1);assert.equal(h.auth.length,1);assert.equal(h.calls[0].url,'https://offline.invalid/rest/v1/rpc/dashboard_admin_live_drilldown');assert.equal(h.calls[0].init.headers.Authorization,'Bearer fresh-offline');assert.equal(h.calls[0].init.cache,'no-store');assert.deepEqual(JSON.parse(h.calls[0].init.body),{p_request:q});
 for(const view of ['full','providers'])await h.api.adminLiveRequest(session,{...base,view});assert(h.calls.slice(1).every(c=>c.url.endsWith('/dashboard_admin_live_query')));
 for(const view of ['full','providers'])assert.throws(()=>h.api.validateAdminLiveRequest({...base,view,hour:1}));assert.throws(()=>h.api.validateAdminLiveRequest({...base,action:'details',view:'drilldown',kind:'hourly',hour:1}));
});
