const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{createRequire}=require('node:module');
const filename=path.join(__dirname,'admin-analysis-drilldown.test.cjs'),req=createRequire(filename);
let prefix=fs.readFileSync(filename,'utf8').split('\ntest(')[0];
prefix=prefix.replace('let calls=[],renders=0;','let calls=[],renders=0,drawers=[];').replace('const root={};','const root={closeDrawer(){}};').replace('render:()=>renders++','customResults:()=>L.customFixture,customRows:()=>L.customFixtureRows||[],openDrawer:(title,html)=>drawers.push({title,html}),render:()=>renders++').replace('return {root,L,instance,action,calls','return {drawers,root,L,instance,action,calls');
const context={require:req,__dirname,console,process,URL};vm.createContext(context);vm.runInContext(prefix+'\nglobalThis.fixture={setup,metric,segment};',context,{filename});
const {setup,metric,segment}=context.fixture;
const flush=async()=>{for(let i=0;i<20;i++)await new Promise(r=>setImmediate(r));};
const links=html=>[...html.matchAll(/liveAnalysisOrders\('([^']+)'\)/g)].map(m=>({key:m[1],value:JSON.parse(decodeURIComponent(m[1]))}));
const response=(q,total=1)=>({complete:true,platform:{id:q.platformId},basis:q.basis,segment:Object.fromEntries(['kind','hour','bucket','hourRange','amountMin','amountMax','amountMaxExclusive','durationVersion','durationRange','cumulative'].filter(k=>q[k]!==undefined).map(k=>[k,q[k]])),total,hasMore:total>q.offset+20,rows:Array.from({length:Math.min(20,Math.max(0,total-q.offset))},(_,i)=>({id:q.platformId+'-'+(q.offset+i),order_number:'RAW-'+q.platformId+'-'+(q.offset+i),provider:q.providers?.[0]||'ScopedPay',raw_provider:'OriginalPay',direction:q.direction,currency:q.currency,status_group:q.basis==='success'?'success':'pending',created_at:'2026-09-20T02:30:00Z',success_at:q.basis==='success'?'2026-09-20T02:31:00Z':null,amount:'210.01'}))});
const aggregate=q=>({complete:true,hasMore:false,summary:[metric()],groups:{daily:[],provider:[{...metric(),provider:'ScopedPay'}],provider_daily:[]}});
test('platform order buttons automatically fetch exact local-hour cohort with independent clocks and render real original keys',async()=>{
 const h=setup(q=>Promise.resolve(response(q)));h.instance.open(segment,'08时');let list=links(h.instance.panel(segment));assert.equal(list.length,4);
 h.root.liveAnalysisOrders(list.find(x=>x.value.platformId==='a'&&x.value.basis==='success').key);await flush();const q=h.calls[0];assert.equal(q.action,'analysisOrders');assert.equal(q.kind,'hourly');assert.equal(q.hour,8);assert.equal(q.platformId,'a');assert.equal(q.basis,'success');assert.equal(q.status,'all');assert.equal(q.limit,20);assert.equal(q.offset,0);assert.equal(q.view,undefined);assert.deepEqual(Array.from(q.providers),['ORIGINAL']);assert.equal(q.startAt,'2026-09-19T18:30:00Z');
 assert.match(h.drawers.at(-1).html,/RAW-a-0/);assert.match(h.drawers.at(-1).title,/成功订单.*成功时间/);h.root.liveAnalysisOrder(0);assert.match(h.drawers.at(-1).html,/原始稳定键/);assert.match(h.drawers.at(-1).html,/OriginalPay/);h.root.liveAnalysisOrdersBack();assert.match(h.drawers.at(-1).html,/RAW-a-0/);
 h.root.liveAnalysisOrders(list.find(x=>x.value.platformId==='b'&&x.value.basis==='created').key);await flush();assert.equal(h.calls.at(-1).basis,'created');assert.equal(h.calls.at(-1).platformId,'b');assert.match(h.drawers.at(-1).title,/全部订单.*创建时间/);
});
test('provider raw orders use the loaded segment cohort, default to an eligible platform and switch independently',async()=>{
 const h=setup(q=>Promise.resolve(q.action==='analysisOrders'?response(q):aggregate(q)));h.L.results.forEach(r=>r.groups.provider=[{...metric(),provider:'OtherGlobalPay'}]);h.instance.button(segment,'08时');h.action(segment,'toggleProvider');await flush();const list=links(h.instance.panel(segment));assert.equal(list.length,2);assert.equal(list[0].value.provider,'ScopedPay');h.root.liveAnalysisOrders(list.find(x=>x.value.basis==='created').key);await flush();let q=h.calls.at(-1);assert.equal(q.platformId,'a');assert.equal(q.hour,8);assert.deepEqual(Array.from(q.providers),['ScopedPay']);assert.match(h.drawers.at(-1).html,/区间订单平台/);assert.match(h.drawers.at(-1).html,/RAW-a-0/);assert.doesNotMatch(h.drawers.at(-1).html,/OtherGlobalPay/);h.root.liveAnalysisOrderPlatform(1);await flush();q=h.calls.at(-1);assert.equal(q.platformId,'b');assert.deepEqual(Array.from(q.providers),['ScopedPay']);assert.match(h.drawers.at(-1).html,/RAW-b-0/);h.root.liveAnalysisOrderPlatform(500);await flush();assert.equal(h.calls.length,4);
});
test('matrix and editable hour/amount ranges never broaden or leak display-only placement and bucket',async()=>{
 for(const s of [{kind:'matrix_range',direction:'charge',hour:8,bucket:'100–200'},{kind:'custom',direction:'charge',hourRange:{minHour:2,maxHour:4},amountMin:200,amountMax:250,amountMaxExclusive:true,placement:'analysis-custom'}]){
  const h=setup(q=>Promise.resolve(q.action==='analysisOrders'?response(q):aggregate(q)));h.instance.button(s,'区间');h.action(s,'toggleProvider');await flush();h.root.liveAnalysisOrders(links(h.instance.panel(s)).find(x=>x.value.basis==='success').key);await flush();const q=h.calls.at(-1);assert.equal(q.kind,s.kind);for(const key of ['hour','bucket','amountMin','amountMax','amountMaxExclusive'])assert.equal(q[key],s[key]);assert.equal(JSON.stringify(q.hourRange),JSON.stringify(s.hourRange));assert.equal(q.placement,undefined);assert.equal(q.view,undefined);
 }
});
test('raw order pagination uses endpoint count and does not infer counts from aggregate rows',async()=>{
 const h=setup(q=>Promise.resolve(response(q,25)));h.instance.open(segment,'08时');h.root.liveAnalysisOrders(links(h.instance.panel(segment))[0].key);await flush();assert.match(h.drawers.at(-1).html,/25 笔/);h.root.liveAnalysisOrderPage(1);await flush();assert.equal(h.calls.at(-1).offset,20);assert.match(h.drawers.at(-1).html,/RAW-a-20/);assert.doesNotMatch(h.drawers.at(-1).html,/RAW-a-0</);const before=h.calls.length;h.root.liveAnalysisOrderPage(1);await flush();assert.equal(h.calls.length,before);h.root.liveAnalysisOrderPage(-1);await flush();assert.equal(h.calls.at(-1).offset,0);
});
test('custom platform and provider orders use the independent successful custom read even when that platform main query failed',async()=>{
 const h=setup(q=>Promise.resolve(q.action==='analysisOrders'?response(q):aggregate(q))),p=h.L.catalog[1],s={kind:'custom',direction:'charge',amountMin:200,amountMax:250,amountMaxExclusive:true};h.L.results=h.L.results.slice(0,1);h.L.customFixture={results:[{platform:p}],complete:true};h.L.customFixtureRows=[{...metric(),platformId:p.id,platform:p.name,source:p.source}];h.instance.open(s,'独立区间');h.root.liveAnalysisOrders(links(h.instance.panel(s))[0].key);await flush();assert.equal(h.calls.at(-1).platformId,'b');h.root.closeDrawer();h.action(s,'toggleProvider');await flush();assert.equal(h.calls.at(-1).platformId,'b');h.root.liveAnalysisOrders(links(h.instance.panel(s))[0].key);await flush();assert.equal(h.calls.at(-1).action,'analysisOrders');assert.equal(h.calls.at(-1).platformId,'b');
});
test('close, scope changes and newer clicks prevent late raw orders from reopening or polluting the drawer',async()=>{
 const waiting=[],h=setup(q=>new Promise(resolve=>waiting.push({q,resolve})));h.instance.open(segment,'08时');const list=links(h.instance.panel(segment));h.root.liveAnalysisOrders(list[0].key);const before=h.drawers.length;h.root.closeDrawer();waiting.shift().resolve(response(h.calls[0]));await flush();assert.equal(h.drawers.length,before);
 h.root.liveAnalysisOrders(list[0].key);h.L.serial++;h.instance.panel(segment);const end=h.drawers.length;waiting.shift().resolve(response(h.calls.at(-1)));await flush();assert.equal(h.drawers.length,end);h.root.liveAnalysisOrders(list[0].key);await flush();assert.equal(h.calls.length,2,'old rendered keys cannot authorize a changed scope');
});
test('unregistered rows, mismatched scope and unsupported source failures never become fabricated empty data',async()=>{
 const h=setup(q=>Promise.resolve({...response(q),platform:{id:'wrong'}}));h.instance.open(segment,'08时');h.root.liveAnalysisOrders(encodeURIComponent(JSON.stringify({...segment,platformId:'forged'})));assert.equal(h.calls.length,0);h.root.liveAnalysisOrders(links(h.instance.panel(segment))[0].key);await flush();assert.match(h.drawers.at(-1).html,/响应不完整/);assert.doesNotMatch(h.drawers.at(-1).html,/没有匹配订单/);
 const e=setup(()=>Promise.reject(Error('此来源不支持成功时间读取')));e.instance.open(segment);e.root.liveAnalysisOrders(links(e.instance.panel(segment))[1].key);await flush();assert.match(e.drawers.at(-1).html,/此来源不支持成功时间读取/);assert.doesNotMatch(e.drawers.at(-1).html,/没有匹配订单/);
});
test('only separate expansion remains and historical both snapshots normalize to a single platform view',()=>{
 const h=setup();h.instance.open(segment,'08时');let html=h.instance.panel(segment);assert.doesNotMatch(html,/一起展示|analysis-dual-detail/);const saved=h.instance.capture();saved[0][1].tab='both';h.instance.restore(saved);html=h.instance.panel(segment);assert.doesNotMatch(html,/一起展示|analysis-dual-detail/);assert.equal(h.instance.snapshot().states.get(JSON.stringify(segment)).tab,'platform');assert.match(h.instance.button(segment),/三方展开/);assert.match(h.instance.button(segment),/收起平台/);
});
