const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),ts=require('typescript');
const base=path.join(__dirname,'../supabase/functions');const cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:mod,exports:mod.exports,Request,Response,Headers,URL,TextEncoder,TextDecoder,Uint8Array,atob,crypto:crypto.webcrypto,require:name=>load(path.resolve(path.dirname(file),name))},{filename:file});cache.set(file,mod.exports);return mod.exports;}
const{createApplicationAuthHandler}=load(path.join(base,'application-auth/handler.ts'));const{createSecurityAdminHandler}=load(path.join(base,'security-admin/handler.ts'));const{SecurityError}=load(path.join(base,'_shared/application-security.ts'));
const id='11111111-1111-4111-8111-111111111111',sid='22222222-2222-4222-8222-222222222222',key='unit-test-only-independent-proxy',hash=crypto.createHash('sha256').update(key).digest('hex'),token='eyJhbGciOiJIUzI1NiJ9.'+Buffer.from(JSON.stringify({sub:id,session_id:sid})).toString('base64url')+'.signature';
function request(body,headers={}){return new Request('https://unit.test',{method:'POST',headers:{'content-type':'application/json','x-portal-proxy-key':key,'x-portal-client-ip':'203.0.113.7',authorization:'Bearer '+token,...headers},body:JSON.stringify(body)});}
function fixture(overrides={}){const calls=[],state={approved:true,ipAllowed:true,...overrides},tokens={access_token:token,refresh_token:'test-refresh',expires_at:100,expires_in:90,token_type:'bearer',user:{id}};const gateway={
 async begin(...a){calls.push(['begin',...a]);return{allowed:!state.locked,code:'account_locked',user_id:id,email:'worker@workorder.hensem.local'};},
 async password(...a){calls.push(['password',...a]);if(state.invalid)throw new SecurityError(401,'invalid_credentials','bad');if(state.unavailable)throw Error('PRIVATE');return tokens;},
 async finish(...a){calls.push(['finish',...a]);return{allowed:a[1]==='valid'&&!state.finishDenied,code:state.finishDenied?'account_locked':a[1]==='invalid'?(state.threshold?'account_locked':'invalid_credentials'):'ok'};},
 async refresh(...a){calls.push(['refresh',...a]);return tokens;},async getUser(...a){calls.push(['auth',...a]);return state.badUser?null:{id,email:'worker@workorder.hensem.local'};},
 async check(...a){calls.push(['check',...a]);return{allowed:state.approved,code:'application_session_denied'};},async ipCheck(...a){calls.push(['ip',...a]);return state.ipAllowed;},
 async me(surface){calls.push(['me']);return{ok:true,identity_kind:state.wrongIdentity?'dashboard_owner':surface,account:{permissions:{}},catalog:{}};},
 async revoke(...a){calls.push(['revoke',...a]);},async revokeAll(...a){calls.push(['revokeAll',...a]);},async signout(...a){calls.push(['signout',...a]);if(state.logoutUnavailable)throw Error('PRIVATE');}
 };return{handler:createApplicationAuthHandler(gateway,{proxyKeySha256:hash}),calls,state,gateway};}
const login={action:'login',surface:'workorder',username:'worker',password:'test-password'};
test('only Worker proof and actual client IP enter auth; forged direct headers never reach credentials',async()=>{for(const headers of [{'x-portal-proxy-key':''},{'x-portal-proxy-key':'wrong'},{'x-portal-client-ip':'203.0.113.7, 1.1.1.1'},{'x-portal-client-ip':'','x-forwarded-for':'203.0.113.7'}]){const f=fixture();assert.equal((await f.handler(request(login,headers))).status,403);assert.equal(f.calls.length,0);}});
test('login registers only Auth verified gateway-issued session; returned tokens user is verified',async()=>{const f=fixture();const r=await(await f.handler(request(login))).json();assert.equal(r.ok,true);assert.equal(r.tokens.user.id,id);assert.equal(r.identity_kind,'workorder');assert.deepEqual(r.account.permissions,{});assert.deepEqual(f.calls.find(x=>x[0]==='finish').slice(2),['valid',sid]);assert(f.calls.find(x=>x[0]==='check'));});
test('invalid credential increments once, service failures are unavailable not failed passwords',async()=>{for(const unavailable of [false,true]){const f=fixture(unavailable?{unavailable:true}:{invalid:true,threshold:true});const r=await f.handler(request(login));assert.equal(r.status,unavailable?503:403);assert.equal(f.calls.filter(x=>x[0]==='finish').length,1);assert.equal(f.calls.find(x=>x[0]==='finish')[2],unavailable?'unavailable':'invalid');assert(!f.calls.some(x=>x[0]==='me'));assert(!await r.text().then(t=>t.includes('PRIVATE')));}});
test('locked account cannot invoke password endpoint; denied registration signs out issued token',async()=>{let f=fixture({locked:true});assert.equal((await f.handler(request(login))).status,403);assert(!f.calls.some(x=>x[0]==='password'));f=fixture({finishDenied:true});assert.equal((await f.handler(request(login))).status,403);assert(f.calls.some(x=>x[0]==='signout'));});
test('direct Auth refresh does not register session, me fresh checks fail locked or wrong identity',async()=>{for(const action of ['refresh','me']){const f=fixture({approved:false});assert.equal((await f.handler(request({action,surface:'workorder',refresh_token:'test'}))).status,403);assert(!f.calls.some(x=>x[0]==='finish'||x[0]==='me'));}assert.equal((await fixture({wrongIdentity:true}).handler(request({action:'me',surface:'workorder'}))).status,403);});
test('current IP restriction is checked separately from registered session',async()=>{const f=fixture({ipAllowed:false});assert.equal((await f.handler(request({action:'me',surface:'workorder'}))).status,403);assert(!f.calls.some(x=>x[0]==='me'));});
test('logout revokes first and tolerates Auth outage; logout-all cannot target different user',async()=>{for(const action of ['logout','logout-all']){const f=fixture({logoutUnavailable:true});const response=await f.handler(request({action,surface:'workorder',user_id:'forged'}));assert.equal(response.status,200);const name=action==='logout'?'revoke':'revokeAll';assert.equal(f.calls.find(c=>c[0]===name)[1],id);assert(f.calls.findIndex(c=>c[0]===name)<f.calls.findIndex(c=>c[0]==='signout'));assert.equal(f.calls.find(c=>c[0]==='signout')[2],action==='logout'?'local':'global');}});
test('security-admin forwards only verified actor/session and trusted IP; body spoofing cannot become authority',async()=>{const calls=[];const handler=createSecurityAdminHandler({getUser:async()=>({id}),admin:async(args)=>{calls.push(args);return{ok:true,policy:{version:1}};}},{proxyKeySha256:hash});let response=await handler(request({action:'policy',surface:'workorder',actor:'forged',session:'forged',ip:'198.51.100.1'}));assert.equal(response.status,200);assert.equal(calls[0].actor,id);assert.equal(calls[0].session,sid);assert.equal(calls[0].ip,'203.0.113.7');response=await handler(request({action:'policy',surface:'dashboard'},{authorization:'Bearer malformed'}));assert.equal(response.status,401);assert.equal(calls.length,1);});
