// Synthetic daily facts and platform metadata; no production Auth impersonation.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{PGlite}=require('@electric-sql/pglite');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const migration=read('supabase/migrations/20261002113936_auto_withdraw_registered_coverage.sql'),baseline=read('tests/fixtures/auto-withdraw-registered-coverage-baseline.sql');
const req=(extra={})=>({country:'香港',startAt:'2026-10-01T00:00:00Z',endAt:'2026-10-01T23:59:59Z',limit:20,...extra});
const call=async(db,r)=>(await db.query('select private.dashboard_admin_live_auto_withdraw($1::jsonb) value',[JSON.stringify(r)])).rows[0].value;
async function setup(){const db=new PGlite();await db.exec(`
 create schema private;create role anon;create role authenticated;create role service_role;
 create function private.dashboard_admin_live_scope() returns jsonb language plpgsql stable set search_path='' as $$begin if current_setting('test.denied',true)='yes' then raise exception 'preview_denied' using errcode='42501';end if;return coalesce(nullif(current_setting('test.scope',true),''),'{}')::jsonb;end$$;
 create function private.dashboard_scope_allows(s jsonb,c text,p text) returns boolean language sql immutable set search_path='' as $$select coalesce(s->'targets' @> jsonb_build_array(jsonb_build_array(c,p)),true)$$;
 create function private.dashboard_admin_live_withdraw_key(text) returns text language sql immutable set search_path='' as $$select upper(btrim($1))$$;
 create function private.dashboard_admin_live_report_country(text,text) returns text language sql immutable set search_path='' as $$select $1$$;
 create function private.dashboard_admin_live_can_note() returns boolean language sql stable set search_path='' as $$select false$$;
 create table public.game66_platforms(id uuid default gen_random_uuid(),team_code text,team_name text,platform_name text,enabled boolean default false);
 create table public.auto_withdraw_daily(data_date date,country text,platform text,total bigint,success bigint,rejected bigint,auto_count bigint,manual_count bigint,avg_seconds numeric,source_updated_at timestamptz,updated_at timestamptz);
 create table public.withdraw_operator_daily(data_date date,country text,platform text,account text,processed bigint,rejected bigint,avg_seconds numeric,source_updated_at timestamptz,updated_at timestamptz);
 create table public.newar_business_snapshots(kind text,direction text,country text,country_code text,platform text,stat_date date,payload jsonb,captured_at timestamptz,updated_at timestamptz);
 create table public.auto_withdraw_notes(data_date date,country text,platform text,reason text,updated_at timestamptz);
 create table private.game_facts(team_code text,country text,platform text,data_date date,total bigint);
 create function private.dashboard_admin_live_game66_withdraw(date,date,text,text[]) returns jsonb language sql stable set search_path='' as $$select jsonb_build_object('rows',coalesce(jsonb_agg(jsonb_build_object('data_date',data_date,'country',country,'platform',platform,'total',total,'success',total,'rejected',0,'auto_count',total,'manual_count',0,'avg_seconds',5,'source_updated_at','2026-10-02T00:00:00Z','updated_at','2026-10-02T00:00:00Z')),'[]'::jsonb),'operatorRows','[]'::jsonb) from private.game_facts where data_date between $1 and $2 and country=$3 and ($4 is null or upper(platform)=any($4)) and private.dashboard_scope_allows(private.dashboard_admin_live_scope(),case team_code when 'hong_kong' then 'HK_TEAM' when 'red_crab' then 'RED_CRAB' else upper(team_code) end,platform)$$;
 create function private.dashboard_admin_wg_withdraw_days(jsonb,jsonb,date,date) returns table(data_date date) language sql stable set search_path='' as $$select null::date where false$$;
 insert into public.game66_platforms(team_code,team_name,platform_name) select 'hong_kong','香港','HK-'||lpad(n::text,2,'0') from generate_series(1,16)n;
 insert into public.game66_platforms(team_code,team_name,platform_name) select 'red_crab','红膏蟹','RC-'||lpad(n::text,2,'0') from generate_series(1,8)n;
 insert into private.game_facts select 'hong_kong','香港','HK-'||lpad(n::text,2,'0'),'2026-10-01',case when n=1 then 0 else 2 end from generate_series(1,11)n;
 insert into private.game_facts select 'red_crab','红膏蟹','RC-'||lpad(n::text,2,'0'),'2026-10-01',2 from generate_series(1,5)n;
 insert into private.game_facts values('hong_kong','香港','HK-01','2026-09-30',1);
 grant usage on schema private to authenticated,anon,service_role;
 `);await db.exec(baseline);await db.exec("revoke all on function private.dashboard_admin_live_auto_withdraw(jsonb) from public,anon,authenticated,service_role;grant execute on function private.dashboard_admin_live_auto_withdraw(jsonb) to authenticated;");return db;}
test('24 registered identities expose 8 missing daily facts without inventing zero or changing factual DTOs',async()=>{const db=await setup();try{const old=[];for(const country of ['香港','红膏蟹'])old.push(await call(db,req({country})));await db.exec(migration);for(const [i,country,count,observed]of [[0,'香港',16,11],[1,'红膏蟹',8,5]]){const value=await call(db,req({country})),{platformCoverage,...facts}=value;assert.deepEqual(facts,old[i]);assert.equal(platformCoverage.expectedCount,count);assert.equal(platformCoverage.recordedCount,observed);assert.equal(platformCoverage.missingCount,count-observed);assert(platformCoverage.platforms.every(p=>p.country===country));assert(platformCoverage.platforms.filter(p=>p.state==='no_selected_period_record').every(p=>!('total'in p)&&p.coveredDays===0));}const z=(await call(db,req())).platformCoverage.platforms.find(p=>p.platform==='HK-01');assert.equal(z.state,'recorded','stored zero is observed, unlike a missing fact');assert.equal((await call(db,req())).rows.find(r=>r.platform==='HK-01').total,0);}finally{await db.close();}});
test('selected platforms, source targets and live account scope cannot disclose another team or unselected identity',async()=>{const db=await setup();try{await db.exec(migration);let c=(await call(db,req({platforms:['HK-16']}))).platformCoverage;assert.deepEqual(c.platforms.map(p=>p.platform),['HK-16']);const request=req({country:'印度',scopeTargets:[{country:'香港',platforms:['HK-16']},{country:'红膏蟹',platforms:['RC-08']}]});c=(await call(db,request)).platformCoverage;assert.deepEqual(c.platforms.map(p=>[p.country,p.platform]),[['红膏蟹','RC-08'],['香港','HK-16']]);await db.query("select set_config('test.scope',$1,false)",[JSON.stringify({targets:[['HK_TEAM','HK-16']]})]);c=(await call(db,request)).platformCoverage;assert.deepEqual(c.platforms.map(p=>p.platform),['HK-16']);assert.equal((await call(db,req({platforms:['HK-01']}))).platformCoverage.expectedCount,0);await db.exec("select set_config('test.denied','yes',false)");await assert.rejects(call(db,req()),/preview_denied/);}finally{await db.close();}});
test('range coverage counts source days, preserves pagination/known totals and rejects malformed targets',async()=>{const db=await setup();try{await db.exec(migration);const value=await call(db,req({startAt:'2026-09-30T00:00:00Z',daily:true}));assert.equal(value.platformCoverage.platforms.find(p=>p.platform==='HK-01').coveredDays,2);assert.equal(value.platformCoverage.platforms.find(p=>p.platform==='HK-02').coveredDays,1);assert(value.platformCoverage.platforms.every(p=>p.expectedDays===2));const page=await call(db,req({offset:20}));assert.equal(page.rows.length,0);assert.equal(page.platformCoverage.recordedCount,11);assert.equal(page.totals.total,20);for(const extra of [{scopeTargets:[{country:'香港',platforms:[]}]},{scopeTargets:[{country:'巴西',platforms:['HK-16']}]},{platforms:[true]},{unexpected:true}])await assert.rejects(call(db,req(extra)),/invalid_/);}finally{await db.close();}});
test('full function metadata and anonymous ACL stay closed; drift rolls back atomically',async()=>{for(const drift of [null,'body','acl']){const db=await setup();try{if(drift==='body')await db.exec("create or replace function private.dashboard_admin_live_auto_withdraw(p_request jsonb default '{}'::jsonb) returns jsonb language sql stable security definer set search_path='' as $$select $1$$");if(drift==='acl')await db.exec('grant execute on function private.dashboard_admin_live_auto_withdraw(jsonb) to anon');const before=(await db.query("select to_jsonb(p) value from pg_proc p where oid='private.dashboard_admin_live_auto_withdraw(jsonb)'::regprocedure")).rows[0].value;if(drift){await assert.rejects(db.exec(migration),/auto_withdraw_coverage_.*drift/);await db.exec('rollback');assert.deepEqual((await db.query("select to_jsonb(p) value from pg_proc p where oid='private.dashboard_admin_live_auto_withdraw(jsonb)'::regprocedure")).rows[0].value,before);}else{await db.exec(migration);const after=(await db.query("select to_jsonb(p)-'prosrc' value from pg_proc p where oid='private.dashboard_admin_live_auto_withdraw(jsonb)'::regprocedure")).rows[0].value;delete before.prosrc;assert.deepEqual(after,before);assert.equal((await db.query("select has_function_privilege('anon','private.dashboard_admin_live_auto_withdraw(jsonb)','execute') allowed")).rows[0].allowed,false);assert.equal((await db.query("select has_function_privilege('service_role','private.dashboard_admin_live_auto_withdraw(jsonb)','execute') allowed")).rows[0].allowed,false);}}finally{await db.close();}}});
