// Synthetic session/accounts; real authority definitions and both guarded migrations.
const {test,before,beforeEach,after,afterEach}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const patch=read('supabase/migrations/20261010144205_dashboard_atomic_platform_scope_edit.sql');
let setup,seed,db,f;
const ctx=vm.createContext({__dirname,require:n=>n==='node:test'?{test(){},before:fn=>setup=fn,beforeEach:fn=>seed=fn,after(){},afterEach(){}}:require(n)});
vm.runInContext(read('tests/dashboard-platform-data-scope-sql.test.cjs').split(/\ntest\(/)[0]+'\nglobalThis.getFixture=()=>({db,f});',ctx);
const pairs=(...names)=>({mode:'selected',countries:[],platforms:names.map(platform=>({country:'IN',platform}))});
const scalar=(q,p=[])=>f.scalar(q,p),profile=()=>scalar('select to_jsonb(p) from dashboard_profiles p where auth_user_id=$1',[f.EXISTING]);
async function update(scope=pairs('91CLUB'),overrides={}){const p=overrides.expected||await profile();return scalar('select public.dashboard_update_account_data_scope($1,$2,$3,$4,$5,$6::jsonb)',[overrides.actor||f.ACTOR,overrides.session||f.SID,overrides.target||f.EXISTING,overrides.role===undefined?p.role:overrides.role,overrides.at===undefined?p.updated_at:overrides.at,JSON.stringify(scope)]);}
before(async()=>{await setup();({db,f}=ctx.getFixture());await db.exec(patch);});
beforeEach(async()=>{await seed();await db.query('update dashboard_profiles set data_scope=$1::jsonb where auth_user_id=any($2::uuid[])',[JSON.stringify(pairs('91CLUB')),[f.ACTOR,f.EXISTING]]);});
afterEach(async()=>{await db.exec('rollback');await db.exec('reset role');});after(async()=>db?.close());
test('service-only setter changes only exact scope/timestamp and commits matching audit/ACK',async()=>{for(const role of ['anon','authenticated','service_role'])assert.equal(await scalar('select has_function_privilege($1,$2,$3)',[role,'public.dashboard_update_account_data_scope(uuid,uuid,uuid,text,timestamptz,jsonb)','execute']),role==='service_role');const p=await profile();await db.exec('set role service_role');const ack=await update(pairs(),{expected:p});await db.exec('reset role');assert.equal(ack.ok,true);assert.deepEqual(ack.data_scope,pairs());const next=await profile();for(const key of Object.keys(p).filter(k=>!['data_scope','updated_at'].includes(k)))assert.deepEqual(next[key],p[key],key);assert.deepEqual(next.data_scope,pairs());assert.equal(await scalar('select count(*)::int from dashboard_audit_log'),1);assert.deepEqual(await scalar("select details->'before_scope' from dashboard_audit_log"),pairs('91CLUB'));assert.deepEqual(await scalar("select proconfig from pg_proc where oid='public.dashboard_update_account_data_scope(uuid,uuid,uuid,text,timestamptz,jsonb)'::regprocedure"),['search_path=""']);});
test('fresh actor scope, role permission, assignment and preview revocation deny without scope/audit writes',async()=>{const cases=[['update dashboard_profiles set data_scope=$1::jsonb where auth_user_id=$2',[JSON.stringify(pairs('OTHER')),f.ACTOR]],['update private.dashboard_roles set permissions=array[\'access.view\'] where id=$1',[f.MANAGER]],['delete from private.dashboard_role_assignments where auth_user_id=$1',[f.ACTOR]],['update dashboard_admin_preview_grants set can_view=false where auth_user_id=$1',[f.ACTOR]],['update dashboard_profiles set active=false where auth_user_id=$1',[f.ACTOR]]];for(const [q,args]of cases){await db.exec('savepoint scenario');const p=await profile();await db.query(q,args);await f.denied(()=>update(),/denied/);assert.deepEqual(await profile(),p);assert.equal(await scalar('select count(*)::int from dashboard_audit_log'),0);await db.exec('rollback to savepoint scenario');}});
test('revoked, expired, locked or missing registered/Auth sessions fail closed',async()=>{for(const q of ["update private.application_sessions set revoked_at=now() where user_id=$1","delete from auth.sessions where user_id=$1","update auth.sessions set not_after=now()-interval '1 second' where user_id=$1","insert into private.application_account_security values($1,'dashboard',now())"]){await db.exec('savepoint scenario');const p=await profile();await db.query(q,[f.ACTOR]);await f.denied(()=>update(),/application_session_denied/);assert.deepEqual(await profile(),p);await db.exec('rollback to savepoint scenario');}});
test('target promotion, update timestamp CAS and null/infinite versions cannot bypass target check',async()=>{const old=await profile();await db.query('update dashboard_profiles set updated_at=updated_at+interval \'1 second\' where auth_user_id=$1',[f.EXISTING]);await f.denied(()=>update(pairs(),{at:old.updated_at}),/version_conflict/);await db.query("update dashboard_profiles set role='admin' where auth_user_id=$1",[f.EXISTING]);await f.denied(()=>update(pairs(),{role:'viewer'}),/version_conflict/);for(const at of [null,'infinity'])await f.denied(()=>update(pairs(),{at}),/invalid_account_scope_update/);assert.equal(await scalar('select count(*)::int from dashboard_audit_log'),0);});
test('target role rights and scope expansion are checked again inside setter, owner/self not made editable',async()=>{await db.query('insert into private.dashboard_role_assignments(auth_user_id,role_id) values($1,$2)',[f.EXISTING,f.ROLE]);await db.query("update private.dashboard_roles set permissions=array['ip.view'] where id=$1",[f.ROLE]);await f.denied(()=>update(),/account_scope_update_denied/);await db.query('update private.dashboard_roles set permissions=array[]::text[] where id=$1',[f.ROLE]);for(const scope of [{mode:'selected',countries:['IN']},pairs('OTHER'),{mode:'all',countries:[]}])await f.denied(()=>update(scope),/account_scope_update_denied/);await f.denied(()=>update(pairs(),{target:f.OWNER,role:'viewer'}),/version_conflict/);await f.denied(()=>update(pairs(),{target:f.ACTOR}),/account_scope_update_denied/);});
test('audit failure rolls back the scope and version atomically',async()=>{const p=await profile();await db.exec("create function public.synthetic_scope_audit_failure() returns trigger language plpgsql as $$begin raise exception 'synthetic_scope_audit_failure';end$$;create trigger synthetic_scope_audit_failure before insert on dashboard_audit_log for each row execute function public.synthetic_scope_audit_failure();");await f.denied(()=>update(pairs()),/synthetic_scope_audit_failure/);assert.deepEqual(await profile(),p);assert.equal(await scalar('select count(*)::int from dashboard_audit_log'),0);});
test('authority drift aborts deployment before creating a service entry point',async()=>{await db.exec('savepoint scenario');await db.exec('drop function public.dashboard_update_account_data_scope(uuid,uuid,uuid,text,timestamptz,jsonb)');await db.exec("create or replace function private.dashboard_data_scope_subset(p_child jsonb,p_parent jsonb) returns boolean language sql immutable as $$select true$$");await f.denied(()=>db.exec(patch.slice(patch.indexOf('do $guard$'),patch.indexOf('end $guard$;')+'end $guard$;'.length)),/atomic_scope_authority_drift/);assert.equal(await scalar("select to_regprocedure('public.dashboard_update_account_data_scope(uuid,uuid,uuid,text,timestamptz,jsonb)') is null"),true);await db.exec('rollback to savepoint scenario');});
