// Existing administration handler harness; synthetic requests and profile writes only.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..');
const ctx=vm.createContext({__dirname,require,structuredClone,Buffer,Request,Response,Date,Intl,console,AbortSignal,atob,TextEncoder,TextDecoder,Uint8Array});
vm.runInContext(fs.readFileSync(path.join(__dirname,'account-data-scope-admin.test.cjs'),'utf8').split(/\ntest\(/)[0]+'\nglobalThis.fixture={edge,profile,ALL};',ctx);
const {edge,profile,ALL}=ctx.fixture,scope=(...names)=>({mode:'selected',countries:[],platforms:names.map(platform=>({country:'IN',platform}))});
const plain=x=>JSON.parse(JSON.stringify(x));
test('owner update persists explicit platform scope and canonicalizes harmless case/trim without broadening countries',async()=>{const r=await edge('update-account',{data_scope:scope(' 91club ','VEER.GAME','91CLUB')},{role:'owner'});assert.equal(r.status,200);assert.deepEqual(plain(r.writes[0].data_scope),scope('91CLUB','VEER.GAME'));});
test('scoped actor cannot expand platform access to a country, another native platform or foreign country',async()=>{for(const data_scope of [{mode:'selected',countries:['IN']},scope('OTHER'),{mode:'selected',countries:[],platforms:[{country:'VN',platform:'91CLUB'}]}]){const r=await edge('update-account',{data_scope},{caller:{data_scope:scope('91CLUB')},target:{data_scope:scope('91CLUB')}});assert.equal(r.status,403);assert.equal(r.writes.length,0);}});
test('disabled broader target stays unmanageable; invalid parent never treats empty countries as wildcard',async()=>{for(const options of [{caller:{data_scope:scope('91CLUB')},target:{active:false,data_scope:{mode:'selected',countries:['IN']}}},{caller:{data_scope:{mode:'selected',countries:[],unknown:1}},target:{data_scope:scope('91CLUB')}}]){const r=await edge('update-account',{data_scope:scope('91CLUB'),active:true},options);assert.equal(r.status,403);assert.equal(r.writes.length,0);}});
test('empty whitelist remains explicit deny-all and malformed/mixed-country entries never write',async()=>{const r=await edge('update-account',{data_scope:scope()},{role:'owner'});assert.equal(r.status,200);assert.deepEqual(plain(r.writes[0].data_scope),scope());for(const data_scope of [{...scope('91CLUB'),platforms:null},{...ALL,platforms:[]},{mode:'selected',countries:['IN'],platforms:[{country:'VN',platform:'91CLUB'}]},scope('SECRET\u0001CONTROL')]){const bad=await edge('update-account',{data_scope},{role:'owner'});assert.equal(bad.status,400);assert.equal(bad.writes.length,0);}});
test('account listing and omitted-scope updates retain the exact live platform restriction',async()=>{const r=await edge('list-users',{}, {caller:{data_scope:scope('91CLUB')},users:[profile('same','viewer',{data_scope:scope('91CLUB')}),profile('other','viewer',{data_scope:scope('OTHER')}),profile('country','viewer',{data_scope:{mode:'selected',countries:['IN']}})]});assert.equal(r.status,200);assert.deepEqual(plain(r.body.users.map(u=>u.username)),['same']);const update=await edge('update-account',{active:false},{caller:{data_scope:scope('91CLUB')},target:{data_scope:scope('91CLUB')}});assert.equal(update.status,200);assert.equal(update.writes[0].data_scope,undefined);assert.deepEqual(plain(update.target.data_scope),scope('91CLUB'));});
test('scope-only RPC rejects all mixed input keys including ignored null/unsupported fields',async()=>{for(const action of ['update-account','update-viewer'])for(const extra of [{active:null},{permissions:null},{management_permissions:null},{password:'unused'},{unexpected:1}]){const r=await edge(action,{data_scope:scope('91CLUB'),...extra},{role:'owner'});assert.equal(r.status,400);assert.equal(r.body.code,'data_scope_mixed_patch');assert.equal(r.writes.length,0);assert.equal(r.authCalls.length,0);assert.equal(r.reads.filter(x=>x.rpc==='dashboard_update_account_data_scope').length,0);}});
test('atomic authorization revocation/CAS/error ACK never falls back to direct scope writes',async()=>{for(const [options,status,code] of [[{scopeRpcDenied:true},403,'account_scope_update_denied'],[{race:true},409,'account_scope_version_conflict'],[{scopeRpcFailure:true},503,'account_scope_result_unknown'],[{scopeRpcBadAck:true},503,'account_scope_result_unknown']]){const r=await edge('update-account',{data_scope:scope('91CLUB')},{role:'owner',...options});assert.equal(r.status,status);assert.equal(r.body.code,code);assert.equal(r.writes.length,0);assert.equal(r.authCalls.length,0);assert.equal(r.reads.filter(x=>x.rpc==='dashboard_update_account_data_scope').length,1);}});
