// Synthetic identities, fake clocks and offline callbacks only.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const source=fs.readFileSync(path.join(__dirname,'../src/lib/dashboardPresenceClient.ts'),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const session={user:{id:'synthetic-user-a'},access_token:'synthetic-token-a',refresh_token:'synthetic-refresh'};
const stamp='2026-10-02T00:00:00.000Z';
const response=(extra={})=>({ok:true,onlineCount:1,observedAt:stamp,windowSeconds:120,heartbeatSeconds:30,scope:'authorized',accounts:[{username:'synthetic001',lastSeenAt:stamp}],...extra});
const flush=()=>new Promise(resolve=>setImmediate(resolve));
function moduleHarness(options={}){const module={exports:{}},calls=[];vm.runInNewContext(compiled,{module,exports:module.exports,AbortController,Date,URL,setTimeout,clearTimeout,require:name=>{assert.equal(name,'./dashboardAuthClient');return {APPLICATION_GATEWAY:'https://synthetic-gateway.invalid',ensureDashboardSession:options.ensure|| (async s=>s),dashboardResponseError:(status,payload,fallback)=>Object.assign(Error(fallback),{status})}},fetch:async(url,init)=>{calls.push({url,init});return options.fetch?options.fetch(url,init):{ok:true,json:async()=>response()}}});return {api:module.exports,calls}}
function controllerHarness(options={}){const {api}=moduleHarness(),timers=new Map(),events=new Map(),calls=[],seen=[];let now=100000,id=0;const target={addEventListener:(name,fn)=>{if(!events.has(name))events.set(name,new Set());events.get(name).add(fn)},removeEventListener:(name,fn)=>events.get(name)?.delete(fn)};const doc={...target,visibilityState:'visible'};const c=api.createDashboardPresenceController({request:async(s,action,signal)=>{calls.push({s,action,signal});return options.request?options.request(s,action,signal):response()},now:()=>now,setTimeout:(fn,ms)=>{const key=++id;timers.set(key,{fn,ms});return key},clearTimeout:key=>timers.delete(key),target,document:doc,online:()=>options.offline!==true});c.subscribe(s=>seen.push(s));return {c,calls,timers,events,seen,advance:ms=>now+=ms,event:name=>[...(events.get(name)||[])].forEach(fn=>fn()),fire:ms=>{const row=[...timers].find(([,v])=>v.ms===ms);assert(row,'expected timer '+ms);timers.delete(row[0]);row[1].fn()}}}

test('only explicit authorized server snapshots supply counts; incomplete or duplicate lists fail closed',()=>{
 const {api}=moduleHarness();assert.equal(api.parseDashboardPresenceResponse(response()).onlineCount,1);assert.equal(api.parseDashboardPresenceResponse(response({onlineCount:0,accounts:[]})).onlineCount,0);const restricted=response();delete restricted.accounts;assert.equal(api.parseDashboardPresenceResponse(restricted).accounts,null);
 for(const patch of [{ok:false},{onlineCount:null},{onlineCount:'1'},{onlineCount:-1},{onlineCount:501},{onlineCount:1.5},{scope:'all'},{observedAt:'yesterday'},{windowSeconds:0},{heartbeatSeconds:300},{accounts:[]},{accounts:null},{accounts:[{username:'bad<script>',lastSeenAt:stamp}]},{accounts:[{username:'synthetic001',lastSeenAt:'2026-10-02T00:00:01Z'}]},{accounts:[{username:'synthetic001',lastSeenAt:'2026-10-01T23:57:59Z'}]},{onlineCount:2,accounts:Array(2).fill({username:'synthetic001',lastSeenAt:stamp})}])assert.throws(()=>api.parseDashboardPresenceResponse(response(patch)));
 const safe=api.parseDashboardPresenceResponse(response({token:'never-forward',ip:'private-network',accounts:[{username:'synthetic001',lastSeenAt:stamp,id:'never-forward'}]}));assert.doesNotMatch(JSON.stringify(safe),/never-forward|private-network/);
});

test('presence transport uses the trusted Worker route and fresh user session without arbitrary identity or scope fields',async()=>{
 const h=moduleHarness({ensure:async s=>({...s,access_token:'synthetic-refreshed-token'})});await h.api.requestDashboardPresence(session,'heartbeat',new AbortController().signal);const {url,init}=h.calls[0];assert.equal(url,'https://synthetic-gateway.invalid/api/dashboard-presence');assert.equal(init.headers.Authorization,'Bearer synthetic-refreshed-token');assert.deepEqual(JSON.parse(init.body),{action:'heartbeat'});assert.equal(init.cache,'no-store');assert.equal(init.redirect,'error');assert.equal(init.credentials,'omit');assert.equal(init.method,'POST');
 await assert.rejects(h.api.requestDashboardPresence(session,'leave',new AbortController().signal));assert.equal(h.calls.length,1);const changed=moduleHarness({ensure:async s=>({...s,user:{id:'different-user'}})});await assert.rejects(changed.api.requestDashboardPresence(session,'heartbeat',new AbortController().signal));assert.equal(changed.calls.length,0);
 const controller=new AbortController();controller.abort();await assert.rejects(h.api.requestDashboardPresence(session,'status',controller.signal));assert.equal(h.calls.length,1);
});

test('one controller heartbeat persists across page subscriptions and same-user token renewal, with bounded refresh',async()=>{
 const h=controllerHarness();h.c.setSession(session,'synthetic-scope');await flush();assert.equal(h.calls.length,1);const stop=h.c.subscribe(()=>{});h.c.setSession({...session,access_token:'synthetic-renewed-token'},'synthetic-scope');await h.c.refresh();h.event('focus');h.event('online');assert.equal(h.calls.length,1);assert.equal([...h.events.values()].filter(set=>set.size>0).length,6);
 h.advance(30000);h.fire(30000);await flush();assert.equal(h.calls.length,2);assert.equal(h.calls[1].s.access_token,'synthetic-renewed-token');assert.equal(h.calls[1].action,'heartbeat');stop();h.c.dispose();assert.equal(h.timers.size,0);assert.equal([...h.events.values()].some(set=>set.size),false);
});

test('logout, identity and authorized-scope changes clear old counts and reject late responses',async()=>{
 const pending=[];const h=controllerHarness({request:(s,action,signal)=>new Promise(resolve=>pending.push({resolve,signal,s}))});h.c.setSession(session,'scope-a');assert.equal(h.calls.length,1);h.c.setSession({...session,user:{id:'synthetic-user-b'}},'scope-b');assert.equal(pending[0].signal.aborted,true);assert.equal(h.c.getSnapshot().onlineCount,null);pending[0].resolve(response({onlineCount:2,accounts:[]}));await flush();assert.equal(h.c.getSnapshot().onlineCount,null);pending[1].resolve(response());await flush();assert.equal(h.c.getSnapshot().onlineCount,1);
 h.c.setSession({...session,user:{id:'synthetic-user-b'}},'narrower-scope');assert.equal(h.c.getSnapshot().onlineCount,null);assert.equal(h.calls.length,3);h.c.setSession(null);pending[2].resolve(response());await flush();assert.equal(h.c.getSnapshot().onlineCount,null);assert.equal(h.c.getSnapshot().accounts,null);assert.equal(h.c.getViewerId(),null);assert.equal(h.timers.size,0);assert.deepEqual(h.calls.map(x=>x.action),['heartbeat','heartbeat','heartbeat']);
});

test('timeouts and failed reads immediately remove old online counts rather than displaying zero or stale users',async()=>{
 let resolve;const h=controllerHarness({request:()=>resolve?new Promise(()=>{}):new Promise(done=>resolve=done)});h.c.setSession(session,'scope');resolve(response());await flush();assert.equal(h.c.getSnapshot().onlineCount,1);h.advance(30000);h.fire(30000);h.fire(12000);await flush();assert.equal(h.calls[1].signal.aborted,true);assert.equal(h.c.getSnapshot().onlineCount,null);assert.equal(h.c.getSnapshot().accounts,null);assert.equal(h.c.getSnapshot().reason,'timeout');h.c.dispose();
 const failed=controllerHarness({request:async()=>{throw Error('private backend detail')}});failed.c.setSession(session,'scope');await flush();assert.equal(failed.c.getSnapshot().onlineCount,null);assert.equal(failed.c.getSnapshot().reason,'unavailable');assert.doesNotMatch(JSON.stringify(failed.c.getSnapshot()),/private backend/);failed.c.dispose();
});

test('suspended pages expire the snapshot and resume one heartbeat without leaving other tabs offline',async()=>{
 const h=controllerHarness();h.c.setSession(session,'scope');await flush();h.advance(60000);assert.equal(h.c.getSnapshot().onlineCount,null);assert.equal(h.c.getSnapshot().reason,'stale');h.event('pagehide');await flush();assert.equal(h.timers.size,0);h.event('pageshow');await flush();assert.equal(h.calls.length,2);assert.equal(h.c.getSnapshot().onlineCount,1);assert(h.calls.every(x=>x.action==='heartbeat'));h.c.dispose();
 const offline=controllerHarness({offline:true});offline.c.setSession(session,'scope');assert.equal(offline.calls.length,0);assert.equal(offline.c.getSnapshot().onlineCount,null);assert.equal(offline.c.getSnapshot().reason,'offline');offline.c.dispose();
});
