const {test,before,after,beforeEach,afterEach}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {PGlite}=require('@electric-sql/pglite');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const migration=read('supabase/migrations/20260930180000_dashboard_roles.sql');
const listFix=read('supabase/migrations/20260930230000_role_management_list_fix.sql');
const delegated=read('supabase/migrations/20261001142722_delegated_role_account_permissions.sql');
const retiredCatalog=read('supabase/migrations/20260930231000_retire_channelquality_role_permission.sql');
const OWNER='11111111-1111-4111-8111-111111111111',ADMIN='22222222-2222-4222-8222-222222222222',VIEWER='33333333-3333-4333-8333-333333333333',LEGACY='44444444-4444-4444-8444-444444444444';
let db,acl,profiles,roleFunctions;
const scalar=async(q,p=[])=>Object.values((await db.query(q,p)).rows[0])[0];
const as=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
const admin=()=>db.exec('reset role');
const manage=async r=>scalar('select public.dashboard_role_manage($1::jsonb)',[JSON.stringify(r)]);
const access=()=>scalar('select public.dashboard_role_access()');
const execute=(page,r)=>scalar('select public.dashboard_admin_execute($1,$2::jsonb)',[page,JSON.stringify(r)]);
const create=async permissions=>(await manage({operation:'create',name:'Role '+crypto.randomUUID(),description:' test ',permissions})).role;
const assign=(id,role,expectedVersion=0)=>manage({operation:'assign',accountId:id,roleId:role.id,expectedVersion});
async function granted(id,permissions){await as(OWNER);const r=await create(permissions);await assign(id,r);await as(id);return r;}
async function denied(fn,pattern=/denied|required|permission/){await db.exec('savepoint denied');try{await assert.rejects(fn,pattern);}finally{await db.exec('rollback to savepoint denied');}}
function fn(source,name){const start=source.indexOf('create '+(source.includes('create or replace function '+name)?'or replace ':'')+'function '+name);const end=source.indexOf('\n$$;',start);return source.slice(start,end+4);}
function originalRoleFunction(name){const start=migration.indexOf('create or replace function '+name+'('),delimiter=name==='private.dashboard_role_catalog'?'$catalog$;':'end;$$;';return migration.slice(start,migration.indexOf(delimiter,start)+delimiter.length);}
before(async()=>{
 db=new PGlite();await db.exec(`create schema private;create schema auth;create role anon;create role authenticated;create role service_role;
 grant usage on schema public,private,auth to authenticated;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant execute on function auth.uid() to authenticated;
 create table dashboard_profiles(auth_user_id uuid primary key,username text unique,role text,active boolean,permissions jsonb,management_permissions jsonb default '{}',data_scope jsonb,updated_at timestamptz default now());
 create table dashboard_admin_preview_grants(auth_user_id uuid primary key,can_view boolean,granted_by uuid,updated_at timestamptz default now());
 create table dashboard_audit_log(id bigint generated by default as identity primary key,actor_user_id uuid,actor_username text not null default '',action text not null,target_username text not null default '',details jsonb not null default '{}',created_at timestamptz not null default now());
 create function private.dashboard_current_data_scope() returns jsonb language sql stable security definer as $$select data_scope from public.dashboard_profiles where auth_user_id=auth.uid()$$;
 insert into dashboard_profiles(auth_user_id,username,role,active,permissions,data_scope) values
 ('${OWNER}','owner','owner',true,'{}','{"mode":"all"}'),('${ADMIN}','admin','admin',true,'{"auto_withdraw":true,"third_party":true}','{"mode":"restricted","platforms":["A"]}'),
 ('${VIEWER}','viewer','viewer',true,'{"auto_withdraw":true,"third_party":true}','{"mode":"restricted","platforms":["B"]}'),('${LEGACY}','legacy','viewer',true,'{"third_party":true}','{"mode":"restricted","platforms":["C"]}');
 insert into dashboard_admin_preview_grants select auth_user_id,true,'${OWNER}',now() from dashboard_profiles;`);
 await db.exec(fn(read('supabase/admin-live-query.sql'),'private.dashboard_admin_live_scope('));
 await db.exec(fn(read('supabase/dashboard-v250-owner-fast-query.sql'),'public.dashboard_has_permission('));
 await db.exec(`revoke all on function private.dashboard_admin_live_scope() from public;
 revoke all on function public.dashboard_has_permission(text) from public;grant execute on function public.dashboard_has_permission(text) to anon,authenticated,service_role;
 create function private.dashboard_admin_live_query(p_request jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$declare scope jsonb:=private.dashboard_admin_live_scope();begin if p_request ? 'fail' then raise exception 'fixture_failure';end if;return jsonb_build_object('request',p_request,'scope',scope,'context',private.dashboard_role_context_valid());end$$;
 create function public.dashboard_admin_live_query(p_request jsonb) returns jsonb language sql stable security invoker as $$select private.dashboard_admin_live_query(p_request)$$;
 grant execute on function private.dashboard_admin_live_query(jsonb),public.dashboard_admin_live_query(jsonb) to authenticated;`);
 for(const name of ['submission_analysis','member_daily','workorder_records','auto_withdraw','deposit_issues','configuration_access','provider_config','platform_assignments'])await db.exec(`create function private.dashboard_admin_live_${name}(p_request jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$begin perform private.dashboard_admin_live_scope();return jsonb_build_object('rpc','${name}','request',p_request);end$$;grant execute on function private.dashboard_admin_live_${name}(jsonb) to authenticated;`);
 await db.exec(`create function private.dashboard_admin_live_configuration_write(p_request jsonb) returns jsonb language plpgsql volatile security definer set search_path='' as $$begin perform private.dashboard_admin_live_scope();if not exists(select 1 from public.dashboard_profiles where auth_user_id=auth.uid() and role in ('owner','admin')) or p_request->>'operation'='grant' and not exists(select 1 from public.dashboard_profiles where auth_user_id=auth.uid() and role='owner') then raise exception 'configuration_denied';end if;return p_request;end$$;
 create function private.dashboard_admin_live_withdraw_note(p_request jsonb) returns jsonb language plpgsql volatile security definer set search_path='' as $$begin perform private.dashboard_admin_live_scope();if not exists(select 1 from public.dashboard_profiles where auth_user_id=auth.uid() and role in ('owner','admin')) or not public.dashboard_has_permission('auto_withdraw') then raise exception 'note_denied';end if;return p_request;end$$;
 grant execute on function private.dashboard_admin_live_configuration_write(jsonb),private.dashboard_admin_live_withdraw_note(jsonb) to authenticated;`);
 acl=await scalar("select jsonb_object_agg(oid::regprocedure::text,proacl::text) from pg_proc where oid in ('private.dashboard_admin_live_scope()'::regprocedure,'public.dashboard_has_permission(text)'::regprocedure)");
 profiles=await scalar('select jsonb_agg(to_jsonb(p) order by username) from dashboard_profiles p');await db.exec(migration);
 roleFunctions=await scalar("select jsonb_object_agg(oid::regprocedure::text,jsonb_build_object('acl',proacl::text,'owner',proowner,'config',proconfig,'secdef',prosecdef,'volatile',provolatile)) from pg_proc where oid in ('private.dashboard_role_catalog()'::regprocedure,'private.dashboard_role_access()'::regprocedure,'public.dashboard_role_manage(jsonb)'::regprocedure)");
 await db.exec(listFix);await db.exec(retiredCatalog);
 await db.exec(`create function private.dashboard_data_scope_valid(s jsonb) returns boolean language sql immutable as $$select coalesce(jsonb_typeof(s)='object' and jsonb_typeof(s->'countries')='array' and (s->>'mode'='all' and jsonb_array_length(s->'countries')=0 or s->>'mode'='selected'),false)$$;
 create function private.application_current_session_allowed(surface text) returns boolean language sql stable as $$select coalesce(nullif(current_setting('fixture.session.allowed',true),'')::boolean,true)$$;
 update dashboard_profiles set data_scope='{"mode":"selected","countries":["IN"]}',management_permissions='{"manage_viewers":true}' where role<>'owner';
 update dashboard_profiles set data_scope='{"mode":"all","countries":[]}' where role='owner';`);
 await db.exec(delegated);
});
after(async()=>db?.close());beforeEach(async()=>{await db.exec('begin');await as(OWNER);});afterEach(async()=>{await db.exec('rollback');await admin();});


test('new IP edit exists in catalog without implicitly updating existing roles',async()=>{
 await admin();const c=await scalar('select private.dashboard_role_catalog()');assert.deepEqual(c.pages,JSON.parse(read('src/lib/dashboardRoleCatalog.json')).pages.filter(page=>page.id!=='success_analysis').map(page=>({...page,...(page.id==='stuck'?{label:'代付中与卡单分析',moduleId:'risk',moduleLabel:'智能风控中心'}:{}),requests:page.requests.filter(request=>!['analysisOrders','pendingOrders','submissionStreak'].includes(request))})));assert(c.permissions.some(p=>p.key==='ip.edit'));assert.equal(await scalar('select count(*)::int from private.dashboard_roles'),0);
});
test('owner can assign an empty role while preserving the data scope and removing legacy page authority',async()=>{
 const role=await create([]);await assign(VIEWER,role);
 await as(VIEWER);const live=await access();assert.equal(live.mode,'assigned');assert.equal(live.canView,false);assert.deepEqual(live.permissions,[]);
 await denied(()=>execute('autowithdraw',{action:'autoWithdraw'}));
 await denied(()=>manage({operation:'list'}));
 await admin();assert.deepEqual(await scalar('select data_scope from dashboard_profiles where auth_user_id=$1',[VIEWER]),{mode:'selected',countries:['IN']});
 assert.equal(await scalar("select private.dashboard_actor_has_permission($1,'access.view')",[VIEWER]),false);
});
test('delegated assigned viewer reads its scope and assigns only its own permission subset',async()=>{
 const actorRole=await create(['access.view','access.edit','providers.view','providers.query']);await assign(ADMIN,actorRole);
 const narrow=await create(['providers.view']);await as(ADMIN);
 assert.equal((await manage({operation:'list'})).accounts.length,3);
 const result=await assign(VIEWER,narrow);assert.equal(result.account.role_id,narrow.id);assert.equal(result.account.role,'viewer');assert.deepEqual(result.account.data_scope,{mode:'selected',countries:['IN']});
});
test('role writes reject self, admin peers, owner, cross-scope and any permission increase',async()=>{
 const actorRole=await create(['access.view','access.edit','providers.view']);await assign(VIEWER,actorRole);const high=await create(['providers.view','providers.query']),narrow=await create(['providers.view']);
 await as(VIEWER);for(const who of [OWNER,ADMIN,VIEWER])await denied(()=>assign(who,narrow),/assignment_target_denied/);
 await denied(()=>assign(LEGACY,high),/role_grant_exceeds_actor/);
 await admin();await db.exec(`update dashboard_profiles set data_scope='{"mode":"selected","countries":["BR"]}' where auth_user_id='${LEGACY}'`);await as(VIEWER);await denied(()=>assign(LEGACY,narrow),/assignment_target_denied/);
 for(const operation of ['create','update','archive'])await denied(()=>manage({operation,roleId:narrow.id,expectedVersion:1,name:'New',permissions:['providers.view']}),/role_management_denied/);
});
test('target with greater current role is protected against replacement and password takeover',async()=>{
 const actorRole=await create(['access.view','access.edit','access.reset_password','providers.view']);await assign(ADMIN,actorRole);
 const high=await create(['providers.view','providers.query']);await assign(VIEWER,high);await as(ADMIN);
 await denied(()=>assign(VIEWER,actorRole),/assignment_target_denied/);
 assert.equal(await scalar("select public.dashboard_account_action_allowed($1,'access.reset_password')",[VIEWER]),false);
 assert.equal(await scalar("select public.dashboard_account_action_allowed($1,'access.reset_password')",[LEGACY]),false);
});
test('fresh assigned role overrides old management flag without authorizing unknown keys or old roles',async()=>{
 await admin();await db.exec(`update dashboard_profiles set management_permissions='{}' where auth_user_id='${ADMIN}'`);await as(OWNER);
 const actorRole=await create(['access.view','access.edit','ip.view']);await assign(ADMIN,actorRole);await as(ADMIN);assert((await manage({operation:'list'})).accounts.length>0);
 await admin();assert.equal(await scalar("select private.dashboard_actor_has_permission($1,'ip.view')",[ADMIN]),true);assert.equal(await scalar("select private.dashboard_actor_has_permission($1,'ip.edit')",[ADMIN]),false);
 assert.equal(await scalar("select private.dashboard_actor_has_permission($1,'evil.edit')",[ADMIN]),false);await db.exec(`update private.dashboard_roles set active=false where id='${actorRole.id}'`);await as(ADMIN);await denied(()=>manage({operation:'list'}),/role_management_denied/);
});
test('registered session check precedes all management and cannot be bypassed with an owner identity',async()=>{
 await db.exec("select set_config('fixture.session.allowed','false',true)");await denied(()=>manage({operation:'list'}),/application_session_denied/);await denied(()=>scalar("select public.dashboard_account_action_allowed($1,'access.edit')",[VIEWER]),/application_session_denied/);
});
test('private helper ACLs and existing data grants remain closed',async()=>{
 await admin();for(const actor of ['anon','authenticated','service_role'])for(const fn of ['private.dashboard_actor_data_scope(uuid)','private.dashboard_actor_has_permission(uuid,text)','private.dashboard_actor_can_manage_account(uuid,uuid,text)'])assert.equal(await scalar("select has_function_privilege($1,$2,'EXECUTE')",[actor,fn]),false);
 assert.equal(await scalar("select has_function_privilege('anon','public.dashboard_account_action_allowed(uuid,text)','EXECUTE')"),false);assert.equal(await scalar("select has_function_privilege('authenticated','public.dashboard_account_action_allowed(uuid,text)','EXECUTE')"),true);
});
