// Exact production sync-health function with synthetic receipts and local dates.
const {test,before,beforeEach,after}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const baseline=read('tests/fixtures/dashboard_lg_sync_health_latest_batch-production.sql');
const patch=read('supabase/migrations/20261010141230_dashboard_lg_sync_health_latest_batch.sql');
let setup,db,f,metadata;
const ctx=vm.createContext({__dirname,require:n=>n==='node:test'?{test(){},before:fn=>setup=fn,after(){}}:require(n)});
vm.runInContext(read('tests/admin-sync-health.test.cjs').split(/\ntest\(/)[0]+'\nglobalThis.fixture={get db(){return db},feed,scope};',ctx);
const info=async()=>(await db.query("select md5(prosrc) hash,to_jsonb(p)-'prosrc' metadata,pg_get_functiondef(oid) definition from pg_proc p where oid='private.dashboard_admin_live_sync_health_rows(timestamptz)'::regprocedure")).rows[0];
const call=async(asof='2026-09-26T01:00:00Z')=>(await db.query('select * from private.dashboard_admin_live_sync_health_rows($1::timestamptz)',[asof])).rows;
const lg=(raw='LG-A',country='PH',display='菲律宾',directions=['charge','withdraw'],extra={})=>({dataset:'lg_orders',system:'LG',name:raw,country:display,rawCountry:country,rawPlatform:raw,directions,timezone:'Asia/Manila',provenance:{kind:'direct'},...extra});
const receipt=async(day,status='published',extra={})=>db.query('insert into lg_sync_runs values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[extra.country||'PH',extra.platform||'LG-A',day,extra.kind||'recharge',status,extra.mode||'full',Object.hasOwn(extra,'expected')?extra.expected:0,Object.hasOwn(extra,'fetched')?extra.fetched:0,extra.published??'2026-09-26T00:00:00Z',extra.observed??'2026-09-26T00:00:00Z']);
async function compare(asof){await db.exec(baseline);const old=await call(asof);await db.exec(patch);assert.deepEqual(await call(asof),old);return old;}
before(async()=>{await setup();f=ctx.fixture;db=f.db;await db.exec(`create function private.dashboard_admin_wg_current_feeds(jsonb) returns jsonb language sql immutable as $$select $1$$;set check_function_bodies=off;`);await db.exec(baseline);metadata=(await info()).metadata;assert.equal((await info()).hash,'cb9773a8b4e1a5bc4dc93bb92e6586cc');});
beforeEach(async()=>{await f.scope('{"mode":"all"}');await db.exec(baseline);await db.exec("delete from fixture_feeds where value->>'dataset'='lg_orders';truncate lg_orders,lg_sync_runs;delete from fixture_platforms where source='lg';");});
after(async()=>db?.close());
test('latest collecting/live/superseded receipts override older full snapshots and preserve every status',async()=>{await f.feed(lg());for(const [day,status,extra]of [['2026-09-25','collecting',{}],['2026-09-24','live',{mode:'live'}],['2026-09-23','superseded',{}],['2026-09-22','published',{expected:2,fetched:1}],['2026-09-21','published',{}],['2026-09-20','unknown',{}],['2026-09-19','published',{expected:null,fetched:null}]]){await receipt(day,'published',{observed:'2026-09-25T00:00:00Z'});await receipt(day,status,extra);}const rows=(await compare()).filter(r=>r.platform==='LG-A'&&r.direction==='charge');assert.equal(rows.find(r=>r.data_date.toISOString().startsWith('2026-09-25')).status,'pending');assert.equal(rows.find(r=>r.data_date.toISOString().startsWith('2026-09-24')).evidence,'source_full_day_not_published');assert.equal(rows.find(r=>r.data_date.toISOString().startsWith('2026-09-23')).status,'unverified');assert.equal(rows.find(r=>r.data_date.toISOString().startsWith('2026-09-22')).received,false);assert.equal(rows.find(r=>r.data_date.toISOString().startsWith('2026-09-21')).evidence,'source_completed_zero_rows');assert.equal(rows.find(r=>r.data_date.toISOString().startsWith('2026-09-20')).received,false);});
test('country/platform/direction loops never reuse another scope or prior day zero evidence',async()=>{await f.feed(lg());await f.feed(lg('LG-B'));await f.feed(lg('LG-A','IN','印度',['charge'],{timezone:'Asia/Kolkata'}));await receipt('2026-09-25');await receipt('2026-09-24','published',{platform:'LG-B',expected:4,fetched:4});await receipt('2026-09-25','collecting',{kind:'withdraw'});const rows=(await compare()).filter(r=>r.dataset==='lg_orders');const a=rows.filter(r=>r.platform==='LG-A'&&r.country==='菲律宾');assert.equal(a.filter(r=>r.received).length,1);assert(a.filter(r=>r.direction==='withdraw').every(r=>!r.received));assert(rows.filter(r=>r.country==='印度').every(r=>!r.received));assert.equal(rows.filter(r=>r.platform==='LG-B'&&r.received).length,1);assert(a.filter(r=>r.direction==='charge'&&!r.data_date.toISOString().startsWith('2026-09-25')).every(r=>r.evidence!=='source_completed_zero_rows'));});
test('seven previous local dates and firstDate bounds exclude today/future/outside receipts',async()=>{await f.feed(lg('LG-A','PH','菲律宾',['charge'],{firstDate:'2026-09-24'}));for(const d of ['2026-09-18','2026-09-23','2026-09-24','2026-09-25','2026-09-26','2026-09-27'])await receipt(d);const rows=(await compare('2026-09-25T16:00:00Z')).filter(r=>r.platform==='LG-A');assert.deepEqual(rows.map(r=>r.data_date.toISOString().slice(0,10)),['2026-09-25','2026-09-24']);assert(rows.every(r=>r.received));await f.feed(lg('FUTURE','PH','菲律宾',['charge'],{firstDate:'2026-09-27'}));await compare();assert(!(await call()).some(r=>r.platform==='FUTURE'));});
test('native registered LG feeds, stored rows and fresh account scope retain their original rules',async()=>{await db.exec(`insert into fixture_platforms values('20000000-0000-4000-8000-000000000001','LG-NATIVE','M8','菲律宾','PH','lg','Asia/Manila','PHP','LG-A');insert into lg_orders values('PH','LG-A','recharge','2026-09-24T16:00:00Z','2026-09-25T20:00:00Z');`);await receipt('2026-09-24');const rows=(await compare()).filter(r=>r.platform==='LG-NATIVE');assert.equal(rows.filter(r=>r.received).length,2);assert.equal(rows.find(r=>r.data_date.toISOString().startsWith('2026-09-25')&&r.direction==='charge').evidence,'records_received_completeness_unverified');await f.scope('{"countries":["印度"]}');assert(!(await call()).some(r=>r.platform==='LG-NATIVE'));await f.scope('');await assert.rejects(()=>call(),/unauthorized/);});
test('same observed_at with conflicting states keeps the exact original daily choice',async()=>{await f.feed(lg());await receipt('2026-09-25','collecting');await receipt('2026-09-25','published');await receipt('2026-09-24','published');await receipt('2026-09-24','superseded');await compare();});
test('metadata and signature stay unchanged; replay is safe and drift fails closed',async()=>{await db.exec(patch);const next=await info();assert.equal(next.hash,'4f7b6f978b78830054406d97aee8aa24');assert.deepEqual(next.metadata,metadata);await db.exec(patch);assert.deepEqual(await info(),next);for(const sql of ["alter function private.dashboard_admin_live_sync_health_rows(timestamptz) set jit=on","grant execute on function private.dashboard_admin_live_sync_health_rows(timestamptz) to authenticated",next.definition.replace('begin\n','begin\n -- drift\n')]){await db.exec('begin');await db.exec(sql);await assert.rejects(()=>db.exec(patch),/metadata_drift|baseline_drift/);await db.exec('rollback');}});
