// Real PostgreSQL execution with synthetic fee publications and native orders.
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{createRequire}=require('node:module');
const root=path.join(__dirname,'..'),helper=fs.readFileSync(path.join(root,'supabase/migrations/20261002095221_fee_channel_category_overloads.sql'),'utf8');
const dual=fs.readFileSync(path.join(root,'supabase/migrations/20261002095755_usdt_dual_amount_details.sql'),'utf8'),queryPatch=fs.readFileSync(path.join(root,'supabase/migrations/20261002100315_fee_channel_category_query.sql'),'utf8');
let f,db,native;
before(async()=>{let setup;const filename=path.join(__dirname,'fee-effective-versions.test.cjs'),req=createRequire(filename),ctx={require:n=>n==='node:test'?{test(){},before:fn=>setup=fn,after(){}}:req(n),__dirname,process,console,structuredClone};vm.createContext(ctx);vm.runInContext(fs.readFileSync(filename,'utf8')+'\nglobalThis.fixture={get db(){return db},get native(){return f},input,publish,quote,rate,evidence,scalar,rollback};',ctx,{filename});await setup();f=ctx.fixture;db=f.db;native=f.native;await db.exec(helper);await db.exec(dual);await db.exec(queryPatch);});
after(()=>db?.close());
const scalar=(q,args)=>f.scalar(q,args),rollback=fn=>f.rollback(fn);
const category=(value,country='VN')=>scalar('select private.dashboard_admin_fee_category($1,$2)',[country,value]);
const quote=(type,extra={})=>scalar('select private.dashboard_admin_fee_quote($1,$2,$3,$4,$5,$6,$7,$8)',[extra.country||'VN','Synthetic',extra.provider||'SelectedPay',extra.direction||'charge',extra.currency===undefined?'VND':extra.currency,extra.created===undefined?'2026-09-19T10:00:00+07:00':extra.created,extra.amount===undefined?1000:extra.amount,type]);
async function publish(categories=['BANKQR','MOMO','THẺ CÀO','ZALO'],overrides={}){const rates=categories.map((category,i)=>f.rate({id:'rate'+i,country:'VN',category,collect_fee:(i+1)+'%',payout_fee:(i+5)+'%',...overrides})),ev=rates.map(r=>f.evidence({id:r.id,effectiveFrom:'2026-09-18T00:00:00+07:00'}));return f.publish(f.input(rates,ev));}
test('only confirmed anchored VN tokens and exact observed categories resolve; unknown abbreviations and provider defaults do not',async()=>rollback(async()=>{
 await publish();for(const [value,expected]of [['MOMO','MOMO'],['MoMo1','MOMO'],[' MOMO001 ','MOMO'],['CARD2','THẺ CÀO'],['QR01','BANKQR'],['BankQR','BANKQR'],['ZALO9','ZALO'],['THẺ CÀO','THẺ CÀO']])assert.equal(await category(value),expected,value);
 for(const value of ['VT','CK','MOMOX','xMOMO1','CARDINAL','QR-bank','1VNPay','1VNPay-QR','OTHER',null,''])assert.equal(await category(value),null,value);
 assert.equal(await category('MOMO1','IN'),null);assert.equal(await category('BANKQR','IN'),null);
 await f.publish(f.input([f.rate({category:'BANK'})]));assert.equal(await category(' bank ','IN'),'BANK');assert.equal(await category('BANK2','IN'),null);
}));
test('strict category overload prices each tier; legacy and unknown-category ambiguity are unchanged',async()=>rollback(async()=>{
 await publish();for(const [type,amount]of [['BANKQR',10],['MOMO',20],['THẺ CÀO',30],['ZALO',40]]){assert.equal(Number((await quote(type)).fee_version_estimated_amount),amount);assert.equal(Number((await quote(type,{direction:'withdraw'})).fee_version_estimated_amount),amount+40);}
 assert.equal((await quote(null)).fee_version_state,'unknown');assert.equal((await quote('not-a-category')).fee_version_state,'unknown');
 assert.equal((await scalar("select private.dashboard_admin_fee_quote('VN','Synthetic','SelectedPay','charge','VND','2026-09-19Z',1000)")).fee_version_state,'unknown');
 const all=await scalar("select jsonb_agg(to_jsonb(v)) from private.dashboard_admin_fee_intervals('VN','Synthetic','SelectedPay','charge','VND') v"),fallback=await scalar("select jsonb_agg(to_jsonb(v)) from private.dashboard_admin_fee_intervals('VN','Synthetic','SelectedPay','charge','VND',NULL) v");assert.deepEqual(fallback,all);

}));
test('unknown category preserves unambiguous legacy fallback while a known different category cannot borrow it',async()=>rollback(async()=>{
 await publish(['BANKQR']);assert.equal(Number((await quote(null)).fee_version_estimated_amount),10);assert.equal((await quote(await category('CARD1'))).fee_version_state,'unknown');
}));
test('missing or conflicting evidence in another category does not block the explicit category; same-category evidence still blocks',async()=>rollback(async()=>{
 const rates=[f.rate({id:'bank',country:'VN',category:'BANKQR'}),f.rate({id:'momo',country:'VN',category:'MOMO',collect_fee:'2%'})],ev=[f.evidence({id:'bank'}),f.evidence({id:'momo',state:'missing_effective_time',effectiveFrom:null})];await f.publish(f.input(rates,ev));
 assert.equal(Number((await quote('BANKQR')).fee_version_estimated_amount),10);assert.equal((await quote('MOMO')).fee_version_state,'unknown');assert.equal((await quote(null)).fee_version_state,'unknown');
 await f.publish(f.input([...rates,f.rate({id:'bank-missing',country:'VN',category:'BANKQR'})],[...ev,f.evidence({id:'bank-missing',effectiveFrom:null,state:'missing_effective_time'})]));assert.equal((await quote('BANKQR')).fee_version_state,'unknown');
}));
test('each category retains immutable creation-time intervals, finite values and currency/provider isolation',async()=>rollback(async()=>{
 await publish(['MOMO','BANKQR']);await f.publish(f.input([f.rate({id:'rate0',country:'VN',category:'MOMO',collect_fee:'9%'}),f.rate({id:'rate1',country:'VN',category:'BANKQR',collect_fee:'2%'})],[f.evidence({id:'rate0',effectiveFrom:'2026-09-19T12:00:00+07:00'}),f.evidence({id:'rate1',effectiveFrom:'2026-09-18T00:00:00+07:00'})]));
 assert.equal(Number((await quote('MOMO',{created:'2026-09-19T11:59:59.999+07:00'})).fee_version_estimated_amount),10);assert.equal(Number((await quote('MOMO',{created:'2026-09-19T12:00:00+07:00'})).fee_version_estimated_amount),90);assert.equal(Number((await quote('BANKQR')).fee_version_estimated_amount),20);
 for(const extra of [{country:'IN'},{provider:'Another'},{currency:null},{created:'Infinity'},{created:'-Infinity'},{created:null},{amount:'Infinity'},{amount:'NaN'}])assert.equal((await quote('MOMO',extra)).fee_version_state,'unknown',JSON.stringify(extra));
 const r=f.rate({country:'VN',category:'MOMO',collect_single_fee:'6'});await f.publish(f.input([r],[f.evidence({currency:'VND',effectiveFrom:'2026-09-20T00:00:00+07:00'})]));assert.equal((await quote('MOMO',{created:'2026-09-21Z',currency:'INR'})).fee_version_state,'unknown');
}));
test('private overloads preserve all old helper bodies and never expose pricing tables/functions through role grants',async()=>rollback(async()=>{
 const signatures=['private.dashboard_admin_fee_category(text,text)','private.dashboard_admin_fee_intervals(text,text,text,text,text,text)','private.dashboard_admin_fee_quote(text,text,text,text,text,timestamptz,numeric,text)'];for(const signature of signatures){for(const role of ['anon','authenticated','service_role'])assert.equal(await scalar('select has_function_privilege($1,$2,\'EXECUTE\')',[role,signature]),false);assert.deepEqual(await scalar("select jsonb_build_array(proowner='postgres'::regrole,prosecdef,provolatile,proconfig) from pg_proc where oid=$1::regprocedure",[signature]),[true,true,'s',['search_path=""']]);}
 for(const [signature,hash]of [['private.dashboard_admin_fee_intervals(text,text,text,text,text)','cdb33dd98475b05bae412fb01e20d296'],['private.dashboard_admin_fee_quote(text,text,text,text,text,timestamptz,numeric)','4092a402362a32f85d9fdd24e3e6204c']])assert.equal(await scalar('select md5(prosrc) from pg_proc where oid=$1::regprocedure',[signature]),hash);
 const guard=helper.match(/do \$fee_category_baseline\$[\s\S]*?end \$fee_category_baseline\$;/)[0];await db.exec('savepoint drift;grant execute on function private.dashboard_admin_fee_intervals(text,text,text,text,text) to authenticated');await assert.rejects(db.exec(guard),/fee_category_metadata_drift/);await db.exec('rollback to drift');
}));
async function vnRows(rows){await db.exec("insert into ar_config_targets values('VN','VN-Synthetic','越南','Asia/Ho_Chi_Minh','VND','AR')");for(const [order,type,amount=1000,created='2026-09-19 01:00']of rows)await db.query("insert into ar_collected_orders(source_system,country_code,platform,order_kind,order_no,amount,status,applied_at,completed_at,raw_channel,channel_type) values('AR','VN','VN-Synthetic','recharge',$1,$2,'已支付',$3,'2026-09-19 04:00','SelectedPay',$4)",[order,amount,created,type]);return scalar("select md5('ar:VN:VN-Synthetic')::uuid::text");}
const vnRequest=(platformId,extra={})=>({action:'aggregate',platformId,startAt:'2026-09-19T00:00:00+07:00',endAt:'2026-09-20T00:00:00+07:00',direction:'charge',status:'all',...extra});
test('native AR full/providers/detail price distinct channels and conserve one provider total without duplicate orders',async()=>rollback(async()=>{
 await publish();const id=await vnRows([['M','MOMO1'],['M2','MOMO2'],['C','CARD2'],['Q','QR01'],['Z','ZALO'],['V','VT'],['K','CK'],['F','MOMOX']]);
 for(const view of ['full','providers']){const r=await native.call(vnRequest(id,{view}));assert.equal(r.groups.provider.length,1);const p=r.groups.provider[0];assert.equal(p.all_count,8);assert.equal(p.success_count,8);assert.equal(Number(p.success_amount),8000);assert.equal(p.fee_version_matched_count,5);assert.equal(p.fee_version_unmatched_count,3);assert.equal(Number(p.fee_version_estimated_amount),120);assert.equal(p.fee_version_state,'partial');}
 const detail=await native.call(vnRequest(id,{action:'details',status:'success'}));assert.equal(detail.rows.length,8);assert.equal(new Set(detail.rows.map(r=>r.id)).size,8);const expected={M:[20,'MOMO'],M2:[20,'MOMO'],C:[30,'THẺ CÀO'],Q:[10,'BANKQR'],Z:[40,'ZALO']};for(const r of detail.rows){if(expected[r.order_number]){const [amount,category]=expected[r.order_number];assert.equal(Number(r.fee_version_estimated_amount),amount);assert.equal(r.fee_version_category,category);assert.equal(Number(r.fee_version_percent_rate),amount/1000);assert.equal(Number(r.fee_version_fixed_fee),0);}else assert.equal(r.fee_version_state,'unknown');}
 for(const view of ['full','providers']){const p=(await native.call(vnRequest(id,{view,channelTypes:['MOMO1','CARD2']}))).groups.provider[0];assert.equal(p.success_count,2);assert.equal(p.fee_version_matched_count,2);assert.equal(Number(p.fee_version_estimated_amount),50);}
}));
test('raw category matching prices by creation-time boundary and native currency proof still fails closed',async()=>rollback(async()=>{
 await publish(['MOMO','BANKQR']);await f.publish(f.input([f.rate({id:'rate0',country:'VN',category:'MOMO',collect_fee:'9%'}),f.rate({id:'rate1',country:'VN',category:'BANKQR',collect_fee:'2%'})],[f.evidence({id:'rate0',effectiveFrom:'2026-09-19T00:00:00+07:00'}),f.evidence({id:'rate1',effectiveFrom:'2026-09-18T00:00:00+07:00'})]));
 const id=await vnRows([['BEFORE','MOMO1',1000,'2026-09-18 23:59:59.999'],['AFTER','MOMO1',1000,'2026-09-19 00:00:00'],['BANK','QR2']]);for(const view of ['full','providers']){const p=(await native.call(vnRequest(id,{view}))).groups.provider[0];assert.equal(p.success_count,3);assert.equal(p.fee_version_matched_count,3);assert.equal(Number(p.fee_version_estimated_amount),120);}
 await db.exec("update ar_config_targets set currency=null where country_code='VN'");for(const view of ['full','providers']){const p=(await native.call(vnRequest(id,{view}))).groups.provider[0];assert.equal(p.fee_version_state,'unknown');assert.equal(p.fee_version_matched_count,0);assert.equal(p.fee_version_unmatched_count,3);assert.equal(p.fee_version_estimated_amount,null);}
 const d=await native.call(vnRequest(id,{action:'details',status:'success'}));assert.ok(d.rows.every(r=>r.fee_version_state==='unknown'));
}));
test('type forward preserves the AR dual monetary proof and original query scope denial',async()=>rollback(async()=>{
 await native.add('ar','charge','DUAL-TYPED',1000);await db.exec("update ar_collected_orders set raw_channel='USDT(TRC20)-3',amount=null,amount_text=E'金额： 1000\\n兑换比例： 80\\nUSDT： 12.5' where order_no='DUAL-TYPED'");
 const row=(await native.call(native.request('ar',{action:'details',direction:'charge'}))).rows.find(r=>r.order_number==='DUAL-TYPED');assert.equal(row.settlement_currency,'USDT');assert.equal(row.settlement_amount,'12.5');assert.equal(Number(row.amount),1000);assert.equal(row.fee_version_state,'unknown');
 await native.as('10000000-0000-0000-0000-000000000002');await db.exec('savepoint denied');await assert.rejects(native.call(native.request('ar')),/platform_denied|preview_denied/);await db.exec('rollback to denied');
}));
test('type query forward preserves OID/full metadata, changes only bounded fee projection and guards drift',async()=>rollback(async()=>{
 const signature='private.dashboard_admin_live_query_raw(jsonb)',old=fs.readFileSync(path.join(root,'supabase/migrations/20261002080803_immutable_fee_effective_versions.sql'),'utf8').match(/execute \$definition_0\$([\s\S]*?)\$definition_0\$/)[1];await db.exec(old);await db.exec(dual.match(/do \$patch_dual_money\$[\s\S]*?end \$patch_dual_money\$;/)[0]);
 const metadata=()=>scalar("select to_jsonb(p)-'prosrc' from pg_proc p where oid=$1::regprocedure",[signature]),patch=queryPatch.match(/do \$fee_channel_query\$[\s\S]*?end \$fee_channel_query\$;/)[0],before=await metadata();await db.exec('savepoint beforepatch');await db.exec(patch);assert.deepEqual(await metadata(),before);assert.equal(await scalar('select md5(prosrc) from pg_proc where oid=$1::regprocedure',[signature]),'7b096f2ec23ad7bc280675351224cb9c');await db.exec('rollback to beforepatch');
 for(const statement of ['grant execute on function '+signature+' to authenticated','alter function '+signature+" set work_mem='8MB'"]){await db.exec('savepoint badmeta;'+statement);await assert.rejects(db.exec(patch),/fee_channel_query_metadata_drift/);await db.exec('rollback to badmeta');}
 await db.exec('savepoint badhelper;grant execute on function private.dashboard_admin_fee_quote(text,text,text,text,text,timestamptz,numeric,text) to authenticated');await assert.rejects(db.exec(patch),/fee_channel_helper_drift/);await db.exec('rollback to badhelper');
 await db.exec(old);await db.exec('savepoint badbody');await assert.rejects(db.exec(patch),/fee_channel_query_baseline_drift/);await db.exec('rollback to badbody');
}));

test('non-VN exact categories and legacy unknown types retain fees for existing native sources',async()=>rollback(async()=>{
 await f.publish(f.input());for(const source of ['ar','newar'])for(const view of ['full','providers']){const r=await native.call(native.request(source,{direction:'charge',view}));for(const p of r.groups.provider){assert.equal(p.fee_version_matched_count+p.fee_version_unmatched_count,p.success_count);if(p.provider==='SelectedPay'){assert.ok(p.fee_version_matched_count>0);assert.ok(Number(p.fee_version_estimated_amount)>0);}}}
 const r=(await native.call(native.request('newar',{action:'details',direction:'charge',status:'success'}))).rows.find(x=>x.provider==='SelectedPay'&&Number(x.amount)===100);assert.equal(r.fee_version_category,'BANK');assert.equal(Number(r.fee_version_estimated_amount),1);
}));
