'use strict';
// Real collector route, publisher, archive and new migration in offline Postgres.
// Only mapping-row drift hashes are substituted for synthetic fixture rows.
const {test,beforeEach,afterEach}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {PGlite}=require('@electric-sql/pglite');
const read=f=>fs.readFileSync(path.join(__dirname,f),'utf8');
const collectorBase=read('fixtures/collector-identity-baseline-functions.sql');
const collectorMigration=read('../supabase/migrations/20261001154904_collector_exact_identity_receipts.sql');
const archiveMigration=read('../supabase/migrations/20261002065625_pending_capture_archive.sql');
const migration=read('../supabase/migrations/20261002080201_pending_native_spelling_identity_enrollment.sql');
const targets=[['NEW_AR','DHANIWIN','DhaniWin','INR','e1bdaed762d94d2811c1bc6a1712f8db'],['AR','SHREE.WIN','Shree.Win',null,'8205133f2e564ec476c3a9615a2b36d2'],['AR','VEER.GAME','Veer.Game',null,'d02a0000d2a9e0a7bc5cd2dc7b24869b']];
const kinds=['ar_business_direct','collection_success','workorder_issue','newar_detail','newar_business'];
const hashes=Object.fromEntries(kinds.map((x,i)=>[x,String(i+1).repeat(64)]));
const signatures=['public.publish_ar_collected_orders(text,jsonb)','public.publish_collection_success_snapshot(text,jsonb)','public.publish_workorder_issue_snapshot(text,jsonb)','private.ingest_newar_detail_batch(text,jsonb)','private.ingest_newar_business_batch(text,jsonb)'];
const pendingSignatures=['public.publish_withdraw_pending_details(text,jsonb,jsonb)','public.publish_withdraw_pending_snapshot(text,jsonb)','public.refresh_withdraw_pending_backlog()'];
const hashToken='8'.repeat(64);
let db,sql;
async function setup(){const d=new PGlite();db=d;await d.exec(`create schema private;create schema extensions;create role anon;create role authenticated;create role service_role bypassrls;grant usage on schema private,extensions to service_role;
create function extensions.digest(v text,a text)returns bytea language sql immutable as $$select sha256(convert_to(v,'UTF8'))$$;`);
 const constraint=[...collectorBase.matchAll(/CREATE OR REPLACE FUNCTION ([\s\S]*?)\$function\$\s*;/g)].map(m=>m[0]).find(x=>x.startsWith('CREATE OR REPLACE FUNCTION public.workorder_issue_scopes_are_allowed('));
 await d.exec(constraint);await d.exec(read('fixtures/collector-identity-baseline-schema.sql'));await d.exec(collectorBase);
 for(const sig of signatures)await d.exec(`revoke all on function ${sig}from public,anon,authenticated;grant execute on function ${sig}to service_role;`);
 const pendingSchema=read('fixtures/pending-analysis/pending-capture-publisher-schema.sql');
 await d.exec([...pendingSchema.matchAll(/create table public\.withdraw_pending_[\s\S]*?;\n/g)].map(m=>m[0]).join('\n'));
 await d.exec(read('fixtures/pending-analysis/pending-capture-publisher-baseline.sql'));
 for(const sig of pendingSignatures)await d.exec(`revoke all on function ${sig}from public,anon,authenticated;grant execute on function ${sig}to service_role;`);
 await d.exec('create trigger withdraw_pending_backlog_refresh after insert on withdraw_pending_order_receipts for each row execute function public.refresh_withdraw_pending_backlog();grant select,insert,update,delete on all tables in schema public to service_role;');
 for(const [source,old,native,currency]of targets){await d.query(`insert into dashboard_platform_team_map(team_name,system_name,source_system,country_name,country_code,source_country,platform_name,source_platform)values('M8',$1,$1,'印度','IN','印度',$2,$3)`,[source,old.replace('.',''),old]);
  if(source==='AR')await d.query(`insert into ar_config_targets(country_code,platform,country_name,timezone,currency,source_system)values('IN',$1,'印度','Asia/Kolkata',$2,'AR')`,[native,currency]);
  else await d.query(`insert into newar_detail_platforms(platform,country_code,country,timezone,currency)values($1,'IN','印度','Asia/Kolkata',$2)`,[native,currency]);}
 const raw=[{country_code:'IN',platform:'Shree.Win',timezone:'Asia/Kolkata'},{country_code:'IN',platform:'Veer.Game',timezone:'Asia/Kolkata'},{country_code:'IN',platform:'DhaniWin',timezone:'Asia/Kolkata'},{country_code:'PK',platform:'Shree.Win',timezone:'Asia/Karachi'},{country_code:'IN',platform:'SHREE.WIN',timezone:'Asia/Kolkata'}];
 for(const kind of kinds){const table=kind.startsWith('newar_')?'private.'+kind+'_credentials':'public.'+kind+'_credentials';let scopes=raw;
  if(kind==='ar_business_direct')scopes=raw.map(({country_code,platform})=>({country_code,platform}));if(kind==='workorder_issue')scopes=[raw[2]];
  if(kind==='newar_detail')scopes=[{platform:'DhaniWin',dataset:'workorder'}];if(kind==='newar_business')scopes=[{platform:'DhaniWin',kind:'auto_withdraw_bundle'}];
  const system=kind==='collection_success'?'RECHARGE_REVIEW':kind==='workorder_issue'?'AR_WORKORDER':null;
  await d.query(`insert into ${table}(token_hash,allowed_scopes,expires_at${system?',source_system':''}${kind==='collection_success'?',allowed_source_systems':''})values($1,$2::jsonb,now()+interval '1 day'${system?',\''+system+'\'':''}${kind==='collection_success'?',array[\'RECHARGE_REVIEW\',\'WITHDRAW_REVIEW\']':''})`,[hashes[kind],JSON.stringify(scopes)]);}
 await d.query(`insert into withdraw_pending_credentials(token_hash,source_system,allowed_scopes,expires_at)values($1,'WITHDRAW_REVIEW',$2::jsonb,now()+interval '1 day')`,[hashToken,JSON.stringify(raw.slice(0,3))]);
 await d.exec(collectorMigration);await d.exec(archiveMigration);return d;}
async function fixtureSql(d){await d.exec("set timezone='UTC'");let text=migration;for(const[,old,,,guard]of targets){const v=(await d.query('select md5(to_jsonb(m)::text)hash from dashboard_platform_team_map m where source_platform=$1',[old])).rows[0].hash;assert.equal(text.split(guard).length,2);text=text.replace(guard,v);}return text;}
async function route(kind,scope,d=db){return(await d.query('select private.collector_resolve_exact_route_v1($1,$2,$3::jsonb)r',[kind,hashes[kind],JSON.stringify(scope)])).rows[0].r;}
async function capture(platform,at,d=db){const end=(await d.query("select (($1::timestamptz at time zone 'Asia/Kolkata')::date-1)::text captured_day",[at])).rows[0].captured_day;const days=(await d.query("select to_char($1::date-n,'YYYY-MM-DD') captured_day from generate_series(6,0,-1)n",[end])).rows.map(r=>r.captured_day);
 for(const day of days){const snapshot={schema_version:1,source_system:'WITHDRAW_REVIEW',country_code:'IN',platform,stat_date:day,timezone:'Asia/Kolkata',snapshot_id:randomUUID(),snapshot_at:at,coverage:{complete:true,expected_count:0,fetched_count:0,unique_count:0},totals:{pending_count:0,pending_amount:0},groups:[]};await d.query('select public.publish_withdraw_pending_details($1,$2::jsonb,$3::jsonb)',[hashToken,JSON.stringify(snapshot),JSON.stringify({details_version:1,chunk_count:0,order_count:0})]);}
 return(await d.query('select * from private.withdraw_pending_capture_archive where platform=$1 and snapshot_at=$2',[platform,at])).rows[0];}
beforeEach(async()=>{db=await setup();sql=await fixtureSql(db);await db.exec('begin');});afterEach(async()=>{await db?.close();db=null;});
test('full exact alignment and existing scopes resolve three future identities without guessing null currency',async()=>{const oldMaps=(await db.query('select id,to_jsonb(m)-array[\'source_platform\',\'updated_at\']v from dashboard_platform_team_map m order by id')).rows;
 const credentials=(await db.query('select token_hash,allowed_scopes from collection_success_credentials')).rows;const sourceInstances=(await db.query('select * from private.collector_source_instances order by id')).rows;await db.exec(sql);await db.exec('begin');
 const nowMaps=(await db.query('select id,to_jsonb(m)-array[\'source_platform\',\'updated_at\']v from dashboard_platform_team_map m order by id')).rows;assert.deepEqual(nowMaps,oldMaps);assert.deepEqual((await db.query('select token_hash,allowed_scopes from collection_success_credentials')).rows,credentials);
 assert.equal((await db.query('select count(*)n from private.collector_platform_identities')).rows[0].n,3);
 assert.deepEqual((await db.query('select * from private.collector_source_instances order by id')).rows,sourceInstances);assert.equal((await db.query('select count(*)n from private.collector_exact_scope_bindings')).rows[0].n,8);
 for(const [source,,native,currency]of targets){const r=await route(source==='AR'?'ar_business_direct':'newar_detail',source==='AR'?{country_code:'IN',platform:native}:{platform:native,dataset:'workorder'});assert.equal(r.routing_status,'resolved');assert.equal(r.source_system,source);assert.equal(r.team_name,'M8');assert.equal(r.currency,currency);assert.equal(r.country_code,'IN');assert.equal(r.platform_id,(await db.query('select md5($1)::uuid id',[(source==='AR'?'ar':'newar')+':IN:'+native])).rows[0].id);}
 for(const [kind,scope]of [['collection_success',{country_code:'IN',platform:'Veer.Game',timezone:'Asia/Kolkata'}],['workorder_issue',{country_code:'IN',platform:'DhaniWin',timezone:'Asia/Kolkata'}],['newar_business',{platform:'DhaniWin',kind:'auto_withdraw_bundle'}]])assert.equal((await route(kind,scope)).routing_status,'resolved');
 for(const scope of [{country_code:'PK',platform:'Shree.Win'},{country_code:'IN',platform:'SHREE.WIN'}])assert.equal((await route('ar_business_direct',scope)).routing_status,'legacy_unbound');
 assert.equal((await route('collection_success',{country_code:'IN',platform:'Shree.Win',timezone:'UTC'})).routing_status,'legacy_unbound');
});
test('new enrollment cannot repair immutable legacy captures or attach new identity to delayed pre-enrollment observations',async()=>{const oldAt=new Date(Date.now()-60000).toISOString(),old=await capture('Shree.Win',oldAt);assert.equal(old.identity_status,'legacy_unbound');await db.exec(sql);await db.exec('begin');
 assert.deepEqual((await db.query('select * from private.withdraw_pending_capture_archive where id=$1',[old.id])).rows[0],old);
 const delayed=await capture('Veer.Game',new Date(Date.now()-30000).toISOString());assert.equal(delayed.identity_status,'legacy_unbound');assert.equal(delayed.team_name,null);
 const fresh=await capture('Shree.Win',new Date(Date.now()+60000).toISOString());assert.equal(fresh.identity_status,'resolved');assert.equal(fresh.team_name,'M8');assert.equal(fresh.currency,null);
});
test('full row, native currency/source and conflicting map drift abort before any spelling or enrollment write',async()=>{for(const change of ["update dashboard_platform_team_map set metadata='{\"unknown\":true}' where source_platform='SHREE.WIN'","update ar_config_targets set currency='INR' where platform='Shree.Win'","update ar_config_targets set source_system='NEW_AR' where platform='Veer.Game'","insert into dashboard_platform_team_map(team_name,system_name,source_system,country_name,country_code,source_country,platform_name,source_platform)values('Other','AR','AR','印度','IN','IN','Shree.Win','Shree.Win')"]){await db.exec('savepoint drift');await db.exec(change);await assert.rejects(()=>db.exec(sql),/pending_spelling_.*drift|pending_spelling_mapping_ambiguous/);await db.exec('rollback');await db.exec('begin');assert.equal((await db.query('select count(*)n from private.collector_platform_identities')).rows[0].n,0);assert.equal((await db.query("select count(*)n from dashboard_platform_team_map where source_platform in('DHANIWIN','SHREE.WIN','VEER.GAME')")).rows[0].n,3);}});
test('expired/revoked existing credentials get no new binding and future registry edits still revoke routing',async()=>{await db.exec("update private.newar_detail_credentials set revoked=true;update private.newar_business_credentials set expires_at=now()-interval '1 second'");await db.exec(sql);await db.exec('begin');for(const[kind,scope]of [['newar_detail',{platform:'DhaniWin',dataset:'workorder'}],['newar_business',{platform:'DhaniWin',kind:'auto_withdraw_bundle'}]])assert.equal((await route(kind,scope)).routing_status,'legacy_unbound');
 const scope={country_code:'IN',platform:'Shree.Win'};assert.equal((await route('ar_business_direct',scope)).routing_status,'resolved');await db.exec("update dashboard_platform_team_map set team_name='OTHER'where source_platform='Shree.Win'");assert.equal((await route('ar_business_direct',scope)).reason_code,'mapping_changed');});
test('publisher/resolver contract and archival privileges stay exact',async()=>{const before=(await db.query("select p.oid,md5(pg_get_functiondef(p.oid))hash,proacl::text acl,prosecdef,proconfig from pg_proc p where p.oid=any($1::regprocedure[])order by p.oid",[[...signatures,...pendingSignatures,'private.collector_resolve_exact_route_v1(text,text,jsonb)']])).rows;await db.exec(sql);await db.exec('begin');assert.deepEqual((await db.query("select p.oid,md5(pg_get_functiondef(p.oid))hash,proacl::text acl,prosecdef,proconfig from pg_proc p where p.oid=any($1::regprocedure[])order by p.oid",[[...signatures,...pendingSignatures,'private.collector_resolve_exact_route_v1(text,text,jsonb)']])).rows,before);
 const privileges=(await db.query("select has_function_privilege('anon',$1,'execute')anon,has_function_privilege('authenticated',$1,'execute')auth,has_function_privilege('service_role',$1,'execute')service",['private.archive_withdraw_pending_capture(text,text,text,timestamptz)'])).rows[0];assert.deepEqual(privileges,{anon:false,auth:false,service:true});
});
test('changed archival function or broader ACL aborts before writes',async()=>{for(const change of ["alter function private.archive_withdraw_pending_capture(text,text,text,timestamptz)set search_path='public'","grant execute on function private.archive_withdraw_pending_capture(text,text,text,timestamptz)to authenticated"]){await db.exec(change);await assert.rejects(()=>db.exec(sql),/pending_spelling_archive_contract_drift/);await db.exec('rollback');await db.exec('begin');assert.equal((await db.query('select count(*)n from private.collector_platform_identities')).rows[0].n,0);assert.equal((await db.query("select count(*)n from dashboard_platform_team_map where source_platform in('DHANIWIN','SHREE.WIN','VEER.GAME')")).rows[0].n,3);}});
test('an already bound selector is never reassigned to another platform',async()=>{const fake=randomUUID(),mapping=randomUUID();await db.query("insert into private.collector_platform_identities(platform_id,mapping_id,source_system,source_country,source_platform,team_name,country_code,timezone,currency)values($1,$2,'AR','印度','OTHER','Other','IN','Asia/Kolkata',null)",[fake,mapping]);await db.query("insert into private.collector_exact_scope_bindings(source_instance_id,scope_key,platform_id)select id,'{\"country_code\":\"IN\",\"platform\":\"Shree.Win\"}'::jsonb,$1 from private.collector_source_instances where credential_kind='ar_business_direct'",[fake]);await db.exec('commit;begin');await assert.rejects(()=>db.exec(sql),/pending_spelling_existing_binding_conflict/);await db.exec('rollback;begin');assert.equal((await db.query("select platform_id from private.collector_exact_scope_bindings where scope_key->>'platform'='Shree.Win'")).rows[0].platform_id,fake);assert.equal((await db.query('select count(*)n from private.collector_platform_identities')).rows[0].n,1);assert.equal((await db.query("select count(*)n from dashboard_platform_team_map where source_platform in('DHANIWIN','SHREE.WIN','VEER.GAME')")).rows[0].n,3);});
