const {test,before,after,beforeEach,afterEach}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {PGlite}=require('@electric-sql/pglite');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const migration=read('supabase/migrations/20260930180000_dashboard_roles.sql');
const listFix=read('supabase/migrations/20260930230000_role_management_list_fix.sql');
const delegated=read('supabase/migrations/20261001142722_delegated_role_account_permissions.sql');
const unified=read('supabase/migrations/20261001142800_unified_ip_rule_management.sql');
const retiredCatalog=read('supabase/migrations/20260930231000_retire_channelquality_role_permission.sql');
const OWNER='11111111-1111-4111-8111-111111111111',ADMIN='22222222-2222-4222-8222-222222222222',VIEWER='33333333-3333-4333-8333-333333333333',LEGACY='44444444-4444-4444-8444-444444444444';
const PORTAL='55555555-5555-4555-8555-555555555555',IP='203.0.113.7';
let db,acl,profiles,roleFunctions,attempt=0;
const scalar=async(q,p=[])=>Object.values((await db.query(q,p)).rows[0])[0];
const sid=id=>id.slice(0,8)+'-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const as=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[id,JSON.stringify({role:'authenticated',sub:id,session_id:sid(id)})]);await db.exec('set role authenticated');};
const sec=async(actor,action,body={},surface='dashboard',ip=IP)=>{await db.exec('reset role');return scalar('select public.application_security_admin($1,$2,$3,$4,$5,$6::jsonb)',[actor,sid(actor),ip,surface,action,JSON.stringify(body)]);};
async function login(id){await db.query('insert into auth.sessions values($1,$2,null)',[sid(id),id]);const username=await scalar('select username from dashboard_profiles where auth_user_id=$1',[id]);const attemptId='00000000-0000-4000-8000-'+String(++attempt).padStart(12,'0');const begin=await scalar('select public.application_auth_begin($1,$2,$3,$4)',['dashboard',username,IP,attemptId]);assert.equal(begin.allowed,true);const done=await scalar('select public.application_auth_finish($1,$2,$3)',[attemptId,'valid',sid(id)]);assert.equal(done.allowed,true);}
const admin=()=>db.exec('reset role');
const manage=async r=>scalar('select public.dashboard_role_manage($1::jsonb)',[JSON.stringify(r)]);
const access=()=>scalar('select public.dashboard_role_access()');
const execute=(page,r)=>scalar('select public.dashboard_admin_execute($1,$2::jsonb)',[page,JSON.stringify(r)]);
const create=async permissions=>(await manage({operation:'create',name:'Role '+crypto.randomUUID(),description:' test ',permissions})).role;
const assign=(id,role,expectedVersion=0)=>manage({operation:'assign',accountId:id,roleId:role.id,expectedVersion});
async function granted(id,permissions){await as(OWNER);const r=await create(permissions);await assign(id,r);await as(id);return r;}
async function denied(fn,pattern=/denied|required|permission/){await db.exec('savepoint denied');try{await assert.rejects(fn,pattern);}finally{await db.exec('rollback to savepoint denied');}}
function fn(source,name){const start=source.indexOf('create '+(source.includes('create or replace function '+name)?'or replace ':'')+'function '+name);const end=source.indexOf('\n$$;',start);return source.slice(start,end+4);}
function originalRoleFunction(name){const start=migration.indexOf('create or replace function '+name+'('),delimiter=name==='private.dashboard_role_catalog'?'$catalog$;':'end;$$;';return migration.slice(start,migration.indexOf(delimiter,start)+delimiter.length);}
before(async()=>{
 db=new PGlite();await db.exec(`create schema private;create schema auth;create role anon;create role authenticated;create role service_role;
 grant usage on schema public,private,auth to authenticated;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant execute on function auth.uid() to authenticated;
 create table dashboard_profiles(auth_user_id uuid primary key,username text unique,role text,active boolean,permissions jsonb,management_permissions jsonb default '{}',data_scope jsonb,updated_at timestamptz default now());
 create table dashboard_admin_preview_grants(auth_user_id uuid primary key,can_view boolean,granted_by uuid,updated_at timestamptz default now());
 create table dashboard_audit_log(id bigint generated by default as identity primary key,actor_user_id uuid,actor_username text not null default '',action text not null,target_username text not null default '',details jsonb not null default '{}',created_at timestamptz not null default now());
 create function private.dashboard_current_data_scope() returns jsonb language sql stable security definer as $$select data_scope from public.dashboard_profiles where auth_user_id=auth.uid()$$;
 insert into dashboard_profiles(auth_user_id,username,role,active,permissions,data_scope) values
 ('${OWNER}','owner','owner',true,'{}','{"mode":"all"}'),('${ADMIN}','admin','admin',true,'{"auto_withdraw":true,"third_party":true}','{"mode":"restricted","platforms":["A"]}'),
 ('${VIEWER}','viewer','viewer',true,'{"auto_withdraw":true,"third_party":true}','{"mode":"restricted","platforms":["B"]}'),('${LEGACY}','legacy','viewer',true,'{"third_party":true}','{"mode":"restricted","platforms":["C"]}');
 insert into dashboard_admin_preview_grants select auth_user_id,true,'${OWNER}',now() from dashboard_profiles;`);
 await db.exec(fn(read('supabase/admin-live-query.sql'),'private.dashboard_admin_live_scope('));
 await db.exec(fn(read('supabase/dashboard-v250-owner-fast-query.sql'),'public.dashboard_has_permission('));
 await db.exec(`revoke all on function private.dashboard_admin_live_scope() from public;
 revoke all on function public.dashboard_has_permission(text) from public;grant execute on function public.dashboard_has_permission(text) to anon,authenticated,service_role;
 create function private.dashboard_admin_live_query(p_request jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$declare scope jsonb:=private.dashboard_admin_live_scope();begin if p_request ? 'fail' then raise exception 'fixture_failure';end if;return jsonb_build_object('request',p_request,'scope',scope,'context',private.dashboard_role_context_valid());end$$;
 create function public.dashboard_admin_live_query(p_request jsonb) returns jsonb language sql stable security invoker as $$select private.dashboard_admin_live_query(p_request)$$;
 grant execute on function private.dashboard_admin_live_query(jsonb),public.dashboard_admin_live_query(jsonb) to authenticated;`);
 for(const name of ['submission_analysis','member_daily','workorder_records','auto_withdraw','deposit_issues','configuration_access','provider_config','platform_assignments'])await db.exec(`create function private.dashboard_admin_live_${name}(p_request jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$begin perform private.dashboard_admin_live_scope();return jsonb_build_object('rpc','${name}','request',p_request);end$$;grant execute on function private.dashboard_admin_live_${name}(jsonb) to authenticated;`);
 await db.exec(`create function private.dashboard_admin_live_configuration_write(p_request jsonb) returns jsonb language plpgsql volatile security definer set search_path='' as $$begin perform private.dashboard_admin_live_scope();if not exists(select 1 from public.dashboard_profiles where auth_user_id=auth.uid() and role in ('owner','admin')) or p_request->>'operation'='grant' and not exists(select 1 from public.dashboard_profiles where auth_user_id=auth.uid() and role='owner') then raise exception 'configuration_denied';end if;return p_request;end$$;
 create function private.dashboard_admin_live_withdraw_note(p_request jsonb) returns jsonb language plpgsql volatile security definer set search_path='' as $$begin perform private.dashboard_admin_live_scope();if not exists(select 1 from public.dashboard_profiles where auth_user_id=auth.uid() and role in ('owner','admin')) or not public.dashboard_has_permission('auto_withdraw') then raise exception 'note_denied';end if;return p_request;end$$;
 grant execute on function private.dashboard_admin_live_configuration_write(jsonb),private.dashboard_admin_live_withdraw_note(jsonb) to authenticated;`);
 acl=await scalar("select jsonb_object_agg(oid::regprocedure::text,proacl::text) from pg_proc where oid in ('private.dashboard_admin_live_scope()'::regprocedure,'public.dashboard_has_permission(text)'::regprocedure)");
 profiles=await scalar('select jsonb_agg(to_jsonb(p) order by username) from dashboard_profiles p');await db.exec(migration);
 roleFunctions=await scalar("select jsonb_object_agg(oid::regprocedure::text,jsonb_build_object('acl',proacl::text,'owner',proowner,'config',proconfig,'secdef',prosecdef,'volatile',provolatile)) from pg_proc where oid in ('private.dashboard_role_catalog()'::regprocedure,'private.dashboard_role_access()'::regprocedure,'public.dashboard_role_manage(jsonb)'::regprocedure)");
 await db.exec(listFix);await db.exec(retiredCatalog);
 await db.exec(fn(read('supabase/migrations/20260916183000_game66_team_dashboard.sql'),'private.dashboard_data_scope_valid('));
 await db.exec(`

 update dashboard_profiles set data_scope='{"mode":"selected","countries":["IN"]}',management_permissions='{"manage_viewers":true}' where role<>'owner';
 update dashboard_profiles set data_scope='{"mode":"all","countries":[]}' where role='owner';`);
 await db.exec(`create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
 create table auth.users(id uuid primary key,email text);create table auth.sessions(id uuid primary key,user_id uuid,not_after timestamptz);
 create table workorder_portal_accounts(auth_user_id uuid primary key,username text,role text,active boolean);
 create table dashboard_security_settings(id smallint primary key,ip_whitelist_enabled boolean,updated_by uuid,updated_at timestamptz);
 create table dashboard_ip_whitelist(id bigint generated always as identity primary key,ip text unique,note text,active boolean,created_by uuid,created_at timestamptz default now(),updated_at timestamptz default now());
 create table private.dashboard_admin_classification_audit(id integer);create table private.dashboard_admin_classification_grants(id integer);create table private.dashboard_admin_provider_overrides(id integer);
 insert into auth.users select auth_user_id,username||'@hensem.local' from dashboard_profiles;
 insert into auth.users values('${PORTAL}','worker@workorder.hensem.local');
 insert into workorder_portal_accounts values('${PORTAL}','worker','agent',true);
 insert into dashboard_security_settings values(1,false,null,now());`);
 await db.exec(read('tests/fixtures/security/application-login-prepare.sql'));
 await db.exec(read('supabase/migrations/20261001122420_application_account_ip_security.sql'));
 await db.exec(delegated);
 await db.exec(unified);
 for(const id of [OWNER,ADMIN,VIEWER,LEGACY])await login(id);
 await sec(OWNER,'upsert-ip-rule',{scope:'global',network:IP});
 await sec(OWNER,'policy',{patch:{ip_enabled:true},expected_version:1});
});
after(async()=>db?.close());beforeEach(async()=>{await db.exec('begin');await as(OWNER);});afterEach(async()=>{await db.exec('rollback');await admin();});

test('unified global and bound-account rules keep attribution, activate exclusive account mode and enforce both versions',async()=>{
 const list=await sec(OWNER,'list-rules');assert.equal(list.policy.ip_enabled,true);assert.equal(list.capabilities.manage_global,true);assert.equal(list.rules[0].scope,'global');assert.equal(list.rules[0].username,null);assert.equal(list.rules[0].updated_by,'owner');
 const initial=list.accounts.find(a=>a.id===LEGACY);const created=await sec(OWNER,'upsert-ip-rule',{scope:'account',user_id:LEGACY,expected_version:initial.version,network:'198.51.100.8',note:'Private office'});const rule=created.rules.find(r=>r.user_id===LEGACY);assert.equal(rule.scope,'account');assert.equal(rule.username,'legacy');assert.equal(rule.ip_mode,'allowlist');assert.equal(rule.version,initial.version+1);assert.equal(rule.updated_by,'owner');assert.equal(typeof rule.updated_at,'string');assert.equal(created.accounts.find(a=>a.id===LEGACY).ip_mode,'allowlist');
 assert.equal(await scalar('select public.application_auth_ip_check($1,$2,$3)',['dashboard',IP,LEGACY]),false);assert.equal(await scalar('select public.application_auth_ip_check($1,$2,$3)',['dashboard','198.51.100.8',LEGACY]),true);assert.equal(await scalar('select public.application_auth_ip_check($1,$2,$3)',['dashboard',IP,VIEWER]),true);
 await denied(()=>sec(OWNER,'set-ip-rule-active',{scope:'account',user_id:LEGACY,id:rule.id,active:false,expected_version:initial.version}),/version_conflict/);
 const updated=await sec(OWNER,'upsert-ip-rule',{scope:'account',user_id:LEGACY,id:rule.id,expected_version:rule.version,network:'198.51.100.9',note:'Changed office'});assert.equal(updated.rules.find(r=>r.user_id===LEGACY).version,rule.version+1);
 const global=updated.rules.find(r=>r.scope==='global');await denied(()=>sec(OWNER,'set-ip-rule-active',{scope:'global',id:global.id,active:false,expected_version:global.version}),/current_ip_would_be_blocked/);assert.equal((await sec(OWNER,'list-rules')).rules.find(r=>r.id===global.id&&r.scope==='global').active,true);
});
test('real assigned IP grant edits an eligible subordinate and never permits global or out-of-scope changes',async()=>{
 const actor=await create(['access.view','access.edit','access.status','ip.view','ip.edit','providers.view']);await assign(ADMIN,actor);const narrow=await create(['providers.view']);await assign(VIEWER,narrow);await as(ADMIN);
 const list=await sec(ADMIN,'list-rules');assert.equal(list.capabilities.manage_global,false);assert.equal(list.capabilities.manage_account,true);assert.equal(list.capabilities.manage_policy,false);assert(!list.rules.some(r=>r.scope==='global'));assert(list.accounts.some(a=>a.id===VIEWER));assert(!list.accounts.some(a=>[OWNER,ADMIN].includes(a.id)));
 const target=list.accounts.find(a=>a.id===VIEWER);const result=await sec(ADMIN,'upsert-ip-rule',{scope:'account',user_id:VIEWER,expected_version:target.version,network:'198.51.100.11'});assert(result.rules.some(r=>r.user_id===VIEWER&&r.ip_mode==='allowlist'));
 await denied(()=>sec(ADMIN,'upsert-ip-rule',{scope:'global',network:'198.51.100.12'}),/security_permission_denied/);
 await admin();await db.query("update dashboard_profiles set data_scope=$1::jsonb where auth_user_id=$2",[JSON.stringify({mode:'selected',countries:['BR']}),LEGACY]);await as(OWNER);await assign(LEGACY,narrow);await denied(()=>sec(ADMIN,'upsert-ip-rule',{scope:'account',user_id:LEGACY,expected_version:1,network:'198.51.100.12'}),/security_permission_denied/);
});
test('real assigned helper rejects owner, self, admin peers, high-role takeover and legacy account IP takeover',async()=>{
 const actor=await create(['access.view','access.edit','access.status','access.reset_password','ip.view','ip.edit','providers.view']);await assign(ADMIN,actor);const high=await create(['providers.view','providers.query']);await assign(VIEWER,high);
 for(const target of [OWNER,ADMIN,VIEWER,LEGACY])await denied(()=>sec(ADMIN,'upsert-ip-rule',{scope:'account',user_id:target,expected_version:1,network:'198.51.100.12'}),/security_permission_denied/);
 await denied(()=>sec(ADMIN,'unlock-account',{user_id:VIEWER,expected_version:1}),/security_permission_denied/);
 await as(ADMIN);assert.equal(await scalar("select public.dashboard_account_action_allowed($1,'access.reset_password')",[VIEWER]),false);await denied(()=>assign(VIEWER,actor,1),/assignment_target_denied/);await denied(()=>assign(ADMIN,actor,1),/assignment_target_denied/);
 await as(OWNER);const narrow=await create(['providers.view']);await assign(LEGACY,narrow);await as(ADMIN);const tooHigh=high;await denied(()=>assign(LEGACY,tooHigh,1),/role_grant_exceeds_actor/);
});
test('account view without IP view never leaks global or account IP inventory through any safety read',async()=>{
 const before=await sec(OWNER,'list-rules');const target=before.accounts.find(a=>a.id===VIEWER);await sec(OWNER,'upsert-ip-rule',{scope:'account',user_id:VIEWER,expected_version:target.version,network:IP});
 await as(OWNER);const actor=await create(['access.view','access.edit']);await assign(ADMIN,actor);await admin();await db.query("update dashboard_profiles set data_scope=$1::jsonb where auth_user_id=$2",[JSON.stringify({mode:'all',countries:[]}),ADMIN]);
 const policy=await sec(ADMIN,'policy');assert.equal(policy.capabilities.view,false);assert.deepEqual(policy.rules,[]);assert.deepEqual(policy.accounts,[]);
 const states=await sec(ADMIN,'list-account-security');assert(states.states.some(s=>s.user_id===VIEWER));assert(states.states.every(s=>s.ip_rules.length===0));
 const account=await sec(ADMIN,'account-security',{user_id:VIEWER});assert.deepEqual(account.security.ip_rules,[]);assert.equal(account.capabilities.manage_ip,false);assert.equal(account.capabilities.unlock,false);
 await denied(()=>sec(ADMIN,'list-rules'),/security_permission_denied/);
});
test('read-only IP grant cannot mutate and an inactive assigned role cannot use old coarse management flags',async()=>{
 const actor=await create(['access.view','ip.view','providers.view']);await assign(ADMIN,actor);const narrow=await create(['providers.view']);await assign(VIEWER,narrow);
 const list=await sec(ADMIN,'list-rules');assert.equal(list.capabilities.manage_account,false);await denied(()=>sec(ADMIN,'upsert-ip-rule',{scope:'account',user_id:VIEWER,expected_version:1,network:IP}),/security_permission_denied/);
 await admin();await db.query('update private.dashboard_roles set active=false where id=$1',[actor.id]);await denied(()=>sec(ADMIN,'list-rules'),/security_permission_denied/);await denied(()=>sec(ADMIN,'policy'),/security_permission_denied/);
});
test('service RPC needs a registered current session and private authorization helpers remain uncallable',async()=>{
 await admin();for(const role of ['anon','authenticated','service_role'])for(const signature of ['private.dashboard_actor_data_scope(uuid)','private.dashboard_actor_has_permission(uuid,text)','private.dashboard_actor_can_manage_account(uuid,uuid,text)','private.application_security_account_authorized(uuid,uuid,text,text)','private.application_security_unified_rules(uuid,text,boolean)'])assert.equal(await scalar("select has_function_privilege($1,$2,'EXECUTE')",[role,signature]),false);
 for(const role of ['anon','authenticated'])assert.equal(await scalar("select has_function_privilege($1,'public.application_security_admin(uuid,uuid,text,text,text,jsonb)','EXECUTE')",[role]),false);
 assert.equal(await scalar("select has_function_privilege('service_role','public.application_security_admin(uuid,uuid,text,text,text,jsonb)','EXECUTE')"),true);
 await scalar("select public.application_revoke_session($1,$2,'dashboard')",[OWNER,sid(OWNER)]);await denied(()=>sec(OWNER,'list-rules'),/security_permission_denied/);await as(OWNER);await denied(()=>manage({operation:'list'}),/application_session_denied/);
});

test('workorder account access requires all data scope and never includes portal administrators',async()=>{
 const actor=await create(['access.view','access.edit','ip.view','ip.edit']);await assign(ADMIN,actor);
 await denied(()=>sec(ADMIN,'upsert-ip-rule',{scope:'account',user_id:PORTAL,expected_version:1,network:'198.51.100.15'},'workorder'),/security_permission_denied/);
 await admin();await db.query("update dashboard_profiles set data_scope=$1::jsonb where auth_user_id=$2",[JSON.stringify({mode:'all',countries:[]}),ADMIN]);
 const list=await sec(ADMIN,'list-rules',{},'workorder');assert.deepEqual(list.accounts.map(a=>a.id),[PORTAL]);const saved=await sec(ADMIN,'upsert-ip-rule',{scope:'account',user_id:PORTAL,expected_version:list.accounts[0].version,network:'198.51.100.15'},'workorder');assert.equal(saved.rules[0].ip_mode,'allowlist');
 await admin();await db.query("update workorder_portal_accounts set role='admin' where auth_user_id=$1",[PORTAL]);const next=await sec(ADMIN,'list-rules',{},'workorder');assert.deepEqual(next.accounts,[]);assert.deepEqual(next.rules,[]);await denied(()=>sec(ADMIN,'account-security',{user_id:PORTAL},'workorder'),/security_permission_denied/);
});

test('a wrong account scope or namespace cannot reuse an existing rule ID',async()=>{
 let list=await sec(OWNER,'list-rules');const target=list.accounts.find(a=>a.id===VIEWER);const saved=await sec(OWNER,'upsert-ip-rule',{scope:'account',user_id:VIEWER,expected_version:target.version,network:IP});const account=saved.rules.find(r=>r.user_id===VIEWER);const global=saved.rules.find(r=>r.scope==='global');
 await denied(()=>sec(OWNER,'upsert-ip-rule',{scope:'global',user_id:VIEWER,id:account.id,expected_version:account.version,network:IP}),/invalid_scope/);
 await denied(()=>sec(OWNER,'delete-ip-rule',{scope:'account',user_id:LEGACY,id:account.id,expected_version:saved.accounts.find(a=>a.id===LEGACY).version}),/rule_not_found/);
 await denied(()=>sec(OWNER,'delete-ip-rule',{scope:'account',user_id:VIEWER,id:account.id,expected_version:account.version},'workorder'),/security_permission_denied/);
 list=await sec(OWNER,'list-rules');assert(list.rules.some(r=>r.id===account.id&&r.scope==='account'));assert(list.rules.some(r=>r.id===global.id&&r.scope==='global'));
});
