const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const {createHash,webcrypto}=require('node:crypto');globalThis.crypto=webcrypto;
function load(name,deps={}){const m={exports:{}};const source=fs.readFileSync(path.join(__dirname,'../supabase/functions/workorder-records-data',name),'utf8');new Function('module','exports','require',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m,m.exports,n=>{assert(n in deps,n);return deps[n];});return m.exports;}
const query=load('query.ts'),{createWorkorderRecordsHandler}=load('handler.ts',{'./query.ts':query});
const proxy='synthetic-proof',hash=createHash('sha256').update(proxy).digest('hex');
const account={auth_user_id:'10000000-0000-4000-8000-000000000001',role:'agent',active:true,team:'Synthetic',platforms:['A']};
const initialIdentity={ok:true,identity_kind:'workorder',account,catalog:{platformTeams:{A:'Synthetic'}}};
const fixture={platform:'A',workorderId:'ID',workorderNo:'WO',orderNo:'RC',sourceOrderNo:'SRC',utr:'0001',issueKind:'deposit',statusCode:4,amount:'123.45678901',kycConnected:null,utrMatched:false,reminderCount:0,fieldGaps:['utr_missing','PRIVATE'],attachmentTypes:['pdf','https://PRIVATE.invalid'],raw:{bank:'PRIVATE'},phone:'PRIVATE',bank:'PRIVATE',attachment_url:'PRIVATE',tenant_id:'PRIVATE'};
function harness(result={sourceStatus:'ready',rows:[],total:0}){let current=initialIdentity;const calls={identify:0,query:[]};const handle=createWorkorderRecordsHandler({identify:async()=>{calls.identify++;return current;},query:async(...args)=>{calls.query.push(args);return result;}},{proxyKeySha256:hash});return{calls,setIdentity:v=>{current=v},request:(body={action:'list'},headers={},method='POST')=>handle(new Request('https://edge.invalid',{method,headers:{'Content-Type':'application/json',Authorization:'Bearer SYNTHETIC-TOKEN','x-portal-proxy-key':proxy,'x-portal-client-ip':'192.0.2.1',...headers},...(method==='POST'?{body:JSON.stringify(body)}:{})}))};}
test('proxy proof, IP and token are mandatory; browsers and mutations never reach data',async()=>{for(const headers of [{'x-portal-proxy-key':''},{'x-portal-proxy-key':'wrong'},{'x-portal-client-ip':'unknown'},{Authorization:''},{Origin:'https://portal.invalid'}]){const h=harness(),r=await h.request({action:'list'},headers);assert([401,403].includes(r.status));assert.equal(h.calls.identify,0);assert.equal(h.calls.query.length,0);assert.equal(r.headers.get('Access-Control-Allow-Origin'),null);}for(const method of ['GET','DELETE','PATCH','OPTIONS']){const h=harness();assert.equal((await h.request({}, {},method)).status,405);}for(const body of [{action:'mirror',record:{}},{action:'delete'},{action:'list',account},{action:'list',filters:{owner:'someone'}}]){const h=harness();assert.equal((await h.request(body)).status,400);assert.equal(h.calls.identify,0);}});
test('every query freshly verifies active workorder identity and current team/platform catalogue',async()=>{const h=harness();assert.equal((await h.request()).status,200);h.setIdentity({...initialIdentity,account:{...account,active:false}});assert.equal((await h.request()).status,403);assert.equal(h.calls.identify,2);assert.equal(h.calls.query.length,1);for(const change of [{identity_kind:'dashboard_owner'},{account:{...account,role:'owner'}},{catalog:{platformTeams:{A:'OTHER'}}}]){const h=harness();h.setIdentity({...initialIdentity,...change});assert.equal((await h.request()).status,403);assert.equal(h.calls.query.length,0);}const a=harness();a.setIdentity({...initialIdentity,account:{...account,role:'auditor'}});assert.equal((await a.request()).status,200);});
test('separate validated AND filters and exact allowed page sizes reach the fixed query RPC',async()=>{for(const limit of [20,50,100]){const h=harness();const f={platform:'A',from:'2026-09-01',to:'2026-09-27',workorderNo:'WO',orderNo:'RC',utr:'0001',statusCode:'4',provider:'Pay',operator:'Employee',minAmount:'1',maxAmount:'20',kyc:'unknown',utrMatch:'no'};assert.equal((await h.request({action:'list',filters:f,limit,offset:limit})).status,200);assert.equal(h.calls.query[0][1].limit,limit);for(const [k,v]of Object.entries(f))assert.equal(h.calls.query[0][1].filters[k],v);}for(const filters of [{platform:'B'},{from:'2026-02-30',to:'2026-03-01'},{from:'2026-01-01',to:'2026-09-27'},{statusCode:'0'},{utr:[]},{provider:'x\u0000'},{minAmount:'2',maxAmount:'1'}]){const h=harness();assert([400,403].includes((await h.request({action:'list',filters})).status));assert.equal(h.calls.query.length,0);}for(const limit of [0,19,101,'50'])assert.equal((await harness().request({action:'list',limit})).status,400);});
test('real records are read-only fixed projections with exact decimal money and no private/source URLs',async()=>{const h=harness({sourceStatus:'ready',rows:[fixture],total:1});const r=await h.request(),data=await r.json(),row=data.rows[0];assert.equal(r.status,200);assert.equal(row.source,'AR');assert.equal(row.amount,'123.45678901');assert.equal(row.statusCode,4);assert.equal(row.readOnly,true);assert.equal(row.retained,true);assert.equal(row.reminderCount,0);assert.equal(row.attachmentAccess,'unavailable');assert.deepEqual(row.attachmentTypes,['pdf']);assert.deepEqual(row.fieldGaps,['utr_missing']);assert(!JSON.stringify(data).includes('PRIVATE'));assert.equal(r.headers.get('Cache-Control'),'private, no-store');});
test('details recheck both exact identifiers and scope and never return an unrelated row',async()=>{const h=harness({sourceStatus:'ready',rows:[fixture],total:1});assert.equal((await h.request({action:'detail',platform:'A',workorderId:'ID'})).status,200);assert.equal((await h.request({action:'detail',platform:'A',workorderId:'OTHER'})).status,503);assert.equal((await h.request({action:'detail',platform:'B',workorderId:'ID'})).status,403);assert.equal((await harness().request({action:'detail',platform:'A',workorderId:'MISSING'})).status,404);for(const row of [{...fixture,platform:'B'},{...fixture,amount:100},{...fixture,statusCode:6}])assert.equal((await harness({sourceStatus:'ready',rows:[row],total:1}).request()).status,503);});
test('not connected is explicit, empty ready is distinct, and failure never fabricates rows',async()=>{const h=harness({sourceStatus:'not_connected',rows:[],total:0}),r=await h.request();assert.equal((await r.json()).sourceStatus,'not_connected');assert.equal((await h.request({action:'detail',platform:'A',workorderId:'ID'})).status,503);assert.equal((await (await harness().request()).json()).sourceStatus,'ready');assert.equal((await harness({sourceStatus:'not_connected',rows:[fixture],total:1}).request()).status,503);});
