"use client";
import {useEffect,useRef,useState} from "react";
import type {DashboardSession} from "@/lib/dashboardAuthClient";
import {securityRequest} from "@/lib/accountSecurityClient";
import AccountEditorDialog from "./AccountEditorDialog";
import "./AccountLoginPolicy.css";

type Surface="dashboard"|"workorder";
type Version=number;
type Policy={failure_limit:number;version:Version};
type Security={failed_count:number;failure_limit:number|null;locked:boolean;locked_at:string|null;version:Version};
type Target={id:string;username:string;active:boolean};
export type AccountLoginSnapshot={status:"loading"|"ready"|"error";states:Record<string,Security>;failureLimit:number|null};
const limit=(value:unknown)=>Number.isInteger(value)&&Number(value)>=1&&Number(value)<=20;
const hasVersion=(value:unknown)=>Number.isInteger(value)&&Number(value)>=1;
function readPolicy(value:any):Policy{const p=value?.policy;if(!p||!limit(p.failure_limit)||!hasVersion(p.version))throw Error("登录策略返回不完整，请重新读取");return p}
function readSecurity(value:any):Security{const s=value?.security;if(!s||!Number.isInteger(s.failed_count)||s.failed_count<0||s.failure_limit!==null&&!limit(s.failure_limit)||typeof s.locked!=="boolean"||!hasVersion(s.version)||s.locked_at!==null&&typeof s.locked_at!=="string")throw Error("账号登录状态返回不完整，请重新读取");return {failed_count:s.failed_count,failure_limit:s.failure_limit,locked:s.locked,locked_at:s.locked_at,version:s.version}}
export default function AccountLoginPolicy({session,surface,target,onClose,onSnapshot}:{session:DashboardSession;surface:Surface;target?:Target|null;onClose?:()=>void;onSnapshot?:(snapshot:AccountLoginSnapshot)=>void}){
 const sessionRef=useRef(session);sessionRef.current=session;const snapshotRef=useRef<AccountLoginSnapshot>({status:"loading",states:{},failureLimit:null}),snapshotListener=useRef(onSnapshot);snapshotListener.current=onSnapshot;
 function publish(snapshot:AccountLoginSnapshot){snapshotRef.current=snapshot;snapshotListener.current?.(snapshot)}
 const [policy,setPolicy]=useState<Policy|null>(null),[defaultLimit,setDefaultLimit]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[revision,setRevision]=useState(0);
 const [security,setSecurity]=useState<Security|null>(null),[override,setOverride]=useState("inherit"),[accountLoading,setAccountLoading]=useState(false),[accountBusy,setAccountBusy]=useState(false),[accountError,setAccountError]=useState(""),[accountMessage,setAccountMessage]=useState(""),[accountRevision,setAccountRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setLoading(true);setPolicy(null);setDefaultLimit("");setError("");setMessage("");publish({status:"loading",states:{},failureLimit:null});Promise.all([securityRequest(sessionRef.current,{action:"policy",surface},c.signal),securityRequest(sessionRef.current,{action:"list-account-security",surface},c.signal)]).then(([policyResult,list])=>{if(c.signal.aborted)return;const p=readPolicy(policyResult);if(!Array.isArray(list.states))throw Error("账号登录状态列表返回不完整，请重新读取");const states:Record<string,Security>={};for(const row of list.states){if(typeof row.user_id!=="string"||!row.user_id||states[row.user_id])throw Error("账号登录状态列表返回不完整，请重新读取");states[row.user_id]=readSecurity({security:row})}setPolicy(p);setDefaultLimit(String(p.failure_limit));publish({status:"ready",states,failureLimit:p.failure_limit})}).catch(e=>{if(!c.signal.aborted){setError(e instanceof Error?e.message:"读取登录策略失败");publish({status:"error",states:{},failureLimit:null})}}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[session.user.id,surface,revision]);
 useEffect(()=>{const c=new AbortController();setSecurity(null);setAccountError("");setAccountMessage("");setOverride("inherit");if(!target){setAccountLoading(false);return()=>c.abort()}setAccountLoading(true);securityRequest(sessionRef.current,{action:"account-security",surface,user_id:target.id},c.signal).then(result=>{if(c.signal.aborted)return;const s=readSecurity(result);setSecurity(s);publish({...snapshotRef.current,states:{...snapshotRef.current.states,[target.id]:s}});setOverride(s.failure_limit===null?"inherit":String(s.failure_limit))}).catch(e=>{if(!c.signal.aborted)setAccountError(e instanceof Error?e.message:"读取账号登录状态失败")}).finally(()=>{if(!c.signal.aborted)setAccountLoading(false)});return()=>c.abort()},[session.user.id,surface,target?.id,accountRevision]);
 async function savePolicy(event:React.FormEvent){event.preventDefault();if(!policy||busy||loading||!limit(Number(defaultLimit)))return;setBusy(true);setError("");setMessage("");try{const p=readPolicy(await securityRequest(sessionRef.current,{action:"policy",surface,patch:{failure_limit:Number(defaultLimit)},expected_version:policy.version}));setPolicy(p);setDefaultLimit(String(p.failure_limit));publish({...snapshotRef.current,failureLimit:p.failure_limit});setMessage("默认失败阈值已保存")}catch(e){setError(e instanceof Error?e.message:"保存登录策略失败")}finally{setBusy(false)}}
 async function saveAccount(unlock=false){if(!target||!security||accountBusy||accountLoading)return;const value=override==="inherit"?null:Number(override);if(!unlock&&value!==null&&!limit(value))return;setAccountBusy(true);setAccountError("");setAccountMessage("");try{const result=await securityRequest(sessionRef.current,unlock?{action:"unlock-account",surface,user_id:target.id,expected_version:security.version}:{action:"set-account-policy",surface,user_id:target.id,failure_limit:value,expected_version:security.version});const next=readSecurity(result);setSecurity(next);publish({...snapshotRef.current,states:{...snapshotRef.current.states,[target.id]:next}});setOverride(next.failure_limit===null?"inherit":String(next.failure_limit));setAccountMessage(unlock?"自动锁定与失败次数已清除；手动启停状态不变":"该账号失败阈值已保存")}catch(e){setAccountError(e instanceof Error?e.message:"操作结果未确认，请重新读取核对")}finally{setAccountBusy(false)}}
 const scopeLabel=surface==="workorder"?"工单":"后台";
 return <><section className="account-login-policy"><div><h4>{scopeLabel}登录失败限制</h4><p>连续失败达到阈值后自动锁定；手动停用独立控制。</p></div><form onSubmit={savePolicy}><label>默认阈值<select aria-label={scopeLabel+"默认登录失败阈值"} value={defaultLimit} disabled={!policy||loading||busy} onChange={e=>setDefaultLimit(e.target.value)}>{!policy&&<option value="">{loading?"读取中…":"未读取"}</option>}{Array.from({length:20},(_,i)=><option key={i+1} value={i+1}>{i+1} 次</option>)}</select></label><button type="submit" disabled={!policy||loading||busy||Number(defaultLimit)===policy.failure_limit}>{busy?"保存中…":"保存阈值"}</button><button type="button" disabled={busy||loading} onClick={()=>setRevision(n=>n+1)}>重新读取</button></form>{loading&&<span role="status">读取登录策略…</span>}{error&&<p role="alert" className="account-security-error">{error}</p>}{message&&!loading&&!error&&<p role="status" className="account-security-success">{message}</p>}</section>
 {target&&<AccountEditorDialog title={scopeLabel+"账号登录安全 · "+target.username} busy={accountBusy} onClose={()=>onClose?.()} bodyClassName="account-login-details"><p className="account-security-manual">手动状态：<b>{target.active?"启用":"停用"}</b>{!target.active&&" · 解除自动锁定不会启用此账号"}</p>{accountLoading&&<p role="status">正在读取此账号登录状态…</p>}{accountError&&<p role="alert" className="account-security-error">{accountError}</p>}{accountMessage&&<p role="status" className="account-security-success">{accountMessage}</p>}{security&&<><dl className="account-security-facts"><div><dt>连续失败</dt><dd>{security.failed_count} 次</dd></div><div><dt>自动锁定</dt><dd>{security.locked?"已锁定":"未锁定"}</dd></div><div><dt>生效阈值</dt><dd>{security.failure_limit??policy?.failure_limit??"待读取"}{security.failure_limit!==null?" 次 · 单独设置":policy?" 次 · 跟随默认":" · 跟随默认"}</dd></div>{security.locked_at&&<div><dt>锁定时间</dt><dd>{security.locked_at}</dd></div>}</dl><label className="account-security-override">该账号失败阈值<select value={override} disabled={accountBusy} onChange={e=>setOverride(e.target.value)}><option value="inherit">跟随{scopeLabel}默认{policy?"（"+policy.failure_limit+" 次）":""}</option>{Array.from({length:20},(_,i)=><option key={i+1} value={i+1}>{i+1} 次</option>)}</select></label><div className="account-security-actions"><button type="button" disabled={accountBusy} onClick={()=>void saveAccount()}>保存账号阈值</button><button type="button" disabled={accountBusy||!security.locked&&!security.failed_count} onClick={()=>void saveAccount(true)}>{security.locked?"解除自动锁定":"清零失败次数"}</button></div></>}<button type="button" className="account-security-reload" disabled={accountBusy||accountLoading} onClick={()=>setAccountRevision(n=>n+1)}>重新读取账号状态</button></AccountEditorDialog>}
 </>;
}
