"use client";
import {useEffect,useState} from "react";
import type {DashboardSession} from "@/lib/dashboardAuthClient";
import {adminPreviewRequest,type PreviewGrant} from "@/lib/adminPreviewClient";
export default function AdminPreviewGrants({session,onClose}:{session:DashboardSession;onClose:()=>void}){
 const [rows,setRows]=useState<PreviewGrant[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(""),[query,setQuery]=useState(""),[search,setSearch]=useState(""),[page,setPage]=useState(1),[size,setSize]=useState(20),[total,setTotal]=useState(0),[jump,setJump]=useState(""),[loading,setLoading]=useState(true);
 const pages=Math.max(1,Math.ceil(total/size)),start=Math.max(1,Math.min(page-3,pages-6));
 useEffect(()=>{let stop=false;setLoading(true);setError("");const params=new URLSearchParams({action:"grants",offset:String((page-1)*size),limit:String(size),search});adminPreviewRequest(session,"?"+params).then(r=>r.json()).then(data=>{if(!stop){setRows(data.accounts||[]);setTotal(data.total||0);const max=Math.max(1,Math.ceil((data.total||0)/size));if(page>max)setPage(max)}}).catch(e=>{if(!stop){setRows([]);setError(e.message)}}).finally(()=>{if(!stop)setLoading(false)});return()=>{stop=true}},[session,page,size,search]);
 async function save(row:PreviewGrant,canView:boolean){setBusy(row.auth_user_id);setError("");try{const result=await adminPreviewRequest(session,"?action=grants",{method:"POST",body:JSON.stringify({auth_user_id:row.auth_user_id,can_view:canView})});const data=await result.json();setRows(old=>old.map(x=>x.auth_user_id===row.auth_user_id?{...x,can_view:data.can_view}:x))}catch(e){setError(e instanceof Error?e.message:"保存失败")}finally{setBusy("")}}
 const move=(next:number)=>{if(Number.isInteger(next)&&next>=1&&next<=pages){setPage(next);setJump("")}};
 return <div role="dialog" aria-modal="true" aria-label="新版后台查看授权" style={{position:"fixed",inset:0,zIndex:1100,background:"#0c1c3f66",display:"grid",placeItems:"center"}}><section style={{width:"min(1080px,95vw)",maxHeight:"85vh",overflow:"auto",background:"white",padding:22,borderRadius:10}}>
 <header style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2 style={{fontSize:18}}>新版后台查看授权</h2><button className="ghost-btn" onClick={onClose}>关闭</button></header>
 <p style={{fontSize:12,color:"#62728c"}}>勾选后，该账号可查看新版业务样本及存款只读快照的全量数据。Owner 固定可见，其他账号默认关闭；这里不会改变旧模块权限。</p>
 <form onSubmit={e=>{e.preventDefault();setPage(1);setSearch(query.trim())}} style={{display:"flex",gap:8,marginBottom:12}}><input aria-label="搜索授权账号" placeholder="搜索账号" value={query} onChange={e=>setQuery(e.target.value)} style={{padding:8}}/><button className="ghost-btn">查询</button></form>
 {error&&<p role="alert" style={{color:"#b03232"}}>{error}</p>}
 <table style={{width:"100%",fontSize:13,borderCollapse:"collapse"}}><thead><tr><th>账号</th><th>角色</th><th>状态</th><th>允许查看新版后台</th></tr></thead><tbody>{rows.map(r=><tr key={r.auth_user_id}><td style={{padding:10}}>{r.username}</td><td>{r.role}</td><td>{r.active?"启用":"已停用"}</td><td><input type="checkbox" aria-label={`允许 ${r.username} 查看新版后台`} checked={r.role==="owner"||r.can_view} disabled={!r.active||r.role==="owner"||!!busy||loading} onChange={e=>save(r,e.target.checked)}/>{busy===r.auth_user_id?" 保存中":""}</td></tr>)}</tbody></table>
 {loading&&<p role="status">正在读取账号…</p>}
 <footer style={{display:"flex",gap:5,flexWrap:"wrap",alignItems:"center",fontSize:12,paddingTop:14}}><span style={{marginRight:"auto"}}>共 {total} 条　{total?(page-1)*size+1:0}–{Math.min(page*size,total)}</span><select aria-label="授权列表每页条数" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{[20,30,50,100,500].map(n=><option key={n} value={n}>{n} 条 / 页</option>)}</select><button className="ghost-btn" disabled={page<=1||loading} onClick={()=>move(1)}>首页</button><button className="ghost-btn" disabled={page<=1||loading} onClick={()=>move(page-1)}>上一页</button>{Array.from({length:Math.min(7,pages)},(_,i)=>start+i).map(n=><button key={n} className="ghost-btn" aria-current={n===page?"page":undefined} style={n===page?{background:"#4b74df",color:"#fff"}:{}} disabled={loading} onClick={()=>move(n)}>{n}</button>)}<button className="ghost-btn" disabled={page>=pages||loading} onClick={()=>move(page+1)}>下一页</button><button className="ghost-btn" disabled={page>=pages||loading} onClick={()=>move(pages)}>末页</button><span>共 {pages} 页　前往</span><input aria-label="授权列表跳转页码" type="number" min={1} max={pages} value={jump} onChange={e=>setJump(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")move(Number(jump))}} style={{width:50}}/><span>页</span><button className="ghost-btn" disabled={loading||!jump} onClick={()=>move(Number(jump))}>确定</button></footer>
 </section></div>
}
