"use client";
import { useEffect, useRef, useState } from "react";
import type { DashboardSession } from "@/lib/dashboardAuthClient";
import { workOrderAccountRequest, type WorkOrderAccount, type WorkOrderAccountCatalog, type WorkOrderAccountFields, type WorkOrderRole } from "@/lib/workOrderAccountClient";
import "./WorkOrderAccountAdmin.css";
import AccountEditorDialog from "./AccountEditorDialog";
import AccountLoginPolicy, {type AccountLoginSnapshot} from "./AccountLoginPolicy";

const roles:Record<WorkOrderRole,string>={supervisor:"主管",agent:"员工",auditor:"审计员"};
type Draft=WorkOrderAccountFields & {username:string;password:string};
const fresh=():Draft=>({username:"",password:"",display_name:"",role:"agent",team:"",platforms:[],active:true,permissions:{}});

export default function WorkOrderAccountAdmin({session}:{session:DashboardSession}) {
  const sessionRef=useRef(session);sessionRef.current=session;
  const [rows,setRows]=useState<WorkOrderAccount[]>([]),[catalog,setCatalog]=useState<WorkOrderAccountCatalog|null>(null);
  const [loading,setLoading]=useState(true),[loaded,setLoaded]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState("");
  const [nameFilter,setNameFilter]=useState(""),[roleFilter,setRoleFilter]=useState("all"),[teamFilter,setTeamFilter]=useState("all"),[platformFilter,setPlatformFilter]=useState("all"),[statusFilter,setStatusFilter]=useState("all");
  const [editing,setEditing]=useState<WorkOrderAccount|null>(null),[creating,setCreating]=useState(false),[draft,setDraft]=useState<Draft>(fresh);
  const [resetTarget,setResetTarget]=useState<WorkOrderAccount|null>(null),[password,setPassword]=useState("");
  const [revision,setRevision]=useState(0),[permissionNotice,setPermissionNotice]=useState("");
  const [securityTarget,setSecurityTarget]=useState<WorkOrderAccount|null>(null),[securitySnapshot,setSecuritySnapshot]=useState<AccountLoginSnapshot>({status:"loading",states:{},failureLimit:null});
  useEffect(()=>{
    const controller=new AbortController();setLoading(true);setError("");
    workOrderAccountRequest(sessionRef.current,{action:"list-accounts"},controller.signal).then(result=>{
      if(controller.signal.aborted)return;
      if(!Array.isArray(result.accounts)||!result.catalog||!Array.isArray(result.catalog.teams)||!Array.isArray(result.catalog.platforms)||!result.catalog.platformTeams)throw Error("工单账号目录返回不完整，请重试");
      setRows(result.accounts);setCatalog(result.catalog);setLoaded(true);
    }).catch(e=>{if(!controller.signal.aborted){setRows([]);setCatalog(null);setLoaded(false);setError(e instanceof Error?e.message:"读取工单账号失败")}}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});
    return()=>controller.abort();
  },[session.user.id,revision]);
  const permissionOptions=catalog?.permissionOptions||[],permissionDefaults=catalog?.permissionDefaults;
  const permissionsReady=permissionOptions.length>0&&new Set(permissionOptions.map(p=>p.key)).size===permissionOptions.length&&Object.keys(roles).every(role=>permissionDefaults?.[role]&&permissionOptions.every(p=>typeof permissionDefaults[role][p.key]==="boolean"));
  function rolePermissions(role:WorkOrderRole,stored?:Record<string,boolean>|null){const defaults=permissionDefaults?.[role]||{},source=stored==null?defaults:stored;return Object.fromEntries(Object.keys(source).filter(key=>permissionOptions.some(p=>p.key===key)).map(key=>[key,source[key]===true&&defaults[key]===true]))}
  function closeEditor(){setCreating(false);setEditing(null);setDraft(fresh());setPermissionNotice("")}
  function startEdit(row:WorkOrderAccount){closeEditor();setEditing(row);setDraft({...row,password:"",permissions:rolePermissions(row.role,row.permissions)});setResetTarget(null);setPassword("");setError("");setMessage("")}
  function receive(row:WorkOrderAccount|undefined){if(!row)throw Error("操作返回不完整，请刷新账号列表确认结果");setRows(old=>old.some(x=>x.auth_user_id===row.auth_user_id)?old.map(x=>x.auth_user_id===row.auth_user_id?row:x):[...old,row].sort((a,b)=>a.username.localeCompare(b.username)));}
  async function save(event:React.FormEvent){
    event.preventDefault();if(busy||loading||!catalog||(!creating&&!editing))return;
    if(!permissionsReady){setError("操作权限目录未读取完成，请刷新列表后重试");return}
    if(!draft.platforms.length||draft.platforms.some(p=>catalog.platformTeams[p]!==draft.team)){setError("请选择所属团队和该团队的平台");return}
    setBusy(true);setError("");setMessage("");
    try{
      const {username,password,display_name,role,team,platforms,active}=draft;const permissions=rolePermissions(role,draft.permissions);
      const result=await workOrderAccountRequest(sessionRef.current,creating?{action:"create-account",username:username.trim().toLowerCase(),password,display_name:display_name.trim(),role,team,platforms,permissions}:{action:"update-account",auth_user_id:editing!.auth_user_id,expected_updated_at:editing!.updated_at,patch:{display_name:display_name.trim(),role,team,platforms,active,permissions}});
      receive(result.account);closeEditor();setMessage(result.message||"工单账号已保存");
    }catch(e){setError(e instanceof Error?e.message:"保存失败")}finally{setBusy(false)}
  }
  async function toggle(row:WorkOrderAccount){
    if(busy||loading)return;setBusy(true);setError("");setMessage("");
    try{const result=await workOrderAccountRequest(sessionRef.current,{action:"update-account",auth_user_id:row.auth_user_id,expected_updated_at:row.updated_at,patch:{active:!row.active}});receive(result.account);if(editing?.auth_user_id===row.auth_user_id)closeEditor();setMessage(row.active?"工单账号已停用":"工单账号已启用")}catch(e){setError(e instanceof Error?e.message:"操作失败")}finally{setBusy(false)}
  }
  async function reset(event:React.FormEvent){
    event.preventDefault();if(busy||!resetTarget)return;setBusy(true);setError("");setMessage("");
    try{const result=await workOrderAccountRequest(sessionRef.current,{action:"reset-password",auth_user_id:resetTarget.auth_user_id,password});receive(result.account);setPassword("");setResetTarget(null);setMessage("工单密码已重设，请使用新密码重新登录工单系统")}catch(e){setError(e instanceof Error?e.message:"重设密码失败")}finally{setBusy(false)}
  }
  const platforms=(catalog?.platforms||[]).filter(p=>catalog?.platformTeams[p]===draft.team);
  const filterPlatforms=(catalog?.platforms||[]).filter(p=>teamFilter==="all"||catalog?.platformTeams[p]===teamFilter);
  const visible=rows.filter(row=>row.username.toLowerCase().includes(query.trim().toLowerCase())&&row.display_name.toLowerCase().includes(nameFilter.trim().toLowerCase())&&(roleFilter==="all"||row.role===roleFilter)&&(teamFilter==="all"||row.team===teamFilter)&&(platformFilter==="all"||row.platforms.includes(platformFilter))&&(statusFilter==="all"||statusFilter==="active"&&row.active||statusFilter==="disabled"&&!row.active||statusFilter==="locked"&&(securitySnapshot.status!=="ready"||securitySnapshot.states[row.auth_user_id]?.locked===true)));
  const editorOpen=creating||!!editing||!!resetTarget;
  return <div className="workorder-account-admin">
    <div className="wo-account-toolbar"><div><h3>工单账号列表</h3><span>工单账号独立授权，停用保留历史记录。</span></div><div className="wo-account-actions"><button type="button" disabled={busy||loading} onClick={()=>{closeEditor();setResetTarget(null);setPassword("");setRevision(x=>x+1)}}>刷新列表</button><button type="button" className="primary" aria-haspopup="dialog" disabled={busy||loading||!catalog||!permissionsReady} onClick={()=>{closeEditor();setCreating(true);setDraft({...fresh(),permissions:rolePermissions("agent")});setResetTarget(null);setPassword("");setError("");setMessage("")}}>新建工单账号</button></div></div>
    <div className="wo-account-filters"><label>筛选账号<input aria-label="筛选工单账号" placeholder="账号" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>筛选姓名<input placeholder="显示名称" value={nameFilter} onChange={e=>setNameFilter(e.target.value)}/></label><label>筛选角色<select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="all">全部角色</option>{Object.entries(roles).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>筛选团队<select value={teamFilter} onChange={e=>{setTeamFilter(e.target.value);if(e.target.value!=="all"&&platformFilter!=="all"&&catalog?.platformTeams[platformFilter]!==e.target.value)setPlatformFilter("all")}}><option value="all">全部团队</option>{catalog?.teams.map(team=><option key={team}>{team}</option>)}</select></label><label>筛选平台<select value={platformFilter} onChange={e=>setPlatformFilter(e.target.value)}><option value="all">全部平台</option>{filterPlatforms.map(p=><option key={p}>{p}</option>)}</select></label><label>筛选状态<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">全部状态</option><option value="active">启用</option><option value="disabled">手动停用</option><option value="locked">自动锁定</option></select></label><button type="button" onClick={()=>{setQuery("");setNameFilter("");setRoleFilter("all");setTeamFilter("all");setPlatformFilter("all");setStatusFilter("all")}}>重置筛选</button></div>
    <AccountLoginPolicy session={session} surface="workorder" target={securityTarget?{id:securityTarget.auth_user_id,username:securityTarget.username,active:securityTarget.active}:null} onClose={()=>setSecurityTarget(null)} onSnapshot={setSecuritySnapshot}/>{loaded&&!permissionsReady&&<p role="alert" className="wo-account-error">操作权限目录未读取完成，请刷新列表后编辑授权。</p>}
    {error&&!editorOpen&&<p role="alert" className="wo-account-error">{error}</p>}{message&&<p role="status" className="wo-account-success">{message}</p>}
    {(creating||editing)&&<AccountEditorDialog title={creating?"新建工单账号":"编辑工单账号 · "+editing?.username} busy={busy} onClose={closeEditor} bodyClassName="workorder-account-admin"><form className="wo-account-editor" onSubmit={save}>{error&&<p role="alert" className="wo-account-error">{error}</p>}<fieldset disabled={busy||loading}>
      <div className="wo-account-fields">{creating&&<><label>账号<input required minLength={3} maxLength={32} pattern="[a-zA-Z0-9._-]{3,32}" autoComplete="off" value={draft.username} onChange={e=>setDraft({...draft,username:e.target.value})}/></label><label>初始密码<input required type="password" minLength={8} maxLength={128} autoComplete="new-password" value={draft.password} onChange={e=>setDraft({...draft,password:e.target.value})}/></label></>}
        <label>显示名称<input required maxLength={100} value={draft.display_name} onChange={e=>setDraft({...draft,display_name:e.target.value})}/></label><label>角色<select value={draft.role} onChange={e=>{const role=e.target.value as WorkOrderRole;setDraft({...draft,role,permissions:rolePermissions(role)});setPermissionNotice("角色已切换，操作权限已重置为该角色默认值，请核对后保存。")}}>{Object.entries(roles).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>团队<select required value={draft.team} onChange={e=>setDraft({...draft,team:e.target.value,platforms:[]})}><option value="">请选择团队</option>{catalog?.teams.map(team=><option key={team}>{team}</option>)}</select></label>
      </div>
      <div className="wo-account-platform-head"><b>可操作平台</b><button type="button" disabled={!platforms.length} onClick={()=>setDraft({...draft,platforms:[...platforms]})}>全选当前团队</button><button type="button" onClick={()=>setDraft({...draft,platforms:[]})}>清空</button><span>已选 {draft.platforms.length} 个</span></div><div className="wo-account-platforms">{platforms.map(p=><label key={p}><input type="checkbox" checked={draft.platforms.includes(p)} onChange={e=>setDraft({...draft,platforms:e.target.checked?[...draft.platforms,p]:draft.platforms.filter(x=>x!==p)})}/>{p}</label>)}{!draft.team&&<span>先选择团队，再选择平台。</span>}</div>
      <section className="wo-account-role-permissions"><div className="wo-account-platform-head"><b>具体操作权限 · {roles[draft.role]}</b><button type="button" onClick={()=>{setDraft({...draft,permissions:rolePermissions(draft.role)});setPermissionNotice("已恢复当前角色默认操作权限。")}}>恢复角色默认</button><button type="button" onClick={()=>{setDraft({...draft,permissions:{}});setPermissionNotice("已清空操作权限；保存后此账号不能执行任何工单业务操作。")}}>清空操作权限</button></div>{permissionNotice&&<p role="status">{permissionNotice}</p>}<div className="wo-account-permission-options">{permissionOptions.map(item=>{const allowed=permissionDefaults?.[draft.role]?.[item.key]===true;return <label key={item.key} className={allowed?"":"unavailable"} title={allowed?"仍受团队和平台范围限制":"该角色不可授予此操作"}><input type="checkbox" disabled={!allowed} checked={allowed&&draft.permissions[item.key]===true} onChange={e=>setDraft({...draft,permissions:{...draft.permissions,[item.key]:e.target.checked}})}/><span>{item.label}</span></label>})}</div><p>可勾选当前角色允许的操作，授权不会扩大所选团队或平台范围。</p></section>
      <div className="wo-account-actions"><button className="primary" type="submit" disabled={!draft.platforms.length}>{busy?"保存中…":"保存账号"}</button><button type="button" onClick={closeEditor}>取消</button></div>
    </fieldset></form></AccountEditorDialog>}
    {resetTarget&&<AccountEditorDialog title={"重设工单密码 · "+resetTarget.username} busy={busy} onClose={()=>{setResetTarget(null);setPassword("")}} bodyClassName="workorder-account-admin"><form className="wo-account-editor" onSubmit={reset}>{error&&<p role="alert" className="wo-account-error">{error}</p>}<fieldset disabled={busy}><label>新密码<input aria-label="新工单密码" required type="password" minLength={8} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="wo-account-actions"><button type="submit" className="primary">{busy?"保存中…":"保存新密码"}</button><button type="button" onClick={()=>{setResetTarget(null);setPassword("")}}>取消</button></div></fieldset></form></AccountEditorDialog>}
    {loading&&<p role="status">正在读取工单账号…</p>}
    {loaded&&<><p className="wo-account-count">{statusFilter==="locked"&&securitySnapshot.status!=="ready"?"登录状态尚未核实，暂显示全部账号 · ":""}共 {rows.length} 个工单账号 · 当前显示 {visible.length} 个</p><div className="wo-account-table"><table><thead><tr><th>账号</th><th>显示名称</th><th>角色</th><th>团队</th><th>平台范围</th><th>操作权限</th><th>状态 / 登录失败</th><th>操作</th></tr></thead><tbody>{visible.map(row=><tr key={row.auth_user_id}><td>{row.username}</td><td>{row.display_name}</td><td>{roles[row.role]||row.role}</td><td>{row.team}</td><td>{row.platforms.join("、")}</td><td>{permissionsReady?Object.values(rolePermissions(row.role,row.permissions)).filter(Boolean).length+" 项":"待读取"}</td><td><span className={row.active?"active":"inactive"}>{row.active?"启用":"手动停用"}</span><small className="wo-account-login-state">{securitySnapshot.states[row.auth_user_id]?((securitySnapshot.states[row.auth_user_id].locked?"自动锁定 · ":"")+"失败 "+securitySnapshot.states[row.auth_user_id].failed_count+" / "+(securitySnapshot.states[row.auth_user_id].failure_limit??securitySnapshot.failureLimit??"—")+" 次"):securitySnapshot.status==="error"?"登录状态读取失败":"登录状态待读取"}</small></td><td><div className="wo-account-actions"><button disabled={busy||loading||!permissionsReady} aria-haspopup="dialog" onClick={()=>startEdit(row)}>编辑范围 / 角色</button><button disabled={busy||loading} onClick={()=>void toggle(row)}>{row.active?"停用":"启用"}</button><button disabled={busy||loading} aria-haspopup="dialog" onClick={()=>{closeEditor();setResetTarget(row);setPassword("");setError("");setMessage("")}}>重设密码</button><button disabled={busy||loading} aria-haspopup="dialog" onClick={()=>setSecurityTarget(row)}>登录安全</button></div></td></tr>)}</tbody></table>{!visible.length&&!loading&&!error&&<p className="wo-account-empty">{rows.length?"没有符合筛选条件的工单账号。":"还没有工单账号，可点击“新建工单账号”。"}</p>}</div></>}
  </div>;
}
