-- 36_IP白名单登录控制.sql
-- 默认关闭。Owner 在管理后台添加 IP 后，可选择开启“必须白名单才能登录”。

begin;

create table if not exists public.dashboard_security_settings (
  id smallint primary key default 1 check (id = 1),
  ip_whitelist_enabled boolean not null default false,
  updated_by uuid,
  updated_at timestamptz not null default now()
);

insert into public.dashboard_security_settings (id, ip_whitelist_enabled)
values (1, false)
on conflict (id) do nothing;

alter table public.dashboard_security_settings enable row level security;

create table if not exists public.dashboard_ip_whitelist (
  id bigint generated by default as identity primary key,
  ip text not null unique,
  note text not null default '',
  active boolean not null default true,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dashboard_ip_whitelist_active_idx
  on public.dashboard_ip_whitelist (active, ip);

alter table public.dashboard_ip_whitelist enable row level security;

-- 不开放给浏览器直接读写；全部经 dashboard-user-admin Edge Function 管理。
revoke all on public.dashboard_security_settings from anon, authenticated;
revoke all on public.dashboard_ip_whitelist from anon, authenticated;

commit;

select * from public.dashboard_security_settings;
select id, ip, note, active, created_at from public.dashboard_ip_whitelist order by id;
